[package]
name = "omega-post-allocation-machine-to-optimized-machine"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_post_allocation_machine_to_optimized_machine"
path = "src/lib.rs"

[dependencies]
omega-physical-instructions = { path = "../../representations/omega-physical-instructions" }
omega-selected-instructions-to-register-homes = { path = "../omega-selected-instructions-to-register-homes" }
omega-machine-optimizer = { path = "../omega-machine-optimizer" }
omega-optimization-core = { path = "../../representations/omega-optimization-core" }
omega-regalloc = { path = "../omega-regalloc" }
omega-register-homes-to-post-allocation-machine = { path = "../omega-register-homes-to-post-allocation-machine" }
omega-register-model = { path = "../../representations/omega-register-model" }
omega-target = { path = "../../representations/omega-target" }
