[package]
name = "omega-artifacts"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_artifacts"
path = "src/lib.rs"

[dependencies]
omega-backend-report-types = { path = "../../foundation/omega-backend-report-types" }
psi-checked-trees = { path = "../../../psi-rs/representations/psi-checked-trees" }
omega-core = { path = "../../foundation/omega-core" }
psi-arena = { path = "../../../psi-rs/foundation/psi-arena" }
psi-symbols = { path = "../../../psi-rs/foundation/psi-symbols" }
psi-diagnostics = { path = "../../../psi-rs/foundation/psi-diagnostics" }
omega-calling-conventions = { path = "../../foundation/omega-calling-conventions" }
omega-executable-installation = { path = "../../foundation/omega-executable-installation" }
omega-external-roots = { path = "../omega-external-roots" }
omega-image = { path = "../../backend/images/omega-image" }
omega-target = { path = "../../foundation/omega-target" }

[dev-dependencies]
psi-layout-plans = { path = "../../../psi-rs/foundation/psi-layout-plans" }
psi-extents = { path = "../../../psi-rs/foundation/psi-extents" }
serde_json = "1.0"
