[package]
name = "omega-artifacts"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_artifacts"
path = "src/lib.rs"

[dependencies]
omega-backend-report-types = { path = "../../foundation/omega-backend-report-types" }
omega-checked-trees = { path = "../../representations/omega-checked-trees" }
omega-core = { path = "../../foundation/omega-core" }
omega-calling-conventions = { path = "../../foundation/omega-calling-conventions" }
omega-external-roots = { path = "../../foundation/omega-external-roots" }
omega-image = { path = "../../backend/images/omega-image" }
omega-target = { path = "../../foundation/omega-target" }

[dev-dependencies]
omega-executable-installation = { path = "../../foundation/omega-executable-installation" }
omega-layout-plans = { path = "../../foundation/omega-layout-plans" }
serde_json = "1.0"
