[package]
name = "omega-assigned-target-operations"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_assigned_target_operations"
path = "src/lib.rs"

[dependencies]
omega-control-flow = { path = "../omega-control-flow" }
psi-arena = { path = "../../../psi/foundation/psi-arena" }
psi-numerics = { path = "../../../psi/foundation/psi-numerics" }
omega-target = { path = "../../foundation/omega-target" }
omega-target-operations = { path = "../omega-target-operations" }
