use crate::AssignedOperationKind;

impl From<AssignedOperationKind> for omega_target_operations::TargetOperationKind {
    fn from(kind: AssignedOperationKind) -> Self {
        match kind {
            AssignedOperationKind::EnterFunction => Self::EnterFunction,
            AssignedOperationKind::EnterDispatchLoop {
                entry_dispatch_index,
                terminal_dispatch_index,
            } => Self::EnterDispatchLoop {
                entry_dispatch_index,
                terminal_dispatch_index,
            },
            AssignedOperationKind::EnterDispatchCase { dispatch_index } => {
                Self::EnterDispatchCase { dispatch_index }
            }
            AssignedOperationKind::EvaluateDispatchGuard {
                guard_lowering,
                operator,
                storage_region,
                byte_offset,
                byte_size,
                expected_value,
                has_storage,
                is_float,
            } => Self::EvaluateDispatchGuard {
                guard_lowering,
                operator,
                storage_region,
                byte_offset,
                byte_size,
                expected_value,
                has_storage,
                is_float,
            },
            AssignedOperationKind::CompareRuntimeTextLiteral { buffer, literal } => {
                Self::CompareRuntimeTextLiteral { buffer, literal }
            }
            AssignedOperationKind::CompareRuntimeTextStorage {
                buffer,
                source_region,
                source_offset,
                operator,
            } => Self::CompareRuntimeTextStorage {
                buffer,
                source_region,
                source_offset,
                operator,
            },
            AssignedOperationKind::CompareRuntimeStorage {
                left_region,
                left_offset,
                right_region,
                right_offset,
                byte_size,
                operator,
                is_float,
            } => Self::CompareRuntimeStorage {
                left_region,
                left_offset,
                right_region,
                right_offset,
                byte_size,
                operator,
                is_float,
            },
            AssignedOperationKind::CompareRuntimeStorageValue {
                region,
                byte_offset,
                byte_size,
                expected_value,
                operator,
            } => Self::CompareRuntimeStorageValue {
                region,
                byte_offset,
                byte_size,
                expected_value,
                operator,
            },
            AssignedOperationKind::CompareRuntimeValues {
                left,
                right,
                byte_size,
                operator,
            } => Self::CompareRuntimeValues {
                left,
                right,
                byte_size,
                operator,
            },
            AssignedOperationKind::WriteRuntimeTextLiteral { buffer, literal } => {
                Self::WriteRuntimeTextLiteral { buffer, literal }
            }
            AssignedOperationKind::WriteRuntimeTextLiteralSegment {
                buffer,
                byte_offset,
                literal,
            } => Self::WriteRuntimeTextLiteralSegment {
                buffer,
                byte_offset,
                literal,
            },
            AssignedOperationKind::AppendRuntimeTextStoredSuffix {
                buffer,
                buffer_offset,
                source_region,
                source_offset,
                target_region,
                target_offset,
                length_delta,
            } => Self::AppendRuntimeTextStoredSuffix {
                buffer,
                buffer_offset,
                source_region,
                source_offset,
                target_region,
                target_offset,
                length_delta,
            },
            AssignedOperationKind::MaterializeRuntimeTextBuffer {
                buffer,
                target_region,
                target_offset,
            } => Self::MaterializeRuntimeTextBuffer {
                buffer,
                target_region,
                target_offset,
            },
            AssignedOperationKind::MaterializeRuntimeTextBufferToRuntimePointee {
                buffer,
                pointer_byte_offset,
                field_byte_offset,
            } => Self::MaterializeRuntimeTextBufferToRuntimePointee {
                buffer,
                pointer_byte_offset,
                field_byte_offset,
            },
            AssignedOperationKind::MaterializeRuntimeTextBufferToRuntimeFrameIndexed {
                buffer,
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
            } => Self::MaterializeRuntimeTextBufferToRuntimeFrameIndexed {
                buffer,
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
            },
            AssignedOperationKind::AppendRuntimeTextStoredPlace {
                buffer,
                source_region,
                source_offset,
                target_region,
                target_offset,
            } => Self::AppendRuntimeTextStoredPlace {
                buffer,
                source_region,
                source_offset,
                target_region,
                target_offset,
            },
            AssignedOperationKind::AppendRuntimeTextStoredPlaceToRuntimePointee {
                buffer,
                source_region,
                source_offset,
                pointer_byte_offset,
                field_byte_offset,
            } => Self::AppendRuntimeTextStoredPlaceToRuntimePointee {
                buffer,
                source_region,
                source_offset,
                pointer_byte_offset,
                field_byte_offset,
            },
            AssignedOperationKind::AppendRuntimeTextStoredPlaceToRuntimeFrameIndexed {
                buffer,
                source_region,
                source_offset,
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
            } => Self::AppendRuntimeTextStoredPlaceToRuntimeFrameIndexed {
                buffer,
                source_region,
                source_offset,
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
            },
            AssignedOperationKind::AppendRuntimeTextLiteral {
                buffer,
                target_region,
                target_offset,
                literal,
            } => Self::AppendRuntimeTextLiteral {
                buffer,
                target_region,
                target_offset,
                literal,
            },
            AssignedOperationKind::AppendRuntimeTextLiteralToRuntimePointee {
                buffer,
                pointer_byte_offset,
                field_byte_offset,
                literal,
            } => Self::AppendRuntimeTextLiteralToRuntimePointee {
                buffer,
                pointer_byte_offset,
                field_byte_offset,
                literal,
            },
            AssignedOperationKind::AppendRuntimeTextLiteralToRuntimeFrameIndexed {
                buffer,
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                literal,
            } => Self::AppendRuntimeTextLiteralToRuntimeFrameIndexed {
                buffer,
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                literal,
            },
            AssignedOperationKind::WriteRuntimeMachineInteger {
                byte_offset,
                byte_size,
                value,
            } => Self::WriteRuntimeMachineInteger {
                byte_offset,
                byte_size,
                value,
            },
            AssignedOperationKind::WriteRuntimeStorageInteger {
                target_region,
                byte_offset,
                byte_size,
                value,
            } => Self::WriteRuntimeStorageInteger {
                target_region,
                byte_offset,
                byte_size,
                value,
            },
            AssignedOperationKind::WriteRuntimePointeeInteger {
                pointer_byte_offset,
                field_byte_offset,
                byte_size,
                value,
            } => Self::WriteRuntimePointeeInteger {
                pointer_byte_offset,
                field_byte_offset,
                byte_size,
                value,
            },
            AssignedOperationKind::WriteRuntimeStorageBinary {
                target_region,
                target_offset,
                byte_size,
                left,
                operator,
                right,
                is_float,
            } => Self::WriteRuntimeStorageBinary {
                target_region,
                target_offset,
                byte_size,
                left,
                operator,
                right,
                is_float,
            },
            AssignedOperationKind::WriteRuntimePointeeBinary {
                pointer_byte_offset,
                field_byte_offset,
                byte_size,
                left,
                operator,
                right,
            } => Self::WriteRuntimePointeeBinary {
                pointer_byte_offset,
                field_byte_offset,
                byte_size,
                left,
                operator,
                right,
            },
            AssignedOperationKind::WriteRuntimeFrameIndexedInteger {
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                byte_size,
                value,
            } => Self::WriteRuntimeFrameIndexedInteger {
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                byte_size,
                value,
            },
            AssignedOperationKind::WriteRuntimeFrameBaseIndexedInteger {
                base_byte_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                byte_size,
                value,
            } => Self::WriteRuntimeFrameBaseIndexedInteger {
                base_byte_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                byte_size,
                value,
            },
            AssignedOperationKind::WriteRuntimeMachineIndexedInteger {
                base_byte_offset,
                index_region,
                index_offset,
                element_byte_size,
                field_byte_offset,
                byte_size,
                value,
            } => Self::WriteRuntimeMachineIndexedInteger {
                base_byte_offset,
                index_region,
                index_offset,
                element_byte_size,
                field_byte_offset,
                byte_size,
                value,
            },
            AssignedOperationKind::WriteRuntimeFrameIndexedBinary {
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                byte_size,
                left,
                operator,
                right,
            } => Self::WriteRuntimeFrameIndexedBinary {
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                byte_size,
                left,
                operator,
                right,
            },
            AssignedOperationKind::WriteRuntimeFrameBaseIndexedBinary {
                base_byte_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                byte_size,
                left,
                operator,
                right,
            } => Self::WriteRuntimeFrameBaseIndexedBinary {
                base_byte_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                byte_size,
                left,
                operator,
                right,
            },
            AssignedOperationKind::WriteRuntimeMachineString {
                byte_offset,
                data,
                byte_length,
            } => Self::WriteRuntimeMachineString {
                byte_offset,
                data,
                byte_length,
            },
            AssignedOperationKind::WriteRuntimeFrameString {
                byte_offset,
                data,
                byte_length,
            } => Self::WriteRuntimeFrameString {
                byte_offset,
                data,
                byte_length,
            },
            AssignedOperationKind::WriteRuntimePointeeString {
                pointer_byte_offset,
                field_byte_offset,
                data,
                byte_length,
            } => Self::WriteRuntimePointeeString {
                pointer_byte_offset,
                field_byte_offset,
                data,
                byte_length,
            },
            AssignedOperationKind::WriteRuntimeFrameIndexedString {
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                data,
                byte_length,
            } => Self::WriteRuntimeFrameIndexedString {
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                data,
                byte_length,
            },
            AssignedOperationKind::WriteRuntimeMachineIndexedString {
                base_byte_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                data,
                byte_length,
            } => Self::WriteRuntimeMachineIndexedString {
                base_byte_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                data,
                byte_length,
            },
            AssignedOperationKind::WriteRuntimeStorageAddressToRuntimeFrame {
                source_region,
                source_offset,
                target_offset,
            } => Self::WriteRuntimeStorageAddressToRuntimeFrame {
                source_region,
                source_offset,
                target_offset,
            },
            AssignedOperationKind::WriteRuntimePointeeAddressToRuntimeFrame {
                pointer_byte_offset,
                field_byte_offset,
                target_offset,
            } => Self::WriteRuntimePointeeAddressToRuntimeFrame {
                pointer_byte_offset,
                field_byte_offset,
                target_offset,
            },
            AssignedOperationKind::WriteRuntimeFrameIndexedAddressToRuntimeFrame {
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                target_offset,
            } => Self::WriteRuntimeFrameIndexedAddressToRuntimeFrame {
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                target_offset,
            },
            AssignedOperationKind::WriteRuntimeFrameFixedIndexedAddressToRuntimeFrame {
                descriptor_offset,
                element_index,
                element_byte_size,
                field_byte_offset,
                target_offset,
            } => Self::WriteRuntimeFrameFixedIndexedAddressToRuntimeFrame {
                descriptor_offset,
                element_index,
                element_byte_size,
                field_byte_offset,
                target_offset,
            },
            AssignedOperationKind::WriteRuntimeFrameBaseIndexedAddressToRuntimeFrame {
                base_byte_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                target_offset,
            } => Self::WriteRuntimeFrameBaseIndexedAddressToRuntimeFrame {
                base_byte_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                target_offset,
            },
            AssignedOperationKind::ReadRuntimeTextLine {
                buffer,
                target_region,
                target_offset,
                byte_capacity,
                source,
            } => Self::ReadRuntimeTextLine {
                buffer,
                target_region,
                target_offset,
                byte_capacity,
                source,
            },
            AssignedOperationKind::CopyRuntimeStorage {
                source_region,
                source_offset,
                target_region,
                target_offset,
                byte_count,
            } => Self::CopyRuntimeStorage {
                source_region,
                source_offset,
                target_region,
                target_offset,
                byte_count,
            },
            AssignedOperationKind::CopyRuntimeStorageToRuntimeFrameIndexed {
                source_region,
                source_offset,
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                byte_count,
            } => Self::CopyRuntimeStorageToRuntimeFrameIndexed {
                source_region,
                source_offset,
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                byte_count,
            },
            AssignedOperationKind::CopyRuntimeFrameIndexedToRuntimeFrame {
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                target_offset,
                byte_count,
            } => Self::CopyRuntimeFrameIndexedToRuntimeFrame {
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                target_offset,
                byte_count,
            },
            AssignedOperationKind::CopyRuntimeFrameIndexedToRuntimeStorage {
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                target_region,
                target_offset,
                byte_count,
            } => Self::CopyRuntimeFrameIndexedToRuntimeStorage {
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                target_region,
                target_offset,
                byte_count,
            },
            AssignedOperationKind::CopyRuntimeFrameFixedIndexedToRuntimeFrame {
                descriptor_offset,
                element_index,
                element_byte_size,
                field_byte_offset,
                target_offset,
                byte_count,
            } => Self::CopyRuntimeFrameFixedIndexedToRuntimeFrame {
                descriptor_offset,
                element_index,
                element_byte_size,
                field_byte_offset,
                target_offset,
                byte_count,
            },
            AssignedOperationKind::CopyRuntimeFrameFixedIndexedToRuntimeStorage {
                descriptor_offset,
                element_index,
                element_byte_size,
                field_byte_offset,
                target_region,
                target_offset,
                byte_count,
            } => Self::CopyRuntimeFrameFixedIndexedToRuntimeStorage {
                descriptor_offset,
                element_index,
                element_byte_size,
                field_byte_offset,
                target_region,
                target_offset,
                byte_count,
            },
            AssignedOperationKind::CopyRuntimeFrameFixedIndexedToRuntimePointee {
                descriptor_offset,
                element_index,
                element_byte_size,
                source_field_byte_offset,
                pointer_byte_offset,
                target_field_byte_offset,
                byte_count,
            } => Self::CopyRuntimeFrameFixedIndexedToRuntimePointee {
                descriptor_offset,
                element_index,
                element_byte_size,
                source_field_byte_offset,
                pointer_byte_offset,
                target_field_byte_offset,
                byte_count,
            },
            AssignedOperationKind::CopyRuntimeMachineIndexedToRuntimeStorage {
                base_byte_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                target_region,
                target_offset,
                byte_count,
            } => Self::CopyRuntimeMachineIndexedToRuntimeStorage {
                base_byte_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                target_region,
                target_offset,
                byte_count,
            },
            AssignedOperationKind::CopyRuntimeStorageToRuntimePointee {
                source_region,
                source_offset,
                pointer_byte_offset,
                field_byte_offset,
                byte_count,
            } => Self::CopyRuntimeStorageToRuntimePointee {
                source_region,
                source_offset,
                pointer_byte_offset,
                field_byte_offset,
                byte_count,
            },
            AssignedOperationKind::CopyRuntimePointeeToRuntimeFrame {
                pointer_byte_offset,
                field_byte_offset,
                target_offset,
                byte_count,
            } => Self::CopyRuntimePointeeToRuntimeFrame {
                pointer_byte_offset,
                field_byte_offset,
                target_offset,
                byte_count,
            },
            AssignedOperationKind::SetDispatchState { dispatch_index } => {
                Self::SetDispatchState { dispatch_index }
            }
            AssignedOperationKind::WriteReturnRegisterInteger { byte_size, value } => {
                Self::WriteReturnRegisterInteger { byte_size, value }
            }
            AssignedOperationKind::TerminateDispatch => Self::TerminateDispatch,
            AssignedOperationKind::LeaveDispatchCase => Self::LeaveDispatchCase,
            AssignedOperationKind::LeaveDispatchLoop => Self::LeaveDispatchLoop,
            AssignedOperationKind::BeginPlatformCall => Self::BeginPlatformCall,
            AssignedOperationKind::HostOperation {
                operation_key,
                operands,
            } => Self::HostOperation {
                operation_key,
                operands,
            },
            AssignedOperationKind::LeaveFunction => Self::LeaveFunction,
        }
    }
}
