use crate::AssignedOperationKind;

impl From<omega_target_operations::TargetOperationKind> for AssignedOperationKind {
    fn from(kind: omega_target_operations::TargetOperationKind) -> Self {
        match kind {
            omega_target_operations::TargetOperationKind::EnterFunction => Self::EnterFunction,
            omega_target_operations::TargetOperationKind::EnterDispatchLoop {
                entry_dispatch_index,
                terminal_dispatch_index,
            } => Self::EnterDispatchLoop {
                entry_dispatch_index,
                terminal_dispatch_index,
            },
            omega_target_operations::TargetOperationKind::EnterDispatchCase { dispatch_index } => {
                Self::EnterDispatchCase { dispatch_index }
            }
            omega_target_operations::TargetOperationKind::EvaluateDispatchGuard {
                guard_lowering,
                operator,
                storage_region,
                byte_offset,
                byte_size,
                expected_value,
                has_storage,
            } => Self::EvaluateDispatchGuard {
                guard_lowering,
                operator,
                storage_region,
                byte_offset,
                byte_size,
                expected_value,
                has_storage,
            },
            omega_target_operations::TargetOperationKind::CompareRuntimeTextLiteral {
                buffer,
                literal,
            } => Self::CompareRuntimeTextLiteral { buffer, literal },
            omega_target_operations::TargetOperationKind::CompareRuntimeTextStorage {
                buffer,
                source_region,
                source_offset,
                operator,
            } => Self::CompareRuntimeTextStorage {
                buffer,
                source_region,
                source_offset,
                operator,
            },
            omega_target_operations::TargetOperationKind::CompareRuntimeStorage {
                left_region,
                left_offset,
                right_region,
                right_offset,
                byte_size,
                operator,
            } => Self::CompareRuntimeStorage {
                left_region,
                left_offset,
                right_region,
                right_offset,
                byte_size,
                operator,
            },
            omega_target_operations::TargetOperationKind::CompareRuntimeStorageValue {
                region,
                byte_offset,
                byte_size,
                expected_value,
                operator,
            } => Self::CompareRuntimeStorageValue {
                region,
                byte_offset,
                byte_size,
                expected_value,
                operator,
            },
            omega_target_operations::TargetOperationKind::CompareRuntimeValues {
                left,
                right,
                byte_size,
                operator,
            } => Self::CompareRuntimeValues {
                left,
                right,
                byte_size,
                operator,
            },
            omega_target_operations::TargetOperationKind::WriteRuntimeTextLiteral {
                buffer,
                literal,
            } => Self::WriteRuntimeTextLiteral { buffer, literal },
            omega_target_operations::TargetOperationKind::WriteRuntimeTextLiteralSegment {
                buffer,
                byte_offset,
                literal,
            } => Self::WriteRuntimeTextLiteralSegment {
                buffer,
                byte_offset,
                literal,
            },
            omega_target_operations::TargetOperationKind::AppendRuntimeTextStoredSuffix {
                buffer,
                buffer_offset,
                source_region,
                source_offset,
                target_region,
                target_offset,
                length_delta,
            } => Self::AppendRuntimeTextStoredSuffix {
                buffer,
                buffer_offset,
                source_region,
                source_offset,
                target_region,
                target_offset,
                length_delta,
            },
            omega_target_operations::TargetOperationKind::MaterializeRuntimeTextBuffer {
                buffer,
                target_region,
                target_offset,
            } => Self::MaterializeRuntimeTextBuffer {
                buffer,
                target_region,
                target_offset,
            },
            omega_target_operations::TargetOperationKind::MaterializeRuntimeTextBufferToRuntimePointee {
                buffer,
                pointer_byte_offset,
                field_byte_offset,
            } => Self::MaterializeRuntimeTextBufferToRuntimePointee {
                buffer,
                pointer_byte_offset,
                field_byte_offset,
            },
            omega_target_operations::TargetOperationKind::MaterializeRuntimeTextBufferToRuntimeFrameIndexed {
                buffer,
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
            } => Self::MaterializeRuntimeTextBufferToRuntimeFrameIndexed {
                buffer,
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
            },
            omega_target_operations::TargetOperationKind::AppendRuntimeTextStoredPlace {
                buffer,
                source_region,
                source_offset,
                target_region,
                target_offset,
            } => Self::AppendRuntimeTextStoredPlace {
                buffer,
                source_region,
                source_offset,
                target_region,
                target_offset,
            },
            omega_target_operations::TargetOperationKind::AppendRuntimeTextStoredPlaceToRuntimePointee {
                buffer,
                source_region,
                source_offset,
                pointer_byte_offset,
                field_byte_offset,
            } => Self::AppendRuntimeTextStoredPlaceToRuntimePointee {
                buffer,
                source_region,
                source_offset,
                pointer_byte_offset,
                field_byte_offset,
            },
            omega_target_operations::TargetOperationKind::AppendRuntimeTextStoredPlaceToRuntimeFrameIndexed {
                buffer,
                source_region,
                source_offset,
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
            } => Self::AppendRuntimeTextStoredPlaceToRuntimeFrameIndexed {
                buffer,
                source_region,
                source_offset,
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
            },
            omega_target_operations::TargetOperationKind::AppendRuntimeTextLiteral {
                buffer,
                target_region,
                target_offset,
                literal,
            } => Self::AppendRuntimeTextLiteral {
                buffer,
                target_region,
                target_offset,
                literal,
            },
            omega_target_operations::TargetOperationKind::AppendRuntimeTextLiteralToRuntimePointee {
                buffer,
                pointer_byte_offset,
                field_byte_offset,
                literal,
            } => Self::AppendRuntimeTextLiteralToRuntimePointee {
                buffer,
                pointer_byte_offset,
                field_byte_offset,
                literal,
            },
            omega_target_operations::TargetOperationKind::AppendRuntimeTextLiteralToRuntimeFrameIndexed {
                buffer,
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                literal,
            } => Self::AppendRuntimeTextLiteralToRuntimeFrameIndexed {
                buffer,
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                literal,
            },
            omega_target_operations::TargetOperationKind::WriteRuntimeMachineInteger {
                byte_offset,
                byte_size,
                value,
            } => Self::WriteRuntimeMachineInteger {
                byte_offset,
                byte_size,
                value,
            },
            omega_target_operations::TargetOperationKind::WriteRuntimeStorageInteger {
                target_region,
                byte_offset,
                byte_size,
                value,
            } => Self::WriteRuntimeStorageInteger {
                target_region,
                byte_offset,
                byte_size,
                value,
            },
            omega_target_operations::TargetOperationKind::WriteRuntimePointeeInteger {
                pointer_byte_offset,
                field_byte_offset,
                byte_size,
                value,
            } => Self::WriteRuntimePointeeInteger {
                pointer_byte_offset,
                field_byte_offset,
                byte_size,
                value,
            },
            omega_target_operations::TargetOperationKind::WriteRuntimeStorageBinary {
                target_region,
                target_offset,
                byte_size,
                left,
                operator,
                right,
            } => Self::WriteRuntimeStorageBinary {
                target_region,
                target_offset,
                byte_size,
                left,
                operator,
                right,
            },
            omega_target_operations::TargetOperationKind::WriteRuntimePointeeBinary {
                pointer_byte_offset,
                field_byte_offset,
                byte_size,
                left,
                operator,
                right,
            } => Self::WriteRuntimePointeeBinary {
                pointer_byte_offset,
                field_byte_offset,
                byte_size,
                left,
                operator,
                right,
            },
            omega_target_operations::TargetOperationKind::WriteRuntimeFrameIndexedInteger {
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                byte_size,
                value,
            } => Self::WriteRuntimeFrameIndexedInteger {
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                byte_size,
                value,
            },
            omega_target_operations::TargetOperationKind::WriteRuntimeFrameBaseIndexedInteger {
                base_byte_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                byte_size,
                value,
            } => Self::WriteRuntimeFrameBaseIndexedInteger {
                base_byte_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                byte_size,
                value,
            },
            omega_target_operations::TargetOperationKind::WriteRuntimeMachineIndexedInteger {
                base_byte_offset,
                index_region,
                index_offset,
                element_byte_size,
                field_byte_offset,
                byte_size,
                value,
            } => Self::WriteRuntimeMachineIndexedInteger {
                base_byte_offset,
                index_region,
                index_offset,
                element_byte_size,
                field_byte_offset,
                byte_size,
                value,
            },
            omega_target_operations::TargetOperationKind::WriteRuntimeFrameIndexedBinary {
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                byte_size,
                left,
                operator,
                right,
            } => Self::WriteRuntimeFrameIndexedBinary {
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                byte_size,
                left,
                operator,
                right,
            },
            omega_target_operations::TargetOperationKind::WriteRuntimeFrameBaseIndexedBinary {
                base_byte_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                byte_size,
                left,
                operator,
                right,
            } => Self::WriteRuntimeFrameBaseIndexedBinary {
                base_byte_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                byte_size,
                left,
                operator,
                right,
            },
            omega_target_operations::TargetOperationKind::WriteRuntimeMachineString {
                byte_offset,
                data,
                byte_length,
            } => Self::WriteRuntimeMachineString {
                byte_offset,
                data,
                byte_length,
            },
            omega_target_operations::TargetOperationKind::WriteRuntimeFrameString {
                byte_offset,
                data,
                byte_length,
            } => Self::WriteRuntimeFrameString {
                byte_offset,
                data,
                byte_length,
            },
            omega_target_operations::TargetOperationKind::WriteRuntimePointeeString {
                pointer_byte_offset,
                field_byte_offset,
                data,
                byte_length,
            } => Self::WriteRuntimePointeeString {
                pointer_byte_offset,
                field_byte_offset,
                data,
                byte_length,
            },
            omega_target_operations::TargetOperationKind::WriteRuntimeFrameIndexedString {
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                data,
                byte_length,
            } => Self::WriteRuntimeFrameIndexedString {
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                data,
                byte_length,
            },
            omega_target_operations::TargetOperationKind::WriteRuntimeMachineIndexedString {
                base_byte_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                data,
                byte_length,
            } => Self::WriteRuntimeMachineIndexedString {
                base_byte_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                data,
                byte_length,
            },
            omega_target_operations::TargetOperationKind::WriteRuntimeStorageAddressToRuntimeFrame {
                source_region,
                source_offset,
                target_offset,
            } => Self::WriteRuntimeStorageAddressToRuntimeFrame {
                source_region,
                source_offset,
                target_offset,
            },
            omega_target_operations::TargetOperationKind::WriteRuntimePointeeAddressToRuntimeFrame {
                pointer_byte_offset,
                field_byte_offset,
                target_offset,
            } => Self::WriteRuntimePointeeAddressToRuntimeFrame {
                pointer_byte_offset,
                field_byte_offset,
                target_offset,
            },
            omega_target_operations::TargetOperationKind::WriteRuntimeFrameIndexedAddressToRuntimeFrame {
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                target_offset,
            } => Self::WriteRuntimeFrameIndexedAddressToRuntimeFrame {
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                target_offset,
            },
            omega_target_operations::TargetOperationKind::WriteRuntimeFrameFixedIndexedAddressToRuntimeFrame {
                descriptor_offset,
                element_index,
                element_byte_size,
                field_byte_offset,
                target_offset,
            } => Self::WriteRuntimeFrameFixedIndexedAddressToRuntimeFrame {
                descriptor_offset,
                element_index,
                element_byte_size,
                field_byte_offset,
                target_offset,
            },
            omega_target_operations::TargetOperationKind::WriteRuntimeFrameBaseIndexedAddressToRuntimeFrame {
                base_byte_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                target_offset,
            } => Self::WriteRuntimeFrameBaseIndexedAddressToRuntimeFrame {
                base_byte_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                target_offset,
            },
            omega_target_operations::TargetOperationKind::ReadRuntimeTextLine {
                buffer,
                target_region,
                target_offset,
                byte_capacity,
                source,
            } => Self::ReadRuntimeTextLine {
                buffer,
                target_region,
                target_offset,
                byte_capacity,
                source,
            },
            omega_target_operations::TargetOperationKind::CopyRuntimeStorage {
                source_region,
                source_offset,
                target_region,
                target_offset,
                byte_count,
            } => Self::CopyRuntimeStorage {
                source_region,
                source_offset,
                target_region,
                target_offset,
                byte_count,
            },
            omega_target_operations::TargetOperationKind::CopyRuntimeStorageToRuntimeFrameIndexed {
                source_region,
                source_offset,
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                byte_count,
            } => Self::CopyRuntimeStorageToRuntimeFrameIndexed {
                source_region,
                source_offset,
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                byte_count,
            },
            omega_target_operations::TargetOperationKind::CopyRuntimeFrameIndexedToRuntimeFrame {
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                target_offset,
                byte_count,
            } => Self::CopyRuntimeFrameIndexedToRuntimeFrame {
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                target_offset,
                byte_count,
            },
            omega_target_operations::TargetOperationKind::CopyRuntimeFrameIndexedToRuntimeStorage {
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                target_region,
                target_offset,
                byte_count,
            } => Self::CopyRuntimeFrameIndexedToRuntimeStorage {
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                target_region,
                target_offset,
                byte_count,
            },
            omega_target_operations::TargetOperationKind::CopyRuntimeFrameFixedIndexedToRuntimeFrame {
                descriptor_offset,
                element_index,
                element_byte_size,
                field_byte_offset,
                target_offset,
                byte_count,
            } => Self::CopyRuntimeFrameFixedIndexedToRuntimeFrame {
                descriptor_offset,
                element_index,
                element_byte_size,
                field_byte_offset,
                target_offset,
                byte_count,
            },
            omega_target_operations::TargetOperationKind::CopyRuntimeFrameFixedIndexedToRuntimeStorage {
                descriptor_offset,
                element_index,
                element_byte_size,
                field_byte_offset,
                target_region,
                target_offset,
                byte_count,
            } => Self::CopyRuntimeFrameFixedIndexedToRuntimeStorage {
                descriptor_offset,
                element_index,
                element_byte_size,
                field_byte_offset,
                target_region,
                target_offset,
                byte_count,
            },
            omega_target_operations::TargetOperationKind::CopyRuntimeFrameFixedIndexedToRuntimePointee {
                descriptor_offset,
                element_index,
                element_byte_size,
                source_field_byte_offset,
                pointer_byte_offset,
                target_field_byte_offset,
                byte_count,
            } => Self::CopyRuntimeFrameFixedIndexedToRuntimePointee {
                descriptor_offset,
                element_index,
                element_byte_size,
                source_field_byte_offset,
                pointer_byte_offset,
                target_field_byte_offset,
                byte_count,
            },
            omega_target_operations::TargetOperationKind::CopyRuntimeMachineIndexedToRuntimeStorage {
                base_byte_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                target_region,
                target_offset,
                byte_count,
            } => Self::CopyRuntimeMachineIndexedToRuntimeStorage {
                base_byte_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                target_region,
                target_offset,
                byte_count,
            },
            omega_target_operations::TargetOperationKind::CopyRuntimeStorageToRuntimePointee {
                source_region,
                source_offset,
                pointer_byte_offset,
                field_byte_offset,
                byte_count,
            } => Self::CopyRuntimeStorageToRuntimePointee {
                source_region,
                source_offset,
                pointer_byte_offset,
                field_byte_offset,
                byte_count,
            },
            omega_target_operations::TargetOperationKind::CopyRuntimePointeeToRuntimeFrame {
                pointer_byte_offset,
                field_byte_offset,
                target_offset,
                byte_count,
            } => Self::CopyRuntimePointeeToRuntimeFrame {
                pointer_byte_offset,
                field_byte_offset,
                target_offset,
                byte_count,
            },
            omega_target_operations::TargetOperationKind::SetDispatchState { dispatch_index } => {
                Self::SetDispatchState { dispatch_index }
            }
            omega_target_operations::TargetOperationKind::WriteReturnRegisterInteger {
                byte_size,
                value,
            } => Self::WriteReturnRegisterInteger { byte_size, value },
            omega_target_operations::TargetOperationKind::TerminateDispatch => Self::TerminateDispatch,
            omega_target_operations::TargetOperationKind::LeaveDispatchCase => Self::LeaveDispatchCase,
            omega_target_operations::TargetOperationKind::LeaveDispatchLoop => Self::LeaveDispatchLoop,
            omega_target_operations::TargetOperationKind::BeginPlatformCall => Self::BeginPlatformCall,
            omega_target_operations::TargetOperationKind::HostOperation {
                operation_key,
                operands,
            } => Self::HostOperation {
                operation_key,
                operands,
            },
            omega_target_operations::TargetOperationKind::LeaveFunction => Self::LeaveFunction,
        }
    }
}
