#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum StraightLineWrappingIntegerShiftRightParametersTranslationError {
    SourceParameters,
    SourceStructuralParameters,
    SourceResult,
    SourceEntryClaims,
    SourcePublishedServices,
    SourceBlockRoster,
    SourceOperationRoster,
    SourceParameterRoster,
    SourceParameterShape,
    SourceShiftResultRoster,
    SourceValueOperandLink,
    SourceCountOperandLink,
    SourceValueTypeMismatch,
    SourceCountTypeMismatch,
    SourceReturnLink,
    SourceCleanup,
    AbiPlan,
    AbiParameterCount,
    AbiParameterPlacement,
    TargetProvenance,
    TargetOperation,
}
