#![forbid(unsafe_code)]

//! Optimizer module role: crate map. Selected-program rewrites before register assignment.
//!
//! Rewrites operate on the selected CFG and reconstruct the analyses they
//! invalidate. Register assignment consumes the resulting current program.
//!
//! Start at [`optimize_selected_instructions`] in `selected_optimization.rs`:
//! liveness and live ranges from [`analyses`], then either the identity route
//! or the selected-lowering [`rewrites`] under allocation legality, published
//! as one [`SelectedInstructionOptimizationOutput`] from
//! `selected_optimization::optimization_output`.

mod analyses;
mod peepholes;
mod rewrites;
mod selected_optimization;

pub use analyses::{
    AllocationLegalityError, AllocationLegalityValidationReceipt, AllocatorAvailabilityError,
    AllocatorAvailabilityValidationReceipt, BlockMachineEffects, FixedPrecoloredIntervalError,
    FixedPrecoloredIntervalValidationReceipt, FixedPrecoloredSegmentHomeError,
    FixedPrecoloredSegmentHomeValidationReceipt, FixedPrecoloredSplitRequirementError,
    FixedPrecoloredSplitRequirementValidationReceipt, FunctionMachineEffects,
    InstructionMachineEffects, LiveRangeError, LiveRangeValidationReceipt, LivenessError,
    LivenessValidationReceipt, MachineEffectError, MachineEffectStageError,
    OptimizedAllocationLegalityCustodyError, OptimizedLiveRangeCustodyError,
    OptimizedLivenessCustodyError, OptimizedSelectedReanalysisError, OwnedSelectedProgram,
    PreAllocationMachineEffectDecodeError, PreAllocationMachineEffectIdentity,
    PreAllocationMachineEffectPlan, PreAllocationMachineEffectReceipt, RecoveryClassificationError,
    RecoveryClassificationValidationReceipt, SelectedProgramRef, SpillChoiceError,
    SpillChoiceValidationReceipt, StagedOptimizedAllocationLegality,
    StagedOptimizedAllocationLegalityCustodyReceipt, StagedOptimizedLiveRangeCustodyReceipt,
    StagedOptimizedLiveRanges, StagedOptimizedLiveness, StagedOptimizedLivenessCustodyReceipt,
    StagedOptimizedSelectedReanalysis, StagedOptimizedSelectedReanalysisCustodyReceipt,
    ValidatedAllocationLegality, ValidatedAllocatorAvailability, ValidatedFixedPrecoloredIntervals,
    ValidatedFixedPrecoloredSegmentHomes, ValidatedFixedPrecoloredSplitRequirements,
    ValidatedLiveRanges, ValidatedLiveness, ValidatedPreAllocationMachineEffects,
    ValidatedRecoveryClassifications, ValidatedSelectedAnalysis, ValidatedSpillChoices,
    analyze_allocation_legality, analyze_fixed_precolored_intervals,
    analyze_fixed_precolored_split_requirements, analyze_live_ranges, analyze_live_ranges_reusing,
    analyze_liveness, analyze_liveness_reusing, analyze_machine_effects,
    analyze_pre_allocation_machine_effects, assign_fixed_precolored_segment_homes,
    choose_spill_victims, classify_pressure_recovery, materialize_allocator_availability,
    pre_allocation_machine_effect_identity, stage_optimized_allocation_legality,
    stage_optimized_allocation_legality_for_active_resident_immediate_u64_multi_use_rematerialization_v1,
    stage_optimized_allocation_legality_for_frameless_leaf,
    stage_optimized_allocation_legality_with_availability, stage_optimized_live_ranges,
    stage_optimized_liveness, stage_optimized_selected_reanalysis, validate_allocation_legality,
    validate_allocator_availability, validate_fixed_precolored_intervals,
    validate_fixed_precolored_segment_homes, validate_fixed_precolored_split_requirements,
    validate_live_ranges, validate_liveness, validate_machine_effects,
    validate_optimized_allocation_legality_custody, validate_optimized_live_range_custody,
    validate_optimized_liveness_custody, validate_optimized_selected_reanalysis_custody,
    validate_pre_allocation_machine_effects, validate_recovery_classifications,
    validate_spill_choices, validate_staged_optimized_liveness_custody,
    validated_machine_effect_catalog,
};
#[cfg(any(test, feature = "test-support"))]
pub use analyses::{
    OptimizedAllocationLegalityCustodyFieldForTest, OptimizedLiveRangeCustodyFieldForTest,
    OptimizedLivenessCustodyFieldForTest, OptimizedSelectedReanalysisCustodyFieldForTest,
};
pub use peepholes::{
    ConditionMaterializationError, ConditionMaterializationReceipt, CopiedCallOperandError,
    CopiedCallOperandReceipt, ProjectedAccessError, ProjectedAccessReceipt, TerminatorPairError,
    TerminatorPairReceipt, ValidatedConditionMaterialization, ValidatedCopiedCallOperand,
    ValidatedProjectedAccess, ValidatedTerminatorPair, fold_selected_condition_materialization,
    fold_selected_copied_call_operand, fold_selected_projected_access,
    fold_selected_terminator_pair, validate_condition_materialization_fold,
    validate_copied_call_operand_fold, validate_projected_access_fold,
    validate_terminator_pair_fold,
};
pub use rewrites::{
    ALLOCATION_RECOVERY_RULE_CATALOG, AddressFoldError, AddressFoldReceipt,
    AllocationRecoveryRuleCatalogEntry, AllocationRecoveryRuleCatalogError,
    AllocationRecoveryRuleCatalogPayload, ArmRelocationError, ArmRelocationReceipt,
    BoundaryBooleanError, BoundaryBooleanReceipt, BoundaryBranchError, BoundaryBranchReceipt,
    BypassRelocationError, BypassRelocationReceipt, BypassRunRelocationError,
    BypassRunRelocationReceipt, CommutingInterchangeError, CommutingInterchangeReceipt,
    CommutingMemberRunInterchangeError, CommutingMemberRunInterchangeReceipt,
    CommutingRelocationError, CommutingRelocationReceipt, CommutingRunInterchangeError,
    CommutingRunInterchangeReceipt, CommutingRunRelocationError, CommutingRunRelocationReceipt,
    ConfluenceRelocationError, ConfluenceRelocationReceipt, ConfluenceRunRelocationError,
    ConfluenceRunRelocationReceipt, ConstantBooleanError, ConstantBooleanReceipt,
    ConstantBranchError, ConstantBranchReceipt, CopyRemovalError, CopyRemovalReceipt,
    DeadCompareError, DeadCompareReceipt, DeadStoreEliminationError, DeadStoreEliminationReceipt,
    DiamondRelocationError, DiamondRelocationReceipt, DiamondRunRelocationError,
    DiamondRunRelocationReceipt, EdgeRelocationError, EdgeRelocationReceipt,
    EdgeRunRelocationError, EdgeRunRelocationReceipt, EquivalentCompareError,
    EquivalentCompareReceipt, FixedPrecoloredSegmentHomeDecline, FixedViewCopy,
    FixedViewCopyDecodeError, FixedViewCopyDestination, FixedViewCopyError, FixedViewCopyPlan,
    FixedViewCopyPolicy, FixedViewCopySourceEvidence, FixedViewCopyValidationReceipt,
    ForkRelocationError, ForkRelocationReceipt, ForkRunRelocationError, ForkRunRelocationReceipt,
    FunctionLiteralFold, FunctionPressureRematerialization, InflowRelocationError,
    InflowRelocationReceipt, JoinRelocationError, JoinRelocationReceipt, LiteralFoldAction,
    LiteralFoldDecodeError, LiteralFoldError, LiteralFoldIdentity, LiteralFoldPlan,
    LiteralFoldPolicy, LiteralFoldValidationReceipt, LocalRelocationError, LocalRelocationReceipt,
    LocalScheduleError, LocalScheduleReceipt, MemberRunInterchangeError,
    MemberRunInterchangeReceipt, MemberRunRelocationError, MemberRunRelocationReceipt,
    ORDERED_ALLOCATION_RECOVERY_RULES, ORDERED_SELECTED_LOWERING_RULES,
    OptimizedFixedPrecoloredSegmentHomeCustodyError, OptimizedFixedViewCopyCustodyError,
    OptimizedLiteralFoldCustodyError, PairConsumerBindingAdmission, PairFaultDischarge,
    PairImmediateBound, PairLiteralPosition, PairMachineEffects, PairNonUnitSurface,
    PairOperandResult, PairOperandShape, PairResultDisposition, PairTailCustody,
    PairUnitDefRelation, PairUnitEffects, PredecessorRelocationError, PredecessorRelocationReceipt,
    PredecessorRunRelocationError, PredecessorRunRelocationReceipt,
    PressureRematerializationAction, PressureRematerializationDecodeError,
    PressureRematerializationError, PressureRematerializationPlan, PressureRematerializationPolicy,
    PressureRematerializationRewrite, PressureRematerializationValidationReceipt,
    RedundantCompareError, RedundantCompareReceipt, RedundantExtensionError,
    RedundantExtensionReceipt, RegisterAllocationRuleTargetApplicability, RunInterchangeError,
    RunInterchangeReceipt, RunRelocationError, RunRelocationReceipt, RuntimeRematerializationError,
    RuntimeRematerializationReceipt, RuntimeSpillError, RuntimeSpillReceipt,
    RuntimeSpillSpanPolicy, SELECTED_LOWERING_RULE_CATALOG, SELECTED_STAGE_RULE_CATALOG,
    ScheduledRelocationError, ScheduledRelocationReceipt, SelectedInstructionPairRule,
    SelectedLoweringRuleCatalogEntry, SelectedLoweringRuleCatalogError,
    SelectedLoweringRuleCatalogPayload, SelectedStageRuleCatalogSlice, SelectedStageRuleRows,
    StagedOptimizedFixedPrecoloredSegmentHomeCustodyReceipt,
    StagedOptimizedFixedPrecoloredSegmentHomes, StagedOptimizedFixedViewCopies,
    StagedOptimizedFixedViewCopyCustodyReceipt, StagedOptimizedLiteralFoldAttempt,
    StagedOptimizedLiteralFoldAttemptReceipt, StagedOptimizedLiteralFoldCustodyReceipt,
    StagedOptimizedLiteralFoldIterationReceipt, StagedOptimizedLiteralFoldStep,
    StagedOptimizedLiteralFolds, StagedSelectedLoweringOptimizationCustodyReceipt,
    StagedSelectedLoweringOptimizationRun, StoreMutationMotionError, StoreMutationMotionReceipt,
    StoredLoadForwardingError, StoredLoadForwardingReceipt, TriangleRelocationError,
    TriangleRelocationReceipt, ValidatedAddressFold, ValidatedArmRelocation,
    ValidatedBoundaryBoolean, ValidatedBoundaryBranch, ValidatedBypassRelocation,
    ValidatedBypassRunRelocation, ValidatedCommutingInterchange,
    ValidatedCommutingMemberRunInterchange, ValidatedCommutingRelocation,
    ValidatedCommutingRunInterchange, ValidatedCommutingRunRelocation,
    ValidatedConfluenceRelocation, ValidatedConfluenceRunRelocation, ValidatedConstantBoolean,
    ValidatedConstantBranch, ValidatedCopyRemoval, ValidatedDeadCompare,
    ValidatedDeadStoreElimination, ValidatedDiamondRelocation, ValidatedDiamondRunRelocation,
    ValidatedEdgeRelocation, ValidatedEdgeRunRelocation, ValidatedEquivalentCompare,
    ValidatedFixedViewCopies, ValidatedForkRelocation, ValidatedForkRunRelocation,
    ValidatedInflowRelocation, ValidatedJoinRelocation, ValidatedLiteralFold,
    ValidatedLocalRelocation, ValidatedLocalSchedule, ValidatedMemberRunInterchange,
    ValidatedMemberRunRelocation, ValidatedPredecessorRelocation,
    ValidatedPredecessorRunRelocation, ValidatedPressureRematerialization,
    ValidatedRedundantCompare, ValidatedRedundantExtension, ValidatedRunInterchange,
    ValidatedRunRelocation, ValidatedRuntimeRematerialization, ValidatedRuntimeSpill,
    ValidatedScheduledRelocation, ValidatedStoreMutationMotion, ValidatedStoredLoadForwarding,
    ValidatedTriangleRelocation, eliminate_selected_dead_store, enabled_pair_rules,
    fixed_view_copy_identity, fold_selected_address, fold_selected_boundary_boolean,
    fold_selected_boundary_branch, fold_selected_constant_boolean, fold_selected_constant_branch,
    fold_selected_incoming_literal, forward_selected_stored_load,
    interchange_selected_commuting_member_and_run, interchange_selected_commuting_pair,
    interchange_selected_commuting_runs, interchange_selected_member_and_run,
    interchange_selected_runs, literal_fold_identity, materialize_fixed_view_copies,
    pressure_rematerialization_identity, probe_optimized_fixed_precolored_segment_homes,
    relocate_scheduled_run, relocate_selected_commuting_member, relocate_selected_commuting_run,
    relocate_selected_instruction, relocate_selected_instruction_across_edge,
    relocate_selected_instruction_into_arm, relocate_selected_instruction_into_confluence,
    relocate_selected_instruction_into_predecessor, relocate_selected_instruction_onto_inflow,
    relocate_selected_instruction_out_of_arm, relocate_selected_instruction_out_of_join,
    relocate_selected_instruction_out_of_triangle, relocate_selected_instruction_through_bypass,
    relocate_selected_instruction_through_diamond, relocate_selected_member_run,
    relocate_selected_run, relocate_selected_run_across_edge, relocate_selected_run_into_arm,
    relocate_selected_run_into_confluence, relocate_selected_run_into_predecessor,
    relocate_selected_run_through_bypass, relocate_selected_run_through_diamond,
    rematerialize_selected_active_resident, rematerialize_selected_runtime_value,
    remove_dead_compare, remove_equivalent_compare, remove_redundant_compare, remove_selected_copy,
    remove_selected_redundant_extension, resolve_selected_lowering_rules,
    run_selected_lowering_optimizations, schedule_selected_pair, selected_allocation_recovery_rule,
    selected_stage_catalog_contains, selected_stage_rule_rows, sink_selected_store_mutation,
    spill_selected_runtime_value, spill_selected_runtime_value_with_span_policy,
    stage_first_optimized_literal_fold, stage_next_optimized_literal_fold,
    stage_optimized_fixed_precolored_segment_homes, stage_optimized_fixed_view_copies,
    validate_address_fold, validate_arm_relocation, validate_boundary_boolean_fold,
    validate_boundary_branch_fold, validate_bypass_relocation, validate_bypass_run_relocation,
    validate_commuting_interchange, validate_commuting_member_run_interchange,
    validate_commuting_relocation, validate_commuting_run_interchange,
    validate_commuting_run_relocation, validate_confluence_relocation,
    validate_confluence_run_relocation, validate_constant_boolean_fold,
    validate_constant_branch_fold, validate_copy_removal, validate_dead_compare,
    validate_dead_store_elimination, validate_diamond_relocation, validate_diamond_run_relocation,
    validate_edge_relocation, validate_edge_run_relocation, validate_equivalent_compare,
    validate_fixed_view_copies, validate_fork_relocation, validate_fork_run_relocation,
    validate_inflow_relocation, validate_join_relocation, validate_literal_fold,
    validate_local_relocation, validate_local_schedule, validate_member_run_interchange,
    validate_member_run_relocation, validate_optimized_fixed_precolored_segment_home_custody,
    validate_optimized_fixed_view_copy_custody, validate_optimized_literal_fold_custody,
    validate_predecessor_relocation, validate_predecessor_run_relocation,
    validate_pressure_rematerialization, validate_redundant_compare,
    validate_redundant_extension_removal, validate_run_interchange, validate_run_relocation,
    validate_runtime_rematerialization, validate_runtime_spill,
    validate_runtime_spill_with_span_policy, validate_scheduled_relocation,
    validate_selected_lowering_optimization_custody, validate_store_mutation_motion,
    validate_stored_load_forwarding, validate_triangle_relocation,
};
#[cfg(any(test, feature = "test-support"))]
pub use rewrites::{
    OptimizedFixedPrecoloredSegmentHomeCustodyFieldForTest,
    OptimizedFixedViewCopyCustodyFieldForTest, OptimizedLiteralFoldCustodyFieldForTest,
    SelectedLoweringOptimizationCustodyFieldForTest,
};
pub use selected_optimization::optimization_output::{
    SelectedInstructionOptimizationError, SelectedInstructionOptimizationEvidence,
    SelectedInstructionOptimizationOutput,
};
pub use selected_optimization::optimize_selected_instructions;

#[cfg(any(test, feature = "test-support"))]
pub use rewrites::test_support;

// Durable transform-output identities live with the selected-instruction
// representation; the transform publishes them under its root so callers keep
// one vocabulary.
pub use selected_instructions::{FixedViewCopyIdentity, PressureRematerializationIdentity};
