[package]
name = "omega-runtime-text"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_runtime_text"
path = "src/lib.rs"

[dependencies]
psi-checked-trees = { path = "../../../psi/representations/psi-checked-trees" }
omega-control-flow = { path = "../../representations/omega-control-flow" }
omega-calling-conventions = { path = "../../foundation/omega-calling-conventions" }
psi-arena = { path = "../../../psi/foundation/psi-arena" }
omega-platform-interface = { path = "../omega-platform-interface" }
omega-state-storage = { path = "../omega-state-storage" }
