[package]
name = "omega-page-tables"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_page_tables"
path = "src/lib.rs"

[dependencies]
omega-extents = { path = "../../foundation/omega-extents" }
omega-layout-plans = { path = "../../foundation/omega-layout-plans" }
