[package]
name = "omega-abstract-operations-to-target-operations"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_abstract_operations_to_target_operations"
path = "src/lib.rs"

[dependencies]
omega-abstract-operations = { path = "../../representations/omega-abstract-operations" }
omega-calling-conventions = { path = "../../backend/omega-calling-conventions" }
omega-core = { path = "../../foundation/omega-core" }
omega-platform-interface = { path = "../../backend/omega-platform-interface" }
omega-target = { path = "../../backend/omega-target" }
omega-target-operations = { path = "../../representations/omega-target-operations" }
