[package]
name = "omega-target-operations-to-machine-program"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_target_operations_to_machine_program"
path = "src/lib.rs"

[dependencies]
omega-core = { path = "../../foundation/omega-core" }
omega-machine-program = { path = "../../representations/omega-machine-program" }
omega-target-operations = { path = "../../representations/omega-target-operations" }
