[package]
name = "omega-target-operations-to-machine-program"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_target_operations_to_machine_program"
path = "src/lib.rs"

[dependencies]
omega-assigned-target-operations-to-machine-instructions = { path = "../omega-assigned-target-operations-to-machine-instructions" }
psi-symbols = { path = "../../../psi/foundation/psi-symbols" }
omega-machine-instructions = { path = "../../representations/omega-machine-instructions" }
omega-machine-program = { path = "../../representations/omega-machine-program" }
psi-diagnostics = { path = "../../../psi/foundation/psi-diagnostics" }
psi-language-semantics = { path = "../../../psi/foundation/psi-language-semantics" }
omega-target-operations-to-assigned-target-operations = { path = "../omega-target-operations-to-assigned-target-operations" }
omega-target-operations = { path = "../../representations/omega-target-operations" }

[dev-dependencies]
omega-abstract-operations = { path = "../../representations/omega-abstract-operations" }
