#![forbid(unsafe_code)]

//! Target machine-code programs and their independently replayable records.
//!
//! Start at [`machine_code::MachineCodePlan`]. Its subordinate owners separate
//! functions, calls, storage, control flow, ownership, and boundary evidence.
//! Data construction alone does not grant execution or publication authority.

pub mod machine_code;
pub use machine_code::{
    Aarch64ForeignCallFloatingControlRecord, Aarch64ReturnLinkEvidence,
    BooleanStructuralConditionEvidence, BooleanStructuralFieldRead,
    BoundaryByteSequenceArgumentRecord, BoundaryExecutionRecord, BoundaryResultRecord,
    BoundaryScalarResultRecord, BoundarySettlementRecord, BoundaryStructuralResultRecord,
    CallbackAddressDestination, CallbackAddressEncoding, CallbackAddressMaterialization,
    CalleeSaveFrameSlot, CompilerPrivateMachineCodeFunction, CompletionProviderCustodyBinding,
    DeferredControlEncodingReason, DynamicCallRecord, DynamicInstanceMaterializationRecord,
    DynamicParameterCallMechanismRecord, DynamicParameterCallRecord, DynamicTableAddressEncoding,
    DynamicTableAddressMaterialization, DynamicTraitDescriptorAbiRecord, ForeignCallRelocation,
    ForeignCallScalarArgumentRecord, ForeignCallScalarResultRecord,
    ForwardedDynamicDescriptorAdapterIdentity, ForwardedDynamicDescriptorAdapterRecord,
    ForwardedDynamicDescriptorArgumentRecord, ForwardedDynamicDescriptorCallRecord,
    ForwardedDynamicParameterCallRecord, ForwardedDynamicParameterCallStackEvidence,
    FrameProtocolByteSpan, FrameUnwindPlan, FrameUnwindRestore, FunctionAppliedFrameEpilogue,
    FunctionAppliedFrameProtocol, FunctionFragment, FunctionFragmentBlockSpan,
    FunctionFragmentBranchEvidence, FunctionFragmentConditionalBranchEvidence,
    FunctionFragmentConditionalBranchPredicate, FunctionFragmentControlProvenance,
    FunctionFragmentEmissionManifest, FunctionFragmentEmissionManifestDecodeError,
    FunctionFragmentEmissionPlan, FunctionFragmentEmissionStage,
    FunctionFragmentEmissionStatistics, FunctionFragmentEmissionUnavailableData,
    FunctionFragmentFrameApplication, FunctionFragmentFrameApplicationIdentity,
    FunctionFragmentInstructionSpan, FunctionFragmentInternalMachineFixup,
    FunctionFragmentInternalMachineFixupKind, FunctionFragmentInternalMachineFixupState,
    FunctionFragmentJumpEvidence, FunctionFragmentNormalizedForeignCallFixup,
    FunctionFragmentNormalizedForeignCallFixupKind,
    FunctionFragmentNormalizedForeignCallFixupState, FunctionFragmentSuccessorProvenance,
    FunctionFragmentTextSectionManifest, FunctionFragmentTextSectionManifestDecodeError,
    FunctionFragmentTextSectionStage, FunctionFragmentTextSectionStatistics,
    FunctionFragmentTextSectionUnavailableData, FunctionNonAuthoritativeCalleeSaveStorage,
    FunctionSpillFrameRequirements, FunctionTargetFrameLayout, FunctionTargetFrameProtocolEncoding,
    InstalledProviderUnitScalarCallRecord, InternalCallRelocation,
    InternalMachineCallResolutionKind, InternalMachineCallResolutionState,
    InternalStructuralCallResult, InternalStructuralResultHomeRecord,
    InternalUnitCallArgumentRecord, InternalUnitCallRecord, InternalUnitCallSource,
    InternalUnitScalarArgumentSourceRecord, InternalUnitScalarCallArgumentRecord,
    InternalUnitScalarCallRecord, InternalUnitScalarCallResultRecord,
    InternalUnitStructuralArgumentSourceRecord, LocalStorageFrameSlot, MachineCodeFunction,
    MachineCodePlan, MachineCodePlanWithPrivateFunctions, NonAuthoritativeCalleeSaveSlot,
    NonAuthoritativeCalleeSaveSlotId, NonAuthoritativeCalleeSaveStorageIdentity,
    NonAuthoritativeCalleeSaveStoragePlan, NonAuthoritativeCalleeSaveStoragePolicy,
    NonAuthoritativeSpillFrameRequirementIdentity, NonAuthoritativeSpillFrameRequirementPlan,
    NonAuthoritativeSpillFrameRequirementPolicy, NormalizedForeignCallResolutionKind,
    NormalizedForeignCallResolutionState, OutgoingAbiFrameArea, ParameterFunctionAbiRecord,
    PlacedBlockSpan, PlacedFunctionFragment, PlacedInstructionSpan,
    PlacedInternalMachineCallResolution, PlacedNormalizedForeignCallResolution, PortEffectRecord,
    ProviderExecutionRecord, RelocationFreeTextSectionPlacement, ResolvedBranchEvidence,
    ResolvedConditionalBranchEvidence, ResolvedConditionalBranchPredicate, ResolvedJumpEvidence,
    ResolvedMachineLayout, ResolvedMachineProgram, ResolvedPhysicalAddress,
    ResolvedSelectedBlockLayout, ResolvedSelectedFormLayoutIdentity, ResolvedSelectedFormRow,
    ResolvedSelectedFunctionLayout, ReturnAddressFrameCustody, ScalarCallStackEvidence,
    ScalarCleanupPreservationEvidence, ScalarConditionalBranchEvidence, ScalarConditionalCondition,
    ScalarControlAffineCleanupRecord, ScalarControlBlockEvidence, ScalarControlFlowEvidence,
    ScalarControlTerminatorEvidence, ScalarDirectConditionalBranchEvidence,
    ScalarDivisionBranchEvidence, ScalarJoinBranchEvidence, ScalarStackEvidence,
    ScalarStackMutation, ScalarStackMutationKind, ScalarStructuralScalarFieldStoreRecord,
    SelectedFormDecodedFootprint, SelectedFormEncoding, SelectedFormEncodingCounts,
    SelectedFormEncodingIdentity, SelectedFormEncodingRow, SelectedFormEncodingState,
    SelectedFormInternalMachineFixup, SelectedFormInternalMachineFixupKind,
    SelectedFormInternalMachineFixupState, SelectedFormMachineDisposition,
    SelectedFormMachineOptimizationCustody, SelectedFormMovnOptimizationCustody,
    SelectedFormNormalizedForeignCallFixup, SelectedFormNormalizedForeignCallFixupKind,
    SelectedFormNormalizedForeignCallFixupState, SelectedFunctionLayoutPolicy,
    SemanticCodeAttribution, SemanticCodeSite, StackAdjustmentPair, StackProbePlan,
    StoredDynamicCallRecord, StoredDynamicDescriptorMaterializationRecord,
    StructuralCallScalarReturnEvidence, StructuralReturnRecord, StructuralSourceLocation,
    TargetFrameLayoutIdentity, TargetFrameLayoutPlan, TargetFrameLayoutPolicy,
    TargetFrameProtocolEncodingIdentity, TargetFrameProtocolEncodingPlan,
    TargetFrameProtocolEncodingPolicy, TextSectionPlacementPolicy,
    TextSectionRelocationRequirements, UnitAffineCleanupRecord,
    UnitAffineScalarRecordEstablishmentRecord, UnitCallStackEvidence, UnitContinuationRecord,
    UnitEntryRegisterSpillRecord, UnitIntegerConstantRecord, UnitParameterHomeRecord,
    UnitParameterRecord, UnitScalarHomeRecord, UnitScalarParameterLocationRecord,
    UnitStackEvidence, UnitStructuralScalarFieldStoreRecord, UnitWriteOnlyPrimitiveStoreRecord,
    UnitWriteOnlyPrimitiveStoreSourceRecord, WholeFunctionCrashEvidence,
    WholeFunctionEntryAssumption, WholeFunctionExitContract, WholeFunctionExitContractIdentity,
    WholeFunctionExitEvidence, WholeFunctionExitLayoutCustody, WholeFunctionExitPolicy,
    WholeFunctionFrameDisposition, WholeFunctionHardeningPolicy, WholeFunctionProcessExitEvidence,
    WholeFunctionReturnEvidence, WholeFunctionReturnFragmentEvidence, WholeFunctionReturnMechanism,
    WholeFunctionReturnValueEvidence, X86BranchRelaxationIdentity, X86FloatingControlRecord,
    X86ForeignCallFloatingControlRecord, X86ScalarFmaFormat, X86ScalarFmaFragment,
    X86ScalarFmaOccurrenceRecord, X86ScalarFmaOperandRecord, arguments, boundary, callbacks, calls,
    control_flow, derive_completion_provider_custody, dynamic, encoding, execution, exit_contract,
    fixups, foreign, fragments, frame_application, frame_identity, frame_layout, frame_protocol,
    function_fragment_emission_identity, function_fragment_frame_application_identity, functions,
    identity, instructions, internal, layout, ownership, parameters, ports, provenance,
    publication, relocation_free_text_section_identity, resolved_machine_layout_identity, results,
    scalars, settlements, stack, storage, stores, target_frame_layout_identity,
    target_frame_protocol_encoding_identity, whole_function_exit_contract_identity, x86_fma,
    x86_scalar_fma_fragment_identity,
};
