[package]
name = "omega-liveness-to-live-ranges"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_liveness_to_live_ranges"
path = "src/lib.rs"

[dependencies]
omega-optimization-core = { path = "../../representations/omega-optimization-core" }
omega-register-model = { path = "../../representations/omega-register-model" }
omega-regalloc = { path = "../omega-regalloc" }
omega-selected-instructions = { path = "../../representations/omega-selected-instructions" }
omega-selected-instructions-to-liveness = { path = "../omega-selected-instructions-to-liveness" }
omega-target = { path = "../../representations/omega-target" }
psi-core = { path = "../../../psi/foundation/psi-core" }
psi-terminal = { path = "../../../psi/representations/psi-terminal" }
