[package]
name = "omega-target-to-register-environment"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_target_to_register_environment"
path = "src/lib.rs"

[dependencies]
omega-register-model = { path = "../../representations/omega-register-model" }
omega-selected-instructions = { path = "../../representations/omega-selected-instructions" }
omega-target = { path = "../../representations/omega-target" }
omega-target-operations = { path = "../../representations/omega-target-operations" }
omega-isa-aarch64 = { path = "../../backend/instruction_set_architectures/omega-isa-aarch64" }
omega-isa-x86_64 = { path = "../../backend/instruction_set_architectures/omega-isa-x86_64" }
