[package]
name = "omega-machine-bytes"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_machine_bytes"
path = "src/lib.rs"

[dependencies]
omega-control-flow = { path = "../omega-control-flow" }
psi-arena = { path = "../../../psi-rs/foundation/psi-arena" }
psi-language-core = { path = "../../../psi-rs/foundation/psi-language-core" }
omega-machine-instructions = { path = "../omega-machine-instructions" }
omega-target-operations = { path = "../omega-target-operations" }
omega-target = { path = "../../foundation/omega-target" }
