[package]
name = "omega-image"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_image"
path = "src/lib.rs"

[dependencies]
omega-calling-conventions = { path = "../../../representations/omega-calling-conventions" }
omega-function-identity = { path = "../../../representations/omega-function-identity" }
psi-arena = { path = "../../../../psi/foundation/psi-arena" }
psi-diagnostics = { path = "../../../../psi/foundation/psi-diagnostics" }
omega-object-file = { path = "../../object/omega-object-file" }
omega-target = { path = "../../../representations/omega-target" }
sha2 = "0.10.9"
