//! Target-neutral external-entry stack context and epoch plans.
//!
//! These carriers describe the finite shape a target/provider claims. The
//! validated wrapper proves only structural closure and canonical identity;
//! installation still has to bind the plan to sealed target facts, emitted
//! adapter bytes, or an admitted opaque-provider receipt.

use crate::{EntryStack, PlanDiagnostic, Preemption};

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct ArrivalContextId(u64);

impl ArrivalContextId {
    pub const fn new(value: u64) -> Option<Self> {
        if value == 0 { None } else { Some(Self(value)) }
    }

    pub const fn get(self) -> u64 {
        self.0
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum StackDomainRef {
    Interrupted,
    Dedicated { class: u16 },
    ProviderSelected,
}

impl From<EntryStack> for StackDomainRef {
    fn from(value: EntryStack) -> Self {
        match value {
            EntryStack::Interrupted => Self::Interrupted,
            EntryStack::Dedicated { class } => Self::Dedicated { class },
            EntryStack::ProviderSelected => Self::ProviderSelected,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EntryStackStage {
    Enter,
    Body,
    Exit,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct StackOccupancy {
    pub domain: StackDomainRef,
    pub bytes: u64,
    pub alignment: u64,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EntryStackEpoch {
    pub stage: EntryStackStage,
    pub active_domain: StackDomainRef,
    pub occupancy_by_domain: Vec<StackOccupancy>,
    pub nesting: Preemption,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ArrivalContextRealization {
    pub context: ArrivalContextId,
    pub epochs: Vec<EntryStackEpoch>,
}

/// The body stack selected for one admissible arrival context.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ArrivalContextStackDomain {
    pub context: ArrivalContextId,
    pub domain: StackDomainRef,
}

/// Exact finite context-to-body-domain closure for one public `EntryStack`
/// disposition. Validation proves shape and fixed-stack agreement only;
/// installation still has to bind it to sealed target facts, generated bytes,
/// or admitted provider evidence.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ValidatedEntryStackDomainClosure {
    boundary_stack: EntryStack,
    contexts: Vec<ArrivalContextStackDomain>,
    non_authoritative_report_fingerprint: u64,
}

impl ValidatedEntryStackDomainClosure {
    pub const fn boundary_stack(&self) -> EntryStack {
        self.boundary_stack
    }

    pub fn contexts(&self) -> &[ArrivalContextStackDomain] {
        &self.contexts
    }

    /// Compact report/cache coordinate. Exact closure authority remains in
    /// `boundary_stack` and `contexts`.
    pub const fn report_fingerprint(&self) -> u64 {
        self.non_authoritative_report_fingerprint
    }
}

pub fn validate_entry_stack_domain_closure(
    boundary_stack: EntryStack,
    mut contexts: Vec<ArrivalContextStackDomain>,
) -> Result<ValidatedEntryStackDomainClosure, PlanDiagnostic> {
    if contexts.is_empty() {
        return Err(PlanDiagnostic(
            "entry stack domain closure has no admissible arrival context".into(),
        ));
    }
    contexts.sort_by_key(|context| context.context);
    let fixed = match boundary_stack {
        EntryStack::Interrupted => Some(StackDomainRef::Interrupted),
        EntryStack::Dedicated { class } => Some(StackDomainRef::Dedicated { class }),
        EntryStack::ProviderSelected => None,
    };
    for (index, context) in contexts.iter().enumerate() {
        if index > 0 && contexts[index - 1].context == context.context {
            return Err(PlanDiagnostic(
                "entry stack domain closure repeats an arrival-context identity".into(),
            ));
        }
        if context.domain == StackDomainRef::ProviderSelected {
            return Err(PlanDiagnostic(format!(
                "arrival context 0x{:016x} retains an unresolved provider-selected body stack domain",
                context.context.get()
            )));
        }
        if fixed.is_some_and(|domain| context.domain != domain) {
            return Err(PlanDiagnostic(format!(
                "arrival context 0x{:016x} body stack domain differs from the fixed boundary stack disposition",
                context.context.get()
            )));
        }
    }
    let mut hash = Fnv1a::new();
    match boundary_stack {
        EntryStack::Interrupted => hash.u64(0),
        EntryStack::Dedicated { class } => {
            hash.u64(1);
            hash.u64(u64::from(class));
        }
        EntryStack::ProviderSelected => hash.u64(2),
    }
    hash.u64(contexts.len() as u64);
    for context in &contexts {
        hash.u64(context.context.get());
        report_fingerprint_domain(&mut hash, context.domain);
    }
    Ok(ValidatedEntryStackDomainClosure {
        boundary_stack,
        contexts,
        non_authoritative_report_fingerprint: hash.finish(),
    })
}

/// Exact installed-code identity consumed by sealed target arrival rules.
///
/// These are compiler identities, not source-visible interrupt vocabulary.
/// The entry offset is allowed to be zero; every nominal identity must already
/// have been established by the installation pipeline.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct InstalledEntryFactIdentity {
    pub target_profile: X86_64TargetProfileIdentity,
    pub artifact: u64,
    pub installed_code: u64,
    pub entry: u64,
    pub entry_offset: u64,
    /// Compact report coordinate for the boundary plan.
    pub boundary_plan_report_fingerprint: u64,
    /// Domain-separated commitment to the complete canonical boundary plan.
    pub boundary_plan_commitment: [u8; 32],
}

/// Closed identity of the compiler-owned x86-64 target rule that validates an
/// installed gate and derives its hardware arrival frame.
///
/// A target/provider may cite this identity through compiler installation
/// metadata, but cannot construct a new rule identity or supply frame sizes.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct X86_64TargetProfileIdentity(u64);

impl X86_64TargetProfileIdentity {
    pub const LONG_MODE_INTERRUPT_GATES: Self = Self(0x7838_365f_6c6d_6967);

    pub const fn get(self) -> u64 {
        self.0
    }
}

/// Closed x86-64 gate category retained only as compiler installation data.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum X86_64GateKind {
    Interrupt,
    Trap,
}

/// Closed architectural cause for one admissible arrival at an installed
/// x86-64 gate. The gate's exact vector is retained separately. In particular,
/// an exception arrival may push an architectural error code while an external
/// or software arrival at the same vector does not.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum X86_64ArrivalMechanism {
    Exception,
    ExternalInterrupt,
    NonMaskableInterrupt,
    SoftwareInterrupt,
}

/// The stack selection performed atomically by x86-64 hardware.
///
/// `Current` means no hardware switch. The other variants name the provisioned
/// compiler stack domain reached by the validated gate/TSS installation; no
/// source program can manufacture or inspect this value.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum X86_64HardwareStackSelection {
    Current,
    PrivilegeTransition { dedicated_class: u16 },
    InterruptStackTable { slot: u8, dedicated_class: u16 },
}

/// One exact admissible arrival context from a validated x86-64 installation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct X86_64InstalledArrivalContext {
    pub context: ArrivalContextId,
    pub mechanism: X86_64ArrivalMechanism,
    pub interrupted_privilege: u8,
    pub entry_privilege: u8,
    pub stack_selection: X86_64HardwareStackSelection,
    pub nesting: Preemption,
}

/// Unvalidated exact facts decoded from one installed x86-64 gate and its
/// target-owned installation metadata.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct X86_64InstalledHardwareEntryFacts {
    pub identity: InstalledEntryFactIdentity,
    pub vector: u8,
    pub gate: X86_64GateKind,
    pub boundary_stack: EntryStack,
    pub contexts: Vec<X86_64InstalledArrivalContext>,
}

/// Canonical, fail-closed installed facts accepted by the sealed x86-64
/// hardware-arrival rule.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ValidatedX86_64InstalledHardwareEntryFacts {
    facts: X86_64InstalledHardwareEntryFacts,
    non_authoritative_report_fingerprint: u64,
}

impl ValidatedX86_64InstalledHardwareEntryFacts {
    pub const fn facts(&self) -> &X86_64InstalledHardwareEntryFacts {
        &self.facts
    }

    /// Compact report/cache coordinate over the retained exact facts.
    pub const fn report_fingerprint(&self) -> u64 {
        self.non_authoritative_report_fingerprint
    }
}

/// Sealed target-derived arrival result. It binds the exact installed facts to
/// both the context-to-body-domain closure and the complete epoch realization.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct X86_64TargetDerivedHardwareArrival {
    installed_identity: InstalledEntryFactIdentity,
    installed_facts_report_fingerprint: u64,
    body_domains: ValidatedEntryStackDomainClosure,
    realization: ValidatedEntryStackRealization,
    non_authoritative_report_fingerprint: u64,
}

impl X86_64TargetDerivedHardwareArrival {
    pub const fn installed_identity(&self) -> InstalledEntryFactIdentity {
        self.installed_identity
    }

    pub const fn installed_facts_report_fingerprint(&self) -> u64 {
        self.installed_facts_report_fingerprint
    }

    pub const fn body_domains(&self) -> &ValidatedEntryStackDomainClosure {
        &self.body_domains
    }

    pub const fn realization(&self) -> &ValidatedEntryStackRealization {
        &self.realization
    }

    /// Compact report/cache coordinate. The exact installed facts, domain
    /// closure, realization, and boundary-plan commitment remain retained.
    pub const fn report_fingerprint(&self) -> u64 {
        self.non_authoritative_report_fingerprint
    }
}

/// Validate and canonicalize the exact installation facts consumed by the
/// compiler's sealed x86-64 arrival rule.
pub fn validate_x86_64_installed_hardware_entry_facts(
    mut facts: X86_64InstalledHardwareEntryFacts,
) -> Result<ValidatedX86_64InstalledHardwareEntryFacts, PlanDiagnostic> {
    let identity = facts.identity;
    if identity.target_profile != X86_64TargetProfileIdentity::LONG_MODE_INTERRUPT_GATES
        || identity.artifact == 0
        || identity.installed_code == 0
        || identity.entry == 0
        || identity.boundary_plan_report_fingerprint == 0
        || identity.boundary_plan_commitment == [0; 32]
    {
        return Err(PlanDiagnostic(
            "x86-64 installed hardware entry has an absent exact identity".into(),
        ));
    }
    if facts.contexts.is_empty() {
        return Err(PlanDiagnostic(
            "x86-64 installed hardware entry has no admissible arrival context".into(),
        ));
    }
    facts.contexts.sort_by_key(|context| context.context);
    let mut body_domains = Vec::with_capacity(facts.contexts.len());
    for (index, context) in facts.contexts.iter().enumerate() {
        if index > 0 && facts.contexts[index - 1].context == context.context {
            return Err(PlanDiagnostic(
                "x86-64 installed hardware entry repeats an arrival-context identity".into(),
            ));
        }
        validate_x86_64_arrival_context(facts.vector, context)?;
        body_domains.push(ArrivalContextStackDomain {
            context: context.context,
            domain: x86_64_body_domain(context.stack_selection),
        });
    }
    // This reuses the general closure validator to reject a target-derived
    // context set that disagrees with the requirement's fixed stack contract.
    validate_entry_stack_domain_closure(facts.boundary_stack, body_domains)?;
    let non_authoritative_report_fingerprint = x86_64_installed_facts_report_fingerprint(&facts);
    Ok(ValidatedX86_64InstalledHardwareEntryFacts {
        facts,
        non_authoritative_report_fingerprint,
    })
}

fn validate_x86_64_arrival_context(
    vector: u8,
    context: &X86_64InstalledArrivalContext,
) -> Result<(), PlanDiagnostic> {
    match context.mechanism {
        X86_64ArrivalMechanism::Exception if vector >= 32 => {
            return Err(PlanDiagnostic(format!(
                "x86-64 arrival context 0x{:016x} classifies non-exception vector {vector} as an exception",
                context.context.get()
            )));
        }
        X86_64ArrivalMechanism::ExternalInterrupt if vector < 32 => {
            return Err(PlanDiagnostic(format!(
                "x86-64 arrival context 0x{:016x} classifies reserved vector {vector} as an external interrupt",
                context.context.get()
            )));
        }
        X86_64ArrivalMechanism::NonMaskableInterrupt if vector != 2 => {
            return Err(PlanDiagnostic(format!(
                "x86-64 arrival context 0x{:016x} classifies vector {vector} as the non-maskable interrupt",
                context.context.get()
            )));
        }
        _ => {}
    }
    if context.interrupted_privilege > 3 || context.entry_privilege > 3 {
        return Err(PlanDiagnostic(format!(
            "x86-64 arrival context 0x{:016x} has a privilege level outside 0..=3",
            context.context.get()
        )));
    }
    if context.entry_privilege > context.interrupted_privilege {
        return Err(PlanDiagnostic(format!(
            "x86-64 arrival context 0x{:016x} enters a less privileged level",
            context.context.get()
        )));
    }
    match context.stack_selection {
        X86_64HardwareStackSelection::Current => {
            if context.interrupted_privilege != context.entry_privilege {
                return Err(PlanDiagnostic(format!(
                    "x86-64 arrival context 0x{:016x} changes privilege without a hardware stack switch",
                    context.context.get()
                )));
            }
        }
        X86_64HardwareStackSelection::PrivilegeTransition { .. } => {
            if context.interrupted_privilege == context.entry_privilege {
                return Err(PlanDiagnostic(format!(
                    "x86-64 arrival context 0x{:016x} selects a privilege-transition stack without changing privilege",
                    context.context.get()
                )));
            }
        }
        X86_64HardwareStackSelection::InterruptStackTable { slot, .. } => {
            if !(1..=7).contains(&slot) {
                return Err(PlanDiagnostic(format!(
                    "x86-64 arrival context 0x{:016x} selects invalid IST slot {slot}",
                    context.context.get()
                )));
            }
        }
    }
    match context.nesting {
        Preemption::NotApplicable | Preemption::Masked => {}
        Preemption::Nestable { maximum_depth } if maximum_depth > 0 => {}
        Preemption::Nestable { .. } => {
            return Err(PlanDiagnostic(format!(
                "x86-64 arrival context 0x{:016x} has zero finite nesting depth",
                context.context.get()
            )));
        }
        Preemption::ProviderDefined => {
            return Err(PlanDiagnostic(format!(
                "x86-64 arrival context 0x{:016x} retains unresolved provider-defined nesting",
                context.context.get()
            )));
        }
    }
    Ok(())
}

/// Apply the sealed x86-64 architectural arrival rule to exact validated
/// installation facts.
///
/// Hardware stack selection and the arrival push are atomic, so no fictional
/// pre/post-switch epoch is emitted. The hardware frame remains live in the
/// single body epoch: RIP/CS/RFLAGS for a same-CPL entry, plus old RSP/SS for
/// any hardware stack switch, plus the target-derived error-code word where
/// applicable.
pub fn derive_x86_64_hardware_arrival(
    installed: &ValidatedX86_64InstalledHardwareEntryFacts,
) -> Result<X86_64TargetDerivedHardwareArrival, PlanDiagnostic> {
    let recomputed = x86_64_installed_facts_report_fingerprint(&installed.facts);
    if recomputed != installed.non_authoritative_report_fingerprint {
        return Err(PlanDiagnostic(
            "x86-64 installed hardware-entry facts failed canonical identity revalidation".into(),
        ));
    }

    let body_domains = validate_entry_stack_domain_closure(
        installed.facts.boundary_stack,
        installed
            .facts
            .contexts
            .iter()
            .map(|context| ArrivalContextStackDomain {
                context: context.context,
                domain: x86_64_body_domain(context.stack_selection),
            })
            .collect(),
    )?;
    let realization = validate_entry_stack_realization(EntryStackRealization {
        contexts: installed
            .facts
            .contexts
            .iter()
            .map(|context| {
                let domain = x86_64_body_domain(context.stack_selection);
                ArrivalContextRealization {
                    context: context.context,
                    epochs: vec![EntryStackEpoch {
                        stage: EntryStackStage::Body,
                        active_domain: domain,
                        occupancy_by_domain: vec![StackOccupancy {
                            domain,
                            bytes: x86_64_arrival_frame_bytes(installed.facts.vector, context),
                            alignment: 8,
                        }],
                        nesting: context.nesting,
                    }],
                }
            })
            .collect(),
    })?;

    let mut hash = Fnv1a::new();
    hash.u64(0x7838_365f_6172_7276); // "x86_arrv"
    hash.u64(installed.non_authoritative_report_fingerprint);
    hash.u64(body_domains.report_fingerprint());
    hash.u64(realization.report_fingerprint());
    Ok(X86_64TargetDerivedHardwareArrival {
        installed_identity: installed.facts.identity,
        installed_facts_report_fingerprint: installed.non_authoritative_report_fingerprint,
        body_domains,
        realization,
        non_authoritative_report_fingerprint: hash.finish(),
    })
}

fn x86_64_body_domain(selection: X86_64HardwareStackSelection) -> StackDomainRef {
    match selection {
        X86_64HardwareStackSelection::Current => StackDomainRef::Interrupted,
        X86_64HardwareStackSelection::PrivilegeTransition { dedicated_class }
        | X86_64HardwareStackSelection::InterruptStackTable {
            dedicated_class, ..
        } => StackDomainRef::Dedicated {
            class: dedicated_class,
        },
    }
}

fn x86_64_arrival_frame_bytes(vector: u8, context: &X86_64InstalledArrivalContext) -> u64 {
    let machine_words = match context.stack_selection {
        X86_64HardwareStackSelection::Current => 3,
        X86_64HardwareStackSelection::PrivilegeTransition { .. }
        | X86_64HardwareStackSelection::InterruptStackTable { .. } => 5,
    } + u64::from(x86_64_arrival_pushes_error_code(vector, context));
    machine_words * 8
}

fn x86_64_arrival_pushes_error_code(vector: u8, context: &X86_64InstalledArrivalContext) -> bool {
    context.mechanism == X86_64ArrivalMechanism::Exception
        && matches!(
            // Intel 64 architecturally error-code-bearing exceptions. The
            // target profile owns this closed table; providers never supply a
            // byte count or error-code bit.
            vector,
            8 | 10 | 11 | 12 | 13 | 14 | 17 | 21 | 29 | 30
        )
}

fn x86_64_installed_facts_report_fingerprint(facts: &X86_64InstalledHardwareEntryFacts) -> u64 {
    let mut hash = Fnv1a::new();
    hash.u64(0x7838_365f_696e_7374); // "x86_inst"
    hash.u64(facts.identity.target_profile.get());
    hash.u64(facts.identity.artifact);
    hash.u64(facts.identity.installed_code);
    hash.u64(facts.identity.entry);
    hash.u64(facts.identity.entry_offset);
    hash.u64(facts.identity.boundary_plan_report_fingerprint);
    hash.bytes(&facts.identity.boundary_plan_commitment);
    hash.u64(u64::from(facts.vector));
    hash.u64(match facts.gate {
        X86_64GateKind::Interrupt => 0,
        X86_64GateKind::Trap => 1,
    });
    match facts.boundary_stack {
        EntryStack::Interrupted => hash.u64(0),
        EntryStack::Dedicated { class } => {
            hash.u64(1);
            hash.u64(u64::from(class));
        }
        EntryStack::ProviderSelected => hash.u64(2),
    }
    hash.u64(facts.contexts.len() as u64);
    for context in &facts.contexts {
        hash.u64(context.context.get());
        hash.u64(match context.mechanism {
            X86_64ArrivalMechanism::Exception => 0,
            X86_64ArrivalMechanism::ExternalInterrupt => 1,
            X86_64ArrivalMechanism::NonMaskableInterrupt => 2,
            X86_64ArrivalMechanism::SoftwareInterrupt => 3,
        });
        hash.u64(u64::from(context.interrupted_privilege));
        hash.u64(u64::from(context.entry_privilege));
        match context.stack_selection {
            X86_64HardwareStackSelection::Current => hash.u64(0),
            X86_64HardwareStackSelection::PrivilegeTransition { dedicated_class } => {
                hash.u64(1);
                hash.u64(u64::from(dedicated_class));
            }
            X86_64HardwareStackSelection::InterruptStackTable {
                slot,
                dedicated_class,
            } => {
                hash.u64(2);
                hash.u64(u64::from(slot));
                hash.u64(u64::from(dedicated_class));
            }
        }
        match context.nesting {
            Preemption::NotApplicable => hash.u64(0),
            Preemption::Masked => hash.u64(1),
            Preemption::Nestable { maximum_depth } => {
                hash.u64(2);
                hash.u64(u64::from(maximum_depth));
            }
            Preemption::ProviderDefined => hash.u64(3),
        }
    }
    hash.finish()
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct EntryStackRealization {
    pub contexts: Vec<ArrivalContextRealization>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ValidatedEntryStackRealization {
    realization: EntryStackRealization,
    non_authoritative_report_fingerprint: u64,
}

impl ValidatedEntryStackRealization {
    pub const fn realization(&self) -> &EntryStackRealization {
        &self.realization
    }

    /// Compact report/cache coordinate over the retained exact realization.
    pub const fn report_fingerprint(&self) -> u64 {
        self.non_authoritative_report_fingerprint
    }
}

pub fn validate_entry_stack_realization(
    mut realization: EntryStackRealization,
) -> Result<ValidatedEntryStackRealization, PlanDiagnostic> {
    if realization.contexts.is_empty() {
        return Err(PlanDiagnostic(
            "entry stack realization has no admissible arrival context".into(),
        ));
    }
    realization.contexts.sort_by_key(|context| context.context);
    for index in 0..realization.contexts.len() {
        if index > 0
            && realization.contexts[index - 1].context == realization.contexts[index].context
        {
            return Err(PlanDiagnostic(
                "entry stack realization repeats an arrival-context identity".into(),
            ));
        }
        validate_context(&mut realization.contexts[index])?;
    }
    let non_authoritative_report_fingerprint = realization_report_fingerprint(&realization);
    Ok(ValidatedEntryStackRealization {
        realization,
        non_authoritative_report_fingerprint,
    })
}

fn validate_context(context: &mut ArrivalContextRealization) -> Result<(), PlanDiagnostic> {
    if context.epochs.is_empty() {
        return Err(PlanDiagnostic(format!(
            "arrival context 0x{:016x} has no stack epoch",
            context.context.get()
        )));
    }
    let mut body_count = 0usize;
    let mut phase = EntryStackStage::Enter;
    for (epoch_index, epoch) in context.epochs.iter_mut().enumerate() {
        if epoch.active_domain == StackDomainRef::ProviderSelected {
            return Err(PlanDiagnostic(format!(
                "arrival context 0x{:016x} epoch {epoch_index} retains an unresolved provider-selected active stack domain",
                context.context.get()
            )));
        }
        match epoch.nesting {
            Preemption::NotApplicable | Preemption::Masked => {}
            Preemption::Nestable { maximum_depth } if maximum_depth > 0 => {}
            Preemption::Nestable { .. } => {
                return Err(PlanDiagnostic(format!(
                    "arrival context 0x{:016x} epoch {epoch_index} has zero finite nesting depth",
                    context.context.get()
                )));
            }
            Preemption::ProviderDefined => {
                return Err(PlanDiagnostic(format!(
                    "arrival context 0x{:016x} epoch {epoch_index} retains unresolved provider-defined nesting",
                    context.context.get()
                )));
            }
        }
        match epoch.stage {
            EntryStackStage::Enter if phase == EntryStackStage::Enter => {}
            EntryStackStage::Body if phase == EntryStackStage::Enter => {
                phase = EntryStackStage::Body;
                body_count += 1;
            }
            EntryStackStage::Exit
                if matches!(phase, EntryStackStage::Body | EntryStackStage::Exit) =>
            {
                phase = EntryStackStage::Exit;
            }
            _ => {
                return Err(PlanDiagnostic(format!(
                    "arrival context 0x{:016x} has a noncanonical enter/body/exit epoch order",
                    context.context.get()
                )));
            }
        }
        epoch
            .occupancy_by_domain
            .sort_by_key(|occupancy| occupancy.domain);
        for occupancy_index in 0..epoch.occupancy_by_domain.len() {
            let occupancy = epoch.occupancy_by_domain[occupancy_index];
            if occupancy.domain == StackDomainRef::ProviderSelected {
                return Err(PlanDiagnostic(format!(
                    "arrival context 0x{:016x} epoch {epoch_index} retains unresolved provider-selected occupancy",
                    context.context.get()
                )));
            }
            if occupancy.bytes == 0 {
                return Err(PlanDiagnostic(format!(
                    "arrival context 0x{:016x} epoch {epoch_index} has zero-byte occupancy",
                    context.context.get()
                )));
            }
            if occupancy.alignment == 0 || !occupancy.alignment.is_power_of_two() {
                return Err(PlanDiagnostic(format!(
                    "arrival context 0x{:016x} epoch {epoch_index} has non-power-of-two occupancy alignment {}",
                    context.context.get(),
                    occupancy.alignment
                )));
            }
            if occupancy_index > 0
                && epoch.occupancy_by_domain[occupancy_index - 1].domain == occupancy.domain
            {
                return Err(PlanDiagnostic(format!(
                    "arrival context 0x{:016x} epoch {epoch_index} repeats one occupancy domain",
                    context.context.get()
                )));
            }
        }
    }
    if body_count != 1 {
        return Err(PlanDiagnostic(format!(
            "arrival context 0x{:016x} has {body_count} body epochs instead of exactly one",
            context.context.get()
        )));
    }
    Ok(())
}

fn realization_report_fingerprint(realization: &EntryStackRealization) -> u64 {
    let mut hash = Fnv1a::new();
    hash.u64(realization.contexts.len() as u64);
    for context in &realization.contexts {
        hash.u64(context.context.get());
        hash.u64(context.epochs.len() as u64);
        for epoch in &context.epochs {
            hash.u64(match epoch.stage {
                EntryStackStage::Enter => 1,
                EntryStackStage::Body => 2,
                EntryStackStage::Exit => 3,
            });
            report_fingerprint_domain(&mut hash, epoch.active_domain);
            match epoch.nesting {
                Preemption::NotApplicable => hash.u64(0),
                Preemption::Masked => hash.u64(1),
                Preemption::Nestable { maximum_depth } => {
                    hash.u64(2);
                    hash.u64(u64::from(maximum_depth));
                }
                Preemption::ProviderDefined => unreachable!("validated above"),
            }
            hash.u64(epoch.occupancy_by_domain.len() as u64);
            for occupancy in &epoch.occupancy_by_domain {
                report_fingerprint_domain(&mut hash, occupancy.domain);
                hash.u64(occupancy.bytes);
                hash.u64(occupancy.alignment);
            }
        }
    }
    hash.finish()
}

fn report_fingerprint_domain(hash: &mut Fnv1a, domain: StackDomainRef) {
    match domain {
        StackDomainRef::Interrupted => hash.u64(0),
        StackDomainRef::Dedicated { class } => {
            hash.u64(1);
            hash.u64(u64::from(class));
        }
        StackDomainRef::ProviderSelected => unreachable!("validated above"),
    }
}

struct Fnv1a(u64);

impl Fnv1a {
    const fn new() -> Self {
        Self(0xcbf29ce484222325)
    }

    fn u64(&mut self, value: u64) {
        self.bytes(&value.to_le_bytes());
    }

    fn bytes(&mut self, bytes: &[u8]) {
        for byte in bytes {
            self.0 ^= u64::from(*byte);
            self.0 = self.0.wrapping_mul(0x100000001b3);
        }
    }

    const fn finish(self) -> u64 {
        self.0
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn installed_identity() -> InstalledEntryFactIdentity {
        InstalledEntryFactIdentity {
            target_profile: X86_64TargetProfileIdentity::LONG_MODE_INTERRUPT_GATES,
            artifact: 0x20,
            installed_code: 0x30,
            entry: 0x31,
            entry_offset: 0,
            boundary_plan_report_fingerprint: 0x40,
            boundary_plan_commitment: [0x40; 32],
        }
    }

    fn x86_context(
        id: u64,
        interrupted_privilege: u8,
        entry_privilege: u8,
        stack_selection: X86_64HardwareStackSelection,
        mechanism: X86_64ArrivalMechanism,
    ) -> X86_64InstalledArrivalContext {
        X86_64InstalledArrivalContext {
            context: ArrivalContextId::new(id).expect("context identity"),
            mechanism,
            interrupted_privilege,
            entry_privilege,
            stack_selection,
            nesting: Preemption::Nestable { maximum_depth: 2 },
        }
    }

    fn x86_facts(
        vector: u8,
        boundary_stack: EntryStack,
        contexts: Vec<X86_64InstalledArrivalContext>,
    ) -> X86_64InstalledHardwareEntryFacts {
        X86_64InstalledHardwareEntryFacts {
            identity: installed_identity(),
            vector,
            gate: X86_64GateKind::Interrupt,
            boundary_stack,
            contexts,
        }
    }

    fn context(value: u64, occupancy: Vec<StackOccupancy>) -> ArrivalContextRealization {
        ArrivalContextRealization {
            context: ArrivalContextId::new(value).expect("context identity"),
            epochs: vec![EntryStackEpoch {
                stage: EntryStackStage::Body,
                active_domain: StackDomainRef::Interrupted,
                occupancy_by_domain: occupancy,
                nesting: Preemption::Nestable { maximum_depth: 2 },
            }],
        }
    }

    #[test]
    fn canonical_identity_ignores_context_and_occupancy_input_order() {
        let interrupted = StackOccupancy {
            domain: StackDomainRef::Interrupted,
            bytes: 24,
            alignment: 8,
        };
        let dedicated = StackOccupancy {
            domain: StackDomainRef::Dedicated { class: 7 },
            bytes: 16,
            alignment: 16,
        };
        let first = validate_entry_stack_realization(EntryStackRealization {
            contexts: vec![
                context(2, vec![interrupted, dedicated]),
                context(1, vec![dedicated, interrupted]),
            ],
        })
        .expect("first realization");
        let second = validate_entry_stack_realization(EntryStackRealization {
            contexts: vec![
                context(1, vec![interrupted, dedicated]),
                context(2, vec![dedicated, interrupted]),
            ],
        })
        .expect("second realization");

        assert_eq!(first, second);
        assert_eq!(first.report_fingerprint(), second.report_fingerprint());
    }

    #[test]
    fn structural_validation_rejects_open_or_malformed_realizations() {
        let valid_context = context(
            1,
            vec![StackOccupancy {
                domain: StackDomainRef::Interrupted,
                bytes: 8,
                alignment: 8,
            }],
        );
        let cases = [
            (
                EntryStackRealization::default(),
                "no admissible arrival context",
            ),
            (
                EntryStackRealization {
                    contexts: vec![valid_context.clone(), valid_context.clone()],
                },
                "repeats an arrival-context identity",
            ),
            (
                EntryStackRealization {
                    contexts: vec![ArrivalContextRealization {
                        context: ArrivalContextId::new(1).expect("identity"),
                        epochs: vec![EntryStackEpoch {
                            stage: EntryStackStage::Body,
                            active_domain: StackDomainRef::ProviderSelected,
                            occupancy_by_domain: Vec::new(),
                            nesting: Preemption::Masked,
                        }],
                    }],
                },
                "unresolved provider-selected active stack domain",
            ),
            (
                EntryStackRealization {
                    contexts: vec![ArrivalContextRealization {
                        context: ArrivalContextId::new(1).expect("identity"),
                        epochs: vec![EntryStackEpoch {
                            stage: EntryStackStage::Body,
                            active_domain: StackDomainRef::Interrupted,
                            occupancy_by_domain: Vec::new(),
                            nesting: Preemption::ProviderDefined,
                        }],
                    }],
                },
                "unresolved provider-defined nesting",
            ),
        ];
        for (realization, expected) in cases {
            let error = validate_entry_stack_realization(realization)
                .expect_err("malformed realization must reject");
            assert!(error.0.contains(expected), "{}", error.0);
        }
    }

    #[test]
    fn context_domain_closure_is_exact_and_fixed_stacks_cannot_drift() {
        let context = |id, domain| ArrivalContextStackDomain {
            context: ArrivalContextId::new(id).expect("context identity"),
            domain,
        };
        let selected = validate_entry_stack_domain_closure(
            EntryStack::ProviderSelected,
            vec![
                context(2, StackDomainRef::Dedicated { class: 3 }),
                context(1, StackDomainRef::Interrupted),
            ],
        )
        .expect("provider-selected domains may vary by context");
        assert_eq!(selected.contexts()[0].context.get(), 1);
        assert_eq!(selected.contexts()[1].context.get(), 2);

        let error = validate_entry_stack_domain_closure(
            EntryStack::Interrupted,
            vec![context(1, StackDomainRef::Dedicated { class: 3 })],
        )
        .expect_err("fixed interrupted stack cannot close to a dedicated domain");
        assert!(error.0.contains("differs from the fixed boundary"));
    }

    #[test]
    fn epoch_order_and_body_cardinality_are_closed() {
        let epoch = |stage| EntryStackEpoch {
            stage,
            active_domain: StackDomainRef::Interrupted,
            occupancy_by_domain: Vec::new(),
            nesting: Preemption::Masked,
        };
        let wrong_order = EntryStackRealization {
            contexts: vec![ArrivalContextRealization {
                context: ArrivalContextId::new(1).expect("identity"),
                epochs: vec![epoch(EntryStackStage::Body), epoch(EntryStackStage::Enter)],
            }],
        };
        assert!(
            validate_entry_stack_realization(wrong_order)
                .expect_err("enter after body must reject")
                .0
                .contains("noncanonical")
        );

        let two_bodies = EntryStackRealization {
            contexts: vec![ArrivalContextRealization {
                context: ArrivalContextId::new(1).expect("identity"),
                epochs: vec![epoch(EntryStackStage::Body), epoch(EntryStackStage::Body)],
            }],
        };
        assert!(
            validate_entry_stack_realization(two_bodies)
                .expect_err("two body epochs must reject")
                .0
                .contains("noncanonical")
        );
    }

    #[test]
    fn x86_same_privilege_arrival_is_derived_on_the_interrupted_stack() {
        for (vector, mechanism, expected_bytes) in [
            (14, X86_64ArrivalMechanism::SoftwareInterrupt, 24),
            (14, X86_64ArrivalMechanism::Exception, 32),
        ] {
            let installed = validate_x86_64_installed_hardware_entry_facts(x86_facts(
                vector,
                EntryStack::Interrupted,
                vec![x86_context(
                    1,
                    0,
                    0,
                    X86_64HardwareStackSelection::Current,
                    mechanism,
                )],
            ))
            .expect("same-CPL installation facts");
            let derived = derive_x86_64_hardware_arrival(&installed)
                .expect("sealed same-CPL target derivation");
            let context = &derived.realization().realization().contexts[0];

            assert_eq!(context.epochs.len(), 1);
            assert_eq!(context.epochs[0].stage, EntryStackStage::Body);
            assert_eq!(context.epochs[0].active_domain, StackDomainRef::Interrupted);
            assert_eq!(
                context.epochs[0].occupancy_by_domain,
                vec![StackOccupancy {
                    domain: StackDomainRef::Interrupted,
                    bytes: expected_bytes,
                    alignment: 8,
                }]
            );
            assert_eq!(
                derived.body_domains().contexts(),
                &[ArrivalContextStackDomain {
                    context: ArrivalContextId::new(1).expect("identity"),
                    domain: StackDomainRef::Interrupted,
                }]
            );
        }
    }

    #[test]
    fn x86_privilege_and_ist_switches_derive_complete_dedicated_frames() {
        for (stack_selection, vector, mechanism, expected_bytes) in [
            (
                X86_64HardwareStackSelection::PrivilegeTransition { dedicated_class: 7 },
                32,
                X86_64ArrivalMechanism::ExternalInterrupt,
                40,
            ),
            (
                X86_64HardwareStackSelection::PrivilegeTransition { dedicated_class: 7 },
                14,
                X86_64ArrivalMechanism::Exception,
                48,
            ),
            (
                X86_64HardwareStackSelection::InterruptStackTable {
                    slot: 3,
                    dedicated_class: 7,
                },
                32,
                X86_64ArrivalMechanism::ExternalInterrupt,
                40,
            ),
            (
                X86_64HardwareStackSelection::InterruptStackTable {
                    slot: 3,
                    dedicated_class: 7,
                },
                14,
                X86_64ArrivalMechanism::Exception,
                48,
            ),
        ] {
            let (interrupted_privilege, entry_privilege) = match stack_selection {
                X86_64HardwareStackSelection::PrivilegeTransition { .. } => (3, 0),
                X86_64HardwareStackSelection::InterruptStackTable { .. } => (0, 0),
                X86_64HardwareStackSelection::Current => unreachable!(),
            };
            let installed = validate_x86_64_installed_hardware_entry_facts(x86_facts(
                vector,
                EntryStack::Dedicated { class: 7 },
                vec![x86_context(
                    1,
                    interrupted_privilege,
                    entry_privilege,
                    stack_selection,
                    mechanism,
                )],
            ))
            .expect("hardware-switched installation facts");
            let derived = derive_x86_64_hardware_arrival(&installed)
                .expect("sealed hardware-switch target derivation");
            let epoch = &derived.realization().realization().contexts[0].epochs[0];

            assert_eq!(epoch.active_domain, StackDomainRef::Dedicated { class: 7 });
            assert_eq!(epoch.occupancy_by_domain[0].bytes, expected_bytes);
        }
    }

    #[test]
    fn x86_mixed_contexts_are_canonical_and_context_complete() {
        let same = x86_context(
            1,
            0,
            0,
            X86_64HardwareStackSelection::Current,
            X86_64ArrivalMechanism::Exception,
        );
        let transition = x86_context(
            2,
            3,
            0,
            X86_64HardwareStackSelection::PrivilegeTransition { dedicated_class: 9 },
            X86_64ArrivalMechanism::Exception,
        );
        let first = validate_x86_64_installed_hardware_entry_facts(x86_facts(
            14,
            EntryStack::ProviderSelected,
            vec![transition, same],
        ))
        .expect("mixed installed contexts");
        let second = validate_x86_64_installed_hardware_entry_facts(x86_facts(
            14,
            EntryStack::ProviderSelected,
            vec![same, transition],
        ))
        .expect("same mixed contexts in canonical order");

        assert_eq!(first, second);
        assert_eq!(first.report_fingerprint(), second.report_fingerprint());
        let derived = derive_x86_64_hardware_arrival(&first).expect("mixed derivation");
        assert_eq!(derived.realization().realization().contexts.len(), 2);
        assert_eq!(
            derived
                .realization()
                .realization()
                .contexts
                .iter()
                .flat_map(|context| &context.epochs)
                .flat_map(|epoch| &epoch.occupancy_by_domain)
                .map(|occupancy| occupancy.bytes)
                .max(),
            Some(48),
            "mutually exclusive same-CPL/transition contexts contribute their maximum arrival frame",
        );
        assert_eq!(
            derived.body_domains().contexts(),
            &[
                ArrivalContextStackDomain {
                    context: ArrivalContextId::new(1).expect("identity"),
                    domain: StackDomainRef::Interrupted,
                },
                ArrivalContextStackDomain {
                    context: ArrivalContextId::new(2).expect("identity"),
                    domain: StackDomainRef::Dedicated { class: 9 },
                },
            ]
        );
    }

    #[test]
    fn x86_installation_validation_fails_closed_on_invalid_exact_facts() {
        let current = x86_context(
            1,
            0,
            0,
            X86_64HardwareStackSelection::Current,
            X86_64ArrivalMechanism::ExternalInterrupt,
        );
        let mut absent_identity = x86_facts(32, EntryStack::Interrupted, vec![current]);
        absent_identity.identity.artifact = 0;
        let mut absent_boundary_commitment = x86_facts(32, EntryStack::Interrupted, vec![current]);
        absent_boundary_commitment.identity.boundary_plan_commitment = [0; 32];
        let duplicate = x86_facts(32, EntryStack::Interrupted, vec![current, current]);
        let reserved_external = x86_facts(
            14,
            EntryStack::Interrupted,
            vec![x86_context(
                1,
                0,
                0,
                X86_64HardwareStackSelection::Current,
                X86_64ArrivalMechanism::ExternalInterrupt,
            )],
        );
        let bad_privilege = x86_facts(
            32,
            EntryStack::Interrupted,
            vec![x86_context(
                1,
                4,
                0,
                X86_64HardwareStackSelection::Current,
                X86_64ArrivalMechanism::ExternalInterrupt,
            )],
        );
        let missing_switch = x86_facts(
            32,
            EntryStack::ProviderSelected,
            vec![x86_context(
                1,
                3,
                0,
                X86_64HardwareStackSelection::Current,
                X86_64ArrivalMechanism::ExternalInterrupt,
            )],
        );
        let fake_transition = x86_facts(
            32,
            EntryStack::Dedicated { class: 2 },
            vec![x86_context(
                1,
                0,
                0,
                X86_64HardwareStackSelection::PrivilegeTransition { dedicated_class: 2 },
                X86_64ArrivalMechanism::ExternalInterrupt,
            )],
        );
        let bad_ist = x86_facts(
            32,
            EntryStack::Dedicated { class: 2 },
            vec![x86_context(
                1,
                0,
                0,
                X86_64HardwareStackSelection::InterruptStackTable {
                    slot: 0,
                    dedicated_class: 2,
                },
                X86_64ArrivalMechanism::ExternalInterrupt,
            )],
        );
        let fixed_domain_drift = x86_facts(
            32,
            EntryStack::Interrupted,
            vec![x86_context(
                1,
                0,
                0,
                X86_64HardwareStackSelection::InterruptStackTable {
                    slot: 1,
                    dedicated_class: 2,
                },
                X86_64ArrivalMechanism::ExternalInterrupt,
            )],
        );

        for (facts, expected) in [
            (absent_identity, "absent exact identity"),
            (absent_boundary_commitment, "absent exact identity"),
            (duplicate, "repeats an arrival-context identity"),
            (reserved_external, "classifies reserved vector"),
            (bad_privilege, "outside 0..=3"),
            (missing_switch, "without a hardware stack switch"),
            (fake_transition, "without changing privilege"),
            (bad_ist, "invalid IST slot"),
            (fixed_domain_drift, "differs from the fixed boundary"),
        ] {
            let error = validate_x86_64_installed_hardware_entry_facts(facts)
                .expect_err("invalid x86 installation facts must reject");
            assert!(error.0.contains(expected), "{}", error.0);
        }
    }

    #[test]
    fn x86_derived_identity_binds_every_exact_installation_fact_and_revalidates() {
        let facts = x86_facts(
            32,
            EntryStack::Interrupted,
            vec![x86_context(
                1,
                0,
                0,
                X86_64HardwareStackSelection::Current,
                X86_64ArrivalMechanism::ExternalInterrupt,
            )],
        );
        let installed =
            validate_x86_64_installed_hardware_entry_facts(facts.clone()).expect("baseline facts");
        let baseline = derive_x86_64_hardware_arrival(&installed).expect("baseline derivation");

        let mut changed = facts;
        changed.gate = X86_64GateKind::Trap;
        let changed = validate_x86_64_installed_hardware_entry_facts(changed)
            .expect("changed exact gate facts");
        let changed = derive_x86_64_hardware_arrival(&changed).expect("changed derivation");
        assert_ne!(baseline.report_fingerprint(), changed.report_fingerprint());

        let mut tampered = installed;
        tampered.facts.vector = 33;
        let error = derive_x86_64_hardware_arrival(&tampered)
            .expect_err("post-validation fact tampering must fail closed");
        assert!(error.0.contains("canonical identity revalidation"));
    }
}
