#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum KeywordKind {
    As,
    CallingConvention,
    Capability,
    Contains,
    Data,
    Else,
    Entry,
    Enum,
    False,
    Foreign,
    Host,
    If,
    Invariant,
    Let,
    Library,
    Loop,
    Machine,
    Match,
    Owns,
    Platform,
    Pub,
    Return,
    SelfType,
    SelfValue,
    State,
    Struct,
    Target,
    Transition,
    True,
    Use,
    When,
    While,
    #[default]
    Unknown,
}

impl KeywordKind {
    pub fn from_lexeme(lexeme: &str) -> Option<Self> {
        Some(match lexeme {
            "as" => Self::As,
            "calling_convention" => Self::CallingConvention,
            "capability" => Self::Capability,
            "contains" => Self::Contains,
            "data" => Self::Data,
            "else" => Self::Else,
            "entry" => Self::Entry,
            "enum" => Self::Enum,
            "false" => Self::False,
            "foreign" => Self::Foreign,
            "host" => Self::Host,
            "if" => Self::If,
            "invariant" => Self::Invariant,
            "let" => Self::Let,
            "library" => Self::Library,
            "loop" => Self::Loop,
            "machine" => Self::Machine,
            "match" => Self::Match,
            "owns" => Self::Owns,
            "platform" => Self::Platform,
            "pub" => Self::Pub,
            "return" => Self::Return,
            "Self" => Self::SelfType,
            "self" => Self::SelfValue,
            "state" => Self::State,
            "struct" => Self::Struct,
            "target" => Self::Target,
            "transition" => Self::Transition,
            "true" => Self::True,
            "use" => Self::Use,
            "when" => Self::When,
            "while" => Self::While,
            _ => return None,
        })
    }

    pub fn is_strict_identifier_keyword(self) -> bool {
        matches!(self, Self::SelfType | Self::SelfValue)
    }
}
