use super::{TargetOperation, TargetOperationKind};
use crate::{
    HostOperationKey, RuntimeTextReadSource, TargetDataObjectHandle, TargetValueOperandHandle,
    target_data_handle_from_abstract,
};

impl From<&omega_abstract_operations::AbstractOperation> for TargetOperation {
    fn from(operation: &omega_abstract_operations::AbstractOperation) -> Self {
        Self {
            kind: TargetOperationKind::from(&operation.kind),
            source_key: operation.source_key,
            source_statement: operation.source_statement,
        }
    }
}

impl From<&omega_abstract_operations::AbstractOperationKind> for TargetOperationKind {
    fn from(kind: &omega_abstract_operations::AbstractOperationKind) -> Self {
        match kind {
            omega_abstract_operations::AbstractOperationKind::EnterFunction => Self::EnterFunction,
            omega_abstract_operations::AbstractOperationKind::EnterDispatchLoop {
                entry_dispatch_index,
                terminal_dispatch_index,
            } => Self::EnterDispatchLoop {
                entry_dispatch_index: *entry_dispatch_index,
                terminal_dispatch_index: *terminal_dispatch_index,
            },
            omega_abstract_operations::AbstractOperationKind::EnterDispatchCase {
                dispatch_index,
            } => Self::EnterDispatchCase {
                dispatch_index: *dispatch_index,
            },
            omega_abstract_operations::AbstractOperationKind::EvaluateDispatchGuard {
                guard_lowering,
                operator,
                storage_region,
                byte_offset,
                byte_size,
                expected_value,
                has_storage,
                is_float,
            } => Self::EvaluateDispatchGuard {
                guard_lowering: *guard_lowering,
                operator: *operator,
                storage_region: *storage_region,
                byte_offset: *byte_offset,
                byte_size: *byte_size,
                expected_value: *expected_value,
                has_storage: *has_storage,
                is_float: *is_float,
            },
            omega_abstract_operations::AbstractOperationKind::CompareRuntimeTextLiteral {
                buffer,
                literal,
            } => Self::CompareRuntimeTextLiteral {
                buffer: remap_data_handle(*buffer),
                literal: literal.clone(),
            },
            omega_abstract_operations::AbstractOperationKind::CompareRuntimeTextStorage {
                buffer,
                source_region,
                source_offset,
                operator,
            } => Self::CompareRuntimeTextStorage {
                buffer: remap_data_handle(*buffer),
                source_region: *source_region,
                source_offset: *source_offset,
                operator: *operator,
            },
            omega_abstract_operations::AbstractOperationKind::CompareRuntimeStorage {
                left_region,
                left_offset,
                right_region,
                right_offset,
                byte_size,
                operator,
                is_float,
            } => Self::CompareRuntimeStorage {
                left_region: *left_region,
                left_offset: *left_offset,
                right_region: *right_region,
                right_offset: *right_offset,
                byte_size: *byte_size,
                operator: *operator,
                is_float: *is_float,
            },
            omega_abstract_operations::AbstractOperationKind::CompareRuntimeStorageValue {
                region,
                byte_offset,
                byte_size,
                expected_value,
                operator,
            } => Self::CompareRuntimeStorageValue {
                region: *region,
                byte_offset: *byte_offset,
                byte_size: *byte_size,
                expected_value: *expected_value,
                operator: *operator,
            },
            omega_abstract_operations::AbstractOperationKind::CompareRuntimeValues {
                left,
                right,
                byte_size,
                operator,
            } => Self::CompareRuntimeValues {
                left: remap_runtime_value_handle(*left),
                right: remap_runtime_value_handle(*right),
                byte_size: *byte_size,
                operator: *operator,
            },
            omega_abstract_operations::AbstractOperationKind::WriteRuntimeTextLiteral {
                buffer,
                literal,
            } => Self::WriteRuntimeTextLiteral {
                buffer: remap_data_handle(*buffer),
                literal: literal.clone(),
            },
            omega_abstract_operations::AbstractOperationKind::WriteRuntimeTextLiteralSegment {
                buffer,
                byte_offset,
                literal,
            } => Self::WriteRuntimeTextLiteralSegment {
                buffer: remap_data_handle(*buffer),
                byte_offset: *byte_offset,
                literal: literal.clone(),
            },
            omega_abstract_operations::AbstractOperationKind::AppendRuntimeTextStoredSuffix {
                buffer,
                buffer_offset,
                source_region,
                source_offset,
                target_region,
                target_offset,
                length_delta,
            } => Self::AppendRuntimeTextStoredSuffix {
                buffer: remap_data_handle(*buffer),
                buffer_offset: *buffer_offset,
                source_region: *source_region,
                source_offset: *source_offset,
                target_region: *target_region,
                target_offset: *target_offset,
                length_delta: *length_delta,
            },
            omega_abstract_operations::AbstractOperationKind::MaterializeRuntimeTextBuffer {
                buffer,
                target_region,
                target_offset,
            } => Self::MaterializeRuntimeTextBuffer {
                buffer: remap_data_handle(*buffer),
                target_region: *target_region,
                target_offset: *target_offset,
            },
            omega_abstract_operations::AbstractOperationKind::MaterializeRuntimeTextBufferToRuntimePointee {
                buffer,
                pointer_byte_offset,
                field_byte_offset,
            } => Self::MaterializeRuntimeTextBufferToRuntimePointee {
                buffer: remap_data_handle(*buffer),
                pointer_byte_offset: *pointer_byte_offset,
                field_byte_offset: *field_byte_offset,
            },
            omega_abstract_operations::AbstractOperationKind::MaterializeRuntimeTextBufferToRuntimeFrameIndexed {
                buffer,
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
            } => Self::MaterializeRuntimeTextBufferToRuntimeFrameIndexed {
                buffer: remap_data_handle(*buffer),
                descriptor_offset: *descriptor_offset,
                index_offset: *index_offset,
                element_byte_size: *element_byte_size,
                field_byte_offset: *field_byte_offset,
            },
            omega_abstract_operations::AbstractOperationKind::AppendRuntimeTextStoredPlace {
                buffer,
                source_region,
                source_offset,
                target_region,
                target_offset,
            } => Self::AppendRuntimeTextStoredPlace {
                buffer: remap_data_handle(*buffer),
                source_region: *source_region,
                source_offset: *source_offset,
                target_region: *target_region,
                target_offset: *target_offset,
            },
            omega_abstract_operations::AbstractOperationKind::AppendRuntimeTextStoredPlaceToRuntimePointee {
                buffer,
                source_region,
                source_offset,
                pointer_byte_offset,
                field_byte_offset,
            } => Self::AppendRuntimeTextStoredPlaceToRuntimePointee {
                buffer: remap_data_handle(*buffer),
                source_region: *source_region,
                source_offset: *source_offset,
                pointer_byte_offset: *pointer_byte_offset,
                field_byte_offset: *field_byte_offset,
            },
            omega_abstract_operations::AbstractOperationKind::AppendRuntimeTextStoredPlaceToRuntimeFrameIndexed {
                buffer,
                source_region,
                source_offset,
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
            } => Self::AppendRuntimeTextStoredPlaceToRuntimeFrameIndexed {
                buffer: remap_data_handle(*buffer),
                source_region: *source_region,
                source_offset: *source_offset,
                descriptor_offset: *descriptor_offset,
                index_offset: *index_offset,
                element_byte_size: *element_byte_size,
                field_byte_offset: *field_byte_offset,
            },
            omega_abstract_operations::AbstractOperationKind::AppendRuntimeTextLiteral {
                buffer,
                target_region,
                target_offset,
                literal,
            } => Self::AppendRuntimeTextLiteral {
                buffer: remap_data_handle(*buffer),
                target_region: *target_region,
                target_offset: *target_offset,
                literal: literal.clone(),
            },
            omega_abstract_operations::AbstractOperationKind::AppendRuntimeTextLiteralToRuntimePointee {
                buffer,
                pointer_byte_offset,
                field_byte_offset,
                literal,
            } => Self::AppendRuntimeTextLiteralToRuntimePointee {
                buffer: remap_data_handle(*buffer),
                pointer_byte_offset: *pointer_byte_offset,
                field_byte_offset: *field_byte_offset,
                literal: literal.clone(),
            },
            omega_abstract_operations::AbstractOperationKind::AppendRuntimeTextLiteralToRuntimeFrameIndexed {
                buffer,
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                literal,
            } => Self::AppendRuntimeTextLiteralToRuntimeFrameIndexed {
                buffer: remap_data_handle(*buffer),
                descriptor_offset: *descriptor_offset,
                index_offset: *index_offset,
                element_byte_size: *element_byte_size,
                field_byte_offset: *field_byte_offset,
                literal: literal.clone(),
            },
            omega_abstract_operations::AbstractOperationKind::AppendWireLiteralByte {
                out_region,
                out_offset,
                written_region,
                written_offset,
                value,
            } => Self::AppendWireLiteralByte {
                out_region: *out_region,
                out_offset: *out_offset,
                written_region: *written_region,
                written_offset: *written_offset,
                value: *value,
            },
            omega_abstract_operations::AbstractOperationKind::AppendWireScalarVarint {
                source_region,
                source_offset,
                byte_size,
                zigzag,
                out_region,
                out_offset,
                written_region,
                written_offset,
            } => Self::AppendWireScalarVarint {
                source_region: *source_region,
                source_offset: *source_offset,
                byte_size: *byte_size,
                zigzag: *zigzag,
                out_region: *out_region,
                out_offset: *out_offset,
                written_region: *written_region,
                written_offset: *written_offset,
            },
            omega_abstract_operations::AbstractOperationKind::AppendWireTextBytes {
                source_region,
                source_offset,
                out_region,
                out_offset,
                out_length,
                written_region,
                written_offset,
            } => Self::AppendWireTextBytes {
                source_region: *source_region,
                source_offset: *source_offset,
                out_region: *out_region,
                out_offset: *out_offset,
                out_length: *out_length,
                written_region: *written_region,
                written_offset: *written_offset,
            },
            omega_abstract_operations::AbstractOperationKind::ReadWireExpectedByte {
                buffer_region,
                buffer_offset,
                buffer_length,
                read_region,
                read_offset,
                ok_region,
                ok_offset,
                expected,
            } => Self::ReadWireExpectedByte {
                buffer_region: *buffer_region,
                buffer_offset: *buffer_offset,
                buffer_length: *buffer_length,
                read_region: *read_region,
                read_offset: *read_offset,
                ok_region: *ok_region,
                ok_offset: *ok_offset,
                expected: *expected,
            },
            omega_abstract_operations::AbstractOperationKind::ReadWireScalarVarint {
                buffer_region,
                buffer_offset,
                buffer_length,
                read_region,
                read_offset,
                ok_region,
                ok_offset,
                target_region,
                target_offset,
                byte_size,
                zigzag,
            } => Self::ReadWireScalarVarint {
                buffer_region: *buffer_region,
                buffer_offset: *buffer_offset,
                buffer_length: *buffer_length,
                read_region: *read_region,
                read_offset: *read_offset,
                ok_region: *ok_region,
                ok_offset: *ok_offset,
                target_region: *target_region,
                target_offset: *target_offset,
                byte_size: *byte_size,
                zigzag: *zigzag,
            },
            omega_abstract_operations::AbstractOperationKind::ReadWireByteSlice {
                buffer_region,
                buffer_offset,
                buffer_length,
                read_region,
                read_offset,
                ok_region,
                ok_offset,
                target_region,
                target_offset,
            } => Self::ReadWireByteSlice {
                buffer_region: *buffer_region,
                buffer_offset: *buffer_offset,
                buffer_length: *buffer_length,
                read_region: *read_region,
                read_offset: *read_offset,
                ok_region: *ok_region,
                ok_offset: *ok_offset,
                target_region: *target_region,
                target_offset: *target_offset,
            },
            omega_abstract_operations::AbstractOperationKind::ReadWireNestedOpen {
                buffer_region,
                buffer_offset,
                buffer_length,
                read_region,
                read_offset,
                ok_region,
                ok_offset,
                end_region,
                end_offset,
            } => Self::ReadWireNestedOpen {
                buffer_region: *buffer_region,
                buffer_offset: *buffer_offset,
                buffer_length: *buffer_length,
                read_region: *read_region,
                read_offset: *read_offset,
                ok_region: *ok_region,
                ok_offset: *ok_offset,
                end_region: *end_region,
                end_offset: *end_offset,
            },
            omega_abstract_operations::AbstractOperationKind::ReadWireNestedClose {
                buffer_region,
                buffer_offset,
                read_region,
                read_offset,
                ok_region,
                ok_offset,
                end_region,
                end_offset,
            } => Self::ReadWireNestedClose {
                buffer_region: *buffer_region,
                buffer_offset: *buffer_offset,
                read_region: *read_region,
                read_offset: *read_offset,
                ok_region: *ok_region,
                ok_offset: *ok_offset,
                end_region: *end_region,
                end_offset: *end_offset,
            },
            omega_abstract_operations::AbstractOperationKind::AppendWireRepeatedScalarVarint {
                source_region,
                source_offset,
                byte_size,
                zigzag,
                index,
                count_region,
                count_offset,
                out_region,
                out_offset,
                written_region,
                written_offset,
            } => Self::AppendWireRepeatedScalarVarint {
                source_region: *source_region,
                source_offset: *source_offset,
                byte_size: *byte_size,
                zigzag: *zigzag,
                index: *index,
                count_region: *count_region,
                count_offset: *count_offset,
                out_region: *out_region,
                out_offset: *out_offset,
                written_region: *written_region,
                written_offset: *written_offset,
            },
            omega_abstract_operations::AbstractOperationKind::ReadWireRepeatedScalarVarint {
                buffer_region,
                buffer_offset,
                buffer_length,
                read_region,
                read_offset,
                ok_region,
                ok_offset,
                end_region,
                end_offset,
                count_region,
                count_offset,
                target_region,
                target_offset,
                byte_size,
                zigzag,
            } => Self::ReadWireRepeatedScalarVarint {
                buffer_region: *buffer_region,
                buffer_offset: *buffer_offset,
                buffer_length: *buffer_length,
                read_region: *read_region,
                read_offset: *read_offset,
                ok_region: *ok_region,
                ok_offset: *ok_offset,
                end_region: *end_region,
                end_offset: *end_offset,
                count_region: *count_region,
                count_offset: *count_offset,
                target_region: *target_region,
                target_offset: *target_offset,
                byte_size: *byte_size,
                zigzag: *zigzag,
            },
            omega_abstract_operations::AbstractOperationKind::WriteRuntimeMachineInteger {
                byte_offset,
                byte_size,
                value,
            } => Self::WriteRuntimeMachineInteger {
                byte_offset: *byte_offset,
                byte_size: *byte_size,
                value: *value,
            },
            omega_abstract_operations::AbstractOperationKind::WriteRuntimeStorageInteger {
                target_region,
                byte_offset,
                byte_size,
                value,
            } => Self::WriteRuntimeStorageInteger {
                target_region: *target_region,
                byte_offset: *byte_offset,
                byte_size: *byte_size,
                value: *value,
            },
            omega_abstract_operations::AbstractOperationKind::WriteRuntimePointeeInteger {
                pointer_byte_offset,
                field_byte_offset,
                byte_size,
                value,
            } => Self::WriteRuntimePointeeInteger {
                pointer_byte_offset: *pointer_byte_offset,
                field_byte_offset: *field_byte_offset,
                byte_size: *byte_size,
                value: *value,
            },
            omega_abstract_operations::AbstractOperationKind::WriteRuntimeStorageBinary {
                target_region,
                target_offset,
                byte_size,
                left,
                operator,
                right,
                is_float,
                domain,
                target_signed,
            } => Self::WriteRuntimeStorageBinary {
                target_region: *target_region,
                target_offset: *target_offset,
                byte_size: *byte_size,
                left: remap_runtime_value_handle(*left),
                operator: *operator,
                right: remap_runtime_value_handle(*right),
                is_float: *is_float,
                domain: *domain,
                target_signed: *target_signed,
            },
            omega_abstract_operations::AbstractOperationKind::WriteRuntimeStorageConvert {
                target_region,
                target_offset,
                target_byte_size,
                source,
                source_byte_size,
                source_is_float,
                target_is_float,
                source_signed,
            } => Self::WriteRuntimeStorageConvert {
                target_region: *target_region,
                target_offset: *target_offset,
                target_byte_size: *target_byte_size,
                source: remap_runtime_value_handle(*source),
                source_byte_size: *source_byte_size,
                source_is_float: *source_is_float,
                target_is_float: *target_is_float,
                source_signed: *source_signed,
            },
            omega_abstract_operations::AbstractOperationKind::AtomicFetchAdd {
                target_region,
                target_offset,
                byte_size,
                delta,
            } => Self::AtomicFetchAdd {
                target_region: *target_region,
                target_offset: *target_offset,
                byte_size: *byte_size,
                delta: remap_runtime_value_handle(*delta),
            },
            omega_abstract_operations::AbstractOperationKind::AtomicCompareExchange {
                target_region,
                target_offset,
                byte_size,
                expected,
                new_value,
            } => Self::AtomicCompareExchange {
                target_region: *target_region,
                target_offset: *target_offset,
                byte_size: *byte_size,
                expected: remap_runtime_value_handle(*expected),
                new_value: remap_runtime_value_handle(*new_value),
            },
            omega_abstract_operations::AbstractOperationKind::WriteRuntimePointeeBinary {
                pointer_byte_offset,
                field_byte_offset,
                byte_size,
                left,
                operator,
                right,
            } => Self::WriteRuntimePointeeBinary {
                pointer_byte_offset: *pointer_byte_offset,
                field_byte_offset: *field_byte_offset,
                byte_size: *byte_size,
                left: remap_runtime_value_handle(*left),
                operator: *operator,
                right: remap_runtime_value_handle(*right),
            },
            omega_abstract_operations::AbstractOperationKind::WriteRuntimeFrameIndexedInteger {
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                byte_size,
                value,
            } => Self::WriteRuntimeFrameIndexedInteger {
                descriptor_offset: *descriptor_offset,
                index_offset: *index_offset,
                element_byte_size: *element_byte_size,
                field_byte_offset: *field_byte_offset,
                byte_size: *byte_size,
                value: *value,
            },
            omega_abstract_operations::AbstractOperationKind::WriteRuntimeFrameBaseIndexedInteger {
                base_byte_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                byte_size,
                value,
            } => Self::WriteRuntimeFrameBaseIndexedInteger {
                base_byte_offset: *base_byte_offset,
                index_offset: *index_offset,
                element_byte_size: *element_byte_size,
                field_byte_offset: *field_byte_offset,
                byte_size: *byte_size,
                value: *value,
            },
            omega_abstract_operations::AbstractOperationKind::WriteRuntimeMachineIndexedInteger {
                base_byte_offset,
                index_region,
                index_offset,
                element_byte_size,
                field_byte_offset,
                byte_size,
                value,
            } => Self::WriteRuntimeMachineIndexedInteger {
                base_byte_offset: *base_byte_offset,
                index_region: *index_region,
                index_offset: *index_offset,
                element_byte_size: *element_byte_size,
                field_byte_offset: *field_byte_offset,
                byte_size: *byte_size,
                value: *value,
            },
            omega_abstract_operations::AbstractOperationKind::WriteRuntimeFrameIndexedBinary {
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                byte_size,
                left,
                operator,
                right,
            } => Self::WriteRuntimeFrameIndexedBinary {
                descriptor_offset: *descriptor_offset,
                index_offset: *index_offset,
                element_byte_size: *element_byte_size,
                field_byte_offset: *field_byte_offset,
                byte_size: *byte_size,
                left: remap_runtime_value_handle(*left),
                operator: *operator,
                right: remap_runtime_value_handle(*right),
            },
            omega_abstract_operations::AbstractOperationKind::WriteRuntimeFrameBaseIndexedBinary {
                base_byte_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                byte_size,
                left,
                operator,
                right,
            } => Self::WriteRuntimeFrameBaseIndexedBinary {
                base_byte_offset: *base_byte_offset,
                index_offset: *index_offset,
                element_byte_size: *element_byte_size,
                field_byte_offset: *field_byte_offset,
                byte_size: *byte_size,
                left: remap_runtime_value_handle(*left),
                operator: *operator,
                right: remap_runtime_value_handle(*right),
            },
            omega_abstract_operations::AbstractOperationKind::WriteRuntimeMachineString {
                byte_offset,
                data,
                byte_length,
            } => Self::WriteRuntimeMachineString {
                byte_offset: *byte_offset,
                data: remap_data_handle(*data),
                byte_length: *byte_length,
            },
            omega_abstract_operations::AbstractOperationKind::WriteRuntimeMachineBoundedBuffer {
                byte_offset,
                literal,
                target_in_frame,
            } => Self::WriteRuntimeMachineBoundedBuffer {
                byte_offset: *byte_offset,
                literal: literal.clone(),
                target_in_frame: *target_in_frame,
            },
            omega_abstract_operations::AbstractOperationKind::AppendRuntimeMachineBoundedBufferSource {
                target_byte_offset,
                source_byte_offset,
                source_in_frame,
            } => Self::AppendRuntimeMachineBoundedBufferSource {
                target_byte_offset: *target_byte_offset,
                source_byte_offset: *source_byte_offset,
                source_in_frame: *source_in_frame,
            },
            omega_abstract_operations::AbstractOperationKind::AppendRuntimeMachineBoundedBufferLiteral {
                target_byte_offset,
                literal,
            } => Self::AppendRuntimeMachineBoundedBufferLiteral {
                target_byte_offset: *target_byte_offset,
                literal: literal.clone(),
            },
            omega_abstract_operations::AbstractOperationKind::WriteRuntimeFrameString {
                byte_offset,
                data,
                byte_length,
            } => Self::WriteRuntimeFrameString {
                byte_offset: *byte_offset,
                data: remap_data_handle(*data),
                byte_length: *byte_length,
            },
            omega_abstract_operations::AbstractOperationKind::WriteRuntimePointeeString {
                pointer_byte_offset,
                field_byte_offset,
                data,
                byte_length,
            } => Self::WriteRuntimePointeeString {
                pointer_byte_offset: *pointer_byte_offset,
                field_byte_offset: *field_byte_offset,
                data: remap_data_handle(*data),
                byte_length: *byte_length,
            },
            omega_abstract_operations::AbstractOperationKind::WriteRuntimePointeeBoundedBuffer {
                pointer_byte_offset,
                field_byte_offset,
                literal,
            } => Self::WriteRuntimePointeeBoundedBuffer {
                pointer_byte_offset: *pointer_byte_offset,
                field_byte_offset: *field_byte_offset,
                literal: literal.clone(),
            },
            omega_abstract_operations::AbstractOperationKind::WriteRuntimeFrameIndexedString {
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                data,
                byte_length,
            } => Self::WriteRuntimeFrameIndexedString {
                descriptor_offset: *descriptor_offset,
                index_offset: *index_offset,
                element_byte_size: *element_byte_size,
                field_byte_offset: *field_byte_offset,
                data: remap_data_handle(*data),
                byte_length: *byte_length,
            },
            omega_abstract_operations::AbstractOperationKind::WriteRuntimeMachineIndexedString {
                base_byte_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                data,
                byte_length,
            } => Self::WriteRuntimeMachineIndexedString {
                base_byte_offset: *base_byte_offset,
                index_offset: *index_offset,
                element_byte_size: *element_byte_size,
                field_byte_offset: *field_byte_offset,
                data: remap_data_handle(*data),
                byte_length: *byte_length,
            },
            omega_abstract_operations::AbstractOperationKind::WriteRuntimeStorageAddressToRuntimeFrame {
                source_region,
                source_offset,
                target_offset,
            } => Self::WriteRuntimeStorageAddressToRuntimeFrame {
                source_region: *source_region,
                source_offset: *source_offset,
                target_offset: *target_offset,
            },
            omega_abstract_operations::AbstractOperationKind::WriteRuntimePointeeAddressToRuntimeFrame {
                pointer_byte_offset,
                field_byte_offset,
                target_offset,
            } => Self::WriteRuntimePointeeAddressToRuntimeFrame {
                pointer_byte_offset: *pointer_byte_offset,
                field_byte_offset: *field_byte_offset,
                target_offset: *target_offset,
            },
            omega_abstract_operations::AbstractOperationKind::WriteRuntimeFrameIndexedAddressToRuntimeFrame {
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                target_offset,
            } => Self::WriteRuntimeFrameIndexedAddressToRuntimeFrame {
                descriptor_offset: *descriptor_offset,
                index_offset: *index_offset,
                element_byte_size: *element_byte_size,
                field_byte_offset: *field_byte_offset,
                target_offset: *target_offset,
            },
            omega_abstract_operations::AbstractOperationKind::WriteRuntimeFrameFixedIndexedAddressToRuntimeFrame {
                descriptor_offset,
                element_index,
                element_byte_size,
                field_byte_offset,
                target_offset,
            } => Self::WriteRuntimeFrameFixedIndexedAddressToRuntimeFrame {
                descriptor_offset: *descriptor_offset,
                element_index: *element_index,
                element_byte_size: *element_byte_size,
                field_byte_offset: *field_byte_offset,
                target_offset: *target_offset,
            },
            omega_abstract_operations::AbstractOperationKind::WriteRuntimeFrameBaseIndexedAddressToRuntimeFrame {
                base_byte_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                target_offset,
            } => Self::WriteRuntimeFrameBaseIndexedAddressToRuntimeFrame {
                base_byte_offset: *base_byte_offset,
                index_offset: *index_offset,
                element_byte_size: *element_byte_size,
                field_byte_offset: *field_byte_offset,
                target_offset: *target_offset,
            },
            omega_abstract_operations::AbstractOperationKind::ReadRuntimeTextLine {
                buffer,
                target_region,
                target_offset,
                byte_capacity,
                is_bounded_buffer,
            } => Self::ReadRuntimeTextLine {
                buffer: remap_data_handle(*buffer),
                target_region: *target_region,
                target_offset: *target_offset,
                byte_capacity: *byte_capacity,
                source: RuntimeTextReadSource::HostOperation {
                    operation_key: HostOperationKey::new(
                        omega_calling_conventions::HostCapability::Stdin,
                        omega_calling_conventions::HostOperation::Read,
                    ),
                },
                is_bounded_buffer: *is_bounded_buffer,
            },
            omega_abstract_operations::AbstractOperationKind::CopyRuntimeStorage {
                source_region,
                source_offset,
                target_region,
                target_offset,
                byte_count,
            } => Self::CopyRuntimeStorage {
                source_region: *source_region,
                source_offset: *source_offset,
                target_region: *target_region,
                target_offset: *target_offset,
                byte_count: *byte_count,
            },
            omega_abstract_operations::AbstractOperationKind::CopyRuntimeStorageToRuntimeFrameIndexed {
                source_region,
                source_offset,
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                byte_count,
            } => Self::CopyRuntimeStorageToRuntimeFrameIndexed {
                source_region: *source_region,
                source_offset: *source_offset,
                descriptor_offset: *descriptor_offset,
                index_offset: *index_offset,
                element_byte_size: *element_byte_size,
                field_byte_offset: *field_byte_offset,
                byte_count: *byte_count,
            },
            omega_abstract_operations::AbstractOperationKind::CopyRuntimeFrameIndexedToRuntimeFrame {
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                target_offset,
                byte_count,
            } => Self::CopyRuntimeFrameIndexedToRuntimeFrame {
                descriptor_offset: *descriptor_offset,
                index_offset: *index_offset,
                element_byte_size: *element_byte_size,
                field_byte_offset: *field_byte_offset,
                target_offset: *target_offset,
                byte_count: *byte_count,
            },
            omega_abstract_operations::AbstractOperationKind::CopyRuntimeFrameIndexedToRuntimeStorage {
                descriptor_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                target_region,
                target_offset,
                byte_count,
            } => Self::CopyRuntimeFrameIndexedToRuntimeStorage {
                descriptor_offset: *descriptor_offset,
                index_offset: *index_offset,
                element_byte_size: *element_byte_size,
                field_byte_offset: *field_byte_offset,
                target_region: *target_region,
                target_offset: *target_offset,
                byte_count: *byte_count,
            },
            omega_abstract_operations::AbstractOperationKind::CopyRuntimeFrameFixedIndexedToRuntimeFrame {
                descriptor_offset,
                element_index,
                element_byte_size,
                field_byte_offset,
                target_offset,
                byte_count,
            } => Self::CopyRuntimeFrameFixedIndexedToRuntimeFrame {
                descriptor_offset: *descriptor_offset,
                element_index: *element_index,
                element_byte_size: *element_byte_size,
                field_byte_offset: *field_byte_offset,
                target_offset: *target_offset,
                byte_count: *byte_count,
            },
            omega_abstract_operations::AbstractOperationKind::CopyRuntimeFrameFixedIndexedToRuntimeStorage {
                descriptor_offset,
                element_index,
                element_byte_size,
                field_byte_offset,
                target_region,
                target_offset,
                byte_count,
            } => Self::CopyRuntimeFrameFixedIndexedToRuntimeStorage {
                descriptor_offset: *descriptor_offset,
                element_index: *element_index,
                element_byte_size: *element_byte_size,
                field_byte_offset: *field_byte_offset,
                target_region: *target_region,
                target_offset: *target_offset,
                byte_count: *byte_count,
            },
            omega_abstract_operations::AbstractOperationKind::CopyRuntimeFrameFixedIndexedToRuntimePointee {
                descriptor_offset,
                element_index,
                element_byte_size,
                source_field_byte_offset,
                pointer_byte_offset,
                target_field_byte_offset,
                byte_count,
            } => Self::CopyRuntimeFrameFixedIndexedToRuntimePointee {
                descriptor_offset: *descriptor_offset,
                element_index: *element_index,
                element_byte_size: *element_byte_size,
                source_field_byte_offset: *source_field_byte_offset,
                pointer_byte_offset: *pointer_byte_offset,
                target_field_byte_offset: *target_field_byte_offset,
                byte_count: *byte_count,
            },
            omega_abstract_operations::AbstractOperationKind::CopyRuntimeFrameIndexedToRuntimePointee {
                descriptor_offset,
                index_offset,
                element_byte_size,
                source_field_byte_offset,
                pointer_byte_offset,
                target_field_byte_offset,
                byte_count,
            } => Self::CopyRuntimeFrameIndexedToRuntimePointee {
                descriptor_offset: *descriptor_offset,
                index_offset: *index_offset,
                element_byte_size: *element_byte_size,
                source_field_byte_offset: *source_field_byte_offset,
                pointer_byte_offset: *pointer_byte_offset,
                target_field_byte_offset: *target_field_byte_offset,
                byte_count: *byte_count,
            },
            omega_abstract_operations::AbstractOperationKind::CopyRuntimeMachineIndexedToRuntimeStorage {
                base_byte_offset,
                index_offset,
                element_byte_size,
                field_byte_offset,
                target_region,
                target_offset,
                byte_count,
            } => Self::CopyRuntimeMachineIndexedToRuntimeStorage {
                base_byte_offset: *base_byte_offset,
                index_offset: *index_offset,
                element_byte_size: *element_byte_size,
                field_byte_offset: *field_byte_offset,
                target_region: *target_region,
                target_offset: *target_offset,
                byte_count: *byte_count,
            },
            omega_abstract_operations::AbstractOperationKind::CopyRuntimeStorageToRuntimePointee {
                source_region,
                source_offset,
                pointer_byte_offset,
                field_byte_offset,
                byte_count,
            } => Self::CopyRuntimeStorageToRuntimePointee {
                source_region: *source_region,
                source_offset: *source_offset,
                pointer_byte_offset: *pointer_byte_offset,
                field_byte_offset: *field_byte_offset,
                byte_count: *byte_count,
            },
            omega_abstract_operations::AbstractOperationKind::CopyRuntimePointeeToRuntimeFrame {
                pointer_byte_offset,
                field_byte_offset,
                target_offset,
                byte_count,
            } => Self::CopyRuntimePointeeToRuntimeFrame {
                pointer_byte_offset: *pointer_byte_offset,
                field_byte_offset: *field_byte_offset,
                target_offset: *target_offset,
                byte_count: *byte_count,
            },
            omega_abstract_operations::AbstractOperationKind::SetDispatchState {
                dispatch_index,
            } => Self::SetDispatchState {
                dispatch_index: *dispatch_index,
            },
            omega_abstract_operations::AbstractOperationKind::WriteReturnRegisterInteger {
                byte_size,
                value,
            } => Self::WriteReturnRegisterInteger {
                byte_size: *byte_size,
                value: *value,
            },
            omega_abstract_operations::AbstractOperationKind::CopyRuntimeStorageToReturnRegister {
                region,
                byte_offset,
                byte_size,
            } => Self::CopyRuntimeStorageToReturnRegister {
                region: *region,
                byte_offset: *byte_offset,
                byte_size: *byte_size,
            },
            omega_abstract_operations::AbstractOperationKind::TerminateDispatch => Self::TerminateDispatch,
            omega_abstract_operations::AbstractOperationKind::LeaveDispatchCase => Self::LeaveDispatchCase,
            omega_abstract_operations::AbstractOperationKind::LeaveDispatchLoop => Self::LeaveDispatchLoop,
            omega_abstract_operations::AbstractOperationKind::BeginPlatformCall => Self::BeginPlatformCall,
            omega_abstract_operations::AbstractOperationKind::HostOperation { .. } => {
                panic!("abstract host operation ordinals must be lowered in omega-abstract-operations-to-target-operations")
            }
            omega_abstract_operations::AbstractOperationKind::PreparePlatformOutputHandle { .. }
            | omega_abstract_operations::AbstractOperationKind::WritePlatformNewline { .. } => {
                panic!("logical abstract host operations must be lowered in omega-abstract-operations-to-target-operations")
            }
            omega_abstract_operations::AbstractOperationKind::LeaveFunction => Self::LeaveFunction,
        }
    }
}

fn remap_data_handle(
    handle: omega_abstract_operations::AbstractDataObjectHandle,
) -> TargetDataObjectHandle {
    target_data_handle_from_abstract(handle)
}

fn remap_runtime_value_handle(
    handle: omega_abstract_operations::AbstractValueOperandHandle,
) -> TargetValueOperandHandle {
    omega_core::arena::Handle::from_parts(handle.arena_index(), handle.generation())
}
