[package]
name = "lowered-psi-to-lowered-psi"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
semantic-vocabulary = { path = "../../foundation/semantic-vocabulary" }
terminal-semantics = { path = "../../semantics/terminal-semantics" }
lowered-psi = { path = "../../representations/lowered-psi" }
optimization = { path = "../../representations/optimization" }
terminal-psi = { path = "../../representations/terminal-psi" }
terminal-codec = { path = "../../semantics/terminal-codec" }
terminal-verifier = { path = "../../semantics/terminal-verifier" }
