//! REAL-filesystem provider acceptance (build.omg rungs 1+2, TASKS_FS
//! open-work #3).
//!
//! Rung 1 (the provider): the SAME program, interpreted twice --
//!   1. `interpret_with_options(RealUnscoped)`: the staged file must appear ON
//!      REAL DISK with the exact bytes (the build.omg use case: an interpreted
//!      build program staging assets itself), and
//!   2. plain `interpret()` (hermetic default): the identical program must
//!      still run and exit identically against the VIRTUAL fs, with NOTHING
//!      appearing on real disk (the differential oracle stays hermetic).
//! The A/B is the point: one program, one exit code, two worlds.
//!
//! Rung 2 (grants): under `RealScoped { read: src, write: out }` a probe
//! program must (a) read from the read root, (b) stage + read back under the
//! write root, (c) get EACCES creating under the read-only root, and (d) get
//! EACCES reading outside every root -- with the denied files verifiably
//! absent from real disk afterwards.

use omega_compiler::{CheckedCompilation, compile_to_checked};
use psi_checked_interpreter::{
    BuildMachineEvaluationFailureKind, BuildTimeValue, FilesystemAccess,
    FilesystemEvaluationHaltKind, FilesystemGrantRoot, FilesystemGrantRootIdentity,
    FilesystemLogicalHandleInputResolution, FilesystemLogicalHandleKind,
    FilesystemOperationAttemptOutcome, FilesystemOperationResult, FilesystemSponsor,
    FilesystemSponsorLimits, FsGrants, InterpretOptions, InterpretOutcome,
    evaluate_build_machine_with_filesystem, evaluate_build_machine_with_filesystem_measured,
    interpret_entry, interpret_entry_with_options,
};
use std::path::Path;

fn grant_root(identity: u32, path: impl Into<std::path::PathBuf>) -> FilesystemGrantRoot {
    FilesystemGrantRoot::new(
        FilesystemGrantRootIdentity::new(identity).expect("test grant identity is nonzero"),
        path,
    )
}

fn interpret(checked: &CheckedCompilation, stdin: &[u8]) -> InterpretOutcome {
    interpret_entry(checked, "Main::main", stdin)
}

fn interpret_with_options(
    checked: &CheckedCompilation,
    stdin: &[u8],
    options: InterpretOptions,
) -> InterpretOutcome {
    interpret_entry_with_options(checked, "Main::main", stdin, options)
}

/// Render a host path for embedding in generated omega source: forward
/// slashes, so a windows path (`C:\Users\...`) never reads as string escape
/// sequences (`\U`) to the lexer; every host fs API accepts them.
fn omg_path(path: &Path) -> String {
    path.display().to_string().replace('\\', "/")
}

/// A build-shaped staging program against RAW `FilesystemHost` ops (the same
/// surface `native_crud` pins natively): mkdir a staging dir, create + write a
/// 17-byte asset, close, reopen, read it back, and exit with the read count.
/// `base` is baked in as path literals so the program needs no argv plumbing.
fn staging_program(base: &Path) -> String {
    let dir = base.join("staging");
    let file = dir.join("asset.txt");
    format!(
        r#"// Real-fs provider acceptance probe (generated by tests/real_fs.rs).
use omega::language::std::filesystem_host;

boundary trait Console {{ machine exit_process(return_code: i32); }}

data Main {{
    fs: FilesystemHost;
    console: Console;
    dir_mode: i32;
    mode: i32;
    read_flags: i32;
    cap: u64;
    rc: i64;
    fd: i32;
    n: i64;
    rn: i64;
    buffer: [u8; 64];
}}

machine Main::main(&mut self) {{
    self.dir_mode = 493;
    self.mode = 438;
    self.read_flags = 0;
    self.cap = 64;
    self.rc = self.fs.create_dir("{dir}", self.dir_mode);
    self.fd = self.fs.create("{file}", self.mode);
    transition self.fd >= 0 {{ true -> wrote() _ -> fail() }}
    state wrote(&mut self) {{
        self.n = self.fs.write(self.fd, "real fs rung one\n");
        self.n = self.fs.close(self.fd);
        self.fd = self.fs.open("{file}", self.read_flags);
        transition self.fd >= 0 {{ true -> rd() _ -> fail() }}
    }}
    state rd(&mut self) {{
        self.rn = self.fs.read(self.fd, &mut self.buffer, self.cap);
        self.n = self.fs.close(self.fd);
        transition {{ _ -> done(self.rn) }}
    }}
    state done(&mut self, count: i64) {{ self.console.exit_process(count as i32); }}
    state fail(&mut self) {{ self.console.exit_process(101); }}
}}
"#,
        dir = omg_path(&dir),
        file = omg_path(&file),
    )
}

#[test]
fn real_mode_stages_files_on_disk_and_hermetic_default_does_not() {
    // Unique per-run scratch base under the std temp dir; pid + a self-clean
    // keep reruns deterministic.
    let base = std::env::temp_dir().join(format!("omega_real_fs_probe_{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&base);
    std::fs::create_dir_all(&base).expect("create probe base dir");

    let main_path = base.join("main.omg");
    std::fs::write(&main_path, staging_program(&base)).expect("write probe program");

    let checked = compile_to_checked(&main_path, None).unwrap_or_else(|diagnostics| {
        panic!(
            "real-fs probe compile failed:\n{}",
            diagnostics
                .iter()
                .map(|d| d.to_string())
                .collect::<Vec<_>>()
                .join("\n")
        )
    });

    let staged = base.join("staging").join("asset.txt");

    // 1. REAL mode: the asset appears on real disk with the exact bytes.
    let real = interpret_with_options(
        &checked,
        &[],
        InterpretOptions {
            filesystem: FilesystemAccess::RealUnscoped,
            ..InterpretOptions::default()
        },
    );
    assert!(!real.is_error(), "real-mode run errored: {:?}", real.error);
    assert_eq!(real.exit_code, 17, "real-mode read-back count");
    assert_eq!(
        std::fs::read(&staged).expect("staged asset must exist on real disk"),
        b"real fs rung one\n",
        "staged asset bytes"
    );

    // 2. Hermetic default: same program, same exit code, NOTHING on disk.
    std::fs::remove_dir_all(base.join("staging")).expect("clear staging between runs");
    let hermetic = interpret(&checked, &[]);
    assert!(
        !hermetic.is_error(),
        "hermetic run errored: {:?}",
        hermetic.error
    );
    assert_eq!(hermetic.exit_code, 17, "virtual-fs read-back count");
    assert!(
        !staged.exists(),
        "hermetic default must not touch the real filesystem"
    );

    let _ = std::fs::remove_dir_all(&base);
}

#[test]
fn duplicate_descriptors_share_one_open_file_cursor_in_both_providers() {
    let base = std::env::temp_dir().join(format!(
        "omega_real_fs_duplicate_cursor_{}",
        std::process::id()
    ));
    let _ = std::fs::remove_dir_all(&base);
    std::fs::create_dir_all(&base).expect("create duplicate-cursor probe root");
    let file = base.join("cursor.bin");
    let source = format!(
        r#"use omega::language::std::filesystem_host;

boundary trait Console {{ machine exit_process(return_code: i32); }}

data Main {{
    fs: FilesystemHost;
    console: Console;
    fd: i32;
    duplicate_fd: i32;
    count: i64;
    position: i64;
    buffer: [u8; 2];
}}

machine Main::main(&mut self) {{
    self.fd = self.fs.create("{file}", 438);
    self.count = self.fs.write(self.fd, "abcdef");
    self.count = self.fs.close(self.fd);
    self.fd = self.fs.open("{file}", 0);
    self.duplicate_fd = self.fs.duplicate(self.fd);
    self.count = self.fs.read(self.fd, &mut self.buffer, 2);
    self.position = self.fs.seek(self.duplicate_fd, 0, 1);
    self.count = self.fs.close(self.duplicate_fd);
    self.count = self.fs.close(self.fd);
    self.console.exit_process(self.position as i32);
}}
"#,
        file = omg_path(&file),
    );
    let main_path = base.join("main.omg");
    std::fs::write(&main_path, source).expect("write duplicate-cursor probe");
    let checked = compile_to_checked(&main_path, None).unwrap_or_else(|diagnostics| {
        panic!(
            "duplicate-cursor probe compile failed:\n{}",
            diagnostics
                .iter()
                .map(ToString::to_string)
                .collect::<Vec<_>>()
                .join("\n")
        )
    });

    let real = interpret_with_options(
        &checked,
        &[],
        InterpretOptions {
            filesystem: FilesystemAccess::RealUnscoped,
            ..InterpretOptions::default()
        },
    );
    assert!(!real.is_error(), "real duplicate probe: {:?}", real.error);
    assert_eq!(real.exit_code, 2, "real duplicate must share the cursor");
    std::fs::remove_file(&file).expect("remove real-provider probe output");

    let hermetic = interpret(&checked, &[]);
    assert!(
        !hermetic.is_error(),
        "virtual duplicate probe: {:?}",
        hermetic.error
    );
    assert_eq!(
        hermetic.exit_code, 2,
        "virtual duplicate must share the cursor"
    );
    assert!(
        !file.exists(),
        "virtual provider must not write the host file"
    );

    let _ = std::fs::remove_dir_all(&base);
}

/// The grant-boundary probe: one program touching all four authorization
/// quadrants. Exit 70 = every quadrant behaved; 71..77 name the failing step.
fn grants_program(base: &Path) -> String {
    let src = base.join("src");
    let out = base.join("out");
    let secret = base.join("secret");
    format!(
        r#"// Grant-scoping probe (generated by tests/real_fs.rs).
use omega::language::std::filesystem_host;

boundary trait Console {{ machine exit_process(return_code: i32); }}

data Main {{
    fs: FilesystemHost;
    console: Console;
    mode: i32;
    rd: i32;
    cap: u64;
    fd: i32;
    n: i64;
    rn: i64;
    e: i64;
    buffer: [u8; 64];
}}

machine Main::main(&mut self) {{
    self.mode = 438;
    self.rd = 0;
    self.cap = 64;
    // (a) READ under the read root.
    self.fd = self.fs.open("{src}/input.txt", self.rd);
    transition self.fd >= 0 {{ true -> readsrc() _ -> bad(71) }}
    state readsrc(&mut self) {{
        self.rn = self.fs.read(self.fd, &mut self.buffer, self.cap);
        self.n = self.fs.close(self.fd);
        transition self.rn == 13 {{ true -> stage() _ -> bad(72) }}
    }}
    // (b) WRITE under the write root, then read it back (write grant
    // implies read-back).
    state stage(&mut self) {{
        self.fd = self.fs.create("{out}/artifact.txt", self.mode);
        transition self.fd >= 0 {{ true -> put() _ -> bad(73) }}
    }}
    state put(&mut self) {{
        self.n = self.fs.write(self.fd, "granted artifact\n");
        self.n = self.fs.close(self.fd);
        self.fd = self.fs.open("{out}/artifact.txt", self.rd);
        transition self.fd >= 0 {{ true -> readback() _ -> bad(74) }}
    }}
    state readback(&mut self) {{
        self.rn = self.fs.read(self.fd, &mut self.buffer, self.cap);
        self.n = self.fs.close(self.fd);
        transition self.rn == 17 {{ true -> denywrite() _ -> bad(75) }}
    }}
    // (c) CREATE under the read-only root must refuse with EACCES.
    state denywrite(&mut self) {{
        self.fd = self.fs.create("{src}/evil.txt", self.mode);
        self.e = self.fs.errno();
        transition self.fd < 0 && self.e == 13 {{ true -> denyhardlink() _ -> bad(76) }}
    }}
    // (d) A hard link from read-only source into writable staging would make
    // the source inode writable through the alias, so it must be refused.
    state denyhardlink(&mut self) {{
        self.n = self.fs.hard_link("{src}/input.txt", "{out}/source-alias.txt") as i64;
        self.e = self.fs.errno();
        transition self.n < 0 && self.e == 13 {{ true -> denyread() _ -> bad(77) }}
    }}
    // (e) READ outside every root must refuse with EACCES.
    state denyread(&mut self) {{
        self.fd = self.fs.open("{secret}/hidden.txt", self.rd);
        self.e = self.fs.errno();
        transition self.fd < 0 && self.e == 13 {{ true -> good() _ -> bad(78) }}
    }}
    state good(&mut self) {{ self.console.exit_process(70); }}
    state bad(&mut self, code: i32) {{ self.console.exit_process(code); }}
}}
"#,
        src = omg_path(&src),
        out = omg_path(&out),
        secret = omg_path(&secret),
    )
}

#[test]
fn scoped_grants_enforce_read_and_write_roots() {
    let base = std::env::temp_dir().join(format!("omega_fs_grants_probe_{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&base);
    // src (read root) with the input; out (write root) empty; secret with a
    // real file the grant must make unreachable.
    std::fs::create_dir_all(base.join("src")).expect("create src root");
    std::fs::create_dir_all(base.join("out")).expect("create out root");
    std::fs::create_dir_all(base.join("secret")).expect("create secret dir");
    std::fs::write(base.join("src").join("input.txt"), b"hello grants\n").expect("seed input");
    std::fs::write(base.join("secret").join("hidden.txt"), b"top secret\n").expect("seed secret");

    let main_path = base.join("main.omg");
    std::fs::write(&main_path, grants_program(&base)).expect("write probe program");

    let checked = compile_to_checked(&main_path, None).unwrap_or_else(|diagnostics| {
        panic!(
            "grants probe compile failed:\n{}",
            diagnostics
                .iter()
                .map(|d| d.to_string())
                .collect::<Vec<_>>()
                .join("\n")
        )
    });

    let outcome = interpret_with_options(
        &checked,
        &[],
        InterpretOptions {
            filesystem: FilesystemAccess::RealScoped(FsGrants {
                read_roots: vec![grant_root(1, base.join("src"))],
                write_roots: vec![grant_root(2, base.join("out"))],
            }),
            ..InterpretOptions::default()
        },
    );
    assert!(
        !outcome.is_error(),
        "scoped run errored: {:?}",
        outcome.error
    );
    assert_eq!(
        outcome.exit_code, 70,
        "grant quadrant probe (71=read-root open, 72=read bytes, 73=write-root \
         create, 74=read-back open, 75=read-back bytes, 76=read-only-root create \
         not EACCES-refused, 77=read-root hard-link alias not EACCES-refused, \
         78=outside-root open not EACCES-refused)"
    );

    // The world after: the artifact is real; the denied writes never happened.
    assert_eq!(
        std::fs::read(base.join("out").join("artifact.txt")).expect("artifact staged"),
        b"granted artifact\n",
    );
    assert!(
        !base.join("src").join("evil.txt").exists(),
        "denied create must not touch the read-only root"
    );
    assert!(
        !base.join("out").join("source-alias.txt").exists(),
        "denied hard link must not alias read-only source into writable staging"
    );
    assert_eq!(
        std::fs::read(base.join("src").join("input.txt")).expect("source remains intact"),
        b"hello grants\n",
    );
    assert_eq!(
        std::fs::read(base.join("secret").join("hidden.txt")).expect("secret untouched"),
        b"top secret\n",
    );

    let _ = std::fs::remove_dir_all(&base);
}

/// The refusal operations in this probe name existing symlinks in a read-only
/// namespace outside the write grant. Each link points at an object inside the
/// write grant. Authorizing the fully canonicalized leaf would therefore
/// accept the target and either operate on the wrong path or admit a namespace
/// operation whose actual leaf is outside the write root. The final two steps
/// pin ordinary host semantics inside the write root: unlink removes the link,
/// not its target, while rmdir of a symlink reports ENOTDIR.
#[cfg(unix)]
fn namespace_leaf_grant_program(base: &Path) -> String {
    let inside = base.join("inside");
    let outside = base.join("outside");
    format!(
        r#"// Namespace-leaf grant probe (generated by tests/real_fs.rs).
use omega::language::std::filesystem_host;

boundary trait Console {{ machine exit_process(return_code: i32); }}

data Main {{
    fs: FilesystemHost;
    console: Console;
    rc: i64;
    error: i64;
    dirfd: i32;
}}

machine Main::main(&mut self) {{
    self.rc = self.fs.remove("{outside}/remove-link") as i64;
    self.error = self.fs.errno();
    transition self.rc < 0 && self.error == 13 {{ true -> remove_dir() _ -> bad(71) }}
    state remove_dir(&mut self) {{
        self.rc = self.fs.remove_dir("{outside}/rmdir-link") as i64;
        self.error = self.fs.errno();
        transition self.rc < 0 && self.error == 13 {{ true -> mkdir() _ -> bad(72) }}
    }}
    state mkdir(&mut self) {{
        self.rc = self.fs.create_dir("{outside}/mkdir-link", 493) as i64;
        self.error = self.fs.errno();
        transition self.rc < 0 && self.error == 13 {{ true -> rename_source() _ -> bad(73) }}
    }}
    state rename_source(&mut self) {{
        self.rc = self.fs.rename("{outside}/rename-source-link", "{inside}/renamed.txt") as i64;
        self.error = self.fs.errno();
        transition self.rc < 0 && self.error == 13 {{ true -> rename_destination() _ -> bad(74) }}
    }}
    state rename_destination(&mut self) {{
        self.rc = self.fs.rename("{inside}/rename-input.txt", "{outside}/rename-destination-link") as i64;
        self.error = self.fs.errno();
        transition self.rc < 0 && self.error == 13 {{ true -> symlink_destination() _ -> bad(75) }}
    }}
    state symlink_destination(&mut self) {{
        self.rc = self.fs.symlink("replacement", "{outside}/symlink-destination-link") as i64;
        self.error = self.fs.errno();
        transition self.rc < 0 && self.error == 13 {{ true -> hard_link_source() _ -> bad(76) }}
    }}
    state hard_link_source(&mut self) {{
        self.rc = self.fs.hard_link("{outside}/hard-source-link", "{inside}/hard-alias.txt") as i64;
        self.error = self.fs.errno();
        transition self.rc < 0 && self.error == 13 {{ true -> hard_link_destination() _ -> bad(77) }}
    }}
    state hard_link_destination(&mut self) {{
        self.rc = self.fs.hard_link("{inside}/hard-input.txt", "{outside}/hard-destination-link") as i64;
        self.error = self.fs.errno();
        transition self.rc < 0 && self.error == 13 {{ true -> open_outside() _ -> bad(78) }}
    }}
    state open_outside(&mut self) {{
        self.dirfd = self.fs.open("{outside}", 0);
        transition self.dirfd >= 0 {{ true -> unlink_at() _ -> bad(79) }}
    }}
    state unlink_at(&mut self) {{
        self.rc = self.fs.unlink_at(self.dirfd, "unlink-link", 0) as i64;
        self.error = self.fs.errno();
        transition self.rc < 0 && self.error == 13 {{ true -> remove_in_root_link() _ -> bad(80) }}
    }}
    state remove_in_root_link(&mut self) {{
        self.rc = self.fs.remove("{inside}/allowed-remove-link") as i64;
        transition self.rc == 0 {{ true -> rmdir_in_root_link() _ -> bad(81) }}
    }}
    state rmdir_in_root_link(&mut self) {{
        self.rc = self.fs.remove_dir("{inside}/allowed-rmdir-link") as i64;
        self.error = self.fs.errno();
        transition self.rc < 0 && self.error == 20 {{ true -> good() _ -> bad(82) }}
    }}
    state good(&mut self) {{ self.console.exit_process(70); }}
    state bad(&mut self, code: i32) {{ self.console.exit_process(code); }}
}}
"#,
        inside = omg_path(&inside),
        outside = omg_path(&outside),
    )
}

#[cfg(unix)]
#[test]
fn scoped_namespace_mutations_authorize_the_leaf_not_its_symlink_target() {
    use std::os::unix::fs::symlink;

    let base = std::env::temp_dir().join(format!(
        "omega_fs_namespace_leaf_probe_{}",
        std::process::id()
    ));
    let _ = std::fs::remove_dir_all(&base);
    let inside = base.join("inside");
    let outside = base.join("outside");
    std::fs::create_dir_all(inside.join("rmdir-target")).expect("create rmdir target");
    std::fs::create_dir_all(inside.join("mkdir-target")).expect("create mkdir target");
    std::fs::create_dir_all(&outside).expect("create read-only outside namespace");

    let seeded_files = [
        "remove-target.txt",
        "rename-source-target.txt",
        "rename-input.txt",
        "rename-destination-target.txt",
        "symlink-destination-target.txt",
        "hard-source-target.txt",
        "hard-input.txt",
        "hard-destination-target.txt",
        "unlink-target.txt",
    ];
    for name in seeded_files {
        std::fs::write(inside.join(name), name.as_bytes()).expect("seed in-grant target");
    }

    let links = [
        ("remove-link", "remove-target.txt"),
        ("rmdir-link", "rmdir-target"),
        ("mkdir-link", "mkdir-target"),
        ("rename-source-link", "rename-source-target.txt"),
        ("rename-destination-link", "rename-destination-target.txt"),
        ("symlink-destination-link", "symlink-destination-target.txt"),
        ("hard-source-link", "hard-source-target.txt"),
        ("hard-destination-link", "hard-destination-target.txt"),
        ("unlink-link", "unlink-target.txt"),
    ];
    for (link, target) in links {
        symlink(inside.join(target), outside.join(link)).expect("seed outside symlink");
    }
    std::fs::write(inside.join("allowed-remove-target.txt"), b"remove target")
        .expect("seed allowed remove target");
    std::fs::create_dir(inside.join("allowed-rmdir-target")).expect("seed allowed rmdir target");
    symlink(
        inside.join("allowed-remove-target.txt"),
        inside.join("allowed-remove-link"),
    )
    .expect("seed in-root remove symlink");
    symlink(
        inside.join("allowed-rmdir-target"),
        inside.join("allowed-rmdir-link"),
    )
    .expect("seed in-root rmdir symlink");

    let main_path = base.join("main.omg");
    std::fs::write(&main_path, namespace_leaf_grant_program(&base))
        .expect("write namespace-leaf probe");
    let checked = compile_to_checked(&main_path, None).unwrap_or_else(|diagnostics| {
        panic!(
            "namespace-leaf probe compile failed:\n{}",
            diagnostics
                .iter()
                .map(|diagnostic| diagnostic.to_string())
                .collect::<Vec<_>>()
                .join("\n")
        )
    });

    let outcome = interpret_with_options(
        &checked,
        &[],
        InterpretOptions {
            filesystem: FilesystemAccess::RealScoped(FsGrants {
                read_roots: vec![grant_root(1, outside.clone())],
                write_roots: vec![grant_root(2, inside.clone())],
            }),
            ..InterpretOptions::default()
        },
    );
    assert!(
        !outcome.is_error(),
        "namespace-leaf probe errored: {:?}",
        outcome.error
    );
    assert_eq!(
        outcome.exit_code, 70,
        "every outside namespace leaf must be EACCES-refused (71 remove, 72 rmdir, \
         73 mkdir, 74 rename source, 75 rename destination, 76 symlink destination, \
         77 hard-link source, 78 hard-link destination, 79 dirfd open, 80 unlinkat); \
         ordinary in-root leaf semantics must remain intact (81 unlink, 82 rmdir errno)"
    );

    for (link, target) in links {
        let path = outside.join(link);
        assert!(
            std::fs::symlink_metadata(&path)
                .expect("outside symlink remains")
                .file_type()
                .is_symlink(),
            "{link} must remain a symlink"
        );
        assert_eq!(
            std::fs::read_link(&path).expect("read unchanged symlink target"),
            inside.join(target),
            "{link} target must remain unchanged"
        );
    }
    for name in seeded_files {
        assert_eq!(
            std::fs::read(inside.join(name)).expect("in-grant target remains"),
            name.as_bytes(),
            "{name} must not be removed or replaced through an outside symlink"
        );
    }
    assert!(inside.join("rmdir-target").is_dir());
    assert!(inside.join("mkdir-target").is_dir());
    assert!(!inside.join("renamed.txt").exists());
    assert!(!inside.join("hard-alias.txt").exists());
    assert!(!inside.join("allowed-remove-link").exists());
    assert_eq!(
        std::fs::read(inside.join("allowed-remove-target.txt"))
            .expect("unlink must retain the symlink target"),
        b"remove target"
    );
    assert!(
        std::fs::symlink_metadata(inside.join("allowed-rmdir-link"))
            .expect("failed rmdir retains its symlink leaf")
            .file_type()
            .is_symlink()
    );
    assert!(inside.join("allowed-rmdir-target").is_dir());

    let _ = std::fs::remove_dir_all(&base);
}

/// The WRAPPER-level dir-enumeration probe: `Filesystem::read_dir_count`
/// (open dirfd -> read_dir -> decode darwin dirent records -> skip `.`/`..`)
/// runs against a REAL directory. This exercises the full stack -- the std
/// wrapper's count, stats, and indexed-entry decode loops over the real
/// provider's packed records. The seeded directory deliberately exceeds one
/// 512-byte fill, pinning cursor-based pagination in the real-filesystem
/// interpreter provider.
fn read_dir_program(assets: &Path) -> String {
    format!(
        r#"// Real read_dir probe (generated by tests/real_fs.rs).
use omega::language::std::filesystem;
use omega::language::std::filesystem_host;

boundary trait Console {{ machine exit_process(return_code: i32); }}

data Main {{
    console: Console;
    fs: Filesystem;
    io_result: IoResult;
    stats_result: DirStatsResult;
    entry_result: DirEntryResult;
    open_result: OpenResult;
    file_fd: i32;
    close_rc: i32;
}}

machine Main::main(&mut self) {{
    self.io_result = self.fs.read_dir_count("{assets}");
    transition self.io_result {{ IoResult::Ok {{ count }} -> ck(count) _ -> bad(72) }}
    state ck(&mut self, count: u64) {{
        transition count == 48 {{ true -> stats() _ -> bad(71) }}
    }}
    state stats(&mut self) {{
        self.stats_result = self.fs.read_dir_stats("{assets}");
        transition self.stats_result {{ DirStatsResult::Ok {{ stats }} -> stats_ck(stats) _ -> bad(73) }}
    }}
    state stats_ck(&mut self, stats: DirStats) {{
        transition stats.entries == 48 && stats.subdirs == 0 && stats.files == 48 {{ true -> nth() _ -> bad(74) }}
    }}
    state nth(&mut self) {{
        self.entry_result = self.fs.read_dir_nth("{assets}", 47);
        transition self.entry_result {{ DirEntryResult::Ok {{ entry }} -> nth_ck(entry) _ -> bad(75) }}
    }}
    state nth_ck(&mut self, entry: DirEntry) {{
        transition entry.is_file && entry.name_len > 0 {{ true -> end() _ -> bad(76) }}
    }}
    state end(&mut self) {{
        self.entry_result = self.fs.read_dir_nth("{assets}", 48);
        transition self.entry_result {{ DirEntryResult::End -> fd_open() _ -> bad(77) }}
    }}
    state fd_open(&mut self) {{
        self.open_result = self.fs.open("{assets}");
        transition self.open_result {{ OpenResult::Ok {{ file }} -> fd_lookup(file) _ -> bad(78) }}
    }}
    state fd_lookup(&mut self, file: File) {{
        self.file_fd = file.fd;
        self.entry_result = self.fs.read_dir_entry_fd(self.file_fd, 47);
        transition self.entry_result {{ DirEntryResult::Ok {{ entry }} -> fd_ck(entry) _ -> bad(79) }}
    }}
    state fd_ck(&mut self, entry: DirEntry) {{
        transition entry.is_file && entry.name_len > 0 {{ true -> fd_close() _ -> bad(80) }}
    }}
    state fd_close(&mut self) {{
        self.close_rc = self.fs.close(File {{ fd: self.file_fd }});
        transition self.close_rc == 0 {{ true -> good() _ -> bad(81) }}
    }}
    state good(&mut self) {{ self.console.exit_process(70); }}
    state bad(&mut self, code: i32) {{ self.console.exit_process(code); }}
}}
"#,
        assets = omg_path(&assets),
    )
}

#[test]
fn scoped_wrapper_read_dir_count_enumerates_a_real_directory() {
    let base =
        std::env::temp_dir().join(format!("omega_real_readdir_probe_{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&base);
    let assets = base.join("assets");
    std::fs::create_dir_all(&assets).expect("create assets dir");
    for index in 0..48 {
        let name = format!("entry_{index:02}_with_a_long_record_name.dat");
        std::fs::write(assets.join(name), b"asset\n").expect("seed asset");
    }

    let main_path = base.join("main.omg");
    std::fs::write(&main_path, read_dir_program(&assets)).expect("write probe program");

    let checked = compile_to_checked(&main_path, None).unwrap_or_else(|diagnostics| {
        panic!(
            "read_dir probe compile failed:\n{}",
            diagnostics
                .iter()
                .map(|d| d.to_string())
                .collect::<Vec<_>>()
                .join("\n")
        )
    });

    let outcome = interpret_with_options(
        &checked,
        &[],
        InterpretOptions {
            filesystem: FilesystemAccess::RealScoped(FsGrants {
                read_roots: vec![grant_root(1, assets.clone())],
                write_roots: vec![],
            }),
            ..InterpretOptions::default()
        },
    );
    assert!(
        !outcome.is_error(),
        "read_dir probe errored: {:?}",
        outcome.error
    );
    assert_eq!(
        outcome.exit_code, 70,
        "directory count, stats, and indexed lookup must drain 48 real entries across multiple fills"
    );

    let _ = std::fs::remove_dir_all(&base);
}

/// The GRANTED BUILD probe (rung 4, interpreter side): an augmenting
/// `build(builder: &mut Build)` machine that BOTH stages a real asset through its
/// granted filesystem AND augments the Build value the compiler reads back --
/// the settled open-work #3 shape (no declarative asset list; build code
/// copies assets itself; the grant is the audit surface).
fn granted_build_program(out: &Path) -> String {
    format!(
        r#"// Granted-build probe (generated by tests/real_fs.rs).
use omega::language::std::filesystem_host;

data Build {{
    target_index: i64;
    staged: i64;
}}

data Stager {{
    fs: FilesystemHost;
    fd: i32;
    n: i64;
}}

machine Stager::build(&mut self, builder: &mut Build) {{
    self.fd = self.fs.create("{out}/asset.bin", 438);
    transition self.fd >= 0 {{ true -> put(builder) _ -> mark(builder, 0 - 1) }}
    state put(&mut self, builder: &mut Build) {{
        self.n = self.fs.write(self.fd, "staged by build\n");
        self.n = self.fs.close(self.fd);
        transition true {{ true -> mark(builder, 1) _ -> mark(builder, 1) }}
    }}
    state mark(&mut self, builder: &mut Build, staged: i64) {{
        builder.target_index = 7;
        builder.staged = staged;
    }}
}}

data Main {{ }}
machine Main::main(&mut self) {{ }}
"#,
        out = omg_path(&out),
    )
}

fn zero_build() -> BuildTimeValue {
    BuildTimeValue::Struct {
        type_name: "Build".to_owned(),
        fields: vec![
            ("target_index".to_owned(), BuildTimeValue::Int(0)),
            ("staged".to_owned(), BuildTimeValue::Int(0)),
        ],
    }
}

fn build_field(build: &BuildTimeValue, name: &str) -> i64 {
    let BuildTimeValue::Struct { fields, .. } = build else {
        panic!("expected the augmented Build struct, got {build:?}");
    };
    match fields.iter().find(|(field, _)| field == name) {
        Some((_, BuildTimeValue::Int(value))) => *value,
        other => panic!("Build field {name} missing or non-int: {other:?}"),
    }
}

#[test]
fn filesystem_operands_prepare_before_real_authority() {
    let base = std::env::temp_dir().join(format!(
        "omega_filesystem_preparation_{}",
        std::process::id()
    ));
    let _ = std::fs::remove_dir_all(&base);
    let out = base.join("out");
    std::fs::create_dir_all(&out).expect("create preparation output root");
    let prepared_file = out.join("prepared.txt");
    let cross_domain_file = out.join("cross-domain.txt");
    std::fs::write(&cross_domain_file, "unchanged\n").expect("seed cross-domain probe file");
    let original_modified = std::fs::metadata(&cross_domain_file)
        .unwrap()
        .modified()
        .unwrap();
    let outside = base.join("outside-link");
    let main_path = base.join("main.omg");
    std::fs::write(
        &main_path,
        format!(
            r#"use omega::language::std::filesystem_host;

data Build {{ target_index: i64; staged: i64; }}

data IgnoredOperandProbe {{
    fs: FilesystemHost;
    dividend: i32 in Trapping;
    divisor: i32 in Trapping;
    fd: i32;
}}

machine IgnoredOperandProbe::run(&mut self, build: &mut Build) {{
    self.dividend = 1;
    self.divisor = 0;
    self.fd = self.fs.create(
        "{prepared_file}",
        (self.dividend / self.divisor) as i32
    );
    build.target_index = 7;
}}

data InvalidOutputProbe {{
    fs: FilesystemHost;
    buffer: [u8; 1];
    n: i64;
}}

machine InvalidOutputProbe::run(&mut self, build: &mut Build) {{
    self.n = self.fs.read_link("{outside}", &mut self.buffer, 2);
    build.target_index = 9;
}}

data CanonicalizeOutputProbe {{
    fs: FilesystemHost;
    buffer: [u8; 1023];
    result: i64;
}}

machine CanonicalizeOutputProbe::run(&mut self, build: &mut Build) {{
    self.result = self.fs.canonicalize("{outside}", &mut self.buffer);
    build.target_index = 11;
}}

data CrossDomainProbe {{
    fs: FilesystemHost;
    descriptor: i32;
    handle: i64;
    filetime: [u8; 8];
    result: i32;
}}

machine CrossDomainProbe::run(&mut self, build: &mut Build) {{
    self.descriptor = self.fs.open("{cross_domain_file}", 2);
    self.handle = self.descriptor as i64;
    self.result = self.fs.set_file_time(self.handle, 0, &self.filetime, &self.filetime);
    build.target_index = 13;
}}
"#,
            prepared_file = omg_path(&prepared_file),
            outside = omg_path(&outside),
            cross_domain_file = omg_path(&cross_domain_file),
        ),
    )
    .expect("write preparation probe");
    let checked = compile_to_checked(&main_path, None).unwrap_or_else(|diagnostics| {
        panic!(
            "filesystem preparation probe compile failed:\n{}",
            diagnostics
                .iter()
                .map(|diagnostic| diagnostic.to_string())
                .collect::<Vec<_>>()
                .join("\n")
        )
    });
    let options = || InterpretOptions {
        filesystem: FilesystemAccess::RealScoped(FsGrants {
            read_roots: vec![],
            write_roots: vec![grant_root(2, out.clone())],
        }),
        ..InterpretOptions::default()
    };

    let ignored_operand_failure = evaluate_build_machine_with_filesystem_measured(
        &checked.typed,
        "IgnoredOperandProbe::run",
        vec![zero_build()],
        options(),
    )
    .expect_err("the formerly ignored create mode must be evaluated");
    assert_eq!(
        ignored_operand_failure.kind(),
        BuildMachineEvaluationFailureKind::Trap
    );
    let [ignored_operand_attempt] = ignored_operand_failure
        .observations()
        .expect("ordinary preparation failure retains observations")
        .filesystem_operation_attempts()
    else {
        panic!("ignored-operand failure must retain exactly one outer operation attempt")
    };
    assert_eq!(ignored_operand_attempt.operation_tag(), 1);
    assert_eq!(
        ignored_operand_attempt.outcome(),
        Some(FilesystemOperationAttemptOutcome::EvaluationHalted(
            FilesystemEvaluationHaltKind::Trap
        ))
    );
    assert!(ignored_operand_attempt.grant_refusals().is_empty());
    assert!(
        !prepared_file.exists(),
        "ignored ABI operands must finish preparation before create can touch disk"
    );

    let failure = evaluate_build_machine_with_filesystem_measured(
        &checked.typed,
        "InvalidOutputProbe::run",
        vec![zero_build()],
        options(),
    )
    .expect_err("an undersized mutable output must reject during preparation");
    assert_eq!(failure.kind(), BuildMachineEvaluationFailureKind::Trap);
    let [attempt] = failure
        .observations()
        .expect("ordinary preparation failure retains observations")
        .filesystem_operation_attempts()
    else {
        panic!("preparation failure must retain exactly one outer operation attempt")
    };
    assert_eq!(attempt.operation_tag(), 21);
    assert_eq!(
        attempt.outcome(),
        Some(FilesystemOperationAttemptOutcome::EvaluationHalted(
            FilesystemEvaluationHaltKind::Trap
        ))
    );
    assert!(
        attempt.grant_refusals().is_empty(),
        "mutable-output preparation must fail before path grants are consulted"
    );

    let canonicalize_failure = evaluate_build_machine_with_filesystem_measured(
        &checked.typed,
        "CanonicalizeOutputProbe::run",
        vec![zero_build()],
        options(),
    )
    .expect_err("canonicalize must enforce its declared PATH_MAX carrier");
    assert_eq!(
        canonicalize_failure.kind(),
        BuildMachineEvaluationFailureKind::Trap
    );
    let [canonicalize_attempt] = canonicalize_failure
        .observations()
        .expect("ordinary preparation failure retains observations")
        .filesystem_operation_attempts()
    else {
        panic!("canonicalize preparation failure must retain exactly one operation attempt")
    };
    assert_eq!(canonicalize_attempt.operation_tag(), 22);
    assert_eq!(
        canonicalize_attempt.outcome(),
        Some(FilesystemOperationAttemptOutcome::EvaluationHalted(
            FilesystemEvaluationHaltKind::Trap
        ))
    );
    assert!(
        canonicalize_attempt.grant_refusals().is_empty(),
        "canonicalize capacity preparation must fail before path grants are consulted"
    );

    let cross_domain_failure = evaluate_build_machine_with_filesystem_measured(
        &checked.typed,
        "CrossDomainProbe::run",
        vec![zero_build()],
        options(),
    )
    .expect_err("a descriptor token cannot be used as an unborrowed native handle");
    assert_eq!(
        cross_domain_failure.kind(),
        BuildMachineEvaluationFailureKind::Trap
    );
    let [opened, rejected] = cross_domain_failure
        .observations()
        .expect("cross-domain preflight failure retains observations")
        .filesystem_operation_attempts()
    else {
        panic!("cross-domain probe must retain its open and rejected mutation")
    };
    assert_eq!(opened.operation_tag(), 2);
    assert!(matches!(
        opened.outcome(),
        Some(FilesystemOperationAttemptOutcome::Returned {
            result: FilesystemOperationResult::LogicalHandle(_),
            ..
        })
    ));
    assert_eq!(rejected.operation_tag(), 32);
    assert_eq!(
        rejected.outcome(),
        Some(FilesystemOperationAttemptOutcome::EvaluationHalted(
            FilesystemEvaluationHaltKind::Trap
        ))
    );
    let [native_input] = rejected.logical_handle_inputs() else {
        panic!("rejected native operation must retain its prepared handle input")
    };
    assert_eq!(native_input.kind(), FilesystemLogicalHandleKind::Native);
    assert_eq!(
        native_input.resolution(),
        FilesystemLogicalHandleInputResolution::Unknown
    );
    assert_eq!(
        std::fs::metadata(&cross_domain_file)
            .unwrap()
            .modified()
            .unwrap(),
        original_modified,
        "logical-domain rejection must precede provider metadata mutation"
    );

    let _ = std::fs::remove_dir_all(&base);
}

#[test]
fn staging_sponsor_preserves_source_reads_errno_and_resource_ceiling() {
    let base =
        std::env::temp_dir().join(format!("omega_filesystem_sponsor_{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&base);
    let source = base.join("source");
    let out = base.join("out");
    std::fs::create_dir_all(&source).expect("create source root");
    std::fs::create_dir_all(&out).expect("create output root");
    std::fs::write(source.join("input.txt"), b"source bytes").expect("seed source file");

    let main_path = base.join("main.omg");
    std::fs::write(
        &main_path,
        format!(
            r#"use omega::language::std::filesystem_host;

data Build {{ target_index: i64; staged: i64; }}

data SourceReadProbe {{
    fs: FilesystemHost;
    flags: i32;
    capacity: u64;
    fd: i32;
    read_count: i64;
    close_result: i64;
    buffer: [u8; 16];
}}

machine SourceReadProbe::run(&mut self, build: &mut Build) {{
    self.flags = 0;
    self.capacity = 16;
    self.fd = self.fs.open("{source}/input.txt", self.flags);
    self.read_count = self.fs.read(self.fd, &mut self.buffer, self.capacity);
    self.close_result = self.fs.close(self.fd);
    build.target_index = self.read_count;
}}

data MissingParentProbe {{ fs: FilesystemHost; fd: i32; error: i64; }}

machine MissingParentProbe::run(&mut self, build: &mut Build) {{
    self.fd = self.fs.create("{out}/missing/artifact", 438);
    self.error = self.fs.errno();
    build.target_index = self.error;
}}

data ResourceProbe {{ fs: FilesystemHost; fd: i32; written: i64; }}

machine ResourceProbe::run(&mut self, build: &mut Build) {{
    self.fd = self.fs.create("{out}/artifact", 438);
    self.written = self.fs.write(self.fd, "12345");
    build.target_index = self.written;
}}
"#,
            source = omg_path(&source),
            out = omg_path(&out),
        ),
    )
    .expect("write sponsor probe");
    let checked = compile_to_checked(&main_path, None).unwrap_or_else(|diagnostics| {
        panic!(
            "filesystem sponsor probe compile failed:\n{}",
            diagnostics
                .iter()
                .map(|diagnostic| diagnostic.to_string())
                .collect::<Vec<_>>()
                .join("\n")
        )
    });
    let canonical_out = std::fs::canonicalize(&out).expect("canonicalize output root");
    let sponsor = FilesystemSponsor::with_limits(
        canonical_out,
        FilesystemSponsorLimits {
            maximum_entries: 1,
            maximum_total_logical_bytes: 4,
            maximum_object_extent: 4,
        },
    )
    .expect("create staging sponsor");
    let options = || InterpretOptions {
        filesystem: FilesystemAccess::RealScopedSponsored {
            grants: FsGrants {
                read_roots: vec![grant_root(1, source.clone())],
                write_roots: vec![grant_root(2, out.clone())],
            },
            sponsor: sponsor.clone(),
        },
        ..InterpretOptions::default()
    };

    evaluate_build_machine_with_filesystem_measured(
        &checked.typed,
        "SourceReadProbe::run",
        vec![zero_build()],
        options(),
    )
    .expect("read-only source access stays outside the staging account");
    assert_eq!(sponsor.snapshot().unwrap().entries, 0);

    evaluate_build_machine_with_filesystem_measured(
        &checked.typed,
        "MissingParentProbe::run",
        vec![zero_build()],
        options(),
    )
    .expect("a missing output parent remains an ordinary errno result");
    assert_eq!(sponsor.snapshot().unwrap().entries, 0);
    assert!(!out.join("missing/artifact").exists());

    let failure = evaluate_build_machine_with_filesystem_measured(
        &checked.typed,
        "ResourceProbe::run",
        vec![zero_build()],
        options(),
    )
    .expect_err("a write beyond the sponsored extent must halt before mutation");
    assert_eq!(
        failure.kind(),
        BuildMachineEvaluationFailureKind::ResourceExhausted
    );
    assert!(
        failure
            .observations()
            .expect("resource failure retains operation evidence")
            .filesystem_operation_attempts()
            .iter()
            .any(|attempt| attempt.outcome()
                == Some(FilesystemOperationAttemptOutcome::EvaluationHalted(
                    FilesystemEvaluationHaltKind::ResourceExhausted
                )))
    );
    assert_eq!(std::fs::metadata(out.join("artifact")).unwrap().len(), 0);
    let snapshot = sponsor.snapshot().expect("inspect staging account");
    assert_eq!(snapshot.entries, 1);
    assert_eq!(snapshot.total_logical_bytes, 0);
    assert_eq!(snapshot.open_descriptors, 0);

    let _ = std::fs::remove_dir_all(&base);
}

#[test]
fn granted_build_machine_stages_assets_and_augments_the_build() {
    let base = std::env::temp_dir().join(format!("omega_granted_build_{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&base);
    let out = base.join("out");
    std::fs::create_dir_all(&out).expect("create out root");

    let main_path = base.join("main.omg");
    std::fs::write(&main_path, granted_build_program(&out)).expect("write probe program");
    let checked = compile_to_checked(&main_path, None).unwrap_or_else(|diagnostics| {
        panic!(
            "granted-build probe compile failed:\n{}",
            diagnostics
                .iter()
                .map(|d| d.to_string())
                .collect::<Vec<_>>()
                .join("\n")
        )
    });

    // REAL SCOPED: the asset lands on disk; the augmented Build reads back.
    let real_evaluation = evaluate_build_machine_with_filesystem_measured(
        &checked.typed,
        "Stager::build",
        vec![zero_build()],
        InterpretOptions {
            filesystem: FilesystemAccess::RealScoped(FsGrants {
                read_roots: vec![],
                write_roots: vec![grant_root(2, out.clone())],
            }),
            ..InterpretOptions::default()
        },
    )
    .expect("granted build run");
    let logical_handles = |observations: &psi_checked_interpreter::EvaluationObservations| {
        observations
            .filesystem_operation_attempts()
            .iter()
            .map(|attempt| {
                (
                    attempt.operation_tag(),
                    attempt.logical_handle_inputs().to_vec(),
                    attempt.logical_handle_output(),
                    attempt.retired_logical_handles().to_vec(),
                )
            })
            .collect::<Vec<_>>()
    };
    let real_logical_handles = logical_handles(real_evaluation.observations());
    let augmented = real_evaluation.into_value();
    let build = augmented.last().expect("the Build argument comes back");
    assert_eq!(
        build_field(build, "staged"),
        1,
        "staging must have succeeded"
    );
    assert_eq!(build_field(build, "target_index"), 7);
    assert_eq!(
        std::fs::read(out.join("asset.bin")).expect("staged asset on real disk"),
        b"staged by build\n",
    );

    // HERMETIC DEFAULT: the same machine runs against the virtual fs --
    // same augmentation, nothing on real disk.
    std::fs::remove_file(out.join("asset.bin")).expect("clear staged asset");
    let hermetic_evaluation = evaluate_build_machine_with_filesystem_measured(
        &checked.typed,
        "Stager::build",
        vec![zero_build()],
        InterpretOptions::default(),
    )
    .expect("hermetic granted build run");
    assert_eq!(
        logical_handles(hermetic_evaluation.observations()),
        real_logical_handles,
        "equivalent virtual and scoped-real operations must normalize to the same logical lifetimes"
    );
    let hermetic = hermetic_evaluation.into_value();
    let build = hermetic.last().expect("the Build argument comes back");
    assert_eq!(build_field(build, "staged"), 1, "virtual staging succeeds");
    assert!(
        !out.join("asset.bin").exists(),
        "hermetic default must not touch real disk"
    );

    let _ = std::fs::remove_dir_all(&base);
}

#[test]
fn granted_build_serves_console_and_rejects_other_boundaries() {
    let base = std::env::temp_dir().join(format!("omega_granted_deny_{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&base);
    std::fs::create_dir_all(&base).expect("create probe base");

    let main_path = base.join("main.omg");
    std::fs::write(
        &main_path,
        r#"// Granted-build backstop probe (generated by tests/real_fs.rs).
// CONSOLE writes are SERVED during granted builds (owner answer #5,
// 2026-07-11k -- the compile-time effect gate verifies the declared rows;
// this direct-entry probe exercises the evaluator's own behavior); every
// OTHER non-filesystem boundary still trips the backstop.
boundary trait Console { machine write(text: &[u8]); }
boundary trait Beeper { machine beep(count: i32); }

data Build { target_index: i64; }

data Chatty { console: Console; }

machine Chatty::build(&mut self, builder: &mut Build) {
    self.console.write("granted build logging is served");
    builder.target_index = 1;
}

data Noisy { beeper: Beeper; }

machine Noisy::build(&mut self, builder: &mut Build) {
    self.beeper.beep(3);
    builder.target_index = 2;
}

data Main { }
machine Main::main(&mut self) { }
"#,
    )
    .expect("write probe program");
    let checked = compile_to_checked(&main_path, None).unwrap_or_else(|diagnostics| {
        panic!(
            "backstop probe compile failed:\n{}",
            diagnostics
                .iter()
                .map(|d| d.to_string())
                .collect::<Vec<_>>()
                .join("\n")
        )
    });

    let zero = || BuildTimeValue::Struct {
        type_name: "Build".to_owned(),
        fields: vec![("target_index".to_owned(), BuildTimeValue::Int(0))],
    };

    let served = evaluate_build_machine_with_filesystem(
        &checked.typed,
        "Chatty::build",
        vec![zero()],
        InterpretOptions::default(),
    )
    .expect("a console-writing build machine is SERVED, not rejected");
    let BuildTimeValue::Struct { fields, .. } = &served[0] else {
        panic!("expected the augmented Build, got {served:?}");
    };
    assert_eq!(
        fields[0],
        ("target_index".to_owned(), BuildTimeValue::Int(1)),
        "the console-writing build's augmentation must flow"
    );

    let error = evaluate_build_machine_with_filesystem(
        &checked.typed,
        "Noisy::build",
        vec![zero()],
        InterpretOptions::default(),
    )
    .expect_err("a non-console non-filesystem boundary must still be rejected");
    assert!(
        error.contains("NON-filesystem") || error.contains("not yet supported"),
        "the refusal is LOUD (backstop policy or unsupported host call), got: {error}"
    );

    let _ = std::fs::remove_dir_all(&base);
}

/// The OP-PARITY probe (2026-07-10m): every op the virtual fs serves, the
/// real provider now serves. One program walks the formerly-ENOTSUP set --
/// canonicalize, hard_link, symlink + read_link, set_permissions, open_at +
/// read-through, unlink_at, flock EX|NB + UN, set_file_times + stat
/// round-trip -- tallying 14 steps; identical exit on BOTH engines.
fn parity_program(base: &Path) -> String {
    format!(
        r#"// Real-provider op-parity probe (generated by tests/real_fs.rs).
use omega::language::std::filesystem_host;

boundary trait Console {{ machine exit_process(return_code: i32); }}

data Main {{
    console: Console;
    fs: FilesystemHost;
    mode: i32;
    fd: i32;
    dirfd: i32;
    n: i64;
    rc: i64;
    flag: i64;
    buffer: [u8; 1024];
    times: [u8; 32];
    stat_buf: [u8; 144];
    mtime: i64 in Wrapping;
    passed: i32 in Wrapping;
}}

machine Main::main(&mut self) {{
    self.mode = 438;
    // 0. The working dir must exist in BOTH worlds (the temp base exists
    // only on real disk; the virtual fs needs its own create_dir).
    self.rc = self.fs.create_dir("{base}/w", 493);
    transition self.rc == 0 {{ true -> seed() _ -> done() }}
    state seed(&mut self) {{
        self.passed = self.passed + 1;
    // 1. Seed a real file.
    self.fd = self.fs.create("{base}/w/x.txt", self.mode);
    self.n = self.fs.write(self.fd, "abc");
    self.n = self.fs.close(self.fd);
    transition self.n == 0 {{ true -> canonical() _ -> done() }}
    }}
    state canonical(&mut self) {{
        self.passed = self.passed + 1;
        // 2. canonicalize resolves to a non-zero success flag.
        self.flag = self.fs.canonicalize("{base}/w/x.txt", &mut self.buffer);
        transition self.flag != 0 {{ true -> link() _ -> done() }}
    }}
    state link(&mut self) {{
        self.passed = self.passed + 1;
        // 3. hard_link mints a second name.
        self.rc = self.fs.hard_link("{base}/w/x.txt", "{base}/w/y.txt");
        transition self.rc == 0 {{ true -> sym() _ -> done() }}
    }}
    state sym(&mut self) {{
        self.passed = self.passed + 1;
        // 4. symlink records a target...
        self.rc = self.fs.symlink("x.txt", "{base}/w/z.lnk");
        transition self.rc == 0 {{ true -> readback_link() _ -> done() }}
    }}
    state readback_link(&mut self) {{
        self.passed = self.passed + 1;
        // 5. ...and read_link returns its 5 bytes.
        self.n = self.fs.read_link("{base}/w/z.lnk", &mut self.buffer, 256);
        transition self.n == 5 {{ true -> perms() _ -> done() }}
    }}
    state perms(&mut self) {{
        self.passed = self.passed + 1;
        // 6. chmod 0600.
        self.rc = self.fs.set_permissions("{base}/w/x.txt", 384);
        transition self.rc == 0 {{ true -> at_open() _ -> done() }}
    }}
    state at_open(&mut self) {{
        self.passed = self.passed + 1;
        // 7. openat the hard link through a dirfd and read it back.
        self.dirfd = self.fs.open("{base}/w", 0);
        self.fd = self.fs.open_at(self.dirfd, "y.txt", 0);
        transition self.fd >= 0 {{ true -> at_read() _ -> done() }}
    }}
    state at_read(&mut self) {{
        self.passed = self.passed + 1;
        self.n = self.fs.read(self.fd, &mut self.buffer, 8);
        self.rc = self.fs.close(self.fd);
        transition self.n == 3 {{ true -> at_unlink() _ -> done() }}
    }}
    state at_unlink(&mut self) {{
        self.passed = self.passed + 1;
        // 8. unlinkat removes the hard link; the dirfd closes clean.
        self.rc = self.fs.unlink_at(self.dirfd, "y.txt", 0);
        self.n = self.fs.close(self.dirfd);
        transition self.rc == 0 {{ true -> lock() _ -> done() }}
    }}
    state lock(&mut self) {{
        self.passed = self.passed + 1;
        // 9. flock EX|NB then UN on a writable fd.
        self.fd = self.fs.open("{base}/w/x.txt", 2);
        self.rc = self.fs.lock_file(self.fd, 6);
        transition self.rc == 0 {{ true -> unlock() _ -> done() }}
    }}
    state unlock(&mut self) {{
        self.passed = self.passed + 1;
        self.rc = self.fs.lock_file(self.fd, 8);
        transition self.rc == 0 {{ true -> stamp() _ -> done() }}
    }}
    state stamp(&mut self) {{
        self.passed = self.passed + 1;
        // 10. futimens: mtime tv_sec = 1_500_000_000 (0x59682F00 LE at 16).
        self.times[16] = 0;
        self.times[17] = 47;
        self.times[18] = 104;
        self.times[19] = 89;
        self.rc = self.fs.set_file_times(self.fd, &self.times);
        self.n = self.fs.close(self.fd);
        transition self.rc == 0 {{ true -> restat() _ -> done() }}
    }}
    state restat(&mut self) {{
        self.passed = self.passed + 1;
        // 11. The stamped mtime round-trips through stat.
        self.rc = self.fs.read_metadata("{base}/w/x.txt", &mut self.stat_buf);
        transition self.rc == 0 {{ true -> decode() _ -> done() }}
    }}
    state decode(&mut self) {{
        self.mtime = (self.stat_buf[48] as i64 in Wrapping)
            | ((self.stat_buf[49] as i64 in Wrapping) << 8)
            | ((self.stat_buf[50] as i64 in Wrapping) << 16)
            | ((self.stat_buf[51] as i64 in Wrapping) << 24)
            | ((self.stat_buf[52] as i64 in Wrapping) << 32)
            | ((self.stat_buf[53] as i64 in Wrapping) << 40)
            | ((self.stat_buf[54] as i64 in Wrapping) << 48)
            | ((self.stat_buf[55] as i64 in Wrapping) << 56);
        transition self.mtime == 1500000000 {{ true -> finish() _ -> done() }}
    }}
    state finish(&mut self) {{
        self.passed = self.passed + 1;
        transition true {{ true -> done() _ -> done() }}
    }}
    state done(&mut self) {{ self.console.exit_process(self.passed as i32); }}
}}
"#,
        base = omg_path(&base),
    )
}

/// The windows twin of `parity_program`: the SERVED op set only. The
/// unix-gated trio (symlink + read_link riding it, set_permissions) is
/// refused by the real provider on windows BY DESIGN (ENOTSUP, the
/// 2026-07-10m parity ruling) while the host-independent virtual fs serves
/// it everywhere, so those steps cannot tally identically in both worlds on
/// this host; their windows real-mode refusal is pinned by
/// `windows_real_mode_refuses_the_unix_gated_ops` below. The stat decode
/// reads the WINDOWS `_stat64` mtime offset (@40; the darwin twin reads
/// @48). Tally = 11 (the unix walk's 14 minus the three unix-gated steps).
fn parity_program_windows(base: &Path) -> String {
    format!(
        r#"// Real-provider op-parity probe, windows walk (generated by tests/real_fs.rs).
use omega::language::std::filesystem_host;

boundary trait Console {{ machine exit_process(return_code: i32); }}

data Main {{
    console: Console;
    fs: FilesystemHost;
    mode: i32;
    fd: i32;
    dirfd: i32;
    n: i64;
    rc: i64;
    flag: i64;
    buffer: [u8; 1024];
    times: [u8; 32];
    stat_buf: [u8; 144];
    mtime: i64 in Wrapping;
    passed: i32 in Wrapping;
}}

machine Main::main(&mut self) {{
    self.mode = 438;
    // 0. The working dir must exist in BOTH worlds (the temp base exists
    // only on real disk; the virtual fs needs its own create_dir).
    self.rc = self.fs.create_dir("{base}/w", 493);
    transition self.rc == 0 {{ true -> seed() _ -> done() }}
    state seed(&mut self) {{
        self.passed = self.passed + 1;
    // 1. Seed a real file.
    self.fd = self.fs.create("{base}/w/x.txt", self.mode);
    self.n = self.fs.write(self.fd, "abc");
    self.n = self.fs.close(self.fd);
    transition self.n == 0 {{ true -> canonical() _ -> done() }}
    }}
    state canonical(&mut self) {{
        self.passed = self.passed + 1;
        // 2. canonicalize resolves to a non-zero success flag.
        self.flag = self.fs.canonicalize("{base}/w/x.txt", &mut self.buffer);
        transition self.flag != 0 {{ true -> link() _ -> done() }}
    }}
    state link(&mut self) {{
        self.passed = self.passed + 1;
        // 3. hard_link mints a second name.
        self.rc = self.fs.hard_link("{base}/w/x.txt", "{base}/w/y.txt");
        transition self.rc == 0 {{ true -> at_open() _ -> done() }}
    }}
    state at_open(&mut self) {{
        self.passed = self.passed + 1;
        // 4. openat the hard link through a dirfd and read it back.
        self.dirfd = self.fs.open("{base}/w", 0);
        self.fd = self.fs.open_at(self.dirfd, "y.txt", 0);
        transition self.fd >= 0 {{ true -> at_read() _ -> done() }}
    }}
    state at_read(&mut self) {{
        self.passed = self.passed + 1;
        self.n = self.fs.read(self.fd, &mut self.buffer, 8);
        self.rc = self.fs.close(self.fd);
        transition self.n == 3 {{ true -> at_unlink() _ -> done() }}
    }}
    state at_unlink(&mut self) {{
        self.passed = self.passed + 1;
        // 5. unlinkat removes the hard link; the dirfd closes clean.
        self.rc = self.fs.unlink_at(self.dirfd, "y.txt", 0);
        self.n = self.fs.close(self.dirfd);
        transition self.rc == 0 {{ true -> lock() _ -> done() }}
    }}
    state lock(&mut self) {{
        self.passed = self.passed + 1;
        // 6. flock EX|NB then UN on a writable fd.
        self.fd = self.fs.open("{base}/w/x.txt", 2);
        self.rc = self.fs.lock_file(self.fd, 6);
        transition self.rc == 0 {{ true -> unlock() _ -> done() }}
    }}
    state unlock(&mut self) {{
        self.passed = self.passed + 1;
        self.rc = self.fs.lock_file(self.fd, 8);
        transition self.rc == 0 {{ true -> stamp() _ -> done() }}
    }}
    state stamp(&mut self) {{
        self.passed = self.passed + 1;
        // 7. futimens: mtime tv_sec = 1_500_000_000 (0x59682F00 LE at 16).
        self.times[16] = 0;
        self.times[17] = 47;
        self.times[18] = 104;
        self.times[19] = 89;
        self.rc = self.fs.set_file_times(self.fd, &self.times);
        self.n = self.fs.close(self.fd);
        transition self.rc == 0 {{ true -> restat() _ -> done() }}
    }}
    state restat(&mut self) {{
        self.passed = self.passed + 1;
        // 8. The stamped mtime round-trips through stat (windows st_mtime @40).
        self.rc = self.fs.read_metadata("{base}/w/x.txt", &mut self.stat_buf);
        transition self.rc == 0 {{ true -> decode() _ -> done() }}
    }}
    state decode(&mut self) {{
        self.mtime = (self.stat_buf[40] as i64 in Wrapping)
            | ((self.stat_buf[41] as i64 in Wrapping) << 8)
            | ((self.stat_buf[42] as i64 in Wrapping) << 16)
            | ((self.stat_buf[43] as i64 in Wrapping) << 24)
            | ((self.stat_buf[44] as i64 in Wrapping) << 32)
            | ((self.stat_buf[45] as i64 in Wrapping) << 40)
            | ((self.stat_buf[46] as i64 in Wrapping) << 48)
            | ((self.stat_buf[47] as i64 in Wrapping) << 56);
        transition self.mtime == 1500000000 {{ true -> finish() _ -> done() }}
    }}
    state finish(&mut self) {{
        self.passed = self.passed + 1;
        transition true {{ true -> done() _ -> done() }}
    }}
    state done(&mut self) {{ self.console.exit_process(self.passed as i32); }}
}}
"#,
        base = omg_path(&base),
    )
}

#[test]
fn real_provider_serves_the_full_virtual_op_set() {
    let base = std::env::temp_dir().join(format!("omega_fs_parity_{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&base);
    std::fs::create_dir_all(&base).expect("create parity base");

    let main_path = base.join("main.omg");
    let (program, tally) = if cfg!(windows) {
        (parity_program_windows(&base), 11)
    } else {
        (parity_program(&base), 14)
    };
    std::fs::write(&main_path, program).expect("write probe program");
    let checked = compile_to_checked(&main_path, None).unwrap_or_else(|diagnostics| {
        panic!(
            "parity probe compile failed:\n{}",
            diagnostics
                .iter()
                .map(|d| d.to_string())
                .collect::<Vec<_>>()
                .join("\n")
        )
    });

    // REAL mode: the whole walk against real disk.
    let real = interpret_with_options(
        &checked,
        &[],
        InterpretOptions {
            filesystem: FilesystemAccess::RealScoped(FsGrants {
                read_roots: vec![],
                write_roots: vec![grant_root(2, base.clone())],
            }),
            ..InterpretOptions::default()
        },
    );
    assert!(
        !real.is_error(),
        "real parity run errored: {:?}",
        real.error
    );
    assert_eq!(real.exit_code, tally, "real-mode parity steps");
    // The world after: the hard link is gone, the symlink is real (unix
    // walk only -- the windows walk has no symlink step), the stamped
    // mtime persisted.
    assert!(
        !base.join("w").join("y.txt").exists(),
        "unlink_at removed the link"
    );
    #[cfg(unix)]
    assert!(
        std::fs::symlink_metadata(base.join("w").join("z.lnk"))
            .expect("symlink exists")
            .file_type()
            .is_symlink(),
        "z.lnk is a real symlink"
    );

    // HERMETIC: the identical program walks the virtual fs to the same tally.
    let hermetic = interpret(&checked, &[]);
    assert!(
        !hermetic.is_error(),
        "hermetic parity run errored: {:?}",
        hermetic.error
    );
    assert_eq!(hermetic.exit_code, tally, "virtual-mode parity steps");

    let _ = std::fs::remove_dir_all(&base);
}

/// The DESIGNED windows real-mode refusal surface (the 2026-07-10m parity
/// ruling's unix-gated trio): symlink, set_permissions, and change_owner
/// refuse with ENOTSUP (45, the single modeled value) on the real provider.
/// Hermetic is deliberately NOT compared here -- the host-independent
/// virtual fs serves these ops everywhere; this test documents that designed
/// divergence instead of hiding it.
#[cfg(windows)]
#[test]
fn windows_real_mode_refuses_the_unix_gated_ops() {
    let base = std::env::temp_dir().join(format!("omega_fs_enotsup_{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&base);
    std::fs::create_dir_all(&base).expect("create refusal base");

    let program = format!(
        r#"// Windows unix-gated-op refusal probe (generated by tests/real_fs.rs).
use omega::language::std::filesystem_host;

boundary trait Console {{ machine exit_process(return_code: i32); }}

data Main {{
    console: Console;
    fs: FilesystemHost;
    mode: i32;
    fd: i32;
    n: i64;
    rc: i64;
    e: i64;
}}

machine Main::main(&mut self) {{
    self.mode = 438;
    self.fd = self.fs.create("{base}/x.txt", self.mode);
    self.n = self.fs.close(self.fd);
    transition self.fd >= 0 {{ true -> sym() _ -> bad(71) }}
    state sym(&mut self) {{
        self.rc = self.fs.symlink("x.txt", "{base}/z.lnk");
        self.e = self.fs.errno();
        transition self.rc == 0 - 1 {{ true -> sym_errno() _ -> bad(72) }}
    }}
    state sym_errno(&mut self) {{
        transition self.e == 45 {{ true -> perms() _ -> bad(73) }}
    }}
    state perms(&mut self) {{
        self.rc = self.fs.set_permissions("{base}/x.txt", 384);
        self.e = self.fs.errno();
        transition self.rc == 0 - 1 {{ true -> perms_errno() _ -> bad(74) }}
    }}
    state perms_errno(&mut self) {{
        transition self.e == 45 {{ true -> owner() _ -> bad(75) }}
    }}
    state owner(&mut self) {{
        self.rc = self.fs.change_owner("{base}/x.txt", 0 - 1, 0 - 1);
        self.e = self.fs.errno();
        transition self.rc == 0 - 1 {{ true -> owner_errno() _ -> bad(76) }}
    }}
    state owner_errno(&mut self) {{
        transition self.e == 45 {{ true -> good() _ -> bad(77) }}
    }}
    state good(&mut self) {{ self.console.exit_process(70); }}
    state bad(&mut self, code: i32) {{ self.console.exit_process(code); }}
}}
"#,
        base = omg_path(&base),
    );
    let main_path = base.join("main.omg");
    std::fs::write(&main_path, program).expect("write probe program");
    let checked = compile_to_checked(&main_path, None).unwrap_or_else(|diagnostics| {
        panic!(
            "refusal probe compile failed:\n{}",
            diagnostics
                .iter()
                .map(|d| d.to_string())
                .collect::<Vec<_>>()
                .join("\n")
        )
    });

    let real = interpret_with_options(
        &checked,
        &[],
        InterpretOptions {
            filesystem: FilesystemAccess::RealScoped(FsGrants {
                read_roots: vec![],
                write_roots: vec![grant_root(2, base.clone())],
            }),
        },
    );
    assert!(!real.is_error(), "refusal probe errored: {:?}", real.error);
    assert_eq!(
        real.exit_code, 70,
        "each unix-gated op must refuse with rc -1 + errno ENOTSUP(45) \
         (71 seed; 72/73 symlink rc/errno; 74/75 set_permissions; 76/77 change_owner)"
    );
    assert!(
        !base.join("z.lnk").exists(),
        "the refused symlink must not appear on disk"
    );

    let _ = std::fs::remove_dir_all(&base);
}
