[package]
name = "omega-optimization-policy-offline"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_optimization_policy_offline"
path = "src/lib.rs"

[[bin]]
name = "omega-optimization-policy-offline"
path = "src/bin/omega-optimization-policy-offline/main.rs"

[dependencies]
omega-optimization-core = { path = "../../representations/omega-optimization-core" }
sha2 = "0.10.9"
