[package]
name = "omega-layout"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_layout"
path = "src/lib.rs"

[dependencies]
omega-core = { path = "../../foundation/omega-core" }
omega-typed-program = { path = "../../representations/omega-typed-program" }
