[package]
name = "omega-syntax-trees-to-symbol-resolved-trees"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_syntax_trees_to_symbol_resolved_trees"
path = "src/lib.rs"

[dependencies]
psi-syntax-trees-to-symbol-resolved-trees = { path = "../../../psi-rs/pipeline/psi-syntax-trees-to-symbol-resolved-trees" }
