[package]
name = "omega-state-guards"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_state_guards"
path = "src/lib.rs"

[dependencies]
psi-checked-trees = { path = "../../../psi/representations/psi-checked-trees" }
omega-control-flow = { path = "../../representations/omega-control-flow" }
psi-arena = { path = "../../../psi/foundation/psi-arena" }
psi-symbols = { path = "../../../psi/foundation/psi-symbols" }
omega-layout = { path = "../omega-layout" }
omega-runtime-storage = { path = "../omega-runtime-storage" }
omega-state-dispatch = { path = "../omega-state-dispatch" }
omega-state-graph = { path = "../../representations/omega-state-graph" }
omega-state-values = { path = "../omega-state-values" }
omega-target-operations = { path = "../../representations/omega-target-operations" }
psi-numerics = { path = "../../../psi/foundation/psi-numerics" }
psi-typed-trees = { path = "../../../psi/representations/psi-typed-trees" }
