[package]
name = "omega-state-graph-to-control-flow"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_state_graph_to_control_flow"
path = "src/lib.rs"

[dependencies]
psi-checked-trees = { path = "../../../psi-rs/representations/psi-checked-trees" }
omega-control-flow = { path = "../../representations/omega-control-flow" }
omega-core = { path = "../../foundation/omega-core" }
psi-symbols = { path = "../../../psi-rs/foundation/psi-symbols" }
omega-state-graph = { path = "../../representations/omega-state-graph" }
psi-diagnostics = { path = "../../../psi-rs/foundation/psi-diagnostics" }
psi-numerics = { path = "../../../psi-rs/foundation/psi-numerics" }

[dev-dependencies]
psi-language-semantics = { path = "../../../psi-rs/foundation/psi-language-semantics" }
