[package]
name = "component-publication"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "component_publication"
path = "src/lib.rs"

[dependencies]
effects = { path = "../../../representations/effects" }
executable-installation = { path = "../executable-installation" }
external-roots = { path = "../external-roots" }
image-emission = { path = "../../images/image-emission", features = ["installed-artifact"] }
