[package]
name = "omega-instruction-selection"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_instruction_selection"
path = "src/lib.rs"

[dependencies]
omega-abstract-operations = { path = "../../representations/omega-abstract-operations" }
omega-calling-conventions = { path = "../omega-calling-conventions" }
omega-checked-trees = { path = "../../representations/omega-checked-trees" }
omega-control-flow = { path = "../../representations/omega-control-flow" }
omega-core = { path = "../../foundation/omega-core" }
omega-isa-aarch64 = { path = "../instruction_set_architectures/omega-isa-aarch64" }
omega-isa-x86_64 = { path = "../instruction_set_architectures/omega-isa-x86_64" }
omega-layout = { path = "../omega-layout" }
omega-object-file = { path = "../object/omega-object-file" }
omega-platform-interface = { path = "../omega-platform-interface" }
omega-runtime-abi = { path = "../omega-runtime-abi" }
omega-runtime-bodies = { path = "../omega-runtime-bodies" }
omega-runtime-branching = { path = "../omega-runtime-branching" }
omega-runtime-dispatch-loop = { path = "../omega-runtime-dispatch-loop" }
omega-runtime-storage = { path = "../omega-runtime-storage" }
omega-runtime-text = { path = "../omega-runtime-text" }
omega-state-calls = { path = "../omega-state-calls" }
omega-state-graph = { path = "../../representations/omega-state-graph" }
omega-state-guards = { path = "../omega-state-guards" }
omega-state-schedule = { path = "../omega-state-schedule" }
omega-state-storage = { path = "../omega-state-storage" }
omega-state-values = { path = "../omega-state-values" }
omega-target = { path = "../omega-target" }
