#!/usr/bin/env sh
# CHECKER DIAMOND — diverse double-checking of the trust anchor.
#
# The lattice's security thesis is "diversity = security": independent
# implementations that must agree. The most important place to apply it is the
# CHECKER itself. We have two: check.beta (Beta; term/type trees hand-encoded as
# tagged memory nodes, decided by integer-tag if-cascades) and checker.gamma
# (Gamma; the same logic as algebraic data + pattern matching, run on the gamma
# reference interpreter). They were written differently, in different languages,
# at different rungs. For each proof below — expressed in BOTH input syntaxes — the
# two checkers must return the SAME verdict, and it must be the expected one. A
# disagreement would expose a bug (or a backdoor) in one of them.
cd "$(dirname "$0")"
. ../alpha/seed_env.sh
SEED=../alpha/$ALPHA_SEED
ASM=../beta/$BETA_SEED
T=$(mktemp -d); trap 'rm -rf "$T"' EXIT

( cd ../beta-lang-rs && sh build.sh ../beta-lang/bc.beta >/dev/null ) || { echo "bc build failed"; exit 1; }
bcc() { ../beta-lang-rs/build/bc.exe < "$1" > "$T/a.asm" && "$ASM" < "$T/a.asm" > "$T/a.tape" && stamp_seed "$T/a.tape" "$SEED" "$2" >/dev/null 2>&1; }
bcc check.beta "$T/check.exe"          || { echo "build check.beta failed"; exit 1; }
bcc ../gamma/interp.beta "$T/interp.exe" || { echo "build interp.beta failed"; exit 1; }
DEFS=$(cat ../gamma/checker.gamma)

PASS=0; FAIL=0
# dia DESC  BETA_INPUT  GAMMA_CHECK_EXPR  EXPECT(accept|reject)
dia() {
  vb=$(printf '%s' "$2" | "$T/check.exe")                       # check.beta -> accept/reject
  printf '%s\n%s\n' "$DEFS" "$3" | "$T/interp.exe" >/dev/null; vg=$?   # gamma -> 1/0
  gv=reject; [ "$vg" = 1 ] && gv=accept
  if [ "$vb" = "$gv" ] && [ "$vb" = "$4" ]; then PASS=$((PASS+1))
  else FAIL=$((FAIL+1)); echo "  FAIL $1 : beta=$vb gamma=$gv expect=$4"; fi
}
#    desc            check.beta syntax                                          checker.gamma syntax                                                                   expect
dia "identity"       "(-> P P) (lam P (hyp 0))"                                  "(check (Lam (Atom 0) (Hyp 0)) (Arrow (Atom 0) (Atom 0)))"                              accept
dia "wrong goal"     "(-> P Q) (lam P (hyp 0))"                                  "(check (Lam (Atom 0) (Hyp 0)) (Arrow (Atom 0) (Atom 1)))"                              reject
dia "and-elim"       "(-> (& P Q) P) (lam (& P Q) (fst (hyp 0)))"                "(check (Lam (And (Atom 0) (Atom 1)) (Fst (Hyp 0))) (Arrow (And (Atom 0) (Atom 1)) (Atom 0)))" accept
dia "mismatch"       "(-> (& P Q) Q) (lam (& P Q) (fst (hyp 0)))"                "(check (Lam (And (Atom 0) (Atom 1)) (Fst (Hyp 0))) (Arrow (And (Atom 0) (Atom 1)) (Atom 1)))" reject
dia "modus ponens"   "(-> (& (-> P Q) P) Q) (lam (& (-> P Q) P) (app (fst (hyp 0)) (snd (hyp 0))))" "(check (Lam (And (Arrow (Atom 0) (Atom 1)) (Atom 0)) (App (Fst (Hyp 0)) (Snd (Hyp 0)))) (Arrow (And (Arrow (Atom 0) (Atom 1)) (Atom 0)) (Atom 1)))" accept
dia "or-commute"     "(-> (+ P Q) (+ Q P)) (lam (+ P Q) (case (hyp 0) (lam P (inr Q (hyp 0))) (lam Q (inl P (hyp 0)))))" "(check (Lam (Or (Atom 0) (Atom 1)) (Case (Hyp 0) (Lam (Atom 0) (Inr (Atom 1) (Hyp 0))) (Lam (Atom 1) (Inl (Atom 0) (Hyp 0))))) (Arrow (Or (Atom 0) (Atom 1)) (Or (Atom 1) (Atom 0))))" accept
dia "ex falso"       "(-> (bot) P) (lam (bot) (absurd P (hyp 0)))"               "(check (Lam Bot (Absurd (Atom 0) (Hyp 0))) (Arrow Bot (Atom 0)))"                      accept
dia "unbound hyp"    "P (hyp 0)"                                                 "(check (Hyp 0) (Atom 0))"                                                              reject
dia "refl 2+2=4"     "(= (p (s (s z)) (s (s z))) (s (s (s (s z)))))  (refl (s (s (s (s z)))))" "(check (Refl (Su (Su (Su (Su Ze))))) (Eq (Pl (Su (Su Ze)) (Su (Su Ze))) (Su (Su (Su (Su Ze))))))" accept
dia "reject 2+2=5"   "(= (p (s (s z)) (s (s z))) (s (s (s (s (s z))))))  (refl (s (s (s (s z)))))" "(check (Refl (Su (Su (Su (Su Ze))))) (Eq (Pl (Su (Su Ze)) (Su (Su Ze))) (Su (Su (Su (Su (Su Ze)))))))" reject
# first-order predicate logic: ∀ (gen/inst) and ∃ (wit/unpack)
dia "forall-intro"   "(All (-> (Pred 0 (v 0)) (Pred 0 (v 0)))) (gen (lam (Pred 0 (v 0)) (hyp 0)))" "(check (Gen (Lam (Pred 0 (Iv 0)) (Hyp 0))) (All (Arrow (Pred 0 (Iv 0)) (Pred 0 (Iv 0)))))" accept
dia "forall-elim"    "(-> (All (Pred 0 (v 0))) (Pred 0 z)) (lam (All (Pred 0 (v 0))) (inst (hyp 0) z))" "(check (Lam (All (Pred 0 (Iv 0))) (Inst (Hyp 0) Ze)) (Arrow (All (Pred 0 (Iv 0))) (Pred 0 Ze)))" accept
dia "P0 not forall"  "(-> (Pred 0 z) (All (Pred 0 (v 0)))) (lam (Pred 0 z) (gen (hyp 0)))" "(check (Lam (Pred 0 Ze) (Gen (Hyp 0))) (Arrow (Pred 0 Ze) (All (Pred 0 (Iv 0)))))" reject
dia "exists-intro"   "(-> (Pred 0 z) (Exists (Pred 0 (v 0)))) (lam (Pred 0 z) (wit (Pred 0 (v 0)) z (hyp 0)))" "(check (Lam (Pred 0 Ze) (Wit (Pred 0 (Iv 0)) Ze (Hyp 0))) (Arrow (Pred 0 Ze) (Exists (Pred 0 (Iv 0)))))" accept
dia "exists-elim"    "(-> (Exists (Pred 0 (v 0))) (-> (All (-> (Pred 0 (v 0)) Q)) Q)) (lam (Exists (Pred 0 (v 0))) (lam (All (-> (Pred 0 (v 0)) Q)) (unpack (hyp 1) (hyp 0))))" "(check (Lam (Exists (Pred 0 (Iv 0))) (Lam (All (Arrow (Pred 0 (Iv 0)) (Atom 9))) (Unpack (Hyp 1) (Hyp 0)))) (Arrow (Exists (Pred 0 (Iv 0))) (Arrow (All (Arrow (Pred 0 (Iv 0)) (Atom 9))) (Atom 9))))" accept
dia "witness leak"   "(-> (Exists (Pred 0 (v 0))) (-> (All (-> (Pred 0 (v 0)) (Pred 0 (v 0)))) (Pred 0 (v 0)))) (lam (Exists (Pred 0 (v 0))) (lam (All (-> (Pred 0 (v 0)) (Pred 0 (v 0)))) (unpack (hyp 1) (hyp 0))))" "(check (Lam (Exists (Pred 0 (Iv 0))) (Lam (All (Arrow (Pred 0 (Iv 0)) (Pred 0 (Iv 0)))) (Unpack (Hyp 1) (Hyp 0)))) (Arrow (Exists (Pred 0 (Iv 0))) (Arrow (All (Arrow (Pred 0 (Iv 0)) (Pred 0 (Iv 0)))) (Pred 0 (Iv 0)))))" reject
# real first-order reasoning: instantiate at the gen-bound variable (open witness)
dia "forall-distrib" "(-> (All (-> (Pred 0 (v 0)) (Pred 1 (v 0)))) (-> (All (Pred 0 (v 0))) (All (Pred 1 (v 0))))) (lam (All (-> (Pred 0 (v 0)) (Pred 1 (v 0)))) (lam (All (Pred 0 (v 0))) (gen (app (inst (hyp 1) (v 0)) (inst (hyp 0) (v 0))))))" "(check (Lam (All (Arrow (Pred 0 (Iv 0)) (Pred 1 (Iv 0)))) (Lam (All (Pred 0 (Iv 0))) (Gen (App (Inst (Hyp 1) (Iv 0)) (Inst (Hyp 0) (Iv 0)))))) (Arrow (All (Arrow (Pred 0 (Iv 0)) (Pred 1 (Iv 0)))) (Arrow (All (Pred 0 (Iv 0))) (All (Pred 1 (Iv 0))))))" accept
dia "false converse" "(-> (All (-> (Pred 0 (v 0)) (Pred 1 (v 0)))) (-> (All (Pred 1 (v 0))) (All (Pred 0 (v 0))))) (lam (All (-> (Pred 0 (v 0)) (Pred 1 (v 0)))) (lam (All (Pred 1 (v 0))) (gen (app (inst (hyp 1) (v 0)) (inst (hyp 0) (v 0))))))" "(check (Lam (All (Arrow (Pred 0 (Iv 0)) (Pred 1 (Iv 0)))) (Lam (All (Pred 1 (Iv 0))) (Gen (App (Inst (Hyp 1) (Iv 0)) (Inst (Hyp 0) (Iv 0)))))) (Arrow (All (Arrow (Pred 0 (Iv 0)) (Pred 1 (Iv 0)))) (Arrow (All (Pred 1 (Iv 0))) (All (Pred 0 (Iv 0))))))" reject
# binary relations
dia "rel tautology"  "(All (All (-> (Rel 0 (v 1) (v 0)) (Rel 0 (v 1) (v 0))))) (gen (gen (lam (Rel 0 (v 1) (v 0)) (hyp 0))))" "(check (Gen (Gen (Lam (Rel 0 (Iv 1) (Iv 0)) (Hyp 0)))) (All (All (Arrow (Rel 0 (Iv 1) (Iv 0)) (Rel 0 (Iv 1) (Iv 0))))))" accept
dia "rel args ordered" "(-> (Rel 0 z (s z)) (Rel 0 (s z) z)) (lam (Rel 0 z (s z)) (hyp 0))" "(check (Lam (Rel 0 Ze (Su Ze)) (Hyp 0)) (Arrow (Rel 0 Ze (Su Ze)) (Rel 0 (Su Ze) Ze)))" reject
# capture-avoiding substitution: instantiate under nested quantifiers, and the
# discriminator (a capturing bug would accept the second) — both checkers must agree
dia "inst nested ∀"  "(-> (All (All (Rel 0 (v 1) (v 0)))) (All (Rel 0 (v 0) (v 0)))) (lam (All (All (Rel 0 (v 1) (v 0)))) (gen (inst (inst (hyp 0) (v 0)) (v 0))))" "(check (Lam (All (All (Rel 0 (Iv 1) (Iv 0)))) (Gen (Inst (Inst (Hyp 0) (Iv 0)) (Iv 0)))) (Arrow (All (All (Rel 0 (Iv 1) (Iv 0)))) (All (Rel 0 (Iv 0) (Iv 0)))))" accept
dia "no capture"     "(-> (All (-> (Pred 0 (v 0)) (All (Rel 0 (v 1) (v 0))))) (All (-> (Pred 0 (v 0)) (All (Rel 0 (v 0) (v 0)))))) (lam (All (-> (Pred 0 (v 0)) (All (Rel 0 (v 1) (v 0))))) (gen (inst (hyp 0) (v 0))))" "(check (Lam (All (Arrow (Pred 0 (Iv 0)) (All (Rel 0 (Iv 1) (Iv 0))))) (Gen (Inst (Hyp 0) (Iv 0)))) (Arrow (All (Arrow (Pred 0 (Iv 0)) (All (Rel 0 (Iv 1) (Iv 0))))) (All (Arrow (Pred 0 (Iv 0)) (All (Rel 0 (Iv 0) (Iv 0)))))))" reject
# Peano induction, and the soundness discriminator (identity step) — both must agree
dia "induction princ" "(-> (Pred 0 z) (-> (All (-> (Pred 0 (v 0)) (Pred 0 (s (v 0))))) (All (Pred 0 (v 0))))) (lam (Pred 0 z) (lam (All (-> (Pred 0 (v 0)) (Pred 0 (s (v 0))))) (natind (Pred 0 (v 0)) (hyp 1) (hyp 0))))" "(check (Lam (Pred 0 Ze) (Lam (All (Arrow (Pred 0 (Iv 0)) (Pred 0 (Su (Iv 0))))) (Natind (Pred 0 (Iv 0)) (Hyp 1) (Hyp 0)))) (Arrow (Pred 0 Ze) (Arrow (All (Arrow (Pred 0 (Iv 0)) (Pred 0 (Su (Iv 0))))) (All (Pred 0 (Iv 0))))))" accept
dia "identity step"  "(-> (Pred 0 z) (-> (All (-> (Pred 0 (v 0)) (Pred 0 (v 0)))) (All (Pred 0 (v 0))))) (lam (Pred 0 z) (lam (All (-> (Pred 0 (v 0)) (Pred 0 (v 0)))) (natind (Pred 0 (v 0)) (hyp 1) (hyp 0))))" "(check (Lam (Pred 0 Ze) (Lam (All (Arrow (Pred 0 (Iv 0)) (Pred 0 (Iv 0)))) (Natind (Pred 0 (Iv 0)) (Hyp 1) (Hyp 0)))) (Arrow (Pred 0 Ze) (Arrow (All (Arrow (Pred 0 (Iv 0)) (Pred 0 (Iv 0)))) (All (Pred 0 (Iv 0))))))" reject
# the capstone: ∀n.(n+0 = n) proved by induction + Leibniz eqelim — both checkers agree
dia "n+0=n by induct" "(All (= (p (v 0) z) (v 0))) (natind (= (p (v 0) z) (v 0)) (refl z) (gen (lam (= (p (v 0) z) (v 0)) (eqelim (= (s (p (v 1) z)) (s (v 0))) (hyp 0) (refl (s (p (v 0) z)))))))" "(check (Natind (Eq (Pl (Iv 0) Ze) (Iv 0)) (Refl Ze) (Gen (Lam (Eq (Pl (Iv 0) Ze) (Iv 0)) (Eqelim (Eq (Su (Pl (Iv 1) Ze)) (Su (Iv 0))) (Hyp 0) (Refl (Su (Pl (Iv 0) Ze))))))) (All (Eq (Pl (Iv 0) Ze) (Iv 0))))" accept
dia "n*0=0 by induct" "(All (= (m (v 0) z) z)) (natind (= (m (v 0) z) z) (refl z) (gen (lam (= (m (v 0) z) z) (hyp 0))))" "(check (Natind (Eq (Mu (Iv 0) Ze) Ze) (Refl Ze) (Gen (Lam (Eq (Mu (Iv 0) Ze) Ze) (Hyp 0)))) (All (Eq (Mu (Iv 0) Ze) Ze)))" accept
dia "0 != 1 (disj)"  "(-> (= z (s z)) (bot)) (lam (= z (s z)) (disj (hyp 0)))" "(check (Lam (Eq Ze (Su Ze)) (Disj (Hyp 0))) (Arrow (Eq Ze (Su Ze)) Bot))" accept
dia "succ injective" "(-> (= (s (v 0)) (s z)) (= (v 0) z)) (lam (= (s (v 0)) (s z)) (sinj (hyp 0)))" "(check (Lam (Eq (Su (Iv 0)) (Su Ze)) (Sinj (Hyp 0))) (Arrow (Eq (Su (Iv 0)) (Su Ze)) (Eq (Iv 0) Ze)))" accept
dia "n != s n"       "(All (-> (= (v 0) (s (v 0))) (bot))) (natind (-> (= (v 0) (s (v 0))) (bot)) (lam (= z (s z)) (disj (hyp 0))) (gen (lam (-> (= (v 0) (s (v 0))) (bot)) (lam (= (s (v 0)) (s (s (v 0)))) (app (hyp 1) (sinj (hyp 0)))))))" "(check (Natind (Arrow (Eq (Iv 0) (Su (Iv 0))) Bot) (Lam (Eq Ze (Su Ze)) (Disj (Hyp 0))) (Gen (Lam (Arrow (Eq (Iv 0) (Su (Iv 0))) Bot) (Lam (Eq (Su (Iv 0)) (Su (Su (Iv 0)))) (App (Hyp 1) (Sinj (Hyp 0))))))) (All (Arrow (Eq (Iv 0) (Su (Iv 0))) Bot)))" accept
dia "0 or successor" "(All (+ (= (v 0) z) (Exists (= (v 1) (s (v 0)))))) (natind (+ (= (v 0) z) (Exists (= (v 1) (s (v 0))))) (inl (Exists (= z (s (v 0)))) (refl z)) (gen (lam (+ (= (v 0) z) (Exists (= (v 1) (s (v 0))))) (inr (= (s (v 0)) z) (wit (= (s (v 1)) (s (v 0))) (v 0) (refl (s (v 0))))))))" "(check (Natind (Or (Eq (Iv 0) Ze) (Exists (Eq (Iv 1) (Su (Iv 0))))) (Inl (Exists (Eq Ze (Su (Iv 0)))) (Refl Ze)) (Gen (Lam (Or (Eq (Iv 0) Ze) (Exists (Eq (Iv 1) (Su (Iv 0))))) (Inr (Eq (Su (Iv 0)) Ze) (Wit (Eq (Su (Iv 1)) (Su (Iv 0))) (Iv 0) (Refl (Su (Iv 0)))))))) (All (Or (Eq (Iv 0) Ze) (Exists (Eq (Iv 1) (Su (Iv 0)))))))" accept
dia "eq symmetric"   "(All (All (-> (= (v 1) (v 0)) (= (v 0) (v 1))))) (gen (gen (lam (= (v 1) (v 0)) (eqelim (= (v 0) (v 2)) (hyp 0) (refl (v 1))))))" "(check (Gen (Gen (Lam (Eq (Iv 1) (Iv 0)) (Eqelim (Eq (Iv 0) (Iv 2)) (Hyp 0) (Refl (Iv 1)))))) (All (All (Arrow (Eq (Iv 1) (Iv 0)) (Eq (Iv 0) (Iv 1))))))" accept
dia "eq transitive"  "(All (All (All (-> (= (v 2) (v 1)) (-> (= (v 1) (v 0)) (= (v 2) (v 0))))))) (gen (gen (gen (lam (= (v 2) (v 1)) (lam (= (v 1) (v 0)) (eqelim (= (v 3) (v 0)) (hyp 0) (hyp 1)))))))" "(check (Gen (Gen (Gen (Lam (Eq (Iv 2) (Iv 1)) (Lam (Eq (Iv 1) (Iv 0)) (Eqelim (Eq (Iv 3) (Iv 0)) (Hyp 0) (Hyp 1))))))) (All (All (All (Arrow (Eq (Iv 2) (Iv 1)) (Arrow (Eq (Iv 1) (Iv 0)) (Eq (Iv 2) (Iv 0))))))))" accept
# Lists: append computes the same way in both checkers
dia "concat lists"   "(= (app (cons z (cons (s z) nil)) (cons (s (s z)) nil)) (cons z (cons (s z) (cons (s (s z)) nil)))) (refl (cons z (cons (s z) (cons (s (s z)) nil))))" "(check (Refl (Lcons Ze (Lcons (Su Ze) (Lcons (Su (Su Ze)) Lnil)))) (Eq (Lapp (Lcons Ze (Lcons (Su Ze) Lnil)) (Lcons (Su (Su Ze)) Lnil)) (Lcons Ze (Lcons (Su Ze) (Lcons (Su (Su Ze)) Lnil)))))" accept
dia "list distinct"  "(= (cons z nil) (cons (s z) nil)) (refl (cons z nil))" "(check (Refl (Lcons Ze Lnil)) (Eq (Lcons Ze Lnil) (Lcons (Su Ze) Lnil)))" reject
# list induction: forall l. l ++ nil = l, and the identity-step soundness discriminator
dia "l ++ nil = l"   "(All (= (app (v 0) nil) (v 0))) (listind (= (app (v 0) nil) (v 0)) (refl nil) (gen (gen (lam (= (app (v 0) nil) (v 0)) (eqelim (= (cons (v 2) (app (v 1) nil)) (cons (v 2) (v 0))) (hyp 0) (refl (cons (v 1) (app (v 0) nil))))))))" "(check (Listind (Eq (Lapp (Iv 0) Lnil) (Iv 0)) (Refl Lnil) (Gen (Gen (Lam (Eq (Lapp (Iv 0) Lnil) (Iv 0)) (Eqelim (Eq (Lcons (Iv 2) (Lapp (Iv 1) Lnil)) (Lcons (Iv 2) (Iv 0))) (Hyp 0) (Refl (Lcons (Iv 1) (Lapp (Iv 0) Lnil)))))))) (All (Eq (Lapp (Iv 0) Lnil) (Iv 0))))" accept
dia "list ident step" "(-> (Pred 0 nil) (-> (All (All (-> (Pred 0 (v 0)) (Pred 0 (v 0))))) (All (Pred 0 (v 0))))) (lam (Pred 0 nil) (lam (All (All (-> (Pred 0 (v 0)) (Pred 0 (v 0))))) (listind (Pred 0 (v 0)) (hyp 1) (hyp 0))))" "(check (Lam (Pred 0 Lnil) (Lam (All (All (Arrow (Pred 0 (Iv 0)) (Pred 0 (Iv 0))))) (Listind (Pred 0 (Iv 0)) (Hyp 1) (Hyp 0)))) (Arrow (Pred 0 Lnil) (Arrow (All (All (Arrow (Pred 0 (Iv 0)) (Pred 0 (Iv 0))))) (All (Pred 0 (Iv 0))))))" reject
dia "append assoc"   "(All (All (All (= (app (app (v 0) (v 2)) (v 1)) (app (v 0) (app (v 2) (v 1))))))) (gen (gen (listind (= (app (app (v 0) (v 2)) (v 1)) (app (v 0) (app (v 2) (v 1)))) (refl (app (v 1) (v 0))) (gen (gen (lam (= (app (app (v 0) (v 3)) (v 2)) (app (v 0) (app (v 3) (v 2)))) (eqelim (= (cons (v 2) (app (app (v 1) (v 4)) (v 3))) (cons (v 2) (v 0))) (hyp 0) (refl (cons (v 1) (app (app (v 0) (v 3)) (v 2)))))))))))" "(check (Gen (Gen (Listind (Eq (Lapp (Lapp (Iv 0) (Iv 2)) (Iv 1)) (Lapp (Iv 0) (Lapp (Iv 2) (Iv 1)))) (Refl (Lapp (Iv 1) (Iv 0))) (Gen (Gen (Lam (Eq (Lapp (Lapp (Iv 0) (Iv 3)) (Iv 2)) (Lapp (Iv 0) (Lapp (Iv 3) (Iv 2)))) (Eqelim (Eq (Lcons (Iv 2) (Lapp (Lapp (Iv 1) (Iv 4)) (Iv 3))) (Lcons (Iv 2) (Iv 0))) (Hyp 0) (Refl (Lcons (Iv 1) (Lapp (Lapp (Iv 0) (Iv 3)) (Iv 2))))))))))) (All (All (All (Eq (Lapp (Lapp (Iv 0) (Iv 2)) (Iv 1)) (Lapp (Iv 0) (Lapp (Iv 2) (Iv 1))))))))" accept
dia "len(a++b)"     "(All (All (= (len (app (v 0) (v 1))) (p (len (v 0)) (len (v 1)))))) (gen (listind (= (len (app (v 0) (v 1))) (p (len (v 0)) (len (v 1)))) (refl (len (v 0))) (gen (gen (lam (= (len (app (v 0) (v 2))) (p (len (v 0)) (len (v 2)))) (eqelim (= (s (len (app (v 1) (v 3)))) (s (v 0))) (hyp 0) (refl (s (len (app (v 0) (v 2)))))))))))" "(check (Gen (Listind (Eq (Llen (Lapp (Iv 0) (Iv 1))) (Pl (Llen (Iv 0)) (Llen (Iv 1)))) (Refl (Llen (Iv 0))) (Gen (Gen (Lam (Eq (Llen (Lapp (Iv 0) (Iv 2))) (Pl (Llen (Iv 0)) (Llen (Iv 2)))) (Eqelim (Eq (Su (Llen (Lapp (Iv 1) (Iv 3)))) (Su (Iv 0))) (Hyp 0) (Refl (Su (Llen (Lapp (Iv 0) (Iv 2))))))))))) (All (All (Eq (Llen (Lapp (Iv 0) (Iv 1))) (Pl (Llen (Iv 0)) (Llen (Iv 1)))))))" accept
dia "n+sm=s(n+m)"   "(All (All (= (p (v 0) (s (v 1))) (s (p (v 0) (v 1)))))) (gen (natind (= (p (v 0) (s (v 1))) (s (p (v 0) (v 1)))) (refl (s (v 0))) (gen (lam (= (p (v 0) (s (v 1))) (s (p (v 0) (v 1)))) (eqelim (= (s (p (v 1) (s (v 2)))) (s (v 0))) (hyp 0) (refl (s (p (v 0) (s (v 1))))))))))" "(check (Gen (Natind (Eq (Pl (Iv 0) (Su (Iv 1))) (Su (Pl (Iv 0) (Iv 1)))) (Refl (Su (Iv 0))) (Gen (Lam (Eq (Pl (Iv 0) (Su (Iv 1))) (Su (Pl (Iv 0) (Iv 1)))) (Eqelim (Eq (Su (Pl (Iv 1) (Su (Iv 2)))) (Su (Iv 0))) (Hyp 0) (Refl (Su (Pl (Iv 0) (Su (Iv 1)))))))))) (All (All (Eq (Pl (Iv 0) (Su (Iv 1))) (Su (Pl (Iv 0) (Iv 1)))))))" accept
dia "+ associative" "(All (All (All (= (p (p (v 0) (v 2)) (v 1)) (p (v 0) (p (v 2) (v 1))))))) (gen (gen (natind (= (p (p (v 0) (v 2)) (v 1)) (p (v 0) (p (v 2) (v 1)))) (refl (p (v 1) (v 0))) (gen (lam (= (p (p (v 0) (v 2)) (v 1)) (p (v 0) (p (v 2) (v 1)))) (eqelim (= (s (p (p (v 1) (v 3)) (v 2))) (s (v 0))) (hyp 0) (refl (s (p (p (v 0) (v 2)) (v 1))))))))))" "(check (Gen (Gen (Natind (Eq (Pl (Pl (Iv 0) (Iv 2)) (Iv 1)) (Pl (Iv 0) (Pl (Iv 2) (Iv 1)))) (Refl (Pl (Iv 1) (Iv 0))) (Gen (Lam (Eq (Pl (Pl (Iv 0) (Iv 2)) (Iv 1)) (Pl (Iv 0) (Pl (Iv 2) (Iv 1)))) (Eqelim (Eq (Su (Pl (Pl (Iv 1) (Iv 3)) (Iv 2))) (Su (Iv 0))) (Hyp 0) (Refl (Su (Pl (Pl (Iv 0) (Iv 2)) (Iv 1)))))))))) (All (All (All (Eq (Pl (Pl (Iv 0) (Iv 2)) (Iv 1)) (Pl (Iv 0) (Pl (Iv 2) (Iv 1))))))))" accept
echo "checker diamond (check.beta vs checker.gamma): $PASS agree, $FAIL disagree"
[ "$FAIL" = 0 ] || exit 1
