#!/usr/bin/env python3
# forall-gen.py — MECHANICALLY generate a ∀-input theorem + its induction proof for a member of the
# constant-increment fold family, in elab.py's named-binder syntax. count-forall.elab (hand-authored) is
# the k=1 instance; this makes the whole family mechanical, proving the proof was a reusable SCHEMA, not a
# one-off — the automation step of the ∀-input climb.
#
# Family: a fold whose accumulator gains a fixed k successors per list element (count is k=1):
#     fold(Nil, n)      = n
#     fold(Cons h t, n) = fold(t, s^k n)
#     agg(Nil)          = 0
#     agg(Cons h t)     = s^k (agg t)                 ; the per-element contribution, aggregated
# Theorem (for every k):   ∀xs ∀n.  fold(xs, n) = agg(xs) + n
# proved by induction on xs, the IH used at the shifted accumulator s^k n, with a local lemma
#     addk:  ∀a ∀b.  uadd(a, s^k b) = s^k (uadd(a, b))            (by induction on the user nat a)
# All emitted terms are user nats (k2/k3) and user lists (k60/k61), matching the meaning route.
#
# usage: forall-gen.py K   ->  prints the .elab source for the k=K instance on stdout
import sys

FOLD, AGG, UADD = 91, 93, 21


def sk(x, k):                          # k nested user-successors around x
    for _ in range(k):
        x = '(k 3 %s)' % x
    return x


def gen(k):
    fold_step = sk('(y 0)', k)                         # fold's recx body: s^k(acc)
    agg_step = sk('(rec 1)', k)                        # agg's body: s^k(agg tail)
    L = []
    L.append('; GENERATED by forall-gen.py k=%d — do not edit by hand.' % k)
    L.append('; Theorem: forall xs n. fold_%d(xs, n) = agg_%d(xs) + n  (fold adds %d per element).' % (k, k, k))
    L.append('(data 2 0 0 0) (data 3 1 1 0) (data 60 0 0 0) (data 61 2 0 1)')
    L.append('(fun %d 2 (y 0)) (fun %d 3 (k 3 (rec 0)))' % (UADD, UADD))          # uadd
    L.append('(fun %d 60 (k 2)) (fun %d 61 %s)' % (AGG, AGG, agg_step))           # agg
    L.append('(fun %d 60 (y 0)) (fun %d 61 (recx 1 %s))' % (FOLD, FOLD, fold_step))  # fold
    # goal
    L.append('(all xs (all n (= (f %d xs n) (f %d (f %d xs) n))))' % (FOLD, UADD, AGG))
    # local lemma addk, then the main induction
    addk_mot = '(all b (= (f %d a %s) %s))' % (UADD, sk('b', k), sk('(f %d a b)' % UADD, k))
    L.append('(have addk %s' % ('(all a %s)' % addk_mot))
    #   addk proof: induction on a
    L.append('  (rec 2 3 a %s' % addk_mot)
    L.append('    (gen b (refl %s))' % sk('b', k))                                # base a=0
    a1_mot = '(all b (= (f %d a1 %s) %s))' % (UADD, sk('b', k), sk('(f %d a1 b)' % UADD, k))
    lhs1 = '(k 3 (f %d a1 %s))' % (UADD, sk('b', k))                              # s(uadd(a1, s^k b))
    L.append('    (gen a1 (lam ih %s' % a1_mot)
    L.append('      (gen b (eqelim x (= %s (k 3 x)) (inst ih b) (refl %s))))))' % (lhs1, lhs1))
    #   main proof: induction on xs
    xs_mot = '(all n (= (f %d xs n) (f %d (f %d xs) n)))' % (FOLD, UADD, AGG)
    t_mot = '(all n (= (f %d t n) (f %d (f %d t) n)))' % (FOLD, UADD, AGG)
    lhs2 = '(f %d t %s)' % (FOLD, sk('n', k))                                     # fold(t, s^k n)
    L.append('  (rec 60 61 xs %s' % xs_mot)
    L.append('    (gen n (refl n))')                                             # base xs=Nil
    L.append('    (gen h (gen t (lam ih %s' % t_mot)
    L.append('      (gen n (eqelim x (= %s x)' % lhs2)
    L.append('        (inst* addk (f %d t) n)' % AGG)                            # addk @ agg(t), n
    L.append('        (inst ih %s))))))))' % sk('n', k))                         # IH @ s^k n
    return '\n'.join(L) + '\n'


if __name__ == '__main__':
    sys.stdout.write(gen(int(sys.argv[1])))
