[package]
name = "psi-tokens-to-syntax-trees"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "psi_tokens_to_syntax_trees"
path = "src/lib.rs"

[dependencies]
psi-arena = { path = "../../foundation/psi-arena" }
psi-language-core = { path = "../../foundation/psi-language-core" }
psi-numerics = { path = "../../foundation/psi-numerics" }
psi-source = { path = "../../foundation/psi-source" }
psi-syntax-trees = { path = "../../representations/psi-syntax-trees" }
psi-tokens = { path = "../../representations/psi-tokens" }

[dev-dependencies]
psi-source-files-to-tokens = { path = "../psi-source-files-to-tokens" }
