[package]
name = "omega-isa-x86_64"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_isa_x86_64"
path = "src/lib.rs"

[dependencies]
omega-calling-conventions = { path = "../../omega-calling-conventions" }
omega-core = { path = "../../../foundation/omega-core" }
omega-target-operations = { path = "../../../representations/omega-target-operations" }
