[package]
name = "omega"
edition.workspace = true
license.workspace = true
version.workspace = true
default-run = "omega"

[[bin]]
name = "omega"
path = "src/main.rs"
test = false

[dependencies]
omega-compiler = { path = "orchestration/omega-compiler" }
omega-core = { path = "foundation/omega-core" }
omega-packages = { path = "orchestration/omega-packages" }
omega-package-compilation = { path = "orchestration/omega-package-compilation" }
omega-resolver-execution = { path = "orchestration/omega-resolver-execution" }
omega-target = { path = "foundation/omega-target" }
psi-checked-trees-to-terminal = { path = "../psi/pipeline/psi-checked-trees-to-terminal" }
psi-core = { path = "../psi/foundation/psi-core" }
psi-checked-interpreter = { path = "../psi/semantics/psi-checked-interpreter" }
psi-proof-admission = { path = "../psi/semantics/psi-proof-admission" }
psi-terminal = { path = "../psi/representations/psi-terminal" }
psi-terminal-fixed-fuel = { path = "../psi/semantics/psi-terminal-fixed-fuel" }
psi-terminal-verifier = { path = "../psi/semantics/psi-terminal-verifier" }
