#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum StraightLineWrappingIntegerDivideParametersTranslationError {
    SourceParameters,
    SourceStructuralParameters,
    SourceResult,
    SourceEntryClaims,
    SourcePublishedServices,
    SourceBlockRoster,
    SourceOperationRoster,
    SourceParameterRoster,
    SourceParameterShape,
    SourceDivideResultRoster,
    SourceLeftOperandLink,
    SourceRightOperandLink,
    SourceOperandTypeMismatch,
    SourceReturnLink,
    SourceCleanup,
    AbiPlan,
    AbiParameterCount,
    AbiParameterPlacement,
    TargetProvenance,
    TargetOperation,
}
