[package]
name = "omega-state-storage"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_state_storage"
path = "src/lib.rs"

[dependencies]
psi-checked-trees = { path = "../../../psi-rs/representations/psi-checked-trees" }
omega-control-flow = { path = "../../representations/omega-control-flow" }
omega-core = { path = "../../foundation/omega-core" }
psi-symbols = { path = "../../../psi-rs/foundation/psi-symbols" }
psi-numerics = { path = "../../../psi-rs/foundation/psi-numerics" }
omega-state-calls = { path = "../omega-state-calls" }
omega-state-graph = { path = "../../representations/omega-state-graph" }
omega-state-values = { path = "../omega-state-values" }
