[package]
name = "lowered-psi-to-lowered-psi"
autotests = false
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
checked-trees-to-lowered-psi = { path = "../05_checked-trees-to-lowered-psi" }
semantic-vocabulary = { path = "../../foundation/semantic-vocabulary" }
terminal-semantics = { path = "../../terminal-semantics" }
terminal-psi = { path = "../../terminal-psi" }
terminal-codec = { path = "../../terminal-codec" }
terminal-verifier = { path = "../../terminal-verifier" }

[dev-dependencies]
language-core = { path = "../../foundation/language-core" }
symbols = { path = "../../foundation/symbols" }

[[test]]
name = "suite"
path = "tests/suite.rs"
