//! Differential coverage for the exact free build activation.
//!
//! These probes keep activation authority on the canonical
//! `machine build(builder: &mut Build)` argument. Filesystem descriptors and
//! operation results are ordinary root locals; no synthesized receiver carries
//! build authority or scratch state.

use super::{grant_root, omg_path};
use checked_interpreter::{
    BuildTimeValue, EvaluationObservations, FilesystemAccess, FilesystemLogicalHandleOutput,
    FsGrants, InterpretOptions, evaluate_build_machine_with_filesystem,
    evaluate_build_machine_with_filesystem_measured,
};
use compiler::{CheckedCompilation, compile_to_checked};
use std::path::Path;

/// The GRANTED BUILD probe (rung 4, interpreter side): one exact free build
/// activation both stages a real asset through its granted filesystem and
/// augments the Build value read back by the compiler.
fn granted_build_program(output_root: &Path) -> String {
    format!(
        r#"// Granted-build probe (generated by tests/real_fs/build_activation.rs).
use omega::language::std::filesystem_host;

data Build {{
    target_index: i64;
    staged: i64;
    filesystem: FilesystemHost;
}}

machine build(builder: &mut Build)
reaches FilesystemHost
invokes FilesystemHost;
{{
    let descriptor: i32 = builder.filesystem.create("{output_root}/asset.bin", 438);
    transition descriptor >= 0 {{
        true -> put(builder, descriptor)
        _ -> mark(builder, 0 - 1)
    }}
    state put(builder: &mut Build, descriptor: i32) {{
        let written: i64 = builder.filesystem.write(descriptor, "staged by build\n");
        let closed: i32 = builder.filesystem.close(descriptor);
        transition written == 16 && closed == 0 {{
            true -> mark(builder, 1)
            _ -> mark(builder, 0 - 1)
        }}
    }}
    state mark(builder: &mut Build, staged: i64) {{
        builder.target_index = 7;
        builder.staged = staged;
    }}
}}

data Main {{ }}
machine Main::main(&mut self) {{ }}
"#,
        output_root = omg_path(output_root),
    )
}

fn staging_build_argument() -> BuildTimeValue {
    BuildTimeValue::Struct {
        type_name: "Build".to_owned(),
        fields: vec![
            ("target_index".to_owned(), BuildTimeValue::Int(0)),
            ("staged".to_owned(), BuildTimeValue::Int(0)),
            (
                "filesystem".to_owned(),
                BuildTimeValue::Struct {
                    type_name: "FilesystemHost".to_owned(),
                    fields: Vec::new(),
                },
            ),
        ],
    }
}

fn build_integer_field(build: &BuildTimeValue, name: &str) -> i64 {
    let BuildTimeValue::Struct { fields, .. } = build else {
        panic!("expected the augmented Build struct, got {build:?}");
    };
    match fields.iter().find(|(field, _)| field == name) {
        Some((_, BuildTimeValue::Int(value))) => *value,
        other => panic!("Build field {name} missing or non-int: {other:?}"),
    }
}

fn logical_handle_lifetimes(
    observations: &EvaluationObservations,
) -> Vec<(
    u16,
    Vec<checked_interpreter::FilesystemLogicalHandleInput>,
    Option<FilesystemLogicalHandleOutput>,
    Vec<checked_interpreter::FilesystemLogicalHandleIdentity>,
)> {
    observations
        .filesystem_operation_attempts()
        .iter()
        .map(|attempt| {
            (
                attempt.operation_tag(),
                attempt.logical_handle_inputs().to_vec(),
                attempt.logical_handle_output(),
                attempt.retired_logical_handles().to_vec(),
            )
        })
        .collect()
}

fn compile_probe(path: &Path, source: &str, label: &str) -> CheckedCompilation {
    std::fs::write(path, source).unwrap_or_else(|error| panic!("write {label} probe: {error}"));
    compile_to_checked(path, None).unwrap_or_else(|diagnostics| {
        panic!(
            "{label} probe compile failed:\n{}",
            diagnostics
                .iter()
                .map(ToString::to_string)
                .collect::<Vec<_>>()
                .join("\n")
        )
    })
}

#[test]
fn granted_build_machine_stages_assets_and_augments_the_build() {
    let base = std::env::temp_dir().join(format!("omega_granted_build_{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&base);
    let output_root = base.join("out");
    std::fs::create_dir_all(&output_root).expect("create output root");

    let checked = compile_probe(
        &base.join("main.omg"),
        &granted_build_program(&output_root),
        "granted build",
    );

    // REAL SCOPED: the asset lands on disk; the augmented Build reads back.
    let real_evaluation = evaluate_build_machine_with_filesystem_measured(
        &checked.typed,
        "build",
        vec![staging_build_argument()],
        InterpretOptions {
            filesystem: FilesystemAccess::RealScoped(FsGrants {
                read_roots: vec![],
                write_roots: vec![grant_root(2, output_root.clone())],
            }),
            ..InterpretOptions::default()
        },
    )
    .expect("granted build run");
    let real_logical_handles = logical_handle_lifetimes(real_evaluation.observations());
    let augmented = real_evaluation.into_value();
    let build = augmented.last().expect("the Build argument comes back");
    assert_eq!(
        build_integer_field(build, "staged"),
        1,
        "staging must have succeeded"
    );
    assert_eq!(build_integer_field(build, "target_index"), 7);
    assert_eq!(
        std::fs::read(output_root.join("asset.bin")).expect("staged asset on real disk"),
        b"staged by build\n",
    );

    // HERMETIC DEFAULT: the identical free machine runs against the virtual
    // filesystem with the same observations and leaves real disk untouched.
    std::fs::remove_file(output_root.join("asset.bin")).expect("clear staged asset");
    let hermetic_evaluation = evaluate_build_machine_with_filesystem_measured(
        &checked.typed,
        "build",
        vec![staging_build_argument()],
        InterpretOptions::default(),
    )
    .expect("hermetic granted build run");
    assert_eq!(
        logical_handle_lifetimes(hermetic_evaluation.observations()),
        real_logical_handles,
        "equivalent virtual and scoped-real operations must normalize to the same logical lifetimes"
    );
    let hermetic = hermetic_evaluation.into_value();
    let build = hermetic.last().expect("the Build argument comes back");
    assert_eq!(
        build_integer_field(build, "staged"),
        1,
        "virtual staging succeeds"
    );
    assert!(
        !output_root.join("asset.bin").exists(),
        "hermetic default must not touch real disk"
    );

    let _ = std::fs::remove_dir_all(&base);
}

const CONSOLE_BUILD_PROGRAM: &str = r#"// Granted-build console probe.
boundary trait Console { machine write(text: &[u8]); }

data Build {
    target_index: i64;
    console: Console;
}

machine build(builder: &mut Build)
reaches Console
{
    let console: &mut Console = &mut builder.console;
    console.write("granted build logging is served");
    builder.target_index = 1;
}
"#;

const BEEPER_BUILD_PROGRAM: &str = r#"// Granted-build unsupported-boundary probe.
boundary trait Beeper { machine beep(count: i32); }

data Build {
    target_index: i64;
    beeper: Beeper;
}

machine build(builder: &mut Build)
reaches Beeper
{
    let beeper: &mut Beeper = &mut builder.beeper;
    beeper.beep(3);
    builder.target_index = 2;
}
"#;

fn boundary_build_argument(field_name: &str, service_name: &str) -> BuildTimeValue {
    BuildTimeValue::Struct {
        type_name: "Build".to_owned(),
        fields: vec![
            ("target_index".to_owned(), BuildTimeValue::Int(0)),
            (
                field_name.to_owned(),
                BuildTimeValue::Struct {
                    type_name: service_name.to_owned(),
                    fields: Vec::new(),
                },
            ),
        ],
    }
}

#[test]
fn granted_build_serves_console_and_rejects_other_boundaries() {
    let base = std::env::temp_dir().join(format!("omega_granted_deny_{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&base);
    std::fs::create_dir_all(&base).expect("create probe base");

    let console = compile_probe(
        &base.join("console.omg"),
        CONSOLE_BUILD_PROGRAM,
        "granted-build console",
    );
    let beeper = compile_probe(
        &base.join("beeper.omg"),
        BEEPER_BUILD_PROGRAM,
        "granted-build unsupported boundary",
    );

    let served = evaluate_build_machine_with_filesystem(
        &console.typed,
        "build",
        vec![boundary_build_argument("console", "Console")],
        InterpretOptions::default(),
    )
    .expect("a console-writing build machine is served, not rejected");
    assert_eq!(
        build_integer_field(&served[0], "target_index"),
        1,
        "the console-writing build's augmentation must flow"
    );

    let error = evaluate_build_machine_with_filesystem(
        &beeper.typed,
        "build",
        vec![boundary_build_argument("beeper", "Beeper")],
        InterpretOptions::default(),
    )
    .expect_err("a non-console non-filesystem boundary must still be rejected");
    assert!(
        error.contains("NON-filesystem") || error.contains("not yet supported"),
        "the refusal is LOUD (backstop policy or unsupported host call), got: {error}"
    );

    let _ = std::fs::remove_dir_all(&base);
}
