// aarch64.rs — ARM64 (macOS) backend, the sibling to x64.rs the module layout
// always anticipated. It emits ARM64 *assembly text*; the driver (main.rs) shells
// out to `clang -arch arm64` to assemble + link a Mach-O and `codesign -s -` for
// the ad-hoc signature Apple Silicon requires before it will exec.
//
// Why text + system assembler here, when x64.rs emits raw machine code: this is
// the THROWAWAY on-ramp (its trust lineage is discarded — see main.rs), and the
// point of this backend is to make delta-rs *runnable, hence verifiable*, on
// macOS arm64, where the x64 PE backend's output cannot execute at all.
//
// Lowering model mirrors x64.rs: a STACK MACHINE. Every expression evaluates into
// w0 and is pushed; binary ops pop rhs then lhs. Locals live in an x29-relative
// frame. The "trap everything" decision (x64's ud2 on overflow / idiv on /0) maps
// to ARM64 condition-flag branches to a single `Ltrap: brk` per machine.
//
// Slices ported to this backend:
//   1. exit_process(<const>)              -> exit status is the constant.
//   2. expressions + locals + arithmetic  -> `let x = 3 + 4*2; exit_process(x)`,
//      with trap-on-overflow (add/sub/mul) and trap-on-divide-by-zero.
//   4. comparisons + `transition`/`state` control flow -> each machine's state
//      blocks become labels; a transition dispatches on the subject.
//   5. mutable reassignment (`i = e`) + back-edge transitions -> real loops.
//   6. machine calls (the DAG) -> every machine is a function; a free call passes
//      args in x0..x3 and `bl`s the callee; the return value comes back in w0.
// Not yet ported (fall through to a safe 0 / no-op): self/fields, method (self)
// calls, host I/O (write_line is a silent no-op for now). Those are later slices.
//
// Each machine lowers to ONE function sharing its x29 frame across `entry` + every
// `state`, so locals persist across transitions. State si of machine mi is labeled
// `Lm<mi>s<si>`; a back-edge is a backward branch = a loop. The entry machine is
// `_main`; others are `Lmachine<mi>`. Cross-machine `bl`s resolve by label, so
// forward references in the call graph just work.

use crate::ast::{BinaryOp, Expr, Machine, Pattern, Program, Statement};
use std::sync::atomic::{AtomicU8, Ordering};

// The arithmetic DOMAIN in force while lowering a `let _: i32 in <Domain> = ...` initializer (0 Trapping
// default, 1 Wrapping, 2 Saturating). The +/-/* arms below pick trap / wrap / saturate accordingly.
// Lowering is single-threaded, so a module flag suffices; it is cleared before the next statement, so
// domain-typed inits should be direct arithmetic (the domain-type slice's samples are).
static DOMAIN: AtomicU8 = AtomicU8::new(0);

pub fn lower_program(program: &Program) -> String {
    let mut asm = String::new();
    asm.push_str("// generated by the proof kernel-rs aarch64 backend (slices 1-2, 4-6)\n");
    asm.push_str(".global _main\n.align 2\n");

    // Machines emit in source order; the entry is found by its `_main` label (a global
    // symbol the linker resolves by name), so its position in the file is immaterial. This
    // keeps the streaming self-hoster's natural source-order emission byte-identical.
    for machine_index in 0..program.machines.len() {
        lower_machine(machine_index, program, &mut asm);
    }

    // The single trap target shared by every machine: overflow, divide-by-zero,
    // and out-of-bounds indexing land here (brk faults the process — the analog of
    // x64's ud2 / idiv #DE).
    if program.uses_imports {
        emit_flush_support(&mut asm);
        asm.push_str("Ltrap:\n    bl Lflush_output\n    brk #0x1\n");
    } else {
        asm.push_str("Ltrap:\n    brk #0x1\n");
    }

    // This target provisions the entry machine's receiver as a zero-initialized
    // instance in writable image storage.
    let entry = &program.machines[program.entry_machine];
    if entry.has_self && program.entry_data_size > 0 {
        let size = align8(program.entry_data_size);
        asm.push_str(&format!(".zerofill __DATA,__bss,_selfdata,{},3\n", size));
    }

    // A 1-byte static scratch buffer for write_byte / read_byte.
    if program.uses_imports {
        asm.push_str(".zerofill __DATA,__bss,_iobyte,1,0\n");
        asm.push_str(".zerofill __DATA,__bss,_iobuf_used,4,2\n");
        asm.push_str(".zerofill __DATA,__bss,_iobuf,4096,4\n");
    }

    // write_line string literals as read-only data (raw bytes — write() uses an
    // explicit length, so no NUL terminator is needed).
    if !program.strings.is_empty() {
        asm.push_str(".section __TEXT,__const\n.align 2\n");
        for (string_index, bytes) in program.strings.iter().enumerate() {
            asm.push_str(&format!("Lstr{}:\n", string_index));
            if !bytes.is_empty() {
                let list: Vec<String> = bytes.iter().map(|b| b.to_string()).collect();
                asm.push_str(&format!("    .byte {}\n", list.join(",")));
            }
        }
    }
    asm
}

fn machine_label(machine_index: usize, program: &Program) -> String {
    if machine_index == program.entry_machine {
        "_main".to_string()
    } else {
        format!("Lmachine{}", machine_index)
    }
}

fn lower_machine(machine_index: usize, program: &Program, asm: &mut String) {
    let machine: &Machine = &program.machines[machine_index];
    let local_count = machine.local_count.max(0) as i32;
    // frame = saved {x29,x30} (16) + a slot per local + (one self-pointer slot),
    // 16-aligned. The self slot sits just past the locals.
    let self_disp = 16 + 8 * local_count;
    let frame = align16(16 + 8 * local_count + if machine.has_self { 8 } else { 0 });

    asm.push_str(&format!("{}:\n", machine_label(machine_index, program)));
    // prologue
    asm.push_str(&format!("    sub sp, sp, #{}\n", frame));
    asm.push_str("    stp x29, x30, [sp]\n");
    asm.push_str("    mov x29, sp\n");
    let is_entry = machine_index == program.entry_machine;
    // A non-entry method takes self in x0, so its value params start at x1.
    let self_register_offset = if machine.has_self && !is_entry { 1 } else { 0 };
    // spill incoming value params into their local slots
    for param_position in 0..machine.param_count {
        asm.push_str(&format!(
            "    str w{}, [x29, #{}]\n",
            param_position + self_register_offset,
            local_displacement(param_position)
        ));
    }
    // establish the self pointer. Entry: the target-provisioned zero-init receiver,
    // but only when there are data fields (`_selfdata` is emitted iff size > 0; a
    // `&mut self` with no fields, e.g. exit7, never dereferences self). Non-entry
    // method: self arrives in x0 (the caller's self-pointer, so every method sees
    // one instance).
    if machine.has_self {
        if is_entry {
            if program.entry_data_size > 0 {
                asm.push_str("    adrp x9, _selfdata@PAGE\n");
                asm.push_str("    add x9, x9, _selfdata@PAGEOFF\n");
                asm.push_str(&format!("    str x9, [x29, #{}]\n", self_disp));
            }
        } else {
            asm.push_str(&format!("    str x0, [x29, #{}]\n", self_disp));
        }
    }

    for statement in &machine.entry {
        lower_statement(statement, machine_index, program, frame, self_disp, asm);
    }
    if !machine.states.is_empty() && block_falls_through(&machine.entry) {
        emit_implicit_return(frame, is_entry && program.uses_imports, asm);
    }
    for (state_index, state_statements) in machine.states.iter().enumerate() {
        asm.push_str(&format!("Lm{}s{}:\n", machine_index, state_index));
        for statement in state_statements {
            lower_statement(statement, machine_index, program, frame, self_disp, asm);
        }
        if state_index + 1 < machine.states.len() && block_falls_through(state_statements) {
            emit_implicit_return(frame, is_entry && program.uses_imports, asm);
        }
    }
    // Preserve the existing trailing default for the final state (or entry when
    // there are no states). Explicit control flow makes it unreachable.
    emit_implicit_return(frame, is_entry && program.uses_imports, asm);
}

fn block_falls_through(statements: &[Statement]) -> bool {
    match statements.last() {
        Some(Statement::Transition(_, _) | Statement::Return(_) | Statement::Exit(_)) => false,
        Some(Statement::Block(inner)) => block_falls_through(inner),
        _ => true,
    }
}

fn emit_implicit_return(frame: i32, flush: bool, asm: &mut String) {
    if flush {
        asm.push_str("    bl Lflush_output\n");
    }
    asm.push_str("    mov w0, #0\n");
    emit_epilogue(frame, asm);
}

fn emit_flush_support(asm: &mut String) {
    asm.push_str(
        r#"Lflush_output:
    stp x19, x20, [sp, #-32]!
    str x30, [sp, #16]
    adrp x9, _iobuf_used@PAGE
    add x9, x9, _iobuf_used@PAGEOFF
    ldr w19, [x9]
    cbz w19, Lflush_done
    mov x20, #0
Lflush_loop:
    mov x0, #1
    adrp x1, _iobuf@PAGE
    add x1, x1, _iobuf@PAGEOFF
    add x1, x1, x20
    sub x2, x19, x20
    bl _write
    cmp x0, #0
    b.le Lflush_discard
    add x20, x20, x0
    cmp x20, x19
    b.lo Lflush_loop
Lflush_discard:
    adrp x9, _iobuf_used@PAGE
    add x9, x9, _iobuf_used@PAGEOFF
    str wzr, [x9]
Lflush_done:
    ldr x30, [sp, #16]
    ldp x19, x20, [sp], #32
    ret
"#,
    );
}

fn align16(n: i32) -> i32 {
    (n + 15) & !15
}

fn align8(n: i32) -> i32 {
    (n + 7) & !7
}

// Local i occupies the slot just past the saved {x29,x30} pair.
fn local_displacement(local_index: usize) -> i32 {
    16 + 8 * local_index as i32
}

fn emit_epilogue(frame: i32, asm: &mut String) {
    // w0 already holds the return/exit value.
    asm.push_str("    mov sp, x29\n");
    asm.push_str("    ldp x29, x30, [sp]\n");
    asm.push_str(&format!("    add sp, sp, #{}\n", frame));
    asm.push_str("    ret\n");
}

fn lower_statement(
    statement: &Statement,
    machine_index: usize,
    program: &Program,
    frame: i32,
    self_disp: i32,
    asm: &mut String,
) {
    match statement {
        Statement::Block(statements) => {
            for inner in statements {
                lower_statement(inner, machine_index, program, frame, self_disp, asm);
            }
        }
        Statement::Assert(expression) => {
            lower_expression(*expression, program, self_disp, asm);
            asm.push_str("    ldr x0, [sp], #16\n"); // pop the condition
            asm.push_str("    cbz w0, Ltrap\n"); // trap if false (zero)
        }
        Statement::Let(local_index, expression, domain) => {
            DOMAIN.store(*domain, Ordering::Relaxed); // arithmetic in the initializer uses this domain
            lower_expression(*expression, program, self_disp, asm);
            DOMAIN.store(0, Ordering::Relaxed);
            asm.push_str("    ldr x0, [sp], #16\n"); // pop value
            asm.push_str(&format!("    str w0, [x29, #{}]\n", local_displacement(*local_index)));
        }
        Statement::Assign(local_index, expression) => {
            lower_expression(*expression, program, self_disp, asm);
            asm.push_str("    ldr x0, [sp], #16\n"); // pop value
            asm.push_str(&format!("    str w0, [x29, #{}]\n", local_displacement(*local_index)));
        }
        Statement::StoreSelfField(offset, expression, domain) => {
            DOMAIN.store(*domain, Ordering::Relaxed); // arithmetic stored into a domain-typed field uses it
            lower_expression(*expression, program, self_disp, asm);
            DOMAIN.store(0, Ordering::Relaxed);
            asm.push_str("    ldr x0, [sp], #16\n"); // pop value
            asm.push_str(&format!("    ldr x9, [x29, #{}]\n", self_disp)); // self pointer
            // LDR/STR (32-bit) scaled immediate maxes at 16380; fold a larger offset into x9.
            if *offset <= 16380 {
                asm.push_str(&format!("    str w0, [x9, #{}]\n", offset)); // self.<field> = value
            } else {
                add_imm_to_x9(*offset, asm);
                asm.push_str("    str w0, [x9]\n");
            }
        }
        Statement::StoreSelfIndex(field_offset, count, element_bytes, index, value) => {
            lower_expression(*value, program, self_disp, asm); // push value
            lower_expression(*index, program, self_disp, asm); // push index (popped first)
            emit_self_element_address(self_disp, *field_offset, *count, *element_bytes, asm); // x9 = &elem
            asm.push_str("    ldr x1, [sp], #16\n"); // pop value
            if *element_bytes == 1 {
                asm.push_str("    strb w1, [x9]\n");
            } else {
                asm.push_str("    str w1, [x9]\n");
            }
        }
        Statement::Eval(expression) => {
            lower_expression(*expression, program, self_disp, asm);
            asm.push_str("    ldr x0, [sp], #16\n"); // pop and discard
        }
        Statement::Return(expression) | Statement::Exit(expression) => {
            lower_expression(*expression, program, self_disp, asm);
            asm.push_str("    ldr x0, [sp], #16\n"); // pop into w0 (exit code / return value)
            if machine_index == program.entry_machine && program.uses_imports {
                asm.push_str("    str x0, [sp, #-16]!\n");
                asm.push_str("    bl Lflush_output\n");
                asm.push_str("    ldr x0, [sp], #16\n");
            }
            emit_epilogue(frame, asm);
        }
        Statement::Transition(subject, arms) => {
            // Evaluate the subject, then dispatch: an Int pattern is a compare +
            // conditional branch to its state label; `_` is an unconditional branch.
            lower_expression(*subject, program, self_disp, asm);
            asm.push_str("    ldr x0, [sp], #16\n"); // pop subject into w0
            let state_arg_base = program.machines[machine_index].param_count;
            for arm in arms {
                if arm.args.is_empty() {
                    // argless arm — unchanged lowering
                    match arm.pattern {
                        Pattern::Int(value) => {
                            emit_load_w1(value, asm);
                            asm.push_str("    cmp w0, w1\n");
                            asm.push_str(&format!("    b.eq Lm{}s{}\n", machine_index, arm.target));
                        }
                        Pattern::Wild => {
                            asm.push_str(&format!("    b Lm{}s{}\n", machine_index, arm.target));
                        }
                    }
                } else {
                    // arg-passing arm: on a match, evaluate args into the shared state-arg
                    // slots, then branch. Eval runs only on the match (branch-away) path, so
                    // w0 (the subject) survives for later arms. `1f`/`1:` is a forward local label.
                    let is_int = matches!(arm.pattern, Pattern::Int(_));
                    if let Pattern::Int(value) = arm.pattern {
                        emit_load_w1(value, asm);
                        asm.push_str("    cmp w0, w1\n");
                        asm.push_str("    b.ne 1f\n");
                    }
                    for arg in &arm.args {
                        lower_expression(*arg, program, self_disp, asm);
                    }
                    for i in (0..arm.args.len()).rev() {
                        asm.push_str("    ldr x0, [sp], #16\n"); // pop last-pushed arg first
                        asm.push_str(&format!(
                            "    str w0, [x29, #{}]\n",
                            local_displacement(state_arg_base + i)
                        ));
                    }
                    asm.push_str(&format!("    b Lm{}s{}\n", machine_index, arm.target));
                    if is_int {
                        asm.push_str("1:\n");
                    }
                }
            }
        }
        Statement::WriteLine(string_index) => {
            // write(1, &Lstr<i>, len) via libSystem. The string bytes are emitted
            // in a read-only data section by lower_program.
            let len = program.strings[*string_index].len() as i32;
            asm.push_str("    bl Lflush_output\n");
            asm.push_str("    mov x0, #1\n"); // fd = stdout
            asm.push_str(&format!("    adrp x1, Lstr{}@PAGE\n", string_index));
            asm.push_str(&format!("    add x1, x1, Lstr{}@PAGEOFF\n", string_index));
            emit_load_reg(2, len, asm); // x2 = len
            asm.push_str("    bl _write\n");
        }
        Statement::WriteByte(expression) => {
            // Buffer single-byte writes. Large compiler outputs otherwise spend
            // nearly all runtime crossing the host boundary one byte at a time.
            lower_expression(*expression, program, self_disp, asm);
            asm.push_str("    ldr x0, [sp], #16\n"); // pop value
            asm.push_str("    adrp x9, _iobuf_used@PAGE\n");
            asm.push_str("    add x9, x9, _iobuf_used@PAGEOFF\n");
            asm.push_str("    ldr w10, [x9]\n");
            asm.push_str("    cmp w10, #1, lsl #12\n");
            asm.push_str("    b.lo 1f\n");
            asm.push_str("    str x0, [sp, #-16]!\n");
            asm.push_str("    bl Lflush_output\n");
            asm.push_str("    ldr x0, [sp], #16\n");
            asm.push_str("    mov w10, #0\n");
            asm.push_str("    adrp x9, _iobuf_used@PAGE\n");
            asm.push_str("    add x9, x9, _iobuf_used@PAGEOFF\n");
            asm.push_str("1:\n");
            asm.push_str("    adrp x11, _iobuf@PAGE\n");
            asm.push_str("    add x11, x11, _iobuf@PAGEOFF\n");
            asm.push_str("    strb w0, [x11, x10]\n");
            asm.push_str("    add w10, w10, #1\n");
            asm.push_str("    str w10, [x9]\n");
        }
    }
}

fn lower_expression(node: usize, program: &Program, self_disp: i32, asm: &mut String) {
    match program.expressions[node] {
        Expr::Int(value) => {
            emit_load_w0(value, asm);
            asm.push_str("    str x0, [sp, #-16]!\n"); // push
        }
        Expr::Local(local_index) => {
            asm.push_str(&format!("    ldr w0, [x29, #{}]\n", local_displacement(local_index)));
            asm.push_str("    str x0, [sp, #-16]!\n"); // push
        }
        Expr::SelfField(offset) => {
            asm.push_str(&format!("    ldr x9, [x29, #{}]\n", self_disp)); // self pointer
            // LDR/STR (32-bit) scaled immediate maxes at 16380; fold a larger offset into x9.
            if offset <= 16380 {
                asm.push_str(&format!("    ldr w0, [x9, #{}]\n", offset)); // self.<field>
            } else {
                add_imm_to_x9(offset, asm);
                asm.push_str("    ldr w0, [x9]\n");
            }
            asm.push_str("    str x0, [sp, #-16]!\n"); // push
        }
        Expr::SelfIndex(field_offset, count, element_bytes, index) => {
            lower_expression(index, program, self_disp, asm); // push index
            emit_self_element_address(self_disp, field_offset, count, element_bytes, asm); // x9 = &elem
            if element_bytes == 1 {
                asm.push_str("    ldrb w0, [x9]\n");
            } else {
                asm.push_str("    ldr w0, [x9]\n");
            }
            asm.push_str("    str x0, [sp, #-16]!\n"); // push
        }
        Expr::SelfCall(machine_index, args_start, arg_count) => {
            // Like Call, but self goes in x0 and the value args shift to x1..x4.
            for index in 0..arg_count {
                lower_expression(program.call_args[args_start + index], program, self_disp, asm);
            }
            for index in (0..arg_count).rev() {
                asm.push_str(&format!("    ldr x{}, [sp], #16\n", index + 1));
            }
            asm.push_str(&format!("    ldr x0, [x29, #{}]\n", self_disp)); // self pointer
            asm.push_str(&format!("    bl {}\n", machine_label(machine_index, program)));
            asm.push_str("    str x0, [sp, #-16]!\n"); // push return value
        }
        Expr::Call(machine_index, args_start, arg_count) => {
            // Evaluate args left-to-right (each pushed), then pop them into x0..x3
            // top-down (arg N-1 is on top), `bl` the callee, push the w0 result.
            for index in 0..arg_count {
                lower_expression(program.call_args[args_start + index], program, self_disp, asm);
            }
            for index in (0..arg_count).rev() {
                asm.push_str(&format!("    ldr x{}, [sp], #16\n", index));
            }
            asm.push_str(&format!("    bl {}\n", machine_label(machine_index, program)));
            asm.push_str("    str x0, [sp, #-16]!\n"); // push return value
        }
        Expr::Binary(op, lhs, rhs) => {
            lower_expression(lhs, program, self_disp, asm);
            lower_expression(rhs, program, self_disp, asm);
            asm.push_str("    ldr x1, [sp], #16\n"); // pop rhs
            asm.push_str("    ldr x0, [sp], #16\n"); // pop lhs
            match op {
                BinaryOp::Add => match DOMAIN.load(Ordering::Relaxed) {
                    1 => asm.push_str("    add w0, w0, w1\n"), // Wrapping
                    2 => asm.push_str(
                        // Saturating: on signed overflow (V), clamp to the sign-correct extreme.
                        // asr#31 ^ 0x80000000 = MAX(0x7fffffff) if the wrapped result is negative
                        // (positive overflow), else MIN(0x80000000); csel picks it only when V is set.
                        "    adds w0, w0, w1\n    asr w2, w0, #31\n    movz w3, #0x8000, lsl #16\n    eor w2, w2, w3\n    csel w0, w2, w0, vs\n",
                    ),
                    _ => asm.push_str("    adds w0, w0, w1\n    b.vs Ltrap\n"), // Trapping (default)
                },
                BinaryOp::Sub => match DOMAIN.load(Ordering::Relaxed) {
                    1 => asm.push_str("    sub w0, w0, w1\n"),
                    2 => asm.push_str(
                        "    subs w0, w0, w1\n    asr w2, w0, #31\n    movz w3, #0x8000, lsl #16\n    eor w2, w2, w3\n    csel w0, w2, w0, vs\n",
                    ),
                    _ => asm.push_str("    subs w0, w0, w1\n    b.vs Ltrap\n"),
                },
                BinaryOp::Mul => match DOMAIN.load(Ordering::Relaxed) {
                    1 => asm.push_str("    mul w0, w0, w1\n"),
                    2 => asm.push_str(
                        // Saturating mul: full 64-bit product; if it doesn't fit i32 clamp by the
                        // product's sign (MIN if negative else MAX).
                        "    smull x0, w0, w1\n    sxtw x2, w0\n    asr x3, x0, #63\n    eor w3, w3, #0x7fffffff\n    cmp x0, x2\n    csel w0, w0, w3, eq\n",
                    ),
                    _ => {
                        // 32x32 -> 64 signed product; result fits in i32 iff it equals
                        // the sign-extension of its low 32 bits.
                        asm.push_str("    smull x0, w0, w1\n");
                        asm.push_str("    sxtw x2, w0\n    cmp x0, x2\n    b.ne Ltrap\n");
                    }
                },
                BinaryOp::Div => {
                    // ARM64 sdiv does NOT trap on /0 (returns 0); enforce the trap.
                    asm.push_str("    cbz w1, Ltrap\n    sdiv w0, w0, w1\n");
                }
                BinaryOp::Rem => {
                    // remainder = w0 - (w0 / w1) * w1; same /0 trap as Div (no native rem).
                    asm.push_str("    cbz w1, Ltrap\n    sdiv w2, w0, w1\n    msub w0, w2, w1, w0\n");
                }
                // bitwise ops: no overflow possible, so no trap.
                BinaryOp::BitAnd => asm.push_str("    and w0, w0, w1\n"),
                BinaryOp::BitOr => asm.push_str("    orr w0, w0, w1\n"),
                BinaryOp::BitXor => asm.push_str("    eor w0, w0, w1\n"),
                // shifts: amount in w1, masked to 0-31 by the hardware (matches x64 cl).
                BinaryOp::Shl => asm.push_str("    lsl w0, w0, w1\n"),
                BinaryOp::Shr => asm.push_str("    asr w0, w0, w1\n"), // arithmetic (signed)
                BinaryOp::Lt => emit_compare(asm, "lt"),
                BinaryOp::Gt => emit_compare(asm, "gt"),
                BinaryOp::Le => emit_compare(asm, "le"),
                BinaryOp::Ge => emit_compare(asm, "ge"),
                BinaryOp::EqEq => emit_compare(asm, "eq"),
                BinaryOp::Ne => emit_compare(asm, "ne"),
            }
            asm.push_str("    str x0, [sp, #-16]!\n"); // push result
        }
        Expr::Min(lhs, rhs) | Expr::Max(lhs, rhs) => {
            lower_expression(lhs, program, self_disp, asm);
            lower_expression(rhs, program, self_disp, asm);
            asm.push_str("    ldr x1, [sp], #16\n"); // pop rhs (b)
            asm.push_str("    ldr x0, [sp], #16\n"); // pop lhs (a)
            asm.push_str("    cmp w0, w1\n");
            // min: a if a<b else b (lt); max: a if a>b else b (gt) — signed, branchless csel.
            let cond = if matches!(program.expressions[node], Expr::Min(..)) { "lt" } else { "gt" };
            asm.push_str(&format!("    csel w0, w0, w1, {}\n", cond));
            asm.push_str("    str x0, [sp, #-16]!\n"); // push result
        }
        Expr::ReadByte => {
            // read(0, &_iobyte, 1); result = (count >= 1) ? _iobyte : -1 (branchless).
            asm.push_str("    bl Lflush_output\n");
            asm.push_str("    mov x0, #0\n"); // fd = stdin
            asm.push_str("    adrp x1, _iobyte@PAGE\n    add x1, x1, _iobyte@PAGEOFF\n");
            asm.push_str("    mov x2, #1\n"); // len = 1
            asm.push_str("    bl _read\n"); // x0 = bytes read
            asm.push_str("    adrp x9, _iobyte@PAGE\n    add x9, x9, _iobyte@PAGEOFF\n");
            asm.push_str("    ldrb w1, [x9]\n"); // w1 = the byte
            emit_load_reg(2, -1, asm); // w2 = -1 (EOF sentinel)
            asm.push_str("    cmp x0, #1\n");
            asm.push_str("    csel w0, w1, w2, ge\n"); // count>=1 ? byte : -1
            asm.push_str("    str x0, [sp, #-16]!\n"); // push
        }
    }
}

// Bounds-checked element address into x9. Pops the index off the stack, traps if
// it is out of range (unsigned index >= count — the runtime counterpart of the
// delta array-bounds VC), then x9 = self + field_offset + index*element_bytes.
// Fold a (possibly large) byte offset into x9. ARM64 `add` immediates are 12-bit
// (0..4095); a larger offset (a big struct -- several KB of buffers + arrays) splits
// into a high part shifted left 12 and a low part, each within range (offsets up to 16M).
fn add_imm_to_x9(offset: i32, asm: &mut String) {
    if offset == 0 {
        return;
    }
    if offset < 4096 {
        asm.push_str(&format!("    add x9, x9, #{}\n", offset));
    } else {
        let hi = offset >> 12;
        let lo = offset & 0xfff;
        asm.push_str(&format!("    add x9, x9, #{}, lsl #12\n", hi));
        if lo != 0 {
            asm.push_str(&format!("    add x9, x9, #{}\n", lo));
        }
    }
}

fn emit_self_element_address(
    self_disp: i32,
    field_offset: i32,
    count: i32,
    element_bytes: i32,
    asm: &mut String,
) {
    asm.push_str("    ldr x0, [sp], #16\n"); // pop index
    emit_load_w1(count, asm); // w1 = count
    asm.push_str("    cmp w0, w1\n    b.hs Ltrap\n"); // trap if index >= count (unsigned)
    asm.push_str("    uxtw x0, w0\n"); // zero-extend the validated index
    asm.push_str(&format!("    ldr x9, [x29, #{}]\n", self_disp)); // self pointer
    add_imm_to_x9(field_offset, asm);
    let shift = match element_bytes {
        2 => 1,
        4 => 2,
        8 => 3,
        _ => 0,
    };
    if shift > 0 {
        asm.push_str(&format!("    add x9, x9, x0, lsl #{}\n", shift)); // + index*element_bytes
    } else {
        asm.push_str("    add x9, x9, x0\n");
    }
}

fn emit_compare(asm: &mut String, condition: &str) {
    asm.push_str("    cmp w0, w1\n");
    asm.push_str(&format!("    cset w0, {}\n", condition));
}

// Load a 32-bit constant into w0 with movz/movk (ARM64 immediates are 16-bit).
fn emit_load_w0(value: i32, asm: &mut String) {
    emit_load_reg(0, value, asm);
}

// Load a pattern constant into w1 (the transition compare operand).
fn emit_load_w1(value: i32, asm: &mut String) {
    emit_load_reg(1, value, asm);
}

fn emit_load_reg(reg: u32, value: i32, asm: &mut String) {
    let bits = value as u32;
    let low = bits & 0xffff;
    let high = (bits >> 16) & 0xffff;
    asm.push_str(&format!("    movz w{}, #{}\n", reg, low));
    if high != 0 {
        asm.push_str(&format!("    movk w{}, #{}, lsl #16\n", reg, high));
    }
}
