mod pipeline;

pub(crate) use psi_source as source;
pub(crate) use psi_source_files_to_tokens as lexer;
pub(crate) use psi_tokens_to_syntax_trees as parser;

pub use omega_optimization_core::{
    DuplicateOptimizationRuleIdentity, IdentityBundleDecodeError, IdentityDecodeError,
    Optimization, OptimizationDecisionLogIdentity, OptimizationIdentityBundle,
    OptimizationIdentityBundleIdentity, OptimizationRuleIdentity, OptimizationRuleSetIdentity,
    OptimizationSelectionIdentity, OptimizationSelections, OptimizationWorkloadProfileIdentity,
    TargetCostModelIdentity, TransformationLedgerIdentity,
};

pub use psi_checked_interpreter::{
    FilesystemSponsor, FilesystemSponsorError, FilesystemSponsorLimits,
};

pub use pipeline::{
    AdmittedExternalRootEntryFactHandoff, AggregateFieldSchema, AggregateFieldValue,
    ArtifactEmissionPolicy, BUILD_OBSERVATION_SCHEMA_VERSION,
    BoundExternalRootPostHandoffWriterInvocation, BuildEvaluationUsage,
    BuildFilesystemAuthorizedPath, BuildFilesystemByteOperand, BuildFilesystemGrantAccess,
    BuildFilesystemGrantRefusal, BuildFilesystemGrantRefusalReason,
    BuildFilesystemLogicalHandleIdentity, BuildFilesystemLogicalHandleInput,
    BuildFilesystemLogicalHandleInputResolution, BuildFilesystemLogicalHandleKind,
    BuildFilesystemLogicalHandleOutput, BuildFilesystemLogicalHandleOutputSource,
    BuildFilesystemMetadataObservation, BuildFilesystemMetadataObservationKind,
    BuildFilesystemMutableByteOperand, BuildFilesystemMutableByteOperandResolution,
    BuildFilesystemMutableI64Operand, BuildFilesystemMutableI64OperandResolution,
    BuildFilesystemObservedByteRegion, BuildFilesystemObservedByteRegionKind,
    BuildFilesystemOperationAttempt, BuildFilesystemOperationResult,
    BuildFilesystemPathLikeOperand, BuildFilesystemProvider, BuildFilesystemReplayRecordError,
    BuildFilesystemReplayRecordLimits, BuildFilesystemReturnedPath,
    BuildFilesystemReturnedPathCompleteness, BuildFilesystemReturnedPathKind, BuildFilesystemRoot,
    BuildFilesystemRootedPathOperandResolution, BuildFilesystemScalarOperand,
    BuildFilesystemScalarOperandValue, BuildObservationClass, BuildObservationSummary,
    BuildStagedOutputMaterializationError, BuildStagedOutputTree, BuildStagedOutputTreeCommitment,
    BuildTimeValue, ByteOrder, CheckedCompilation, CheckedPackageCallableReview,
    CheckedPackageProviderReview, CheckedPackageReviewProjection, CompileHarnessRequest,
    CompileOptions, CompileOutputKind, CompileReport, CompileRequest, CompilerExecutableCommitment,
    CompilerExecutableCommitmentError, ConsumptionInstant, DataSymbolId,
    DecodedPackageReviewCanonicalRow, EntryStubId, ExecutablePublicationDestination,
    ExecutablePublicationReceipt, ExecutableTcbBuildPolicy,
    ExternalRootPostHandoffWriterBindingError, InstalledImageSubextent,
    InstalledProgramStorageRoots, IntegerInterpretation, LayoutFieldEntryReport,
    LayoutPlacementReport, LayoutPlanReport, MaterializationAction, MaterializationContext,
    MaterializationDiagnostic, MaterializationWrite, OrdinaryPackageObligationLedger,
    OrdinaryPackageObligationLedgerRecoveryError, OrdinaryPackageObligationRow,
    PACKAGE_REVIEW_CANONICAL_ROW_RECOVERY_VERSION, PACKAGE_REVIEW_ENCODING_VERSION,
    PACKAGE_REVIEW_ROW_ENCODING_VERSION, PROGRAM_STORAGE_INSTALLATION_ARTIFACT,
    PackageCompilationInputError, PackageCompilationInputs, PackageDependencyBinding,
    PackageDependencyClosure, PackageReviewArithmeticDomain, PackageReviewByteSequencePredicate,
    PackageReviewCallableConformance, PackageReviewCallableContract,
    PackageReviewCallableParameter, PackageReviewCallableRole, PackageReviewCanonicalRow,
    PackageReviewCanonicalRowKind, PackageReviewCanonicalRowRecoveryError,
    PackageReviewCanonicalRowRecoveryLimits, PackageReviewCanonicalRowRisk,
    PackageReviewCanonicalRowSource, PackageReviewCapabilityFlow, PackageReviewCastForm,
    PackageReviewCheckedServiceReach, PackageReviewConformanceBound, PackageReviewConformanceShape,
    PackageReviewConformanceSubject, PackageReviewConstShape, PackageReviewContractBinaryOperator,
    PackageReviewContractCallTarget, PackageReviewContractExpression, PackageReviewContractFact,
    PackageReviewContractKind, PackageReviewContractOperatorMeaning,
    PackageReviewContractStaticArgument, PackageReviewContractUnaryOperator, PackageReviewCrash,
    PackageReviewCrashCall, PackageReviewCrashInterface, PackageReviewCrashPredicate,
    PackageReviewCrashRoute, PackageReviewCrashRouteGuard, PackageReviewCrashSite,
    PackageReviewDangerousAuthority, PackageReviewDangerousAuthorityClass,
    PackageReviewDangerousAuthoritySlack, PackageReviewDataField, PackageReviewDataKind,
    PackageReviewDataMember, PackageReviewDataShape, PackageReviewDomainAliasAtom,
    PackageReviewDomainClassification, PackageReviewDomainEstablishmentKind,
    PackageReviewDomainEstablishmentRoute, PackageReviewDomainSemanticRole,
    PackageReviewDomainShape, PackageReviewEncodingError, PackageReviewEvidenceInterface,
    PackageReviewEvidenceRequirement, PackageReviewInstallationReach,
    PackageReviewMachineParameterContract, PackageReviewMachineParameterSignature,
    PackageReviewMachineParameterValue, PackageReviewMutation, PackageReviewNominalIdentity,
    PackageReviewNominalOwner, PackageReviewOperatorCoordinate, PackageReviewOperatorShape,
    PackageReviewPermissionClaim, PackageReviewPermissionSource, PackageReviewProgressPremise,
    PackageReviewProgressSubject, PackageReviewPropositionApplication,
    PackageReviewPropositionBinder, PackageReviewPropositionBinderArgument,
    PackageReviewPropositionBinderKind, PackageReviewPropositionBinderValue,
    PackageReviewPropositionEvidence, PackageReviewPropositionParameterApplication,
    PackageReviewPropositionParameterSignature, PackageReviewPropositionParameterValue,
    PackageReviewPropositionShape, PackageReviewPublicPropositionBody,
    PackageReviewRepresentationAbiCommitment, PackageReviewRepresentationMechanism,
    PackageReviewRepresentationTcb, PackageReviewSemanticDependency,
    PackageReviewSemanticDependencyExposure, PackageReviewSemanticDependencyKind,
    PackageReviewSourceLocation, PackageReviewSourceLocationOwner, PackageReviewSourceLocationRole,
    PackageReviewSynchronousInvocation, PackageReviewSyntheticSourceKind, PackageReviewTermination,
    PackageReviewToolchainSourceIdentity, PackageReviewTraitParent, PackageReviewTraitRequirement,
    PackageReviewTraitRequirementParameter, PackageReviewTraitShape, PackageReviewTypeIdentity,
    PackageReviewTypeParameter, PackageReviewTypeParameterKind, PackageSourceBinding,
    PackageSourceConsumptionCommitment, PartitionedProgramStorageRoots,
    ProgramEntryPhysicalContractPlan, ProgramEntryReceiverActivation,
    ProgramEntryReceiverActivationError, ProgramEntryReceiverPlacementRecord,
    ProgramEntryReceiverStoragePlan, ProgramEntrySourceExtentFieldLayout,
    ProgramEntrySourceExtentFieldRole, ProgramEntrySourceExtentValueLayout,
    ProgramEntrySourceReceiverSignature, ProgramEntrySourceResultSignature,
    ProgramEntrySourceVisibleParameterSignature, ProgramLocalEntryReceiverActivation,
    ProgramLocalEntryReceiverActivationError, ProgramLocalStorageAccountHandoffError,
    ProgramLocalStorageCustody, ProgramLocalStorageCustodyError,
    ProgramLocalStorageInstallationHandoffError, ProgramLocalStorageRecordEmissionError,
    ProgramLocalStorageRecordedWholeRootArgumentError,
    ProgramLocalStorageRecordedWholeRootArgumentRecovery, ProgramLocalStorageSubjectHandoffError,
    ProgramStorageEntryBridgeError, ProgramStorageEntryContinuationAbiPlan,
    ProgramStorageEntryContinuationInboundArgument, ProgramStorageEntryContinuationInboundPlan,
    ProgramStorageEntryContinuationReceiverAbiPlan, ProgramStorageEntryContinuationReceiverBinding,
    ProgramStorageEntryContinuationReceiverBindingError,
    ProgramStorageEntryContinuationVisibleArgumentPlan, ProgramStorageEntryDiagnostic,
    ProgramStorageEntryEmittedArrivalCopyEvidence, ProgramStorageEntryEmittedArrivalEvidence,
    ProgramStorageEntryEmittedArrivalRootEvidence,
    ProgramStorageEntryEmittedWholeRootArgumentCarrier,
    ProgramStorageEntryEmittedWholeRootArgumentError, ProgramStorageEntryEmittedWrapperEvidence,
    ProgramStorageEntryExecutorDispatch, ProgramStorageEntryExtentLogicalValue,
    ProgramStorageEntryExtentOperandImage, ProgramStorageEntryInitialStorageAuthorityKind,
    ProgramStorageEntryNativeBridgePlan, ProgramStorageEntryOutgoingStackWord,
    ProgramStorageEntryParameter, ProgramStorageEntryPlanBinding,
    ProgramStorageEntryProviderInvocation, ProgramStorageEntryRecordedWholeRootArgumentError,
    ProgramStorageEntryRecordedWholeRootArgumentRecovery,
    ProgramStorageEntryReservedOutgoingStackFrameError,
    ProgramStorageEntryReservedOutgoingStackFramePlan, ProgramStorageEntryRootAuthorityDisposition,
    ProgramStorageEntryRootAuthorityDispositionError, ProgramStorageEntryRootRole,
    ProgramStorageEntrySourceContinuationHandoff, ProgramStorageEntryWholeRootArgumentBinding,
    ProgramStorageEntryWholeRootArgumentCarrier, ProgramStorageEntryWholeRootArgumentError,
    ProgramStorageEntryWholeRootAuthority, ProgramStorageEntryWholeRootAuthorityError,
    ProgramStorageEntryWholeRootLogicalValueCarrier, ProgramStorageEntryWholeRootLogicalValueError,
    ProgramStorageEntryWholeRootOperandCarrier, ProgramStorageEntryWholeRootOperandError,
    ProgramStorageEntryWrapperBodyTemplatePlan, ProgramStorageEntryWrapperBodyTemplateStep,
    ProgramStorageEntryWrapperCallerFrameError, ProgramStorageEntryWrapperCallerFramePlan,
    ProgramStorageEntryWrapperCallerFrameStep, ProgramStorageEntryWrapperReceiverTransfer,
    ProgramStorageEntryWrapperRootTransferPlan, ProgramStorageEntryWrapperTransferPlan,
    ProgramStorageInstallationHandoffError, ProgramStorageInstallationRecord,
    ProgramStorageInstalledExtentRecord, ProgramStoragePartitionError,
    ProgramStorageRecordEmissionError, ProgramStorageRootInput,
    ProgramStorageRootInstallationError, RecordedProgramLocalStorageInstallation,
    RecordedProgramStorageInstallation, RelocationTarget, ReservedProgramEntryReceiverStorage,
    ReviewOnlyBuildFilesystemReplayRecord, SOURCE_CLOSURE_SNAPSHOT_SCHEMA, SOURCE_FEATURE_CATALOG,
    SOURCE_FEATURE_CENSUS_SCHEMA, SOURCE_FEATURE_IDS, SOURCE_RESOURCE_IDS, ScalarFieldSchema,
    ScalarFieldValue, SelectedExternalRootEntryFactBinding,
    SelectedExternalRootPostHandoffWriterPreparation, SelectedExternalRootProviderPlan,
    SelectedExternalRootWriterPreparationError, SelectedProgramEntrySourceSignature,
    SelectedProgramStorageEntryPlan, SourceClosureSnapshot, SourceClosureSnapshotEntry,
    SourceFeatureCensus, SourceFeatureCount, SourceResourceObservation,
    SuppliedTerminalComponentDeploymentError, SymbolicFieldValue, SymbolicMaterializationPlan,
    TerminalComponentCandidate, TerminalComponentCandidateParts, TerminalComponentDeploymentInputs,
    TerminalComponentDeploymentOutputError, TerminalComponentDeploymentOutputStage,
    TerminalComponentDeploymentReportError, TerminalComponentDeploymentSupply,
    TerminalComponentProviderExecution, TerminalComponentProviderSettlement, ValidatedAccessPlan,
    ValidatedPlacementPlan, ValidatedWrittenBoundExternalRootPostHandoffWriterDestination,
    WrittenBoundExternalRootConsumerValidationError,
    WrittenBoundExternalRootPostHandoffWriterDestination,
    WrittenBoundExternalRootWriterRecoveryError, bind_emitted_program_storage_entry_native_bridge,
    bind_external_root_post_handoff_writer_invocation, bind_generated_program_storage_entry_plan,
    bind_program_local_storage_entry_emitted_whole_root_arguments,
    bind_program_local_storage_entry_whole_root_logical_values,
    bind_program_local_storage_entry_whole_root_operands,
    bind_program_storage_entry_emitted_whole_root_arguments, bind_program_storage_entry_plan,
    bind_program_storage_entry_whole_root_arguments,
    bind_program_storage_entry_whole_root_logical_values,
    bind_program_storage_entry_whole_root_operands,
    bind_recorded_program_local_storage_entry_whole_root_arguments,
    bind_recorded_program_storage_entry_whole_root_arguments,
    capture_verified_build_filesystem_replay_record, census_source_closure, compile,
    compile_harness, compile_options, compile_to_checked, compile_to_checked_with_packages,
    compile_to_checked_with_packages_and_replay_record,
    compile_to_checked_with_packages_in_build_dir,
    compile_to_checked_with_packages_in_sponsored_build_dir, compile_to_checked_with_replay_record,
    compiler_intrinsic_diagnostic_label, compute_access_plan, compute_layout_plan,
    compute_placement_plan, decode_package_review_canonical_row,
    decode_package_review_canonical_row_with_limits, decode_scalar_layout,
    deploy_and_write_terminal_component_output, deploy_supplied_terminal_component_output,
    derive_symbolic_materialization, encode_package_review_canonical_row,
    encode_package_review_canonical_row_with_limits,
    establish_program_storage_entry_program_local_roots,
    evaluate_and_materialize_typed_owned_layout_into, evaluate_calling_policy_plan,
    inspect_source_closure, install_and_activate_program_storage_entry_receiver,
    install_established_program_storage_entry_program_local_roots,
    install_program_storage_entry_provider_invocation, materialize_aggregate_layout_into,
    materialize_scalar_layout_into, materialize_typed_owned_layout_into,
    normalized_layout_plan_fingerprint, ordinary_package_obligation_ledger_from_compiler_rows,
    plan_program_local_storage_entry_wrapper_caller_frame,
    plan_program_storage_entry_wrapper_caller_frame, program_storage_installation_record_json,
    project_checked_package_review, reconstruct_ordinary_package_obligation_ledger,
    recover_ordinary_package_obligation_ledger, recover_review_only_build_filesystem_replay_record,
    reserve_program_local_storage_entry_outgoing_stack_frame,
    reserve_program_storage_entry_outgoing_stack_frame, selected_external_root_entry_fact_bindings,
    selected_external_root_provider_plan, selected_external_root_provider_plan_id,
    stage_terminal_component, validate_ordinary_package_obligation_ledger,
    write_finalized_terminal_component_output,
};
