[package]
name = "omega-terminal-image-emission"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_terminal_image_emission"
path = "src/lib.rs"

[dependencies]
psi-diagnostics = { path = "../../../../psi-rs/foundation/psi-diagnostics" }
omega-image = { path = "../omega-image" }
omega-external-roots = { path = "../../../orchestration/omega-external-roots" }
omega-image-elf = { path = "../omega-image-elf" }
omega-image-macho = { path = "../omega-image-macho" }
omega-image-pe = { path = "../omega-image-pe" }
omega-object-file = { path = "../../object/omega-object-file" }
omega-target = { path = "../../../foundation/omega-target" }
omega-x86-encoding = { path = "../../../foundation/omega-x86-encoding" }
omega-terminal-machine-code = { path = "../../../representations/omega-terminal-machine-code" }
omega-terminal-target-operations = { path = "../../../representations/omega-terminal-target-operations" }
psi-core = { path = "../../../../psi-rs/foundation/psi-core" }
psi-terminal = { path = "../../../../psi-rs/representations/psi-terminal" }
sha2 = "0.10"
