[package]
name = "post-allocation-machine-to-post-allocation-machine"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "post_allocation_machine_to_post_allocation_machine"
path = "src/lib.rs"

[dependencies]
optimization-core = { path = "../../representations/optimization-core" }
optimization-unit = { path = "../../representations/optimization-unit" }
physical-instructions = { path = "../../representations/physical-instructions" }
register-homes-to-post-allocation-machine = { path = "../register-homes-to-post-allocation-machine" }
register-model = { path = "../../representations/register-model" }
selected-instructions = { path = "../../representations/selected-instructions" }
selected-instructions-to-register-homes = { path = "../selected-instructions-to-register-homes" }
target = { path = "../../representations/target" }
target-operations = { path = "../../representations/target-operations" }
semantic-vocabulary = { path = "../../../psi/foundation/semantic-vocabulary" }
terminal-psi = { path = "../../../psi/representations/terminal-psi" }
sha2 = "0.10.9"

[dev-dependencies]
isa-aarch64 = { path = "../../backend/instruction_set_architectures/isa-aarch64" }
isa-x86_64 = { path = "../../backend/instruction_set_architectures/isa-x86_64" }
