[package]
name = "omega-optimization-unit"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_optimization_unit"
path = "src/lib.rs"

[dependencies]
omega-optimization-core = { path = "../omega-optimization-core" }
omega-abstract-operations = { path = "../omega-abstract-operations" }
psi-core = { path = "../../../psi/foundation/psi-core" }
psi-terminal = { path = "../../../psi/representations/psi-terminal" }
