//! REAL-filesystem provider acceptance (build.omg rung 1, TASKS_FS open-work
//! #3): the SAME program, interpreted twice --
//!   1. `interpret_with_options(RealUnscoped)`: the staged file must appear ON
//!      REAL DISK with the exact bytes (the build.omg use case: an interpreted
//!      build program staging assets itself), and
//!   2. plain `interpret()` (hermetic default): the identical program must
//!      still run and exit identically against the VIRTUAL fs, with NOTHING
//!      appearing on real disk (the differential oracle stays hermetic).
//! The A/B is the point: one program, one exit code, two worlds.

use omega_compiler::compile_to_checked;
use omega_interpreter::{FilesystemAccess, InterpretOptions, interpret, interpret_with_options};
use std::path::Path;

/// A build-shaped staging program against RAW `FilesystemHost` ops (the same
/// surface `native_crud` pins natively): mkdir a staging dir, create + write a
/// 17-byte asset, close, reopen, read it back, and exit with the read count.
/// `base` is baked in as path literals so the program needs no argv plumbing.
fn staging_program(base: &Path) -> String {
    let dir = base.join("staging");
    let file = dir.join("asset.txt");
    format!(
        r#"// Real-fs provider acceptance probe (generated by tests/real_fs.rs).
use omega::language::std::filesystem_host;

boundary trait Console {{ machine exit_process(return_code: i32); }}

data Main {{
    fs: FilesystemHost;
    console: Console;
    dir_mode: i32;
    mode: i32;
    read_flags: i32;
    cap: usize;
    rc: i64;
    fd: i32;
    n: i64;
    rn: i64;
    buffer: [u8; 64];
}}

machine Main::main(&mut self) {{
    self.dir_mode = 493;
    self.mode = 438;
    self.read_flags = 0;
    self.cap = 64;
    self.rc = self.fs.create_dir("{dir}", self.dir_mode);
    self.fd = self.fs.create("{file}", self.mode);
    transition self.fd >= 0 {{ true -> wrote() _ -> fail() }}
    state wrote(&mut self) {{
        self.n = self.fs.write(self.fd, "real fs rung one\n");
        self.n = self.fs.close(self.fd);
        self.fd = self.fs.open("{file}", self.read_flags);
        transition self.fd >= 0 {{ true -> rd() _ -> fail() }}
    }}
    state rd(&mut self) {{
        self.rn = self.fs.read(self.fd, &mut self.buffer, self.cap);
        self.n = self.fs.close(self.fd);
        transition {{ _ -> done(self.rn) }}
    }}
    state done(&mut self, count: i64) {{ self.console.exit_process(count as i32); }}
    state fail(&mut self) {{ self.console.exit_process(101); }}
}}
"#,
        dir = dir.display(),
        file = file.display(),
    )
}

#[test]
fn real_mode_stages_files_on_disk_and_hermetic_default_does_not() {
    // Unique per-run scratch base under the std temp dir; pid + a self-clean
    // keep reruns deterministic.
    let base = std::env::temp_dir().join(format!("omega_real_fs_probe_{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&base);
    std::fs::create_dir_all(&base).expect("create probe base dir");

    let main_path = base.join("main.omg");
    std::fs::write(&main_path, staging_program(&base)).expect("write probe program");

    let checked = compile_to_checked(&main_path, None).unwrap_or_else(|diagnostics| {
        panic!(
            "real-fs probe compile failed:\n{}",
            diagnostics
                .iter()
                .map(|d| d.to_string())
                .collect::<Vec<_>>()
                .join("\n")
        )
    });

    let staged = base.join("staging").join("asset.txt");

    // 1. REAL mode: the asset appears on real disk with the exact bytes.
    let real = interpret_with_options(
        &checked,
        &[],
        InterpretOptions {
            filesystem: FilesystemAccess::RealUnscoped,
        },
    );
    assert!(!real.is_error(), "real-mode run errored: {:?}", real.error);
    assert_eq!(real.exit_code, 17, "real-mode read-back count");
    assert_eq!(
        std::fs::read(&staged).expect("staged asset must exist on real disk"),
        b"real fs rung one\n",
        "staged asset bytes"
    );

    // 2. Hermetic default: same program, same exit code, NOTHING on disk.
    std::fs::remove_dir_all(base.join("staging")).expect("clear staging between runs");
    let hermetic = interpret(&checked, &[]);
    assert!(
        !hermetic.is_error(),
        "hermetic run errored: {:?}",
        hermetic.error
    );
    assert_eq!(hermetic.exit_code, 17, "virtual-fs read-back count");
    assert!(
        !staged.exists(),
        "hermetic default must not touch the real filesystem"
    );

    let _ = std::fs::remove_dir_all(&base);
}
