//! REAL-filesystem provider acceptance (build.omg rungs 1+2, TASKS_FS
//! open-work #3).
//!
//! Rung 1 (the provider): the SAME program, interpreted twice --
//!   1. `interpret_with_options(RealUnscoped)`: the staged file must appear ON
//!      REAL DISK with the exact bytes (the build.omg use case: an interpreted
//!      build program staging assets itself), and
//!   2. plain `interpret()` (hermetic default): the identical program must
//!      still run and exit identically against the VIRTUAL fs, with NOTHING
//!      appearing on real disk (the differential oracle stays hermetic).
//! The A/B is the point: one program, one exit code, two worlds.
//!
//! Rung 2 (grants): under `RealScoped { read: src, write: out }` a probe
//! program must (a) read from the read root, (b) stage + read back under the
//! write root, (c) get EACCES creating under the read-only root, and (d) get
//! EACCES reading outside every root -- with the denied files verifiably
//! absent from real disk afterwards.

use omega_compiler::compile_to_checked;
use omega_interpreter::{
    FilesystemAccess, FsGrants, InterpretOptions, interpret, interpret_with_options,
};
use std::path::Path;

/// A build-shaped staging program against RAW `FilesystemHost` ops (the same
/// surface `native_crud` pins natively): mkdir a staging dir, create + write a
/// 17-byte asset, close, reopen, read it back, and exit with the read count.
/// `base` is baked in as path literals so the program needs no argv plumbing.
fn staging_program(base: &Path) -> String {
    let dir = base.join("staging");
    let file = dir.join("asset.txt");
    format!(
        r#"// Real-fs provider acceptance probe (generated by tests/real_fs.rs).
use omega::language::std::filesystem_host;

boundary trait Console {{ machine exit_process(return_code: i32); }}

data Main {{
    fs: FilesystemHost;
    console: Console;
    dir_mode: i32;
    mode: i32;
    read_flags: i32;
    cap: usize;
    rc: i64;
    fd: i32;
    n: i64;
    rn: i64;
    buffer: [u8; 64];
}}

machine Main::main(&mut self) {{
    self.dir_mode = 493;
    self.mode = 438;
    self.read_flags = 0;
    self.cap = 64;
    self.rc = self.fs.create_dir("{dir}", self.dir_mode);
    self.fd = self.fs.create("{file}", self.mode);
    transition self.fd >= 0 {{ true -> wrote() _ -> fail() }}
    state wrote(&mut self) {{
        self.n = self.fs.write(self.fd, "real fs rung one\n");
        self.n = self.fs.close(self.fd);
        self.fd = self.fs.open("{file}", self.read_flags);
        transition self.fd >= 0 {{ true -> rd() _ -> fail() }}
    }}
    state rd(&mut self) {{
        self.rn = self.fs.read(self.fd, &mut self.buffer, self.cap);
        self.n = self.fs.close(self.fd);
        transition {{ _ -> done(self.rn) }}
    }}
    state done(&mut self, count: i64) {{ self.console.exit_process(count as i32); }}
    state fail(&mut self) {{ self.console.exit_process(101); }}
}}
"#,
        dir = dir.display(),
        file = file.display(),
    )
}

#[test]
fn real_mode_stages_files_on_disk_and_hermetic_default_does_not() {
    // Unique per-run scratch base under the std temp dir; pid + a self-clean
    // keep reruns deterministic.
    let base = std::env::temp_dir().join(format!("omega_real_fs_probe_{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&base);
    std::fs::create_dir_all(&base).expect("create probe base dir");

    let main_path = base.join("main.omg");
    std::fs::write(&main_path, staging_program(&base)).expect("write probe program");

    let checked = compile_to_checked(&main_path, None).unwrap_or_else(|diagnostics| {
        panic!(
            "real-fs probe compile failed:\n{}",
            diagnostics
                .iter()
                .map(|d| d.to_string())
                .collect::<Vec<_>>()
                .join("\n")
        )
    });

    let staged = base.join("staging").join("asset.txt");

    // 1. REAL mode: the asset appears on real disk with the exact bytes.
    let real = interpret_with_options(
        &checked,
        &[],
        InterpretOptions {
            filesystem: FilesystemAccess::RealUnscoped,
        },
    );
    assert!(!real.is_error(), "real-mode run errored: {:?}", real.error);
    assert_eq!(real.exit_code, 17, "real-mode read-back count");
    assert_eq!(
        std::fs::read(&staged).expect("staged asset must exist on real disk"),
        b"real fs rung one\n",
        "staged asset bytes"
    );

    // 2. Hermetic default: same program, same exit code, NOTHING on disk.
    std::fs::remove_dir_all(base.join("staging")).expect("clear staging between runs");
    let hermetic = interpret(&checked, &[]);
    assert!(
        !hermetic.is_error(),
        "hermetic run errored: {:?}",
        hermetic.error
    );
    assert_eq!(hermetic.exit_code, 17, "virtual-fs read-back count");
    assert!(
        !staged.exists(),
        "hermetic default must not touch the real filesystem"
    );

    let _ = std::fs::remove_dir_all(&base);
}

/// The grant-boundary probe: one program touching all four authorization
/// quadrants. Exit 70 = every quadrant behaved; 71..77 name the failing step.
fn grants_program(base: &Path) -> String {
    let src = base.join("src");
    let out = base.join("out");
    let secret = base.join("secret");
    format!(
        r#"// Grant-scoping probe (generated by tests/real_fs.rs).
use omega::language::std::filesystem_host;

boundary trait Console {{ machine exit_process(return_code: i32); }}

data Main {{
    fs: FilesystemHost;
    console: Console;
    mode: i32;
    rd: i32;
    cap: usize;
    fd: i32;
    n: i64;
    rn: i64;
    e: i64;
    buffer: [u8; 64];
}}

machine Main::main(&mut self) {{
    self.mode = 438;
    self.rd = 0;
    self.cap = 64;
    // (a) READ under the read root.
    self.fd = self.fs.open("{src}/input.txt", self.rd);
    transition self.fd >= 0 {{ true -> readsrc() _ -> bad(71) }}
    state readsrc(&mut self) {{
        self.rn = self.fs.read(self.fd, &mut self.buffer, self.cap);
        self.n = self.fs.close(self.fd);
        transition self.rn == 13 {{ true -> stage() _ -> bad(72) }}
    }}
    // (b) WRITE under the write root, then read it back (write grant
    // implies read-back).
    state stage(&mut self) {{
        self.fd = self.fs.create("{out}/artifact.txt", self.mode);
        transition self.fd >= 0 {{ true -> put() _ -> bad(73) }}
    }}
    state put(&mut self) {{
        self.n = self.fs.write(self.fd, "granted artifact\n");
        self.n = self.fs.close(self.fd);
        self.fd = self.fs.open("{out}/artifact.txt", self.rd);
        transition self.fd >= 0 {{ true -> readback() _ -> bad(74) }}
    }}
    state readback(&mut self) {{
        self.rn = self.fs.read(self.fd, &mut self.buffer, self.cap);
        self.n = self.fs.close(self.fd);
        transition self.rn == 17 {{ true -> denywrite() _ -> bad(75) }}
    }}
    // (c) CREATE under the read-only root must refuse with EACCES.
    state denywrite(&mut self) {{
        self.fd = self.fs.create("{src}/evil.txt", self.mode);
        self.e = self.fs.errno();
        transition self.fd < 0 && self.e == 13 {{ true -> denyread() _ -> bad(76) }}
    }}
    // (d) READ outside every root must refuse with EACCES.
    state denyread(&mut self) {{
        self.fd = self.fs.open("{secret}/hidden.txt", self.rd);
        self.e = self.fs.errno();
        transition self.fd < 0 && self.e == 13 {{ true -> good() _ -> bad(77) }}
    }}
    state good(&mut self) {{ self.console.exit_process(70); }}
    state bad(&mut self, code: i32) {{ self.console.exit_process(code); }}
}}
"#,
        src = src.display(),
        out = out.display(),
        secret = secret.display(),
    )
}

#[test]
fn scoped_grants_enforce_read_and_write_roots() {
    let base = std::env::temp_dir().join(format!("omega_fs_grants_probe_{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&base);
    // src (read root) with the input; out (write root) empty; secret with a
    // real file the grant must make unreachable.
    std::fs::create_dir_all(base.join("src")).expect("create src root");
    std::fs::create_dir_all(base.join("out")).expect("create out root");
    std::fs::create_dir_all(base.join("secret")).expect("create secret dir");
    std::fs::write(base.join("src").join("input.txt"), b"hello grants\n").expect("seed input");
    std::fs::write(base.join("secret").join("hidden.txt"), b"top secret\n").expect("seed secret");

    let main_path = base.join("main.omg");
    std::fs::write(&main_path, grants_program(&base)).expect("write probe program");

    let checked = compile_to_checked(&main_path, None).unwrap_or_else(|diagnostics| {
        panic!(
            "grants probe compile failed:\n{}",
            diagnostics
                .iter()
                .map(|d| d.to_string())
                .collect::<Vec<_>>()
                .join("\n")
        )
    });

    let outcome = interpret_with_options(
        &checked,
        &[],
        InterpretOptions {
            filesystem: FilesystemAccess::RealScoped(FsGrants {
                read_roots: vec![base.join("src")],
                write_roots: vec![base.join("out")],
            }),
        },
    );
    assert!(
        !outcome.is_error(),
        "scoped run errored: {:?}",
        outcome.error
    );
    assert_eq!(
        outcome.exit_code, 70,
        "grant quadrant probe (71=read-root open, 72=read bytes, 73=write-root \
         create, 74=read-back open, 75=read-back bytes, 76=read-only-root create \
         not EACCES-refused, 77=outside-root open not EACCES-refused)"
    );

    // The world after: the artifact is real; the denied writes never happened.
    assert_eq!(
        std::fs::read(base.join("out").join("artifact.txt")).expect("artifact staged"),
        b"granted artifact\n",
    );
    assert!(
        !base.join("src").join("evil.txt").exists(),
        "denied create must not touch the read-only root"
    );
    assert_eq!(
        std::fs::read(base.join("secret").join("hidden.txt")).expect("secret untouched"),
        b"top secret\n",
    );

    let _ = std::fs::remove_dir_all(&base);
}

/// The WRAPPER-level dir-enumeration probe: `Filesystem::read_dir_count`
/// (open dirfd -> read_dir -> decode darwin dirent records -> skip `.`/`..`)
/// runs against a REAL directory. This exercises the full stack -- the std
/// wrapper's decode loop over the real provider's packed records.
fn read_dir_program(assets: &Path) -> String {
    format!(
        r#"// Real read_dir probe (generated by tests/real_fs.rs).
use omega::language::std::filesystem;
use omega::language::std::filesystem_host;

boundary trait Console {{ machine exit_process(return_code: i32); }}

data Main {{
    console: Console;
    fs: Filesystem;
    io_result: IoResult;
}}

machine Main::main(&mut self) {{
    self.io_result = self.fs.read_dir_count("{assets}");
    transition self.io_result {{ IoResult::Ok {{ count }} -> ck(count) _ -> bad(72) }}
    state ck(&mut self, count: usize) {{
        transition count == 3 {{ true -> good() _ -> bad(71) }}
    }}
    state good(&mut self) {{ self.console.exit_process(70); }}
    state bad(&mut self, code: i32) {{ self.console.exit_process(code); }}
}}
"#,
        assets = assets.display(),
    )
}

#[test]
fn scoped_wrapper_read_dir_count_enumerates_a_real_directory() {
    let base =
        std::env::temp_dir().join(format!("omega_real_readdir_probe_{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&base);
    let assets = base.join("assets");
    std::fs::create_dir_all(&assets).expect("create assets dir");
    for name in ["f1.txt", "f2.txt", "f3.txt"] {
        std::fs::write(assets.join(name), b"asset\n").expect("seed asset");
    }

    let main_path = base.join("main.omg");
    std::fs::write(&main_path, read_dir_program(&assets)).expect("write probe program");

    let checked = compile_to_checked(&main_path, None).unwrap_or_else(|diagnostics| {
        panic!(
            "read_dir probe compile failed:\n{}",
            diagnostics
                .iter()
                .map(|d| d.to_string())
                .collect::<Vec<_>>()
                .join("\n")
        )
    });

    let outcome = interpret_with_options(
        &checked,
        &[],
        InterpretOptions {
            filesystem: FilesystemAccess::RealScoped(FsGrants {
                read_roots: vec![assets.clone()],
                write_roots: vec![],
            }),
        },
    );
    assert!(
        !outcome.is_error(),
        "read_dir probe errored: {:?}",
        outcome.error
    );
    assert_eq!(
        outcome.exit_code, 70,
        "wrapper read_dir_count over a real dir (71=count!=3, 72=IoResult::Error)"
    );

    let _ = std::fs::remove_dir_all(&base);
}
