[package]
name = "omega-machine-emission"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_machine_emission"
path = "src/lib.rs"

[dependencies]
omega-assigned-target-operations = { path = "../../representations/omega-assigned-target-operations" }
omega-calling-conventions = { path = "../../foundation/omega-calling-conventions" }
omega-control-flow = { path = "../../representations/omega-control-flow" }
psi-arena = { path = "../../../psi/foundation/psi-arena" }
psi-diagnostics = { path = "../../../psi/foundation/psi-diagnostics" }
psi-language-core = { path = "../../../psi/foundation/psi-language-core" }
psi-numerics = { path = "../../../psi/foundation/psi-numerics" }
omega-instruction-selection = { path = "../omega-instruction-selection" }
omega-isa-aarch64 = { path = "../instruction_set_architectures/omega-isa-aarch64" }
omega-isa-x86_64 = { path = "../instruction_set_architectures/omega-isa-x86_64" }
omega-machine-bytes = { path = "../../representations/omega-machine-bytes" }
omega-machine-instructions = { path = "../../representations/omega-machine-instructions" }
omega-target = { path = "../../foundation/omega-target" }
omega-target-operations = { path = "../../representations/omega-target-operations" }

[dev-dependencies]
psi-symbols = { path = "../../../psi/foundation/psi-symbols" }
