[package]
name = "omega-backend-plan"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_backend_plan"
path = "src/lib.rs"

[dependencies]
omega-calling-conventions = { path = "../../../representations/omega-calling-conventions" }
omega-function-identity = { path = "../../../representations/omega-function-identity" }
psi-arena = { path = "../../../../psi/foundation/psi-arena" }
psi-checked-trees = { path = "../../../../psi/representations/psi-checked-trees" }
psi-layout-plans = { path = "../../../../psi/foundation/psi-layout-plans" }
psi-symbols = { path = "../../../../psi/foundation/psi-symbols" }
omega-target = { path = "../../../representations/omega-target" }
