#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum StraightLineIntegerBitwiseNotParameterTranslationError {
    SourceParameters,
    SourceStructuralParameters,
    SourceResult,
    SourceEntryClaims,
    SourcePublishedServices,
    SourceBlockRoster,
    SourceOperationRoster,
    SourceParameterRoster,
    SourceParameterShape,
    SourceBitwiseNotResultRoster,
    SourceOperandLink,
    SourceOperandTypeMismatch,
    SourceReturnLink,
    SourceCleanup,
    AbiPlan,
    AbiParameterCount,
    AbiParameterPlacement,
    TargetProvenance,
    TargetOperation,
}
