canonical_identity!(
    FunctionFragmentEmissionIdentity,
    b"omega.terminal-function-fragment-emission-identity.v1\0"
);
canonical_identity!(
    FunctionFragmentEmissionManifestIdentity,
    b"omega.function-fragment-emission-manifest-identity.v1\0"
);
canonical_identity!(
    TerminalRelocationFreeTextSectionIdentity,
    b"omega.terminal-relocation-free-text-section-identity.v1\0"
);
canonical_identity!(
    FunctionFragmentTextSectionManifestIdentity,
    b"omega.function-fragment-text-section-manifest-identity.v1\0"
);
canonical_identity!(
    RelocationFreeObjectPlanIdentity,
    b"omega.terminal-relocation-free-object-plan-identity.v1\0"
);
canonical_identity!(
    RelocationFreeObjectContainerIdentity,
    b"omega.terminal-relocation-free-object-container-identity.v1\0"
);
canonical_identity!(
    FunctionFragmentObjectContainerManifestIdentity,
    b"omega.function-fragment-object-container-manifest-identity.v1\0"
);
canonical_identity!(
    OptimizedObjectArtifactIdentity,
    b"omega.optimized-terminal-object-artifact-identity.v1\0"
);
canonical_identity!(
    OptimizedObjectArtifactManifestIdentity,
    b"omega.optimized-terminal-object-artifact-manifest-identity.v1\0"
);
canonical_identity!(
    OptimizedTerminalOrdinaryCallableEntryIdentity,
    b"omega.optimized-terminal-ordinary-callable-entry-identity.v1\0"
);
canonical_identity!(
    OptimizedOrdinaryCallableEntryManifestIdentity,
    b"omega.optimized-terminal-ordinary-callable-entry-manifest-identity.v1\0"
);
canonical_identity!(
    OptimizedProgramStorageSemanticWrapperObjectIdentity,
    b"omega.optimized-program-storage-semantic-wrapper-object-identity.v1\0"
);
canonical_identity!(
    OptimizedProgramStorageSemanticWrapperObjectContainerIdentity,
    b"omega.optimized-program-storage-semantic-wrapper-object-container-identity.v1\0"
);
canonical_identity!(
    OptimizedProgramStorageSemanticWrapperObjectManifestIdentity,
    b"omega.optimized-program-storage-semantic-wrapper-object-manifest-identity.v1\0"
);
