[package]
name = "omega-image-elf"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_image_elf"
path = "src/lib.rs"

[dependencies]
psi-arena = { path = "../../../../psi/foundation/psi-arena" }
psi-diagnostics = { path = "../../../../psi/foundation/psi-diagnostics" }
omega-image = { path = "../omega-image" }
omega-object-file = { path = "../../object/omega-object-file" }
