[package]
name = "psi-typed-trees-to-checked-trees"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "psi_typed_trees_to_checked_trees"
path = "src/lib.rs"

[dependencies]
psi-arena = { path = "../../foundation/psi-arena" }
psi-checked-trees = { path = "../../representations/psi-checked-trees" }
psi-core = { path = "../../foundation/psi-core" }
psi-diagnostics = { path = "../../foundation/psi-diagnostics" }
psi-effects = { path = "../../representations/psi-effects" }
psi-facts = { path = "../../representations/psi-facts" }
psi-language-core = { path = "../../foundation/psi-language-core" }
psi-language-semantics = { path = "../../foundation/psi-language-semantics" }
psi-numerics = { path = "../../foundation/psi-numerics" }
psi-proof = { path = "../../semantics/psi-proof" }
psi-source = { path = "../../foundation/psi-source" }
psi-symbols = { path = "../../foundation/psi-symbols" }
psi-typed-trees = { path = "../../representations/psi-typed-trees" }
psi-validation = { path = "../../semantics/psi-validation" }
sha2 = "0.10"

[dev-dependencies]
psi-source-files-to-tokens = { path = "../psi-source-files-to-tokens" }
psi-symbol-resolved-trees-to-typed-trees = { path = "../psi-symbol-resolved-trees-to-typed-trees" }
psi-syntax-trees-to-symbol-resolved-trees = { path = "../psi-syntax-trees-to-symbol-resolved-trees" }
psi-tokens-to-syntax-trees = { path = "../psi-tokens-to-syntax-trees" }
