[package]
name = "post-allocation-machine-to-selected-form-encoding"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "post_allocation_machine_to_selected_form_encoding"
path = "src/lib.rs"

[features]
test-support = []

[dependencies]
register-homes-to-post-allocation-machine = { path = "../06_register-homes-to-post-allocation-machine" }
target-operations-to-selected-instructions = { path = "../03_target-operations-to-selected-instructions" }
sha2 = "0.10.9"
terminal-psi = { path = "../../../psi/terminal-psi" }
optimization-core = { path = "../../../psi/optimization-core" }
terminal-psi-to-abstract-operations = { path = "../00_terminal-psi-to-abstract-operations" }
abstract-operations-to-target-operations = { path = "../02_abstract-operations-to-target-operations" }
selected-instructions-to-selected-instructions = { path = "../04_selected-instructions-to-selected-instructions" }
selected-instructions-to-register-homes = { path = "../05_selected-instructions-to-register-homes" }
target = { path = "../../../psi/target" }
semantic-vocabulary = { path = "../../../psi/foundation/semantic-vocabulary" }
