[package]
name = "omega-runtime-bodies"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_runtime_bodies"
path = "src/lib.rs"

[dependencies]
psi-checked-trees = { path = "../../../psi/representations/psi-checked-trees" }
omega-control-flow = { path = "../../representations/omega-control-flow" }
omega-core = { path = "../../foundation/omega-core" }
psi-arena = { path = "../../../psi/foundation/psi-arena" }
psi-symbols = { path = "../../../psi/foundation/psi-symbols" }
psi-language-core = { path = "../../../psi/foundation/psi-language-core" }
omega-platform-interface = { path = "../omega-platform-interface" }
omega-state-calls = { path = "../omega-state-calls" }
omega-state-dispatch = { path = "../omega-state-dispatch" }
omega-state-graph = { path = "../../representations/omega-state-graph" }
omega-state-storage = { path = "../omega-state-storage" }
