[package]
name = "omega-control-flow-to-abstract-operations"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_control_flow_to_abstract_operations"
path = "src/lib.rs"

[dependencies]
omega-abstract-operations = { path = "../../representations/omega-abstract-operations" }
omega-calling-conventions = { path = "../../foundation/omega-calling-conventions" }
psi-checked-trees = { path = "../../../psi/representations/psi-checked-trees" }
omega-control-flow = { path = "../../representations/omega-control-flow" }
psi-arena = { path = "../../../psi/foundation/psi-arena" }
psi-symbols = { path = "../../../psi/foundation/psi-symbols" }
omega-effects = { path = "../../representations/omega-effects" }
psi-facts = { path = "../../../psi/representations/psi-facts" }
psi-numerics = { path = "../../../psi/foundation/psi-numerics" }
psi-diagnostics = { path = "../../../psi/foundation/psi-diagnostics" }
omega-instruction-selection = { path = "../../backend/omega-instruction-selection" }
omega-layout = { path = "../../backend/omega-layout" }
omega-platform-interface = { path = "../../backend/omega-platform-interface" }
omega-runtime-abi = { path = "../../foundation/omega-runtime-abi" }
omega-runtime-bodies = { path = "../../backend/omega-runtime-bodies" }
omega-runtime-branching = { path = "../../backend/omega-runtime-branching" }
omega-runtime-dispatch-loop = { path = "../../backend/omega-runtime-dispatch-loop" }
omega-runtime-storage = { path = "../../backend/omega-runtime-storage" }
omega-runtime-text = { path = "../../backend/omega-runtime-text" }
omega-state-calls = { path = "../../backend/omega-state-calls" }
omega-state-graph = { path = "../../representations/omega-state-graph" }
omega-state-guards = { path = "../../backend/omega-state-guards" }
omega-state-storage = { path = "../../backend/omega-state-storage" }
omega-target = { path = "../../foundation/omega-target" }
omega-target-operations = { path = "../../representations/omega-target-operations" }

[dev-dependencies]
psi-language-semantics = { path = "../../../psi/foundation/psi-language-semantics" }
