[package]
name = "omega-layout"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_layout"
path = "src/lib.rs"

[dependencies]
psi-checked-trees = { path = "../../../psi-rs/representations/psi-checked-trees" }
omega-core = { path = "../../foundation/omega-core" }
psi-numerics = { path = "../../../psi-rs/foundation/psi-numerics" }
omega-runtime-abi = { path = "../../foundation/omega-runtime-abi" }
omega-target = { path = "../../foundation/omega-target" }
