[package]
name = "psi-terminal"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "psi_terminal"
path = "src/lib.rs"

[dependencies]
psi-core = { path = "../../foundation/psi-core" }
psi-language-core = { path = "../../foundation/psi-language-core" }
psi-language-semantics = { path = "../../foundation/psi-language-semantics" }
