[package]
name = "omega-symbol-resolved-trees-to-typed-trees"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_symbol_resolved_trees_to_typed_trees"
path = "src/lib.rs"

[dependencies]
omega-typed-trees = { path = "../../representations/omega-typed-trees" }
omega-core = { path = "../../foundation/omega-core" }
omega-symbol-resolved-trees = { path = "../../representations/omega-symbol-resolved-trees" }

[dev-dependencies]
omega-source-files-to-tokens = { path = "../omega-source-files-to-tokens" }
omega-tokens-to-syntax-trees = { path = "../omega-tokens-to-syntax-trees" }
omega-syntax-trees-to-symbol-resolved-trees = { path = "../omega-syntax-trees-to-symbol-resolved-trees" }
