#!/usr/bin/env python3
"""Generate and verify bounded CKIR14 arithmetic source cases.

This registry deliberately owns source inputs and semantic expectations only.
It does not guess the future OMGLOW/CKIR14 producer interface or wire format.
"""

from __future__ import annotations

import argparse
import dataclasses
import json
import re
from pathlib import Path


U32_MAX = 0xFFFF_FFFF
HERE = Path(__file__).resolve().parent
DEFAULT_OUTPUT = HERE / "fixtures" / "ckir14-arithmetic-cases"
GENERATED = "// Generated by gates/ckir14-arithmetic-cases.py; do not edit.\n"
TOKEN = re.compile(r"\s*([A-Za-z_][A-Za-z0-9_.]*|[0-9]+|[-+*/()%])")


class ArithmeticTrap(Exception):
    pass


@dataclasses.dataclass(frozen=True)
class Node:
    kind: str
    value: str | int
    left: "Node | None" = None
    right: "Node | None" = None


@dataclasses.dataclass(frozen=True)
class Expression:
    text: str
    environment: dict[str, int]
    expected: int | str


@dataclasses.dataclass(frozen=True)
class Case:
    name: str
    group: str
    outcome: str
    source: str
    expressions: tuple[Expression, ...]
    contexts: tuple[str, ...] = ("assignment",)
    ck12_view: bool = False
    note: str = ""


class Parser:
    def __init__(self, text: str) -> None:
        self.tokens = TOKEN.findall(text)
        compact = "".join(self.tokens)
        if compact != re.sub(r"\s+", "", text):
            raise ValueError(f"unrecognized expression text: {text}")
        self.at = 0

    def parse(self) -> Node:
        result = self.additive()
        if self.at != len(self.tokens):
            raise ValueError(f"trailing expression token {self.tokens[self.at]!r}")
        return result

    def additive(self) -> Node:
        left = self.multiplicative()
        while self.peek() in ("+", "-"):
            operator = self.take()
            left = Node(operator, operator, left, self.multiplicative())
        return left

    def multiplicative(self) -> Node:
        left = self.primary()
        while self.peek() in ("*", "/", "%"):
            operator = self.take()
            left = Node(operator, operator, left, self.primary())
        return left

    def primary(self) -> Node:
        token = self.take()
        if token == "(":
            value = self.additive()
            if self.take() != ")":
                raise ValueError("missing closing parenthesis")
            return value
        if token.isdigit():
            return Node("integer", int(token))
        if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_.]*", token):
            return Node("name", token)
        raise ValueError(f"unexpected primary token {token!r}")

    def peek(self) -> str | None:
        return None if self.at == len(self.tokens) else self.tokens[self.at]

    def take(self) -> str:
        if self.at == len(self.tokens):
            raise ValueError("unexpected end of expression")
        token = self.tokens[self.at]
        self.at += 1
        return token


def evaluate(node: Node, environment: dict[str, int]) -> int:
    if node.kind == "integer":
        return int(node.value)
    if node.kind == "name":
        return environment[str(node.value)]
    assert node.left is not None and node.right is not None
    left = evaluate(node.left, environment)
    right = evaluate(node.right, environment)
    if node.kind == "+":
        value = left + right
    elif node.kind == "-":
        value = left - right
    elif node.kind == "*":
        value = left * right
    elif node.kind == "/":
        if right == 0:
            raise ArithmeticTrap
        value = left // right
    else:
        if right == 0:
            raise ArithmeticTrap
        value = left % right
    if not 0 <= value <= U32_MAX:
        raise ArithmeticTrap
    return value


def statistics(node: Node) -> dict[str, int]:
    if node.left is None:
        return {"add": 0, "subtract": 0, "multiply": 0,
                "divide": 0, "remainder": 0, "nested_subtract_parent": 0,
                "depth": 1}
    assert node.right is not None
    left = statistics(node.left)
    right = statistics(node.right)
    result = {key: left[key] + right[key] for key in
              ("add", "subtract", "multiply", "divide", "remainder",
               "nested_subtract_parent")}
    result[{"+": "add", "-": "subtract", "*": "multiply",
            "/": "divide", "%": "remainder"}[node.kind]] += 1
    if node.kind in ("+", "*"):
        result["nested_subtract_parent"] += int(node.left.kind == "-")
        result["nested_subtract_parent"] += int(node.right.kind == "-")
    result["depth"] = max(left["depth"], right["depth"]) + 1
    return result


def fields(names: tuple[str, ...], domain: str = "Trapping") -> str:
    return "\n".join(f"    {name}: u32 in {domain};" for name in names)


def assignment_case(owner: str, values: dict[str, int], expression: str,
                    expected: int, domain: str = "Trapping") -> str:
    names = tuple(values) + ("result",)
    stores = "\n".join(f"    self.{name} = {value};" for name, value in values.items())
    return f"""data {owner} {{
{fields(names, domain)}
}}

machine {owner}::run(&mut self) -> u8 {{
{stores}
    self.result = {expression};
    transition self.result == {expected} {{ true -> passed() false -> failed() }}
    state passed(&mut self) {{ 70 }}
    state failed(&mut self) {{ 0 }}
}}
"""


def utf_case(width: int, values: tuple[int, ...], expression: str,
             expected: int) -> Case:
    environment = {f"self.byte{index}": value for index, value in enumerate(values)}
    source_values = {f"byte{index}": value for index, value in enumerate(values)}
    return Case(
        f"utf8-{width}-byte", "utf8", "success-70",
        assignment_case(f"Utf{width}Case", source_values, expression, expected),
        (Expression(expression, environment, expected),),
        note="exact product lexer decode tree",
    )


TWO = "(self.byte0 - 192) * 64 + (self.byte1 - 128)"
THREE = "(self.byte0 - 224) * 4096 + (self.byte1 - 128) * 64 + (self.byte2 - 128)"
FOUR = "(self.byte0 - 240) * 262144 + (self.byte1 - 128) * 4096 + (self.byte2 - 128) * 64 + (self.byte3 - 128)"


def cases() -> tuple[Case, ...]:
    result: list[Case] = [
        utf_case(2, (194, 128), TWO, 128),
        utf_case(3, (224, 160, 128), THREE, 2048),
        utf_case(4, (240, 144, 128, 128), FOUR, 65536),
    ]

    precedence_expressions = (
        Expression("self.a - self.b * self.c + self.d",
                   {"self.a": 20, "self.b": 3, "self.c": 4, "self.d": 2}, 10),
        Expression("self.a - self.b + self.d",
                   {"self.a": 20, "self.b": 3, "self.d": 2}, 19),
        Expression("(self.a - self.b) * self.c + self.d",
                   {"self.a": 20, "self.b": 3, "self.c": 4, "self.d": 2}, 70),
    )
    result.append(Case(
        "precedence-association-parentheses", "grammar", "success-70",
        """data GrammarCase {
    a: u32 in Trapping; b: u32 in Trapping; c: u32 in Trapping; d: u32 in Trapping;
    precedence: u32 in Trapping; association: u32 in Trapping; grouped: u32 in Trapping;
}
machine GrammarCase::run(&mut self) -> u8 {
    self.a = 20; self.b = 3; self.c = 4; self.d = 2;
    self.precedence = self.a - self.b * self.c + self.d;
    self.association = self.a - self.b + self.d;
    self.grouped = (self.a - self.b) * self.c + self.d;
    transition self.precedence == 10 && self.association == 19 && self.grouped == 70 {
        true -> passed() false -> failed()
    }
    state passed(&mut self) { 70 }
    state failed(&mut self) { 0 }
}
""", precedence_expressions))

    context_expression = TWO
    context_env = {"self.byte0": 194, "self.byte1": 128}
    result.append(Case(
        "representative-contexts", "contexts", "success-70",
        """data ArithmeticGate {}
machine ArithmeticGate::keep(&self, prefix: u8, value: u32 in Trapping, suffix: u8) -> u32 in Trapping { value }
data ArithmeticChoice [copy] { case Value(prefix: u8); case Empty; }
data ContextCase {
    gate: ArithmeticGate; choice: ArithmeticChoice;
    byte0: u32 in Trapping; byte1: u32 in Trapping; result: u32 in Trapping;
}
machine ContextCase::run(&mut self) -> u8 {
    self.byte0 = 194; self.byte1 = 128;
    self.result = (self.byte0 - 192) * 64 + (self.byte1 - 128);
    transition self.result == 128 { true -> guard_context() false -> failed() }
    state guard_context(&mut self) {
        transition (self.byte0 - 192) * 64 + (self.byte1 - 128) == 128 {
            true -> call_context() false -> failed()
        }
    }
    state call_context(&mut self) {
        self.result = self.gate.keep(7, (self.byte0 - 192) * 64 + (self.byte1 - 128), 9);
        self.choice = ArithmeticChoice::Value { prefix: 7 };
        transition self.choice {
            ArithmeticChoice::Value { prefix } -> receive(prefix, (self.byte0 - 192) * 64 + (self.byte1 - 128), 9)
            ArithmeticChoice::Empty -> failed()
        }
    }
    state receive(&mut self, prefix: u8, value: u32 in Trapping, suffix: u8) {
        transition prefix == 7 && value == 128 && suffix == 9 { true -> passed() false -> failed() }
    }
    state passed(&mut self) { 70 }
    state failed(&mut self) { 0 }
}
""", tuple(Expression(context_expression, context_env, 128) for _ in range(4)),
        ("assignment", "guard", "call-argument", "transition-argument")))

    trap_specs = (
        ("nested-underflow", {"a": 0, "b": 1, "c": 64, "d": 0},
         "(self.a - self.b) * self.c + self.d"),
        ("multiply-overflow", {"a": U32_MAX, "b": 0, "c": 2, "d": 0},
         "(self.a - self.b) * self.c + self.d"),
        ("add-overflow", {"a": U32_MAX, "b": 0, "c": 1, "d": 1},
         "(self.a - self.b) * self.c + self.d"),
    )
    for name, values, expression in trap_specs:
        result.append(Case(name, "runtime-trap", "trap",
                           assignment_case(name.title().replace("-", ""), values,
                                           expression, 0),
                           (Expression(expression,
                                       {f"self.{key}": value for key, value in values.items()},
                                       "trap"),)))

    depth8 = "self.a - self.b + 1 + 1 + 1 + 1 + 1 + 1"
    depth9 = depth8 + " + 1"
    result.extend((
        Case("depth-8-boundary", "resource", "success-70",
             assignment_case("Depth8Case", {"a": 9, "b": 6}, depth8, 9),
             (Expression(depth8, {"self.a": 9, "self.b": 6}, 9),)),
        Case("depth-9-exhausted", "resource", "reject-252",
             assignment_case("Depth9Case", {"a": 9, "b": 6}, depth9, 10),
             (Expression(depth9, {"self.a": 9, "self.b": 6}, 10),)),
        Case("wrong-domain", "profile-negative", "reject-251",
             assignment_case("WrongDomainCase", {"a": 9, "b": 6, "c": 2},
                             "(self.a - self.b) * self.c", 6, "Saturating"),
             (Expression("(self.a - self.b) * self.c",
                         {"self.a": 9, "self.b": 6, "self.c": 2}, 6),),
             note="other arithmetic policy"),
        Case("unsupported-divide", "profile-negative", "reject-251",
             assignment_case("DivideCase", {"a": 9, "b": 6, "c": 3},
                             "(self.a - self.b) / self.c", 1),
             (Expression("(self.a - self.b) / self.c",
                         {"self.a": 9, "self.b": 6, "self.c": 3}, 1),),
             note="operator outside selected grammar"),
        Case("add-only-selected", "selected-operator", "success-70",
             assignment_case("AddOnlyCase", {"a": 9, "b": 6},
                             "self.a + self.b", 15),
             (Expression("self.a + self.b", {"self.a": 9, "self.b": 6}, 15),),
             note="one selected full-width Add is sufficient"),
        Case("missing-arithmetic", "profile-negative", "reject-251",
             assignment_case("MissingArithmeticCase", {"a": 9},
                             "self.a", 9),
             (Expression("self.a", {"self.a": 9}, 9),),
             note="OMGLOWF and CKIR14 require at least one selected arithmetic node"),
    ))

    view_expression = "(self.value - 64) * 2 + (self.value - 70)"
    result.append(Case(
        "ckir12-view-plus-arithmetic", "composition", "success-70",
        """data ViewArithmeticCase { value: u32 in Trapping; }
machine ViewArithmeticCase::run(&mut self) -> u8 {
    transition { _ -> inspect("F") }
    state inspect(&mut self, view: &[u8]) {
        transition view.len > 0 { true -> present(view[0], view[1..]) false -> failed() }
    }
    state present(&mut self, head: u8, tail: &[u8]) {
        self.value = head as u32 in Trapping;
        self.value = (self.value - 64) * 2 + (self.value - 70);
        transition self.value == 12 { true -> passed() false -> failed() }
    }
    state passed(&mut self) { 70 }
    state failed(&mut self) { 0 }
}
""", (Expression(view_expression, {"self.value": 70}, 12),),
        ("assignment",), True, "compose inherited StaticByteView/nonempty/head/tail"))
    return tuple(result)


def case_projection(case: Case) -> dict[str, object]:
    totals = {key: 0 for key in ("add", "subtract", "multiply", "divide",
                                  "remainder", "nested_subtract_parent")}
    depths: list[int] = []
    for expression in case.expressions:
        node = Parser(expression.text).parse()
        stats = statistics(node)
        for key in totals:
            totals[key] += stats[key]
        depths.append(stats["depth"])
        try:
            observed: int | str = evaluate(node, expression.environment)
        except ArithmeticTrap:
            observed = "trap"
        if observed != expression.expected:
            raise ValueError(f"{case.name}: {expression.text!r} produced {observed}, expected {expression.expected}")
    return {
        "name": case.name,
        "file": f"{case.name}.omg",
        "group": case.group,
        "expected_outcome": case.outcome,
        "contexts": list(case.contexts),
        "ckir12_view_composition": case.ck12_view,
        "arithmetic": totals,
        "maximum_expression_depth": max(depths),
        "expressions": [dataclasses.asdict(expression) for expression in case.expressions],
        "note": case.note,
    }


def generated_files() -> dict[str, bytes]:
    registry = cases()
    if len({case.name for case in registry}) != len(registry):
        raise ValueError("duplicate case name")
    files = {f"{case.name}.omg": (GENERATED + case.source).encode("utf-8")
             for case in registry}
    projections = [case_projection(case) for case in registry]
    utf8 = [row for row in projections if row["group"] == "utf8"]
    utf8_totals = {
        key: sum(row["arithmetic"][key] for row in utf8)
        for key in ("add", "subtract", "multiply", "nested_subtract_parent")
    }
    manifest = {
        "schema": "omega.bootstrap.ckir14-arithmetic-source-cases.v1",
        "authority": "source fixtures and expected semantics only; no CKIR14 wire authority",
        "coverage": {
            "actual_utf8_arithmetic": utf8_totals,
            "representative_contexts": ["assignment", "guard", "call-argument",
                                        "transition-argument"],
            "outcomes": ["success-70", "trap", "reject-251", "reject-252"],
            "expression_depth_boundary": {"accepted": 8, "exhausted": 9},
            "ckir12_view_composition_cases": 1,
        },
        "cases": projections,
    }
    files["manifest.json"] = (json.dumps(manifest, indent=2, sort_keys=True) + "\n").encode("utf-8")
    return files


def write(directory: Path) -> None:
    directory.mkdir(parents=True, exist_ok=True)
    expected = generated_files()
    for name, contents in expected.items():
        (directory / name).write_bytes(contents)


def check(directory: Path) -> None:
    expected = generated_files()
    actual = {path.name: path.read_bytes() for path in directory.iterdir() if path.is_file()}
    if set(actual) != set(expected):
        raise ValueError(f"fixture names differ: missing={sorted(set(expected)-set(actual))}, extra={sorted(set(actual)-set(expected))}")
    for name, contents in expected.items():
        if actual[name] != contents:
            raise ValueError(f"generated fixture differs: {name}")
    manifest = json.loads(actual["manifest.json"])
    rows = manifest["cases"]
    utf = [row for row in rows if row["group"] == "utf8"]
    assert [(row["arithmetic"]["subtract"], row["arithmetic"]["multiply"],
             row["arithmetic"]["add"]) for row in utf] == [(2, 1, 1), (3, 2, 2), (4, 3, 3)]
    assert next(row for row in rows if row["name"] == "depth-8-boundary")["maximum_expression_depth"] == 8
    assert next(row for row in rows if row["name"] == "depth-9-exhausted")["maximum_expression_depth"] == 9
    add_only = next(row for row in rows if row["name"] == "add-only-selected")
    assert add_only["expected_outcome"] == "success-70"
    assert add_only["arithmetic"] == {
        "add": 1, "subtract": 0, "multiply": 0, "divide": 0,
        "remainder": 0, "nested_subtract_parent": 0,
    }
    missing = next(row for row in rows if row["name"] == "missing-arithmetic")
    assert missing["expected_outcome"] == "reject-251"
    assert all(count == 0 for count in missing["arithmetic"].values())
    assert manifest["coverage"]["actual_utf8_arithmetic"] == {
        "add": 6, "subtract": 9, "multiply": 6, "nested_subtract_parent": 9,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=("generate", "check"))
    parser.add_argument("directory", type=Path, nargs="?", default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    if args.command == "generate":
        write(args.directory)
        print(f"CKIR14 arithmetic cases: generated {len(generated_files()) - 1} sources")
    else:
        check(args.directory)
        print(f"CKIR14 arithmetic cases: {len(generated_files()) - 1} generated sources passed")


if __name__ == "__main__":
    main()
