[package]
name = "omega-machine-code"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_machine_code"
path = "src/lib.rs"

[dependencies]
omega-calling-conventions = { path = "../omega-calling-conventions" }
omega-function-identity = { path = "../omega-function-identity" }
omega-optimization-core = { path = "../omega-optimization-core" }
omega-optimization-unit = { path = "../omega-optimization-unit" }
omega-target = { path = "../omega-target" }
omega-register-model = { path = "../omega-register-model" }
omega-abstract-operations = { path = "../omega-abstract-operations" }
omega-selected-instructions = { path = "../omega-selected-instructions" }
omega-target-operations = { path = "../omega-target-operations" }
omega-task-plans = { path = "../omega-task-plans" }
psi-core = { path = "../../../psi/foundation/psi-core" }
psi-terminal = { path = "../../../psi/representations/psi-terminal" }
sha2 = "0.10.9"
