[package]
name = "omega-visualizations"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_visualizations"
path = "src/lib.rs"

[dependencies]
psi-arena = { path = "../../../psi/foundation/psi-arena" }
psi-symbols = { path = "../../../psi/foundation/psi-symbols" }
omega-effects = { path = "../../representations/omega-effects" }
omega-task-plans = { path = "../../representations/omega-task-plans" }
psi-checked-trees = { path = "../../../psi/representations/psi-checked-trees" }
psi-core = { path = "../../../psi/foundation/psi-core" }
psi-effects = { path = "../../../psi/representations/psi-effects" }
psi-facts = { path = "../../../psi/representations/psi-facts" }
psi-language-semantics = { path = "../../../psi/foundation/psi-language-semantics" }
psi-typed-trees = { path = "../../../psi/representations/psi-typed-trees" }

[dev-dependencies]
omega-target = { path = "../../representations/omega-target" }
psi-numerics = { path = "../../../psi/foundation/psi-numerics" }
