[package]
name = "psi-types"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "psi_types"
path = "src/lib.rs"

[dependencies]
psi-arena = { path = "../../foundation/psi-arena" }
psi-language-semantics = { path = "../../foundation/psi-language-semantics" }
psi-numerics = { path = "../../foundation/psi-numerics" }
psi-syntax-trees = { path = "../../representations/psi-syntax-trees" }
