[package]
name = "terminal-psi"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "terminal_psi"
path = "src/lib.rs"

[dependencies]
semantic-vocabulary = { path = "../../foundation/semantic-vocabulary" }
language-core = { path = "../../foundation/language-core" }
language-semantics = { path = "../../foundation/language-semantics" }
sha2 = "0.10"
