[package]
name = "omega-optimization-policy-offline"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_optimization_policy_offline"
path = "src/lib.rs"

[dependencies]
omega-optimization-core = { path = "../../representations/omega-optimization-core" }
omega-optimization-policy = { path = "../../pipeline/optimization/omega-optimization-policy" }
sha2 = "0.10.9"
