[package]
name = "omega-assigned-target-operations-to-machine-instructions"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_assigned_target_operations_to_machine_instructions"
path = "src/lib.rs"

[dependencies]
omega-assigned-target-operations = { path = "../../representations/omega-assigned-target-operations" }
omega-calling-conventions = { path = "../../foundation/omega-calling-conventions" }
omega-control-flow = { path = "../../representations/omega-control-flow" }
psi-arena = { path = "../../../psi/foundation/psi-arena" }
psi-symbols = { path = "../../../psi/foundation/psi-symbols" }
omega-machine-instructions = { path = "../../representations/omega-machine-instructions" }
omega-target = { path = "../../foundation/omega-target" }
psi-diagnostics = { path = "../../../psi/foundation/psi-diagnostics" }

[dev-dependencies]
omega-abstract-operations = { path = "../../representations/omega-abstract-operations" }
psi-language-semantics = { path = "../../../psi/foundation/psi-language-semantics" }
