#!/usr/bin/env sh
# Canonical repository paths for the bootstrap chain.
#
# This file is replaceable invocation plumbing. It names source owners only;
# it does not perform a translation or contribute semantics to a compiler edge.

if [ -z "${OMEGA_REPO_ROOT:-}" ] || [ ! -f "$OMEGA_REPO_ROOT/TASKS_BOOTSTRAP.md" ]; then
  echo "bootstrap paths: OMEGA_REPO_ROOT is not an Omega repository root" >&2
  return 2
fi

OMEGA_PATH_ALPHA=$OMEGA_REPO_ROOT/source/alpha

OMEGA_PATH_ALPHA_TAPE_ASSEMBLY=$OMEGA_REPO_ROOT/tools/alpha/tape-assembly
OMEGA_PATH_ALPHA_TAPE_ASSEMBLY_COMPILER=$OMEGA_PATH_ALPHA_TAPE_ASSEMBLY/compiler
OMEGA_PATH_ALPHA_TAPE_ASSEMBLER_SOURCE=$OMEGA_PATH_ALPHA_TAPE_ASSEMBLY_COMPILER/assembler.alphaasm
OMEGA_PATH_ALPHA_TAPE_ASSEMBLER_TAPE=$OMEGA_PATH_ALPHA_TAPE_ASSEMBLY_COMPILER/alpha_tape_assembler_bytecode.tape

OMEGA_PATH_BETA=$OMEGA_REPO_ROOT/source/beta
OMEGA_PATH_BETA_EVALUATOR=$OMEGA_PATH_BETA/evaluator
OMEGA_PATH_BETA_EVALUATOR_TAPE=$OMEGA_PATH_BETA_EVALUATOR/beta_evaluator_bytecode.tape

OMEGA_PATH_GAMMA=$OMEGA_REPO_ROOT/source/gamma
OMEGA_PATH_GAMMA_COMPILER=$OMEGA_PATH_GAMMA/compiler
OMEGA_PATH_GAMMA_COMPILER_SOURCE=$OMEGA_PATH_GAMMA_COMPILER/gamma_compiler.beta
OMEGA_PATH_GAMMA_COMPILER_TAPE=$OMEGA_PATH_GAMMA_COMPILER/gamma_compiler_bytecode.tape

OMEGA_PATH_DELTA=$OMEGA_REPO_ROOT/source/delta
OMEGA_PATH_DELTA_COMPILER=$OMEGA_PATH_DELTA/compiler
OMEGA_PATH_DELTA_COMPILER_SOURCE=$OMEGA_PATH_DELTA_COMPILER/delta_compiler.gamma
OMEGA_PATH_DELTA_COMPILER_TAPE=$OMEGA_PATH_DELTA_COMPILER/delta_compiler_bytecode.tape

OMEGA_PATH_OMEGA=$OMEGA_REPO_ROOT/source/omega
OMEGA_PATH_OMEGA_COMPILER_SOURCE=$OMEGA_PATH_OMEGA/omega_compiler.delta

export OMEGA_REPO_ROOT OMEGA_PATH_ALPHA
export OMEGA_PATH_ALPHA_TAPE_ASSEMBLY OMEGA_PATH_ALPHA_TAPE_ASSEMBLY_COMPILER
export OMEGA_PATH_ALPHA_TAPE_ASSEMBLER_SOURCE OMEGA_PATH_ALPHA_TAPE_ASSEMBLER_TAPE
export OMEGA_PATH_BETA OMEGA_PATH_BETA_EVALUATOR OMEGA_PATH_BETA_EVALUATOR_TAPE
export OMEGA_PATH_GAMMA OMEGA_PATH_GAMMA_COMPILER
export OMEGA_PATH_GAMMA_COMPILER_SOURCE OMEGA_PATH_GAMMA_COMPILER_TAPE
export OMEGA_PATH_DELTA OMEGA_PATH_DELTA_COMPILER
export OMEGA_PATH_DELTA_COMPILER_SOURCE OMEGA_PATH_DELTA_COMPILER_TAPE
export OMEGA_PATH_OMEGA OMEGA_PATH_OMEGA_COMPILER_SOURCE
