[package]
name = "omega-platform-interface"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_platform_interface"
path = "src/lib.rs"

[dependencies]
omega-calling-conventions = { path = "../../foundation/omega-calling-conventions" }
psi-checked-trees = { path = "../../../psi/representations/psi-checked-trees" }
omega-control-flow = { path = "../../representations/omega-control-flow" }
omega-core = { path = "../../foundation/omega-core" }
psi-arena = { path = "../../../psi/foundation/psi-arena" }
psi-symbols = { path = "../../../psi/foundation/psi-symbols" }
psi-diagnostics = { path = "../../../psi/foundation/psi-diagnostics" }
omega-target = { path = "../../foundation/omega-target" }
psi-typed-trees = { path = "../../../psi/representations/psi-typed-trees" }

[dev-dependencies]
psi-source-files-to-tokens = { path = "../../../psi/pipeline/psi-source-files-to-tokens" }
psi-symbol-resolved-trees-to-typed-trees = { path = "../../../psi/pipeline/psi-symbol-resolved-trees-to-typed-trees" }
psi-syntax-trees-to-symbol-resolved-trees = { path = "../../../psi/pipeline/psi-syntax-trees-to-symbol-resolved-trees" }
psi-tokens-to-syntax-trees = { path = "../../../psi/pipeline/psi-tokens-to-syntax-trees" }
psi-typed-trees-to-checked-trees = { path = "../../../psi/pipeline/psi-typed-trees-to-checked-trees" }
