#![forbid(unsafe_code)]
//! Optimizer module role: crate map. Enter `lowering/mod.rs`, then descend by result family and semantic responsibility.
mod lowering;
mod model;
mod validation;

pub use lowering::{
    lower_ranked_to_target_operations, lower_to_target_operations,
    lower_to_target_operations_with_provider_executions,
    lower_to_target_operations_with_provider_executions_and_installation,
    lower_to_target_operations_with_provider_executions_installation_and_ieee_float_fma,
    lower_to_target_operations_with_provider_executions_installation_ieee_float_fma_and_native_callbacks,
};
pub use model::{
    AdmittedBoundaryExecution, AdmittedBoundarySettlement, AdmittedIeeeFloatFmaSettlement,
    AdmittedNativeCallbackArgument, LoweringError,
};
pub use validation::{
    AbstractToTargetFunctionRosterReceipt, AbstractToTargetFunctionTranslationDisposition,
    AbstractToTargetFunctionTranslationReceipt, AbstractToTargetTranslationFamily,
    AbstractToTargetTranslationFamilyError, AbstractToTargetTranslationValidationError,
    AbstractToTargetTranslationValidationReceipt,
    StraightLineBooleanEqualParametersTranslationError,
    StraightLineBooleanEqualParametersTranslationReceipt,
    StraightLineBooleanImmediateTranslationError, StraightLineBooleanImmediateTranslationReceipt,
    StraightLineBooleanNotParameterTranslationError,
    StraightLineBooleanNotParameterTranslationReceipt,
    StraightLineBooleanParameterTranslationError, StraightLineBooleanParameterTranslationReceipt,
    StraightLineByteSequenceLiteralUnitReturnTranslationError,
    StraightLineByteSequenceLiteralUnitReturnTranslationReceipt,
    StraightLineExactIntegerAddParametersTranslationError,
    StraightLineExactIntegerAddParametersTranslationReceipt,
    StraightLineExactIntegerDivideParametersTranslationError,
    StraightLineExactIntegerDivideParametersTranslationReceipt,
    StraightLineExactIntegerMultiplyParametersTranslationError,
    StraightLineExactIntegerMultiplyParametersTranslationReceipt,
    StraightLineExactIntegerRemainderParametersTranslationError,
    StraightLineExactIntegerRemainderParametersTranslationReceipt,
    StraightLineExactIntegerShiftLeftParametersTranslationError,
    StraightLineExactIntegerShiftLeftParametersTranslationReceipt,
    StraightLineExactIntegerShiftRightParametersTranslationError,
    StraightLineExactIntegerShiftRightParametersTranslationReceipt,
    StraightLineExactIntegerSubtractParametersTranslationError,
    StraightLineExactIntegerSubtractParametersTranslationReceipt,
    StraightLineIntegerBitwiseAndParametersTranslationError,
    StraightLineIntegerBitwiseAndParametersTranslationReceipt,
    StraightLineIntegerBitwiseNotParameterTranslationError,
    StraightLineIntegerBitwiseNotParameterTranslationReceipt,
    StraightLineIntegerBitwiseOrParametersTranslationError,
    StraightLineIntegerBitwiseOrParametersTranslationReceipt,
    StraightLineIntegerBitwiseXorParametersTranslationError,
    StraightLineIntegerBitwiseXorParametersTranslationReceipt,
    StraightLineIntegerEqualParametersTranslationError,
    StraightLineIntegerEqualParametersTranslationReceipt,
    StraightLineIntegerExactCastParameterTranslationError,
    StraightLineIntegerExactCastParameterTranslationReceipt,
    StraightLineIntegerImmediateTranslationError, StraightLineIntegerImmediateTranslationReceipt,
    StraightLineIntegerLessOrEqualParametersTranslationError,
    StraightLineIntegerLessOrEqualParametersTranslationReceipt,
    StraightLineIntegerLessThanParametersTranslationError,
    StraightLineIntegerLessThanParametersTranslationReceipt,
    StraightLineIntegerParameterTranslationError, StraightLineIntegerParameterTranslationReceipt,
    StraightLineIntegerWidenParameterTranslationError,
    StraightLineIntegerWidenParameterTranslationReceipt,
    StraightLinePortWriteUnitReturnTranslationError,
    StraightLinePortWriteUnitReturnTranslationReceipt,
    StraightLineSaturatingIntegerAddParametersTranslationError,
    StraightLineSaturatingIntegerAddParametersTranslationReceipt,
    StraightLineSaturatingIntegerDivideParametersTranslationError,
    StraightLineSaturatingIntegerDivideParametersTranslationReceipt,
    StraightLineSaturatingIntegerMultiplyParametersTranslationError,
    StraightLineSaturatingIntegerMultiplyParametersTranslationReceipt,
    StraightLineSaturatingIntegerRemainderParametersTranslationError,
    StraightLineSaturatingIntegerRemainderParametersTranslationReceipt,
    StraightLineSaturatingIntegerSubtractParametersTranslationError,
    StraightLineSaturatingIntegerSubtractParametersTranslationReceipt,
    StraightLineScalarCrashTranslationError, StraightLineScalarCrashTranslationReceipt,
    StraightLineTrivialAffineLocalUnitReturnTranslationError,
    StraightLineTrivialAffineLocalUnitReturnTranslationReceipt,
    StraightLineUnitCallReturnTranslationError, StraightLineUnitCallReturnTranslationReceipt,
    StraightLineUnitReturnTranslationError, StraightLineUnitReturnTranslationReceipt,
    StraightLineWrappingIntegerAddParametersTranslationError,
    StraightLineWrappingIntegerAddParametersTranslationReceipt,
    StraightLineWrappingIntegerDivideParametersTranslationError,
    StraightLineWrappingIntegerDivideParametersTranslationReceipt,
    StraightLineWrappingIntegerMultiplyParametersTranslationError,
    StraightLineWrappingIntegerMultiplyParametersTranslationReceipt,
    StraightLineWrappingIntegerRemainderParametersTranslationError,
    StraightLineWrappingIntegerRemainderParametersTranslationReceipt,
    StraightLineWrappingIntegerShiftLeftParametersTranslationError,
    StraightLineWrappingIntegerShiftLeftParametersTranslationReceipt,
    StraightLineWrappingIntegerShiftRightParametersTranslationError,
    StraightLineWrappingIntegerShiftRightParametersTranslationReceipt,
    StraightLineWrappingIntegerSubtractParametersTranslationError,
    StraightLineWrappingIntegerSubtractParametersTranslationReceipt,
    validate_abstract_to_target_translation,
};

#[cfg(test)]
mod tests;
