[package]
name = "omega-machine-instructions"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_machine_instructions"
path = "src/lib.rs"

[dependencies]
omega-assigned-target-operations = { path = "../omega-assigned-target-operations" }
omega-control-flow = { path = "../omega-control-flow" }
psi-arena = { path = "../../../psi/foundation/psi-arena" }
omega-machine-program = { path = "../omega-machine-program" }
omega-target = { path = "../../foundation/omega-target" }
omega-target-operations = { path = "../omega-target-operations" }
