[package]
name = "omega-state-schedule"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_state_schedule"
path = "src/lib.rs"

[dependencies]
psi-checked-trees = { path = "../../../psi/representations/psi-checked-trees" }
omega-control-flow = { path = "../../representations/omega-control-flow" }
psi-arena = { path = "../../../psi/foundation/psi-arena" }
psi-symbols = { path = "../../../psi/foundation/psi-symbols" }
omega-platform-interface = { path = "../omega-platform-interface" }
omega-state-calls = { path = "../omega-state-calls" }
