[package]
name = "omega-target-operations-to-assigned-target-operations"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_target_operations_to_assigned_target_operations"
path = "src/lib.rs"

[dependencies]
omega-calling-conventions = { path = "../../representations/omega-calling-conventions" }
omega-target = { path = "../../representations/omega-target" }
omega-assigned-target-operations = { path = "../../representations/omega-assigned-target-operations" }
omega-target-operations = { path = "../../representations/omega-target-operations" }
psi-core = { path = "../../../psi/foundation/psi-core" }
psi-terminal = { path = "../../../psi/representations/psi-terminal" }
