[package]
name = "omega-effects"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_effects"
path = "src/lib.rs"

[dependencies]
omega-core = { path = "../../foundation/omega-core" }
omega-typed-trees = { path = "../../representations/omega-typed-trees" }
