[package]
name = "omega-machine-program"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_machine_program"
path = "src/lib.rs"

[dependencies]
omega-calling-conventions = { path = "../../backend/omega-calling-conventions" }
omega-core = { path = "../../foundation/omega-core" }
omega-target = { path = "../../backend/omega-target" }
omega-target-operations = { path = "../omega-target-operations" }
