[package]
name = "omega-abstract-operations-to-target-operations"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_abstract_operations_to_target_operations"
path = "src/lib.rs"

[dependencies]
omega-calling-conventions = { path = "../../representations/omega-calling-conventions" }
omega-target = { path = "../../representations/omega-target" }
omega-abstract-operations = { path = "../../representations/omega-abstract-operations" }
omega-installation-evidence = { path = "../../representations/omega-installation-evidence" }
omega-target-operations = { path = "../../representations/omega-target-operations" }
psi-core = { path = "../../../psi/foundation/psi-core" }
psi-terminal = { path = "../../../psi/representations/psi-terminal" }
