[package]
name = "omega-syntax-trees-to-resolved-trees"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_syntax_trees_to_resolved_trees"
path = "src/lib.rs"

[dependencies]
omega-syntax-trees = { path = "../../representations/omega-syntax-trees" }
omega-core = { path = "../../foundation/omega-core" }
omega-resolved-trees = { path = "../../representations/omega-resolved-trees" }

[dev-dependencies]
omega-source-files-to-tokens = { path = "../omega-source-files-to-tokens" }
omega-tokens-to-syntax-trees = { path = "../omega-tokens-to-syntax-trees" }
