[package]
name = "optimization-unit"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "optimization_unit"
path = "src/lib.rs"

[dependencies]
optimization-core = { path = "../optimization-core" }
abstract-operations = { path = "../abstract-operations" }
semantic-vocabulary = { path = "../../../psi/foundation/semantic-vocabulary" }
terminal-psi = { path = "../../../psi/representations/terminal-psi" }
