pub const SOURCE_FEATURE_CATALOG: &str = "omega.omega-self-feature-catalog.v2";

pub const SOURCE_FEATURE_IDS: &[&str] = &[
    "binding.erased",
    "binding.relevance.other",
    "call.acknowledgement.block",
    "call.acknowledgement.suspend",
    "call.acknowledgement.synthesized",
    "call.evidence_argument",
    "call.receiver.expression",
    "call.receiver.free",
    "call.receiver.path",
    "call.static_argument.application",
    "call.static_argument.const",
    "call.static_argument.evidence_projection",
    "call.static_argument.path",
    "contract.crashes",
    "contract.ensures",
    "contract.evidence_binding",
    "contract.requires",
    "data.carry_policy",
    "data.field",
    "data.mixed_record_sum",
    "data.multiplicity.affine",
    "data.multiplicity.linear",
    "data.multiplicity.other",
    "data.multiplicity.unrestricted",
    "data.quotient",
    "data.retired_identity",
    "data.stable_identity",
    "data.supply.checked_shape",
    "data.supply.other",
    "data.variant",
    "data.variant_payload",
    "data.where_fact",
    "expression.array_literal",
    "expression.atomic",
    "expression.binary",
    "expression.binary.add",
    "expression.binary.and",
    "expression.binary.bitwise_and",
    "expression.binary.bitwise_or",
    "expression.binary.bitwise_xor",
    "expression.binary.divide",
    "expression.binary.equal",
    "expression.binary.greater",
    "expression.binary.greater_or_equal",
    "expression.binary.less",
    "expression.binary.less_or_equal",
    "expression.binary.modulo",
    "expression.binary.multiply",
    "expression.binary.not_equal",
    "expression.binary.or",
    "expression.binary.other",
    "expression.binary.shift_left",
    "expression.binary.shift_right",
    "expression.binary.subtract",
    "expression.boolean",
    "expression.borrow",
    "expression.call",
    "expression.cast",
    "expression.cast.domain.exact",
    "expression.cast.domain.other",
    "expression.cast.domain.saturating",
    "expression.cast.domain.trapping",
    "expression.cast.domain.wrapping",
    "expression.cast.form.other",
    "expression.cast.form.recast_mutable",
    "expression.cast.form.recast_shared",
    "expression.cast.form.value",
    "expression.cast.semantic_domain",
    "expression.cast.semantic_domain_argument",
    "expression.float",
    "expression.indexed",
    "expression.integer",
    "expression.member",
    "expression.member.case_payload",
    "expression.membership",
    "expression.name",
    "expression.range",
    "expression.range.end",
    "expression.range.inclusive",
    "expression.range.start",
    "expression.self_value",
    "expression.string",
    "expression.struct_literal",
    "expression.struct_literal.case",
    "expression.unary",
    "expression.unary.bitwise_not",
    "expression.unary.logical_not",
    "expression.unary.other",
    "expression.zero_value",
    "generic.bounds",
    "generic.const_parameter",
    "generic.lifetime_parameter",
    "generic.machine_parameter",
    "generic.parameter_kind.other",
    "generic.proposition_parameter",
    "generic.type_parameter",
    "item.capability",
    "item.conformance",
    "item.const",
    "item.data",
    "item.domain",
    "item.machine",
    "item.measure",
    "item.module",
    "item.operator",
    "item.package",
    "item.platform",
    "item.proposition",
    "item.public",
    "item.target",
    "item.trait",
    "item.use",
    "item.wire_data",
    "machine.attached",
    "machine.blocks",
    "machine.bodyless",
    "machine.boundary",
    "machine.conformance_bound",
    "machine.free",
    "machine.invokes",
    "machine.ranking",
    "machine.ranking.arguments",
    "machine.ranking.range",
    "machine.ranking.subject",
    "machine.ranking.view",
    "machine.satisfies",
    "machine.satisfies.alias",
    "machine.satisfies.arguments",
    "machine.satisfies.requirement",
    "machine.service_reach",
    "machine.service_reach.installation_bound",
    "machine.suspends",
    "machine.target_qualified",
    "machine.terminates",
    "machine.via.compiler_intrinsic",
    "machine.via.dll_import",
    "machine.via.syscall",
    "machine.via.table_function",
    "machine.via.vtable_field",
    "machine.via.vtable_slot",
    "operator.boundary",
    "operator.spelling",
    "proof.fact.expression",
    "proof.fact.membership",
    "state.parameter.const",
    "state.parameter.mutable",
    "state.parameter.self",
    "state.signature.default",
    "state.signature.installation_bound",
    "state.signature.spelling",
    "state.signature.terminates",
    "statement.assembly_fact",
    "statement.assignment",
    "statement.call",
    "statement.call.discards_result",
    "statement.call.receiver_starts_at_self",
    "statement.expression",
    "statement.local_data",
    "statement.local_data.mutable",
    "statement.proof_output_binding",
    "statement.transition",
    "target.boundary_policy",
    "target.boundary_policy.checked",
    "target.boundary_policy.other",
    "target.boundary_policy.unchecked",
    "target.host",
    "target.host.setting.call",
    "target.host.setting.named",
    "trait.boundary",
    "trait.conformance_bound",
    "trait.default_body",
    "trait.parent",
    "trait.requires",
    "transition.aggregate_literal_argument",
    "transition.continuation",
    "transition.crash",
    "transition.evidence_argument",
    "transition.guard.always",
    "transition.guard.when",
    "transition.target.named",
    "transition.target.named.starts_at_self",
    "transition.target.self",
    "transition.target.terminal",
    "transition.target.value",
    "type.const_expression",
    "type.constrained",
    "type.constraint.arithmetic_domain.other",
    "type.constraint.arithmetic_domain.trapping",
    "type.constraint.domain",
    "type.constraint.named",
    "type.constraint.range",
    "type.dynamic_trait",
    "type.fixed_array",
    "type.fixed_array_length.const_call",
    "type.fixed_array_length.const_parameter",
    "type.fixed_array_length.literal",
    "type.generic",
    "type.missing",
    "type.named",
    "type.reference.lifetime",
    "type.reference.mutable",
    "type.reference.other",
    "type.reference.shared",
    "type.self",
    "type.slice",
    "type.unit",
    "wire.field",
    "wire.reserved",
    "wire.version",
];

pub const SOURCE_RESOURCE_IDS: &[(&str, &str, &str)] = &[
    ("binding.string_bytes", "bytes", "per_binding_string"),
    ("call.arguments", "arguments", "per_call"),
    ("call.static_arguments", "arguments", "per_call"),
    ("data.members", "members", "per_data"),
    ("data.variant_payload_fields", "fields", "per_variant"),
    ("expression.array_elements", "elements", "per_literal"),
    ("expression.nesting_depth", "levels", "per_expression_tree"),
    ("expression.string_bytes", "bytes", "per_literal"),
    ("expression.struct_fields", "fields", "per_literal"),
    ("identifier.bytes", "bytes", "per_identifier"),
    ("machine.states", "states", "per_machine"),
    ("path.components", "components", "per_path"),
    ("source.bytes_per_unit", "bytes", "per_source_unit"),
    ("source.bytes_total", "bytes", "per_compilation"),
    ("source.units", "units", "per_compilation"),
    ("state.parameters", "parameters", "per_state"),
    ("state.statements", "statements", "per_state"),
    ("syntax.root_items", "items", "per_compilation"),
    ("transition.arguments", "arguments", "per_transition"),
    ("type.fixed_array_length", "elements", "per_type"),
];
