[package]
name = "resolved-layout-to-resolved-layout"
edition.workspace = true
license.workspace = true
version.workspace = true

[features]
test-support = []

[dependencies]
isa-x86_64 = { path = "../../backend/instruction_set_architectures/isa-x86_64" }
machine-code = { path = "../../representations/machine-code" }
optimization-core = { path = "../../representations/optimization-core" }
physical-instructions = { path = "../../representations/physical-instructions" }
selected-instructions-to-register-homes = { path = "../selected-instructions-to-register-homes" }
register-model = { path = "../../representations/register-model" }
selected-instructions = { path = "../../representations/selected-instructions" }
target = { path = "../../representations/target" }
semantic-vocabulary = { path = "../../../psi/foundation/semantic-vocabulary" }
post-allocation-machine-to-post-allocation-machine = { path = "../post-allocation-machine-to-post-allocation-machine" }
register-homes-to-post-allocation-machine = { path = "../register-homes-to-post-allocation-machine" }
post-allocation-machine-to-selected-form-encoding = { path = "../post-allocation-machine-to-selected-form-encoding" }
selected-form-encoding-to-resolved-layout = { path = "../selected-form-encoding-to-resolved-layout" }
