[package]
name = "omega-packages"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_packages"
path = "src/lib.rs"

[dependencies]
command-group = "5.0.1"
omega-compiler = { path = "../omega-compiler" }
psi-core = { path = "../../../psi/foundation/psi-core" }
psi-diagnostics = { path = "../../../psi/foundation/psi-diagnostics" }
psi-source = { path = "../../../psi/foundation/psi-source" }
psi-source-files-to-tokens = { path = "../../../psi/pipeline/psi-source-files-to-tokens" }
psi-syntax-trees = { path = "../../../psi/representations/psi-syntax-trees" }
psi-tokens = { path = "../../../psi/representations/psi-tokens" }
psi-tokens-to-syntax-trees = { path = "../../../psi/pipeline/psi-tokens-to-syntax-trees" }
sha1-checked = { version = "0.10.0", default-features = false }
sha2 = "0.10.9"

[target.'cfg(unix)'.dependencies]
nix = { version = "0.27", features = ["user"] }
