[package]
name = "psi-source-files-to-tokens"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "psi_source_files_to_tokens"
path = "src/lib.rs"

[dependencies]
psi-source = { path = "../../foundation/psi-source" }
psi-tokens = { path = "../../representations/psi-tokens" }
unicode-ident = "1"
