[package]
name = "omega-platform-custody"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_platform_custody"
path = "src/lib.rs"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Security_Authorization",
    "Win32_System_SystemServices",
    "Win32_System_Threading",
] }
