[package]
name = "omega-terminal-machine-code"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_terminal_machine_code"
path = "src/lib.rs"

[dependencies]
omega-calling-conventions = { path = "../../foundation/omega-calling-conventions" }
omega-target = { path = "../../foundation/omega-target" }
omega-terminal-installation-evidence = { path = "../omega-terminal-installation-evidence" }
omega-terminal-target-operations = { path = "../omega-terminal-target-operations" }
psi-core = { path = "../../../psi-rs/foundation/psi-core" }
psi-terminal = { path = "../../../psi-rs/representations/psi-terminal" }
