//! Checked source trees and their independently established facts.
//!
//! Begin at [`checked_trees`]; validation adds facts to typed trees without
//! replacing them with a second copy of the same source vocabulary.

pub mod checked_trees;

pub use checked_trees::{
    AcceptanceCheck, AcceptanceCheckProvenance, AcceptanceCheckVerdict, AcceptanceDimension,
    AcceptanceSummary, AcceptanceVerdict, AcceptanceView, BlockingFacts, BorrowAccessKind,
    BorrowArgumentAccessFact, BorrowCallCompatibilityOperand, BorrowCallCompatibilitySubject,
    BorrowCallFact, BorrowCompatibilityConclusion, BorrowCompatibilityDerivation,
    BorrowCompatibilityFormation, BorrowCompatibilityPlaceSide, BorrowCompatibilityPremise,
    BorrowCompatibilityPremiseRelation, BorrowCompatibilityPremiseSource,
    BorrowCompatibilitySelectorPosition, BorrowCompatibilitySelectorSnapshot,
    BorrowCompatibilitySelectorValue, BorrowFacts, BorrowLoanFact, BorrowLoanLineage,
    BorrowLoanOwnerSegment, BorrowRootKind, BorrowWritableRootFact,
    BoundaryQualificationAuthorization, BuildBoundProgressDemand, CallAcceptance,
    CallServiceReachRows, CapturedPlace, CapturedPlaceCompatibility, CapturedPlaceContainment,
    CarryFacts, CheckFacts, CheckedAffineConstructionElementPlan, CheckedArithmeticPolicyAdapter,
    CheckedArrayConstructionSource, CheckedBooleanExpression,
    CheckedBorrowCallCompatibilityCertificate, CheckedBorrowCompatibilityCertificate,
    CheckedBorrowMutationCertificate, CheckedBorrowResourceDispositionTarget,
    CheckedBorrowResourceLifecyclePhase, CheckedBoundaryAdapterDispatch,
    CheckedBoundaryMachinePlan, CheckedBoundaryMachineResultPlan,
    CheckedBoundaryOperatorApplicationArgument, CheckedBoundaryOperatorApplicationDemand,
    CheckedBoundaryOperatorApplicationUseSite, CheckedBoundaryScalarReturnMachinePlan,
    CheckedBoundaryScalarReturnPlans, CheckedByteSequenceCarrier, CheckedByteSequenceStoreValue,
    CheckedByteSequenceWritePlan, CheckedCallScalarArgument, CheckedCallbackPlacementIdentity,
    CheckedCallbackResourceReceipt, CheckedClaimFreeAffineStructuralReturnMachinePlan,
    CheckedClosedSumCaseSuccessorPlan, CheckedClosedSumPayloadTransferPlan,
    CheckedComposedUnitControlMachinePlan, CheckedComposedUnitControlStatePlan,
    CheckedComposedUnitControlTerminatorPlan, CheckedContractEntailmentAssumptionDischarge,
    CheckedControlResultPlan, CheckedCrashCallSite, CheckedCrashOperatorSite, CheckedCrashSite,
    CheckedDirectBlockFloatParameter, CheckedDirectBorrowLoanResource,
    CheckedDirectBorrowParentLifetime, CheckedDirectBorrowRestorationObligation,
    CheckedDirectCallFloatResult, CheckedDirectMachineFloatParameter,
    CheckedDirectMachineFloatResult, CheckedDirectOperationFloatResult,
    CheckedDirectStructuralFloatLeaf, CheckedDynamicBinding, CheckedDynamicBindingKind,
    CheckedDynamicDescriptorTransferEdge, CheckedDynamicDescriptorTransferPath,
    CheckedDynamicDescriptorTransferPlan, CheckedDynamicDescriptorTransferSource,
    CheckedDynamicDispatchPlan, CheckedDynamicDispatchPlans, CheckedDynamicJoinBranchPlan,
    CheckedDynamicJoinControlPlan, CheckedDynamicRealizationBodyPlan,
    CheckedDynamicRealizationCallablePlan, CheckedDynamicScalarCallOrigin,
    CheckedDynamicScalarCallPlan, CheckedDynamicScalarHelperPlan, CheckedDynamicSelectionPlan,
    CheckedDynamicStoredDescriptorPlan, CheckedDynamicUnitCallOrigin, CheckedDynamicUnitCallPlan,
    CheckedDynamicUnitContinuationPlan, CheckedEntryResourceEnvelope,
    CheckedErasedProofParameterPlan, CheckedEvidenceInterfaceIdentity, CheckedEvidenceProjection,
    CheckedEvidenceRequirementIdentity, CheckedEvidenceTerm, CheckedFactCallProjection,
    CheckedFloatMeaningEqualityProposition, CheckedFloatMeaningProjection,
    CheckedFloatMeaningProjectionError, CheckedFloatMeaningProjectionOccurrence,
    CheckedFloatMeaningProjectionOccurrenceId, CheckedFloatProjectionContractIdentity,
    CheckedFloatProjectionInput, CheckedFloatProjectionInputId, CheckedFloatProjectionSource,
    CheckedFloatSemanticApplication, CheckedFloatSemanticApplicationError,
    CheckedFloatSemanticApplicationOperand, CheckedFloatUseSite, CheckedFusedServiceErasureReceipt,
    CheckedFusedServiceParameterReceipt, CheckedGuardedJumpPlan, CheckedIeeeFloatComparisonKind,
    CheckedIntegerBinaryKind, CheckedIntegerComparisonKind, CheckedIntegerRange,
    CheckedIntrinsicCallFact, CheckedLocatedProofTerm, CheckedLocatedScalarExpression,
    CheckedMachineContractEnvelopeIdentity, CheckedMachineContractRefinement,
    CheckedMachineResourceEnvelopes, CheckedMathematicalBinder, CheckedMathematicalBinderKind,
    CheckedMathematicalBody, CheckedMathematicalDeclaration, CheckedMathematicalParameter,
    CheckedNamedOperatorUseFact, CheckedNamedRequirementUseFact, CheckedNaturalRankMeasure,
    CheckedNominalAffineUnitCleanupMachinePlan, CheckedNominalAffineUnitCleanupPlans,
    CheckedNominalMachineUse, CheckedOperatorCandidateFact, CheckedOperatorContractUse,
    CheckedOperatorCrashBucket, CheckedOperatorCrashContract, CheckedOperatorFacts,
    CheckedOperatorOccurrence, CheckedOperatorRealizationContract, CheckedOperatorResolutionIssue,
    CheckedOperatorResolutionStatus, CheckedOperatorResolutionSummary, CheckedOperatorUseFact,
    CheckedOperatorUseHandle, CheckedParentBorrowResource,
    CheckedPartialAffineUnitCleanupMachinePlan, CheckedPartialAffineUnitCleanupPlans,
    CheckedPayloadlessCaseReturnMachinePlan, CheckedPayloadlessGuardedCallEvidencePlan,
    CheckedPayloadlessGuardedCallEvidenceUsePlan, CheckedPayloadlessGuardedCallReturnMachinePlan,
    CheckedPlacedViewInput, CheckedPrimitiveStoreDestination, CheckedProofOnlyValueType,
    CheckedProofPropositionId, CheckedProofRankingRelation, CheckedProofRecursiveCallSite,
    CheckedProofRecursiveComponent, CheckedProofRecursiveEdge, CheckedProofRecursiveMember,
    CheckedProofRecursiveTransitionLane, CheckedProofTerm, CheckedProofTermField,
    CheckedProofTermRole, CheckedProofTerms, CheckedProofValueDeclaration, CheckedProofValueId,
    CheckedPropositionApplication, CheckedPropositionBinder, CheckedPropositionBinderArgument,
    CheckedPropositionBinderArgumentKind, CheckedPropositionBinderKind,
    CheckedPropositionDeclaration, CheckedPropositionEvidence, CheckedPropositionVocabulary,
    CheckedProviderAttachmentRequirementPlan, CheckedProviderPlanCommitment,
    CheckedReborrowAccessEffect, CheckedReborrowContainmentCertificate,
    CheckedReborrowContainmentKind, CheckedReborrowLoanResource, CheckedReborrowParentEndStatus,
    CheckedReborrowParentSuspensionBoundary, CheckedReborrowResourceDisposition,
    CheckedReborrowResourceDispositionEvent, CheckedReborrowRestorationObligation,
    CheckedReborrowRestoredCallUseCertificate, CheckedReferenceResultSourcePlan,
    CheckedRequirementCallMachineSelection, CheckedRequirementCallSpecialization,
    CheckedRequirementCallTypeBinding, CheckedResourceAxisAnchor,
    CheckedResourceDerivationObligation, CheckedRetiredParentResourceDispositionStep,
    CheckedReturnPlan, CheckedScalarBinding, CheckedScalarBindingDestination,
    CheckedScalarBindingValue, CheckedScalarBranchDestination, CheckedScalarCaseComputationField,
    CheckedScalarCaseConstruction, CheckedScalarCaseFieldPlan, CheckedScalarComputation,
    CheckedScalarComputationHandle, CheckedScalarComputationKind, CheckedScalarComputationPlans,
    CheckedScalarComputationRoot, CheckedScalarComputationStructuralArgument,
    CheckedScalarDispatchArm, CheckedScalarDispatchPattern, CheckedScalarExpression,
    CheckedScalarExpressionBindings, CheckedScalarExpressionPlans, CheckedScalarExpressionRole,
    CheckedScalarGraphPlans, CheckedScalarGuardedExit, CheckedScalarGuardedTail,
    CheckedScalarMachineGraph, CheckedScalarParameterStorage, CheckedScalarPrimitiveLocalPlan,
    CheckedScalarStateGraph, CheckedScalarStateTerminator, CheckedScalarSuccessor,
    CheckedSelectedFloatComparisonExecution,
    CheckedSelectedOperatorStructuralScalarReturnMachinePlan, CheckedSemanticDependencies,
    CheckedSemanticDependency, CheckedSemanticDependencyExposure, CheckedSemanticDependencyKind,
    CheckedServiceParameterCarrier, CheckedServiceParameterError, CheckedStateNaturalRank,
    CheckedStructuralAccess, CheckedStructuralBooleanConvergencePlan,
    CheckedStructuralByteSequenceFieldByteStorePlan, CheckedStructuralByteSequenceFieldStorePlan,
    CheckedStructuralCallCustodyPlan, CheckedStructuralCallReturnPlans,
    CheckedStructuralCaseReturnPlan, CheckedStructuralControlCleanupPlans,
    CheckedStructuralControlEdgeCleanupPlan, CheckedStructuralControlProjectedEdgeCleanupPlan,
    CheckedStructuralControlProjectedTransferPlan, CheckedStructuralControlStateCleanupPlan,
    CheckedStructuralControlSuccessorPlan, CheckedStructuralControlTransferPlan,
    CheckedStructuralControlTransferSourcePlan, CheckedStructuralDispatchArm,
    CheckedStructuralParameterField, CheckedStructuralPathQualification,
    CheckedStructuralPredicatePathSegment, CheckedStructuralRankedArgumentPlan,
    CheckedStructuralRankedGuardPlan, CheckedStructuralRankedSccEdgePlan,
    CheckedStructuralRankedSccPlan, CheckedStructuralRecordField,
    CheckedStructuralRecordFieldValue, CheckedStructuralResultPlan,
    CheckedStructuralReturnMachinePlan, CheckedStructuralReturnPlans,
    CheckedStructuralReturnedClaimTransferPlan, CheckedStructuralScalarArgumentPlan,
    CheckedStructuralScalarArgumentSourcePlan, CheckedStructuralScalarFieldStoreDestination,
    CheckedStructuralScalarFieldStorePlan, CheckedStructuralScalarFieldStoreValue,
    CheckedStructuralScalarIntegerBoundKind, CheckedStructuralScalarIntegerBoundPlan,
    CheckedStructuralScalarIntegerBoundRequirementPlan, CheckedStructuralScalarParameterPlan,
    CheckedStructuralScalarReturnCleanupAction, CheckedStructuralScalarReturnMachinePlan,
    CheckedStructuralScalarReturnPlans, CheckedStructuralUnitControlMachinePlan,
    CheckedStructuralUnitControlPlans, CheckedStructuralUnitControlStatePlan,
    CheckedStructuralUnitControlTerminatorPlan, CheckedStructuralValue, CheckedStructuralValueCall,
    CheckedStructuralValueHandle, CheckedStructuralValueKind, CheckedStructuralValuePlans,
    CheckedStructuralValueRoot, CheckedSymbolicBoundaryOperatorApplicationArgument,
    CheckedSymbolicBoundaryOperatorApplicationDemand, CheckedTerminalDebugPlans,
    CheckedTerminalMachineDebugPlan, CheckedTerminalMachineSelection,
    CheckedTerminalMachineSelections, CheckedTerminalSignatureEligibility,
    CheckedTerminalStateDebugPlan, CheckedTraitOperatorScalarReturnMachinePlan, CheckedTrees,
    CheckedTrivialAffineStructuralLocalPlan, CheckedUnitCallCoordinate,
    CheckedUnitClaimTransferPlan, CheckedUnitEffectMachinePlan, CheckedUnitEffectOperationPlan,
    CheckedUnitEffectPlans, CheckedUnitEntryClaimPlan,
    CheckedUnitNominalAffineCallerRequirementPlan, CheckedUnitNominalAffineCleanupPlan,
    CheckedUnitNominalAffineCleanupRequirementPlan, CheckedUnitPartialAffineDiscardPlan,
    CheckedUnitPlanOmission, CheckedUnitPlanOmissionStage, CheckedUnitScalarControlPlan,
    CheckedUnitScalarResultBindingPlan, CheckedUnitStructuralArgumentPlan,
    CheckedUnitStructuralArgumentSourcePlan, CheckedUnitStructuralCasePlan,
    CheckedUnitStructuralDomainPlan, CheckedUnitStructuralDomainRequirementPlan,
    CheckedUnitStructuralFieldPlan, CheckedUnitStructuralFieldType,
    CheckedUnitStructuralParameterPlan, CheckedUnitStructuralPathSegment,
    CheckedUnitStructuralResultBindingPlan, CheckedUnitStructuralReturnPlan,
    CheckedUnitStructuralTypePlan, CheckedUnitStructuralTypeShape, CheckedValueFact,
    CheckedValueFacts, CheckedValueHandle, CheckedValueOrigin, CheckedValueStatementRole,
    ClaimCarryPolicyFact, ClosedConformanceConstArgument, ClosedFloatRangeRequirement,
    ClosedIntegerRangeRequirement, ClosedScalarContractValue, ClosedScalarValueContractPlan,
    ContainedMachineFieldFact, ContainedMachineTargetFact, ContentIdentityReshuffleFact,
    ContentPartitionCompositionFact, ContentPartitionInputClaimBinding,
    ContentPartitionPlaceSubstitution, ContentPartitionResultRewrite, ContentProjectionFacts,
    ContractCallFact, ContractEvidenceArgument, ContractExitFact,
    ContractExpressionEvidenceArgumentFact, ContractExpressionEvidenceCallFact,
    ContractExpressionStaticConformanceApplicationFact, ContractOperatorUseFact, ContractProofFact,
    ContractProofFactKind, ContractProofFactOwner, ContractProofFactRef, CrashCallSiteLocation,
    CrashCause, CrashContractCapsule, CrashInterface, CrashPlan, CrashPredicateExpression,
    CrashPredicateIdentity, CrashRouteBucket, CrashRouteBucketId, CrashRouteGuard,
    CrashSiteLocation, DataCarryFact, DomainDependencyFact, DomainDependencyPathFact,
    DomainElementFact, DomainFacts, DynamicConformanceBindingFact, DynamicConformanceBindingFacts,
    DynamicConformanceCandidateFact, DynamicConformanceFacts, DynamicConformanceRowFact,
    DynamicConformanceRowSource, DynamicConformanceSelectionFact, DynamicDescriptorStorageFact,
    EvidenceAssignmentSource, EvidenceForwardingFact, ExitAcceptance, FlowBorrowActivationFact,
    FlowBorrowLifetimeFacts, FlowBorrowWeakeningFact, FlowBorrowWeakeningReason,
    FlowBoundaryEdgeFact, FlowBoundaryFacts, FlowCallFact, FlowClaimJoinAlternative,
    FlowClaimJoinAlternativeSource, FlowClaimJoinExit, FlowClaimJoinExitKind, FlowClaimJoinReceipt,
    FlowClaimOutcomeEntryFact, FlowClaimOutcomeMapFact, FlowClaimOutcomeSource, FlowConstraintKind,
    FlowConstraintRef, FlowContextFacts, FlowControlFacts, FlowExitFact, FlowExitParameterOrigin,
    FlowFacts, FlowInvalidationFact, FlowInvalidationFacts, FlowInvalidationSource,
    FlowOperandReferent, FlowOperatorInvocationFact, FlowOperatorOperandFact,
    FlowOwnedSelectionClaim, FlowOwnedSelectionReceipt, FlowOwnedSelectionSource,
    FlowOwnedSelectionTransfer, FlowOwnershipFacts, FlowPermissionEventFact,
    FlowSemanticContextRef, FlowStateFact, FlowStatementFact, IndexCompatibilityDischarge,
    IndexCompatibilityFact, IndexCompatibilityFacts, InheritedContractScope, LemmaFacts,
    MachineActivationCarryFact, MachineBlockingFact, MachineBuildBoundProgressDemands,
    MachineCarryTopologyFact, MachineContractCommitment, MachineContractIdentity,
    MachineContractPlan, MachineContractPlans, MachineMutationFact, MachineQualifications,
    MachineServiceReachRows, MachineSuspensionFact, MachineSynchronousInvocationFact,
    MachineTerminationFact, MutationFacts, NominalMachineUseFacts, NominalMachineUseSite,
    OperatorAcceptance, OperatorSiteLocation, OutcomeSpecificArmFact, OutcomeSpecificArmRowFact,
    OutcomeSpecificEvidenceInterfaceScopeFact, OutcomeSpecificGuaranteeFact,
    OutcomeSpecificValidityFact, ParentLexicalStatusAtChildEnd, ProgressDemandCallSite,
    ProofFactKind, ProofFacts, ProofLemmaFact, ProofLemmaKind, ProofObligationFact,
    ProofObligationOwner, ProofOutputCallFact, ProofOutputEvidenceArgumentFact, ProofOutputFact,
    ProofOutputRuntimeCallFact, QualificationFacts, QuantifiedBoundFact, QuantifiedRangeFact,
    RealizedMachineContractEnvelope, RequirementCallSpecializationFacts, RetainedBorrowCustodyFact,
    RetiredFlowCall, ServiceReachFacts, StateAcceptance, StateBorrowFact, StateOperationAcceptance,
    StateOperationAcceptanceKind, StateServiceReachRows, StateWriteFramePlan, StatementAcceptance,
    StaticRequirementDispatchFact, SuspensionCrossingCarryFact, SuspensionCrossingLiveValueFact,
    SuspensionCrossingStorage, SuspensionCrossingValueOrigin, SuspensionFacts,
    SynchronousInvocationFacts, TerminationFacts, VacuousQualificationUse, admissibility, borrow,
    byte_predicates, canonical_suspension_crossing_id, contract_identity,
    contract_report_fingerprint, data, domain, expression, facts, finite_family, flow, identity,
    machine, name, operators, proof, proof_only, proposition, ranking, service_parameter,
    signature, state, statement, trait_definition, types, values, wire,
};
/// The identity request a consumer builds when it asks the typed program
/// behind a checked carrier for a binder-aware type identity.
pub use typed_trees::type_identity::TypeIdentityRequest;
