use super::{
    dynamic, dynamic_argument, foreign_call, installed_provider, scalar_call, structural_result,
    structural_scalar,
};
use crate::assignment::shared::*;

mod boundary_settlement;
mod call;
mod conditional;
mod ieee_float;
mod structural_case;

pub(super) fn assign(
    machine: MachineId,
    attachment: Option<semantic_vocabulary::StructuralTypeId>,
    body: &target_operations::TargetUnitBody,
    operation: &TargetUnitOperation,
    preceding_operations: &[TargetUnitOperation],
    preceding_assigned_operations: &[AssignedUnitOperation],
    target: NativeTarget,
    native_callback: Option<&target_operations::TargetNativeCallbackArgument>,
    assigned_scalar_homes: &mut BTreeMap<ValueId, AssignedUnitScalarHome>,
    assigned_structural_homes: &mut BTreeMap<PlaceId, AssignedStructuralHome>,
    next_frame_home: &mut u32,
) -> Result<AssignedUnitOperation, AssignmentError> {
    Ok(match operation {
        TargetUnitOperation::EstablishByteSequenceLiteral {
            psi_operation,
            place,
            structural_type,
            bytes,
        } => AssignedUnitOperation::EstablishByteSequenceLiteral {
            psi_operation: *psi_operation,
            place: *place,
            structural_type: structural_type.clone(),
            bytes: bytes.clone(),
        },
        TargetUnitOperation::IntegerConstant {
            psi_operation,
            result,
            scalar_type,
            value,
        } => AssignedUnitOperation::IntegerConstant {
            psi_operation: *psi_operation,
            result: *result,
            scalar_type: *scalar_type,
            value: *value,
        },
        TargetUnitOperation::BooleanConstant {
            psi_operation,
            result,
            value,
        } => AssignedUnitOperation::BooleanConstant {
            psi_operation: *psi_operation,
            result: *result,
            value: *value,
        },
        TargetUnitOperation::WriteOnlyPrimitiveStore {
            psi_operation,
            destination,
            destination_type,
            destination_placement,
            source,
        } => super::write_only_primitive_store::assign(
            machine,
            body,
            *psi_operation,
            destination,
            destination_type,
            destination_placement,
            *source,
            preceding_operations,
            preceding_assigned_operations,
            target,
        )?,
        TargetUnitOperation::StructuralScalarFieldStore {
            psi_operation,
            destination,
            path,
            field,
            destination_placement,
            field_byte_offset,
            source,
        } => structural_scalar::assign_field_store(
            machine,
            attachment,
            body,
            *psi_operation,
            destination,
            path,
            *field,
            destination_placement,
            *field_byte_offset,
            *source,
            preceding_operations,
            preceding_assigned_operations,
            target,
        )?,
        TargetUnitOperation::IeeeFloatConstant {
            psi_operation,
            result,
            value,
        } => AssignedUnitOperation::IeeeFloatConstant {
            psi_operation: *psi_operation,
            result: *result,
            value: *value,
        },
        TargetUnitOperation::NearestIeeeFloatFusedMultiplyAdd { .. } => {
            ieee_float::assign_fused_multiply_add(machine, operation, preceding_operations, target)?
        }
        TargetUnitOperation::EstablishTrivialAffineLocal {
            psi_operation,
            place,
            structural_type,
        } => AssignedUnitOperation::EstablishTrivialAffineLocal {
            psi_operation: *psi_operation,
            place: *place,
            structural_type: structural_type.clone(),
        },
        TargetUnitOperation::EstablishAffineScalarRecord {
            psi_operation,
            result,
            field,
            value,
            shape,
        } => AssignedUnitOperation::EstablishAffineScalarRecord {
            psi_operation: *psi_operation,
            result: result.clone(),
            field: *field,
            value: *value,
            shape: *shape,
        },
        TargetUnitOperation::Call { .. } => call::assign(
            machine,
            body,
            operation,
            preceding_operations,
            assigned_scalar_homes,
            target,
        )?,
        TargetUnitOperation::ScalarCall {
            psi_operation,
            callee,
            call_plan,
            result_home,
            arguments,
            requirement_obligations,
            crash_continuations,
        } => scalar_call::assign(
            machine,
            *psi_operation,
            *callee,
            call_plan,
            *result_home,
            arguments,
            requirement_obligations,
            crash_continuations,
            preceding_operations,
            target,
            assigned_scalar_homes,
            next_frame_home,
        )?,
        TargetUnitOperation::StructuralScalarCall {
            psi_operation,
            result,
            callee,
            call_plan,
            scalar_arguments,
            arguments,
            claim_transfers,
            requirement_obligations,
            crash_continuations,
        } => structural_scalar::assign_call(
            machine,
            attachment,
            body,
            target,
            *psi_operation,
            *result,
            *callee,
            call_plan,
            scalar_arguments,
            arguments,
            claim_transfers,
            requirement_obligations,
            crash_continuations,
            preceding_operations,
            assigned_scalar_homes,
        )?,
        TargetUnitOperation::StructuralResultCall {
            psi_operation,
            result,
            callee,
            callee_result,
            call_plan,
            scalar_arguments,
            arguments,
            claim_transfers,
            returned_claim_transfers,
            requirement_obligations,
            crash_continuations,
        } => structural_result::assign_result_call(
            machine,
            attachment,
            body,
            target,
            *psi_operation,
            result,
            *callee,
            callee_result,
            call_plan,
            scalar_arguments,
            arguments,
            claim_transfers,
            returned_claim_transfers,
            requirement_obligations,
            crash_continuations,
            preceding_operations,
            assigned_scalar_homes,
        )?,
        TargetUnitOperation::StructuralScalarCallWithDynamicArguments {
            psi_operation,
            result,
            callee,
            call_plan,
            result_home,
            structural_arguments,
            dynamic_arguments,
            claim_transfers,
            requirement_obligations,
            crash_continuations,
        } => dynamic_argument::assign(
            machine,
            body,
            target,
            *psi_operation,
            Some(*result),
            *callee,
            call_plan,
            Some(*result_home),
            structural_arguments,
            dynamic_arguments,
            claim_transfers,
            requirement_obligations,
            crash_continuations,
            assigned_scalar_homes,
            next_frame_home,
        )?,
        TargetUnitOperation::StructuralUnitCallWithDynamicArguments {
            psi_operation,
            callee,
            call_plan,
            structural_arguments,
            dynamic_arguments,
            claim_transfers,
            requirement_obligations,
            crash_continuations,
        } => dynamic_argument::assign(
            machine,
            body,
            target,
            *psi_operation,
            None,
            *callee,
            call_plan,
            None,
            structural_arguments,
            dynamic_arguments,
            claim_transfers,
            requirement_obligations,
            crash_continuations,
            assigned_scalar_homes,
            next_frame_home,
        )?,
        TargetUnitOperation::StoreDynamicDescriptor {
            psi_operation,
            stored,
            source_argument,
        } => dynamic::assign_stored_descriptor(
            machine,
            target,
            *psi_operation,
            stored,
            source_argument,
            next_frame_home,
        )?,
        TargetUnitOperation::StoredDynamicScalarCall {
            psi_operation,
            result,
            dynamic_dispatch,
            call_plan,
            result_home,
            source_argument,
            requirement_obligations,
            crash_continuations,
        } => dynamic::assign_stored_scalar_call(
            machine,
            target,
            *psi_operation,
            *result,
            dynamic_dispatch,
            call_plan,
            *result_home,
            source_argument,
            requirement_obligations,
            crash_continuations,
            preceding_assigned_operations,
            assigned_scalar_homes,
            next_frame_home,
        )?,
        TargetUnitOperation::DynamicScalarCall {
            psi_operation,
            result,
            dynamic_dispatch,
            call_plan,
            result_home,
            initial_argument,
            rebound_argument,
            requirement_obligations,
            crash_continuations,
        } => dynamic::assign(
            machine,
            target,
            *psi_operation,
            *result,
            dynamic_dispatch,
            call_plan,
            *result_home,
            initial_argument,
            rebound_argument,
            requirement_obligations,
            crash_continuations,
            assigned_scalar_homes,
            next_frame_home,
        )?,
        TargetUnitOperation::DynamicUnitCall {
            psi_operation,
            dynamic_dispatch,
            call_plan,
            initial_argument,
            rebound_argument,
            requirement_obligations,
            crash_continuations,
        } => dynamic::assign_unit(
            machine,
            target,
            *psi_operation,
            dynamic_dispatch,
            call_plan,
            initial_argument,
            rebound_argument,
            requirement_obligations,
            crash_continuations,
            next_frame_home,
        )?,
        TargetUnitOperation::StructuralCase { .. } => structural_case::assign(
            machine,
            body,
            operation,
            preceding_operations,
            assigned_scalar_homes,
            assigned_structural_homes,
        )?,
        TargetUnitOperation::ConditionalIntegerEqual { .. }
        | TargetUnitOperation::ConditionalBoolean { .. }
        | TargetUnitOperation::ConditionalBooleanParameter { .. }
        | TargetUnitOperation::ConditionalDispatch { .. }
        | TargetUnitOperation::NonreturningTail { .. } => conditional::assign(
            operation,
            body,
            preceding_operations,
            target,
            assigned_scalar_homes,
        )?,
        TargetUnitOperation::InstalledProviderCall {
            psi_operation,
            boundary,
            provider,
            call_plan,
            scalar_arguments,
            source_arguments,
            arguments,
            claim_transfers,
            completion_claim_sources,
            completion_receipts,
        } => {
            if scalar_arguments.is_empty() {
                return Err(
                    AssignmentError::InstalledProviderCallRequiresOptimizedLane {
                        machine,
                        operation: *psi_operation,
                        boundary: *boundary,
                    },
                );
            }
            installed_provider::assign(
                machine,
                body,
                target,
                *psi_operation,
                *boundary,
                provider,
                call_plan,
                scalar_arguments,
                source_arguments,
                arguments,
                claim_transfers,
                completion_claim_sources,
                completion_receipts,
            )?
        }
        TargetUnitOperation::NormalizedForeignCall {
            psi_operation,
            boundary,
            provider_execution,
            binding,
            scalar_arguments,
            result_home,
        } => {
            let (scalar_arguments, result_home) = foreign_call::assign(
                *psi_operation,
                binding,
                target,
                scalar_arguments,
                *result_home,
                preceding_operations,
                native_callback,
                assigned_scalar_homes,
                next_frame_home,
            )?;
            AssignedUnitOperation::NormalizedForeignCall {
                psi_operation: *psi_operation,
                boundary: *boundary,
                provider_execution: *provider_execution,
                binding: binding.clone(),
                scalar_arguments,
                result_home,
            }
        }
        TargetUnitOperation::PortWrite {
            psi_operation,
            service,
            port,
            value,
        } => AssignedUnitOperation::PortWrite {
            psi_operation: *psi_operation,
            service: *service,
            port: *port,
            value: *value,
        },
        TargetUnitOperation::BoundarySettlement {
            psi_operation,
            boundary,
            result,
            execution,
            realization,
            scalar_arguments,
            runtime_scalar_arguments,
            arguments,
            byte_sequence_arguments,
            completion_claim_sources,
            completion_receipts,
        } => AssignedUnitOperation::BoundarySettlement {
            psi_operation: *psi_operation,
            boundary: *boundary,
            result: boundary_settlement::assign_result(
                *psi_operation,
                result,
                assigned_structural_homes,
                next_frame_home,
            )?,
            execution: *execution,
            realization: *realization,
            scalar_arguments: scalar_arguments.clone(),
            runtime_scalar_arguments: boundary_settlement::assign_runtime_scalar_arguments(
                target,
                runtime_scalar_arguments,
                preceding_operations,
                assigned_scalar_homes,
            )?,
            arguments: arguments.clone(),
            byte_sequence_arguments: byte_sequence_arguments.clone(),
            completion_claim_sources: completion_claim_sources.clone(),
            completion_receipts: completion_receipts.clone(),
        },
        TargetUnitOperation::Return {
            psi_edge,
            cleanup_actions,
        } => AssignedUnitOperation::Return {
            psi_edge: *psi_edge,
            cleanup_actions: cleanup_actions.clone(),
        },
    })
}
