[package]
name = "object-file"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "object_file"
path = "src/lib.rs"

[dependencies]
machine-emission = { path = "../../machine-emission" }
terminal-psi-to-abstract-operations = { path = "../../../pipeline/terminal-psi-to-abstract-operations" }
terminal-codec = { path = "../../../../psi/semantics/terminal-codec" }
machine-code = { path = "../../../representations/machine-code" }
core = { path = "../../../representations/core" }
function-identity = { path = "../../../representations/function-identity" }
optimization-core = { path = "../../../representations/optimization-core" }
selected-instructions = { path = "../../../representations/selected-instructions" }
arena = { path = "../../../../psi/foundation/arena" }
semantic-vocabulary = { path = "../../../../psi/foundation/semantic-vocabulary" }
terminal-psi = { path = "../../../../psi/representations/terminal-psi" }
target = { path = "../../../representations/target" }
sha2 = "0.10.9"

[features]
test-support = ["machine-emission/test-support"]
