#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct MachineInstruction {
    pub selected_instruction_index: u32,
    pub kind: MachineInstructionKind,
}

impl Default for MachineInstruction {
    fn default() -> Self {
        Self {
            selected_instruction_index: 0,
            kind: MachineInstructionKind::NoOp,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MachineInstructionKind {
    NoOp,
    DispatchLoopEnter,
    DispatchCaseEnter,
    DispatchGuardCompareStatic,
    RuntimeTextLiteralCompare,
    RuntimeTextStorageCompare,
    RuntimeStorageCompare,
    RuntimeStorageValueCompare,
    RuntimeTextLiteralWrite,
    RuntimeTextLiteralSegmentWrite,
    RuntimeTextStoredSuffixAppend,
    RuntimeTextBufferMaterialize,
    RuntimeTextBufferMaterializeToRuntimePointee,
    RuntimeTextBufferMaterializeToRuntimeFrameIndexed,
    RuntimeTextStoredPlaceAppend,
    RuntimeTextStoredPlaceAppendToRuntimePointee,
    RuntimeTextStoredPlaceAppendToRuntimeFrameIndexed,
    RuntimeTextLiteralAppend,
    RuntimeTextLiteralAppendToRuntimePointee,
    RuntimeTextLiteralAppendToRuntimeFrameIndexed,
    RuntimeMachineIntegerWrite,
    RuntimePointeeIntegerWrite,
    RuntimeStorageBinaryWrite,
    RuntimeStorageConvert,
    AtomicFetchAdd,
    AtomicCompareExchange,
    RuntimePointeeBinaryWrite,
    RuntimeFrameIndexedIntegerWrite,
    RuntimeFrameBaseIndexedIntegerWrite,
    RuntimeMachineIndexedIntegerWrite,
    WireLiteralByteAppend,
    WireScalarVarintAppend,
    WireTextBytesAppend,
    WireExpectedByteRead,
    WireScalarVarintRead,
    WireByteSliceRead,
    WireNestedOpenRead,
    WireNestedCloseRead,
    WireRepeatedScalarVarintAppend,
    WireRepeatedScalarVarintRead,
    RuntimeFrameIndexedBinaryWrite,
    RuntimeFrameBaseIndexedBinaryWrite,
    RuntimeMachineIndexedBinaryWrite,
    RuntimeMachineStringWrite,
    RuntimeMachineBoundedBufferWrite,
    RuntimeMachineBoundedBufferSourceAppend,
    RuntimeMachineBoundedBufferLiteralAppend,
    RuntimePointeeBoundedBufferWrite,
    RuntimeFrameStringWrite,
    RuntimePointeeStringWrite,
    RuntimeFrameIndexedStringWrite,
    RuntimeMachineIndexedStringWrite,
    RuntimeStorageAddressToRuntimeFrameWrite,
    RuntimePointeeAddressToRuntimeFrameWrite,
    RuntimeFrameIndexedAddressToRuntimeFrameWrite,
    RuntimeFrameFixedIndexedAddressToRuntimeFrameWrite,
    RuntimeFrameBaseIndexedAddressToRuntimeFrameWrite,
    RuntimeTextLineRead,
    RuntimeStorageCopy,
    RuntimeStorageCopyToRuntimeFrameIndexed,
    RuntimeStorageCopyFromRuntimeFrameIndexed,
    RuntimeStorageCopyFromRuntimeFrameFixedIndexed,
    RuntimeStorageCopyFromRuntimeFrameFixedIndexedToRuntimePointee,
    RuntimeStorageCopyFromRuntimeFrameIndexedToRuntimePointee,
    RuntimeStorageCopyFromRuntimeMachineIndexed,
    RuntimeStorageCopyToRuntimeMachineIndexed,
    RuntimeStorageCopyMachineIndexedToMachineIndexed,
    RuntimeStorageCopyToRuntimePointee,
    RuntimeStorageCopyFromRuntimePointeeToRuntimeFrame,
    DispatchStateWrite,
    ReturnRegisterIntegerWrite,
    RuntimeStorageCopyToReturnRegister,
    /// Entry prologue: store an incoming argument register into the entry
    /// parameter's frame slot (the calling plan's inbound direction).
    EntryArgumentRegisterWrite,
    /// Entry prologue: bind `args: &[u8]` as a slice descriptor over the
    /// entry-argument spill.
    EntryArgumentsSliceDescriptorWrite,
    DispatchTerminate,
    DispatchCaseLeave,
    HostCallSequence,
    Return,
}
