[package]
name = "omega-compiler"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_compiler"
path = "src/lib.rs"

[dependencies]
omega-artifacts = { path = "../omega-artifacts" }
omega-core = { path = "../../foundation/omega-core" }
omega-abstract-syntax-tree = { path = "../../frontend/omega-abstract-syntax-tree" }
omega-abstract-syntax-to-typed = { path = "../../lowering/omega-abstract-syntax-to-typed" }
omega-calling-conventions = { path = "../../backend/omega-calling-conventions" }
omega-control-flow = { path = "../../representations/omega-control-flow" }
omega-emission-planning = { path = "../../backend/omega-emission-planning" }
omega-effects = { path = "../../semantics/omega-effects" }
omega-graph = { path = "../../semantics/omega-graph" }
omega-image = { path = "../../backend/images/omega-image" }
omega-image-emission = { path = "../../backend/images/omega-image-emission" }
omega-lexer = { path = "../../frontend/omega-lexer" }
omega-layout = { path = "../../backend/omega-layout" }
omega-machine-program = { path = "../../representations/omega-machine-program" }
omega-native = { path = "../../backend/omega-native" }
omega-native-report = { path = "../../backend/omega-native-report" }
omega-object = { path = "../../backend/object/omega-object" }
omega-parser = { path = "../../frontend/omega-parser" }
omega-platform-interface = { path = "../../backend/omega-platform-interface" }
omega-proof = { path = "../../semantics/omega-proof" }
omega-names = { path = "../../semantics/omega-names" }
omega-state-graph = { path = "../../representations/omega-state-graph" }
omega-target = { path = "../../backend/omega-target" }
omega-target-program = { path = "../../representations/omega-target-program" }
omega-typed-to-control-flow = { path = "../../lowering/omega-typed-to-control-flow" }
omega-typed-program = { path = "../../representations/omega-typed-program" }
omega-types = { path = "../../semantics/omega-types" }
omega-validation = { path = "../../semantics/omega-validation" }
