[package]
name = "omega-state-calls"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_state_calls"
path = "src/lib.rs"

[dependencies]
omega-checked-trees = { path = "../../representations/omega-checked-trees" }
omega-control-flow = { path = "../../representations/omega-control-flow" }
omega-core = { path = "../../foundation/omega-core" }
omega-platform-interface = { path = "../omega-platform-interface" }
omega-state-graph = { path = "../../representations/omega-state-graph" }

[dev-dependencies]
omega-calling-conventions = { path = "../../foundation/omega-calling-conventions" }
omega-checked-trees-to-state-graph = { path = "../../pipeline/omega-checked-trees-to-state-graph" }
omega-platform-interface = { path = "../omega-platform-interface" }
omega-symbol-resolved-trees-to-typed-trees = { path = "../../pipeline/omega-symbol-resolved-trees-to-typed-trees" }
omega-source-files-to-tokens = { path = "../../pipeline/omega-source-files-to-tokens" }
omega-state-graph-to-control-flow = { path = "../../pipeline/omega-state-graph-to-control-flow" }
omega-syntax-trees-to-symbol-resolved-trees = { path = "../../pipeline/omega-syntax-trees-to-symbol-resolved-trees" }
omega-target = { path = "../../foundation/omega-target" }
omega-tokens-to-syntax-trees = { path = "../../pipeline/omega-tokens-to-syntax-trees" }
omega-typed-trees-to-checked-trees = { path = "../../pipeline/omega-typed-trees-to-checked-trees" }
