[package]
name = "syntax-trees"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "syntax_trees"
path = "src/lib.rs"

[dependencies]
arena = { path = "../../foundation/arena" }
diagnostics = { path = "../../foundation/diagnostics" }
language-core = { path = "../../foundation/language-core" }
numerics = { path = "../../foundation/numerics" }
source = { path = "../../foundation/source" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
