[package]
name = "omega-build-output"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_build_output"
path = "src/lib.rs"

[dependencies]
psi-checked-interpreter = { path = "../../../psi/semantics/psi-checked-interpreter" }
psi-diagnostics = { path = "../../../psi/foundation/psi-diagnostics" }
sha2 = "0.10.9"
