[package]
name = "psi-access-plans"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "psi_access_plans"
path = "src/lib.rs"

[dependencies]
psi-extents = { path = "../psi-extents" }
psi-language-core = { path = "../psi-language-core" }
psi-layout-plans = { path = "../psi-layout-plans" }
