[package]
name = "psi-syntax-trees-to-symbol-resolved-trees"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "psi_syntax_trees_to_symbol_resolved_trees"
path = "src/lib.rs"

[dependencies]
psi-arena = { path = "../../foundation/psi-arena" }
psi-diagnostics = { path = "../../foundation/psi-diagnostics" }
psi-language-semantics = { path = "../../foundation/psi-language-semantics" }
psi-numerics = { path = "../../foundation/psi-numerics" }
psi-source = { path = "../../foundation/psi-source" }
psi-symbols = { path = "../../foundation/psi-symbols" }
psi-syntax-trees = { path = "../../representations/psi-syntax-trees" }
psi-symbol-resolved-trees = { path = "../../representations/psi-symbol-resolved-trees" }

[dev-dependencies]
psi-source-files-to-tokens = { path = "../psi-source-files-to-tokens" }
psi-tokens-to-syntax-trees = { path = "../psi-tokens-to-syntax-trees" }
