[package]
name = "omega-terminal-isa-x86_64"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_terminal_isa_x86_64"
path = "src/lib.rs"

[dependencies]
omega-calling-conventions = { path = "../../../foundation/omega-calling-conventions" }
omega-register-model = { path = "../../../representations/omega-register-model" }
omega-target = { path = "../../../foundation/omega-target" }
omega-terminal-installation-evidence = { path = "../../../representations/omega-terminal-installation-evidence" }
omega-terminal-selected-instructions = { path = "../../../representations/omega-terminal-selected-instructions" }
psi-core = { path = "../../../../psi/foundation/psi-core" }
psi-diagnostics = { path = "../../../../psi/foundation/psi-diagnostics" }

[dev-dependencies]
omega-optimization-core = { path = "../../../foundation/omega-optimization-core" }
