[package]
name = "omega-isa-aarch64"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_isa_aarch64"
path = "src/lib.rs"

[dependencies]
omega-calling-conventions = { path = "../../../foundation/omega-calling-conventions" }
omega-core = { path = "../../../foundation/omega-core" }
psi-layout-plans = { path = "../../../../psi-rs/foundation/psi-layout-plans" }
omega-target-operations = { path = "../../../representations/omega-target-operations" }
