//! Reconstructs atomic, place, and storage instruction specifications.

use super::*;

pub(super) fn expected_storage_place_spec(
    architecture: Architecture,
    code: &omega_machine_bytes::EncodedMachineCode,
    kind: omega_machine_bytes::CompilerInstructionValidationKind,
) -> Result<Option<CompilerInstructionSpec>, Diagnostic> {
    let spec: CompilerInstructionSpec = match kind {
                    omega_machine_bytes::CompilerInstructionValidationKind::CompilerBodyAtomic(
                        operation,
                    ) => {
                        let (bytes, validation_tag, address_sites) =
                            replay_compiler_atomic_operation(
                                architecture,
                                &code.runtime_value_operands,
                                operation,
                            )?;
                        (
                            None,
                            bytes,
                            validation_tag,
                            CompilerInstructionRelocationRecipe::DataAddressSites {
                                address_sites,
                            },
                        )
                    }
                    omega_machine_bytes::CompilerInstructionValidationKind::ExitIndirectResultCopy {
                        source,
                        target,
                        byte_count,
                    } => {
                        let (source_offset, pointer_byte_offset) =
                            compiler_exit_indirect_result_copy_offsets(&source, &target)?;
                        (
                            None,
                            match architecture {
                                Architecture::X86_64 => omega_isa_x86_64::encode_copy_places(
                                    &source,
                                    &target,
                                    byte_count,
                                )?
                                .0,
                                Architecture::Aarch64 => omega_isa_aarch64::encode_runtime_storage_copy_to_runtime_pointee(
                                    source_offset,
                                    pointer_byte_offset,
                                    0,
                                    byte_count,
                                )?,
                            },
                            20u8,
                            CompilerInstructionRelocationRecipe::PlaceCopy {
                                source,
                                target,
                                byte_count,
                            },
                        )
                    }
                    omega_machine_bytes::CompilerInstructionValidationKind::CompilerBodyPlaceCopy {
                        source,
                        target,
                        byte_count,
                    } => {
                        let shape = compiler_body_place_copy_shape(&source, &target)?;
                        (
                            None,
                            match architecture {
                                Architecture::X86_64 => omega_isa_x86_64::encode_copy_places(
                                    &source,
                                    &target,
                                    byte_count,
                                )?
                                .0,
                                Architecture::Aarch64 => match shape {
                                    CompilerBodyPlaceCopyShape::Direct {
                                        source_offset,
                                        target_offset,
                                    } => omega_isa_aarch64::encode_runtime_storage_copy(
                                        source_offset,
                                        target_offset,
                                        byte_count,
                                    )?,
                                    CompilerBodyPlaceCopyShape::ToPointee {
                                        source_offset,
                                        pointer_byte_offset,
                                        field_byte_offset,
                                    } => omega_isa_aarch64::encode_runtime_storage_copy_to_runtime_pointee(
                                        source_offset,
                                        pointer_byte_offset,
                                        field_byte_offset,
                                        byte_count,
                                    )?,
                                    CompilerBodyPlaceCopyShape::FromPointee {
                                        pointer_byte_offset,
                                        field_byte_offset,
                                        target_offset,
                                    } => omega_isa_aarch64::encode_runtime_storage_copy_from_runtime_pointee_to_runtime_frame(
                                        pointer_byte_offset,
                                        field_byte_offset,
                                        target_offset,
                                        byte_count,
                                    )?,
                                    CompilerBodyPlaceCopyShape::FromPointeeDoubleIndexed {
                                        descriptor_offset,
                                        outer_index_region,
                                        outer_index_offset,
                                        outer_index_byte_size,
                                        outer_stride,
                                        inner_index_region,
                                        inner_index_offset,
                                        inner_index_byte_size,
                                        inner_stride,
                                        field_byte_offset,
                                        target_offset,
                                    } => omega_isa_aarch64::encode_runtime_storage_copy_from_runtime_pointee_double_indexed_to_runtime_storage(
                                        descriptor_offset,
                                        outer_index_region,
                                        outer_index_offset,
                                        outer_index_byte_size,
                                        outer_stride,
                                        inner_index_region,
                                        inner_index_offset,
                                        inner_index_byte_size,
                                        inner_stride,
                                        field_byte_offset,
                                        target.region,
                                        target_offset,
                                        byte_count,
                                    )?,
                                    CompilerBodyPlaceCopyShape::PointeePair {
                                        source_pointer_byte_offset,
                                        source_field_byte_offset,
                                        target_pointer_byte_offset,
                                        target_field_byte_offset,
                                    } => omega_isa_aarch64::encode_runtime_storage_copy_from_runtime_frame_fixed_indexed_to_runtime_pointee(
                                        source_pointer_byte_offset,
                                        0,
                                        1,
                                        source_field_byte_offset,
                                        target_pointer_byte_offset,
                                        target_field_byte_offset,
                                        byte_count,
                                    )?,
                                    CompilerBodyPlaceCopyShape::FromIndexed {
                                        descriptor_offset,
                                        index_region,
                                        index_offset,
                                        index_byte_size,
                                        element_byte_size,
                                        field_byte_offset,
                                        target_offset,
                                    } => match target.region {
                                        omega_target_operations::RuntimeStorageRegion::RuntimeFrame => omega_isa_aarch64::encode_runtime_storage_copy_from_runtime_frame_indexed_with_index_region(
                                            descriptor_offset,
                                            index_region,
                                            index_offset,
                                            index_byte_size,
                                            element_byte_size,
                                            field_byte_offset,
                                            target_offset,
                                            byte_count,
                                        )?,
                                        omega_target_operations::RuntimeStorageRegion::Machine => omega_isa_aarch64::encode_runtime_storage_copy_from_runtime_frame_indexed_to_runtime_storage_with_index_region(
                                            descriptor_offset,
                                            index_region,
                                            index_offset,
                                            index_byte_size,
                                            element_byte_size,
                                            field_byte_offset,
                                            target_offset,
                                            byte_count,
                                        )?,
                                    },
                                    CompilerBodyPlaceCopyShape::ToIndexed {
                                        source_offset,
                                        descriptor_offset,
                                        index_offset,
                                        index_byte_size,
                                        element_byte_size,
                                        field_byte_offset,
                                    } => omega_isa_aarch64::encode_runtime_storage_copy_to_runtime_frame_indexed(
                                        source_offset,
                                        descriptor_offset,
                                        index_offset,
                                        index_byte_size,
                                        element_byte_size,
                                        field_byte_offset,
                                        byte_count,
                                    )?,
                                    CompilerBodyPlaceCopyShape::ToIndexedByRegion {
                                        source_offset,
                                        descriptor_offset,
                                        index_region,
                                        index_offset,
                                        index_byte_size,
                                        element_byte_size,
                                        field_byte_offset,
                                    } => omega_isa_aarch64::encode_runtime_storage_copy_to_runtime_frame_indexed_with_regions(
                                        source.region,
                                        source_offset,
                                        descriptor_offset,
                                        index_region,
                                        index_offset,
                                        index_byte_size,
                                        element_byte_size,
                                        field_byte_offset,
                                        byte_count,
                                    )?,
                                    CompilerBodyPlaceCopyShape::IndexedToPointee {
                                        descriptor_offset,
                                        index_offset,
                                        index_byte_size,
                                        element_byte_size,
                                        source_field_byte_offset,
                                        pointer_byte_offset,
                                        target_field_byte_offset,
                                    } => omega_isa_aarch64::encode_runtime_storage_copy_from_runtime_frame_indexed_to_runtime_pointee(
                                        descriptor_offset,
                                        index_offset,
                                        index_byte_size,
                                        element_byte_size,
                                        source_field_byte_offset,
                                        pointer_byte_offset,
                                        target_field_byte_offset,
                                        byte_count,
                                    )?,
                                    CompilerBodyPlaceCopyShape::IndexedToPointeeByRegion {
                                        descriptor_offset,
                                        index_region,
                                        index_offset,
                                        index_byte_size,
                                        element_byte_size,
                                        source_field_byte_offset,
                                        pointer_byte_offset,
                                        target_field_byte_offset,
                                    } => omega_isa_aarch64::encode_runtime_storage_copy_from_runtime_frame_indexed_to_runtime_pointee_with_index_region(
                                        descriptor_offset,
                                        index_region,
                                        index_offset,
                                        index_byte_size,
                                        element_byte_size,
                                        source_field_byte_offset,
                                        pointer_byte_offset,
                                        target_field_byte_offset,
                                        byte_count,
                                    )?,
                                    CompilerBodyPlaceCopyShape::FromFrameBaseIndexed {
                                        base_byte_offset,
                                        index_offset,
                                        index_byte_size,
                                        element_byte_size,
                                        field_byte_offset,
                                        target_offset,
                                    } => omega_isa_aarch64::encode_runtime_storage_copy_from_runtime_frame_base_indexed_to_runtime_frame(
                                        base_byte_offset,
                                        index_offset,
                                        index_byte_size,
                                        element_byte_size,
                                        field_byte_offset,
                                        target_offset,
                                        byte_count,
                                    )?,
                                    CompilerBodyPlaceCopyShape::ToFrameBaseIndexed {
                                        source_offset,
                                        base_byte_offset,
                                        index_region,
                                        index_offset,
                                        index_byte_size,
                                        element_byte_size,
                                        field_byte_offset,
                                    } => omega_isa_aarch64::encode_runtime_storage_copy_to_runtime_frame_base_indexed_from_runtime_storage(
                                        source.region,
                                        source_offset,
                                        base_byte_offset,
                                        index_region,
                                        index_offset,
                                        index_byte_size,
                                        element_byte_size,
                                        field_byte_offset,
                                        byte_count,
                                    )?,
                                    CompilerBodyPlaceCopyShape::FrameBaseIndexedToPointee {
                                        base_byte_offset,
                                        index_region,
                                        index_offset,
                                        index_byte_size,
                                        element_byte_size,
                                        source_field_byte_offset,
                                        pointer_byte_offset,
                                        target_field_byte_offset,
                                    } => omega_isa_aarch64::encode_runtime_storage_copy_from_runtime_frame_base_indexed_to_runtime_pointee(
                                        base_byte_offset,
                                        index_region,
                                        index_offset,
                                        index_byte_size,
                                        element_byte_size,
                                        source_field_byte_offset,
                                        pointer_byte_offset,
                                        target_field_byte_offset,
                                        byte_count,
                                    )?,
                                    CompilerBodyPlaceCopyShape::PointeeToFrameBaseIndexed {
                                        pointer_byte_offset,
                                        source_field_byte_offset,
                                        base_byte_offset,
                                        index_region,
                                        index_offset,
                                        index_byte_size,
                                        element_byte_size,
                                        target_field_byte_offset,
                                    } => omega_isa_aarch64::encode_runtime_storage_copy_from_runtime_pointee_to_runtime_frame_base_indexed(
                                        pointer_byte_offset,
                                        source_field_byte_offset,
                                        base_byte_offset,
                                        index_region,
                                        index_offset,
                                        index_byte_size,
                                        element_byte_size,
                                        target_field_byte_offset,
                                        byte_count,
                                    )?,
                                    CompilerBodyPlaceCopyShape::FromMachineIndexed {
                                        base_byte_offset,
                                        index_region,
                                        index_offset,
                                        index_byte_size,
                                        element_byte_size,
                                        field_byte_offset,
                                        target_offset,
                                    } => omega_isa_aarch64::encode_runtime_storage_copy_from_runtime_machine_indexed_to_runtime_storage(
                                        base_byte_offset,
                                        index_offset,
                                        index_region,
                                        index_byte_size,
                                        element_byte_size,
                                        field_byte_offset,
                                        target_offset,
                                        byte_count,
                                    )?,
                                    CompilerBodyPlaceCopyShape::ToMachineIndexed {
                                        source_offset,
                                        base_byte_offset,
                                        index_region,
                                        index_offset,
                                        index_byte_size,
                                        element_byte_size,
                                        field_byte_offset,
                                    } => omega_isa_aarch64::encode_runtime_storage_copy_to_runtime_machine_indexed_from_runtime_storage(
                                        source_offset,
                                        base_byte_offset,
                                        index_offset,
                                        index_region,
                                        index_byte_size,
                                        element_byte_size,
                                        field_byte_offset,
                                        byte_count,
                                    )?,
                                    CompilerBodyPlaceCopyShape::MachineIndexedToPointee {
                                        base_byte_offset,
                                        index_region,
                                        index_offset,
                                        index_byte_size,
                                        element_byte_size,
                                        source_field_byte_offset,
                                        pointer_byte_offset,
                                        target_field_byte_offset,
                                    } => omega_isa_aarch64::encode_runtime_storage_copy_machine_indexed_to_runtime_pointee(
                                        base_byte_offset,
                                        index_region,
                                        index_offset,
                                        index_byte_size,
                                        element_byte_size,
                                        source_field_byte_offset,
                                        pointer_byte_offset,
                                        target_field_byte_offset,
                                        byte_count,
                                    )?,
                                    CompilerBodyPlaceCopyShape::PointeeToMachineIndexed {
                                        pointer_byte_offset,
                                        source_field_byte_offset,
                                        base_byte_offset,
                                        index_region,
                                        index_offset,
                                        index_byte_size,
                                        element_byte_size,
                                        target_field_byte_offset,
                                    } => omega_isa_aarch64::encode_runtime_storage_copy_runtime_pointee_to_machine_indexed(
                                        pointer_byte_offset,
                                        source_field_byte_offset,
                                        base_byte_offset,
                                        index_region,
                                        index_offset,
                                        index_byte_size,
                                        element_byte_size,
                                        target_field_byte_offset,
                                        byte_count,
                                    )?,
                                    CompilerBodyPlaceCopyShape::FromFrameBaseDoubleIndexed {
                                        base_byte_offset,
                                        outer_index_region,
                                        outer_index_offset,
                                        outer_index_byte_size,
                                        outer_stride,
                                        inner_index_region,
                                        inner_index_offset,
                                        inner_index_byte_size,
                                        inner_stride,
                                        field_byte_offset,
                                        target_offset,
                                    } => omega_isa_aarch64::encode_runtime_storage_copy_from_runtime_frame_base_double_indexed_to_runtime_storage(
                                        base_byte_offset,
                                        outer_index_region,
                                        outer_index_offset,
                                        outer_index_byte_size,
                                        outer_stride,
                                        inner_index_region,
                                        inner_index_offset,
                                        inner_index_byte_size,
                                        inner_stride,
                                        field_byte_offset,
                                        target_offset,
                                        byte_count,
                                    )?,
                                    CompilerBodyPlaceCopyShape::FrameBaseDoubleIndexedToPointee {
                                        base_byte_offset,
                                        outer_index_region,
                                        outer_index_offset,
                                        outer_index_byte_size,
                                        outer_stride,
                                        inner_index_region,
                                        inner_index_offset,
                                        inner_index_byte_size,
                                        inner_stride,
                                        source_field_byte_offset,
                                        pointer_byte_offset,
                                        target_field_byte_offset,
                                    } => omega_isa_aarch64::encode_runtime_storage_copy_from_runtime_frame_base_double_indexed_to_runtime_pointee(
                                        base_byte_offset,
                                        outer_index_region,
                                        outer_index_offset,
                                        outer_index_byte_size,
                                        outer_stride,
                                        inner_index_region,
                                        inner_index_offset,
                                        inner_index_byte_size,
                                        inner_stride,
                                        source_field_byte_offset,
                                        pointer_byte_offset,
                                        target_field_byte_offset,
                                        byte_count,
                                    )?,
                                    CompilerBodyPlaceCopyShape::PointeeToFrameBaseDoubleIndexed {
                                        pointer_byte_offset,
                                        source_field_byte_offset,
                                        base_byte_offset,
                                        outer_index_region,
                                        outer_index_offset,
                                        outer_index_byte_size,
                                        outer_stride,
                                        inner_index_region,
                                        inner_index_offset,
                                        inner_index_byte_size,
                                        inner_stride,
                                        target_field_byte_offset,
                                    } => omega_isa_aarch64::encode_runtime_storage_copy_from_runtime_pointee_to_runtime_frame_base_double_indexed(
                                        pointer_byte_offset,
                                        source_field_byte_offset,
                                        base_byte_offset,
                                        outer_index_region,
                                        outer_index_offset,
                                        outer_index_byte_size,
                                        outer_stride,
                                        inner_index_region,
                                        inner_index_offset,
                                        inner_index_byte_size,
                                        inner_stride,
                                        target_field_byte_offset,
                                        byte_count,
                                    )?,
                                    CompilerBodyPlaceCopyShape::MachineDoubleIndexedToPointee {
                                        base_byte_offset,
                                        outer_index_region,
                                        outer_index_offset,
                                        outer_index_byte_size,
                                        outer_stride,
                                        inner_index_region,
                                        inner_index_offset,
                                        inner_index_byte_size,
                                        inner_stride,
                                        source_field_byte_offset,
                                        pointer_byte_offset,
                                        target_field_byte_offset,
                                    } => omega_isa_aarch64::encode_runtime_storage_copy_machine_double_indexed_to_runtime_pointee(
                                        base_byte_offset,
                                        outer_index_region,
                                        outer_index_offset,
                                        outer_index_byte_size,
                                        outer_stride,
                                        inner_index_region,
                                        inner_index_offset,
                                        inner_index_byte_size,
                                        inner_stride,
                                        source_field_byte_offset,
                                        pointer_byte_offset,
                                        target_field_byte_offset,
                                        byte_count,
                                    )?,
                                    CompilerBodyPlaceCopyShape::PointeeToMachineDoubleIndexed {
                                        pointer_byte_offset,
                                        source_field_byte_offset,
                                        base_byte_offset,
                                        outer_index_region,
                                        outer_index_offset,
                                        outer_index_byte_size,
                                        outer_stride,
                                        inner_index_region,
                                        inner_index_offset,
                                        inner_index_byte_size,
                                        inner_stride,
                                        target_field_byte_offset,
                                    } => omega_isa_aarch64::encode_runtime_storage_copy_runtime_pointee_to_machine_double_indexed(
                                        pointer_byte_offset,
                                        source_field_byte_offset,
                                        base_byte_offset,
                                        outer_index_region,
                                        outer_index_offset,
                                        outer_index_byte_size,
                                        outer_stride,
                                        inner_index_region,
                                        inner_index_offset,
                                        inner_index_byte_size,
                                        inner_stride,
                                        target_field_byte_offset,
                                        byte_count,
                                    )?,
                                    CompilerBodyPlaceCopyShape::ToFrameBaseDoubleIndexed {
                                        source_offset,
                                        base_byte_offset,
                                        outer_index_region,
                                        outer_index_offset,
                                        outer_index_byte_size,
                                        outer_stride,
                                        inner_index_region,
                                        inner_index_offset,
                                        inner_index_byte_size,
                                        inner_stride,
                                        field_byte_offset,
                                    } => omega_isa_aarch64::encode_runtime_storage_copy_to_runtime_frame_base_double_indexed_from_runtime_storage(
                                        source.region,
                                        source_offset,
                                        base_byte_offset,
                                        outer_index_region,
                                        outer_index_offset,
                                        outer_index_byte_size,
                                        outer_stride,
                                        inner_index_region,
                                        inner_index_offset,
                                        inner_index_byte_size,
                                        inner_stride,
                                        field_byte_offset,
                                        byte_count,
                                    )?,
                                    CompilerBodyPlaceCopyShape::FromMachineDoubleIndexed {
                                        base_byte_offset,
                                        outer_index_region,
                                        outer_index_offset,
                                        outer_index_byte_size,
                                        outer_stride,
                                        inner_index_region,
                                        inner_index_offset,
                                        inner_index_byte_size,
                                        inner_stride,
                                        field_byte_offset,
                                        target_offset,
                                    } => omega_isa_aarch64::encode_runtime_storage_copy_from_runtime_machine_double_indexed_to_runtime_storage(
                                        base_byte_offset,
                                        outer_index_offset,
                                        outer_index_region,
                                        outer_index_byte_size,
                                        outer_stride,
                                        inner_index_offset,
                                        inner_index_region,
                                        inner_index_byte_size,
                                        inner_stride,
                                        field_byte_offset,
                                        target_offset,
                                        byte_count,
                                    )?,
                                    CompilerBodyPlaceCopyShape::ToMachineDoubleIndexed {
                                        source_offset,
                                        base_byte_offset,
                                        outer_index_region,
                                        outer_index_offset,
                                        outer_index_byte_size,
                                        outer_stride,
                                        inner_index_region,
                                        inner_index_offset,
                                        inner_index_byte_size,
                                        inner_stride,
                                        field_byte_offset,
                                    } => omega_isa_aarch64::encode_runtime_storage_copy_to_runtime_machine_double_indexed_from_runtime_storage(
                                        source.region,
                                        source_offset,
                                        base_byte_offset,
                                        outer_index_offset,
                                        outer_index_region,
                                        outer_index_byte_size,
                                        outer_stride,
                                        inner_index_offset,
                                        inner_index_region,
                                        inner_index_byte_size,
                                        inner_stride,
                                        field_byte_offset,
                                        byte_count,
                                    )?,
                                    CompilerBodyPlaceCopyShape::MachineIndexedPair {
                                        source_base_byte_offset,
                                        source_index_region,
                                        source_index_offset,
                                        source_index_byte_size,
                                        source_element_byte_size,
                                        source_field_byte_offset,
                                        target_base_byte_offset,
                                        target_index_region,
                                        target_index_offset,
                                        target_index_byte_size,
                                        target_element_byte_size,
                                        target_field_byte_offset,
                                    } => omega_isa_aarch64::encode_runtime_storage_copy_machine_indexed_to_machine_indexed(
                                        source_base_byte_offset,
                                        source_index_offset,
                                        source_index_region,
                                        source_index_byte_size,
                                        source_element_byte_size,
                                        source_field_byte_offset,
                                        target_base_byte_offset,
                                        target_index_offset,
                                        target_index_region,
                                        target_index_byte_size,
                                        target_element_byte_size,
                                        target_field_byte_offset,
                                        byte_count,
                                    )?,
                                    CompilerBodyPlaceCopyShape::FrameBaseIndexedPair {
                                        source_base_byte_offset,
                                        source_index_region,
                                        source_index_offset,
                                        source_index_byte_size,
                                        source_element_byte_size,
                                        source_field_byte_offset,
                                        target_base_byte_offset,
                                        target_index_region,
                                        target_index_offset,
                                        target_index_byte_size,
                                        target_element_byte_size,
                                        target_field_byte_offset,
                                    } => omega_isa_aarch64::encode_runtime_storage_copy_frame_base_indexed_to_frame_base_indexed(
                                        source_base_byte_offset,
                                        source_index_region,
                                        source_index_offset,
                                        source_index_byte_size,
                                        source_element_byte_size,
                                        source_field_byte_offset,
                                        target_base_byte_offset,
                                        target_index_region,
                                        target_index_offset,
                                        target_index_byte_size,
                                        target_element_byte_size,
                                        target_field_byte_offset,
                                        byte_count,
                                    )?,
                                    CompilerBodyPlaceCopyShape::CrossRegionIndexedPair {
                                        source_base_byte_offset,
                                        source_index_region,
                                        source_index_offset,
                                        source_index_byte_size,
                                        source_element_byte_size,
                                        source_field_byte_offset,
                                        target_base_byte_offset,
                                        target_index_region,
                                        target_index_offset,
                                        target_index_byte_size,
                                        target_element_byte_size,
                                        target_field_byte_offset,
                                    } => omega_isa_aarch64::encode_runtime_storage_copy_cross_region_indexed_pair(
                                        source.region,
                                        source_base_byte_offset,
                                        source_index_region,
                                        source_index_offset,
                                        source_index_byte_size,
                                        source_element_byte_size,
                                        source_field_byte_offset,
                                        target.region,
                                        target_base_byte_offset,
                                        target_index_region,
                                        target_index_offset,
                                        target_index_byte_size,
                                        target_element_byte_size,
                                        target_field_byte_offset,
                                        byte_count,
                                    )?,
                                    CompilerBodyPlaceCopyShape::CrossRegionDoubleIndexedPair {
                                        source_base_byte_offset,
                                        source_outer_index_region,
                                        source_outer_index_offset,
                                        source_outer_index_byte_size,
                                        source_outer_stride,
                                        source_inner_index_region,
                                        source_inner_index_offset,
                                        source_inner_index_byte_size,
                                        source_inner_stride,
                                        source_field_byte_offset,
                                        target_base_byte_offset,
                                        target_outer_index_region,
                                        target_outer_index_offset,
                                        target_outer_index_byte_size,
                                        target_outer_stride,
                                        target_inner_index_region,
                                        target_inner_index_offset,
                                        target_inner_index_byte_size,
                                        target_inner_stride,
                                        target_field_byte_offset,
                                    } => omega_isa_aarch64::encode_runtime_storage_copy_cross_region_double_indexed_pair(
                                        source.region,
                                        source_base_byte_offset,
                                        source_outer_index_region,
                                        source_outer_index_offset,
                                        source_outer_index_byte_size,
                                        source_outer_stride,
                                        source_inner_index_region,
                                        source_inner_index_offset,
                                        source_inner_index_byte_size,
                                        source_inner_stride,
                                        source_field_byte_offset,
                                        target.region,
                                        target_base_byte_offset,
                                        target_outer_index_region,
                                        target_outer_index_offset,
                                        target_outer_index_byte_size,
                                        target_outer_stride,
                                        target_inner_index_region,
                                        target_inner_index_offset,
                                        target_inner_index_byte_size,
                                        target_inner_stride,
                                        target_field_byte_offset,
                                        byte_count,
                                    )?,
                                    CompilerBodyPlaceCopyShape::FrameBaseDoubleIndexedPair {
                                        source_base_byte_offset,
                                        source_outer_index_region,
                                        source_outer_index_offset,
                                        source_outer_index_byte_size,
                                        source_outer_stride,
                                        source_inner_index_region,
                                        source_inner_index_offset,
                                        source_inner_index_byte_size,
                                        source_inner_stride,
                                        source_field_byte_offset,
                                        target_base_byte_offset,
                                        target_outer_index_region,
                                        target_outer_index_offset,
                                        target_outer_index_byte_size,
                                        target_outer_stride,
                                        target_inner_index_region,
                                        target_inner_index_offset,
                                        target_inner_index_byte_size,
                                        target_inner_stride,
                                        target_field_byte_offset,
                                    } => omega_isa_aarch64::encode_runtime_storage_copy_frame_base_double_indexed_to_frame_base_double_indexed(
                                        source_base_byte_offset,
                                        source_outer_index_region,
                                        source_outer_index_offset,
                                        source_outer_index_byte_size,
                                        source_outer_stride,
                                        source_inner_index_region,
                                        source_inner_index_offset,
                                        source_inner_index_byte_size,
                                        source_inner_stride,
                                        source_field_byte_offset,
                                        target_base_byte_offset,
                                        target_outer_index_region,
                                        target_outer_index_offset,
                                        target_outer_index_byte_size,
                                        target_outer_stride,
                                        target_inner_index_region,
                                        target_inner_index_offset,
                                        target_inner_index_byte_size,
                                        target_inner_stride,
                                        target_field_byte_offset,
                                        byte_count,
                                    )?,
                                    CompilerBodyPlaceCopyShape::MachineDoubleIndexedPair {
                                        source_base_byte_offset,
                                        source_outer_index_region,
                                        source_outer_index_offset,
                                        source_outer_index_byte_size,
                                        source_outer_stride,
                                        source_inner_index_region,
                                        source_inner_index_offset,
                                        source_inner_index_byte_size,
                                        source_inner_stride,
                                        source_field_byte_offset,
                                        target_base_byte_offset,
                                        target_outer_index_region,
                                        target_outer_index_offset,
                                        target_outer_index_byte_size,
                                        target_outer_stride,
                                        target_inner_index_region,
                                        target_inner_index_offset,
                                        target_inner_index_byte_size,
                                        target_inner_stride,
                                        target_field_byte_offset,
                                    } => omega_isa_aarch64::encode_runtime_storage_copy_machine_double_indexed_to_machine_double_indexed(
                                        source_base_byte_offset,
                                        source_outer_index_region,
                                        source_outer_index_offset,
                                        source_outer_index_byte_size,
                                        source_outer_stride,
                                        source_inner_index_region,
                                        source_inner_index_offset,
                                        source_inner_index_byte_size,
                                        source_inner_stride,
                                        source_field_byte_offset,
                                        target_base_byte_offset,
                                        target_outer_index_region,
                                        target_outer_index_offset,
                                        target_outer_index_byte_size,
                                        target_outer_stride,
                                        target_inner_index_region,
                                        target_inner_index_offset,
                                        target_inner_index_byte_size,
                                        target_inner_stride,
                                        target_field_byte_offset,
                                        byte_count,
                                    )?,
                                    CompilerBodyPlaceCopyShape::General => {
                                        return Err(Diagnostic::error(
                                            "final aarch64 compiler-body place copy reached the x86-only general materializer class",
                                        ));
                                    }
                                },
                            },
                            21u8,
                            CompilerInstructionRelocationRecipe::PlaceCopy {
                                source,
                                target,
                                byte_count,
                            },
                        )
                    }
                    omega_machine_bytes::CompilerInstructionValidationKind::CompilerBodyPlaceIntegerWrite {
                        target,
                        value,
                        byte_size,
                    } => {
                        let shape = compiler_body_place_write_shape_with_cross_region_frame_base(&target)?;
                        (
                            None,
                            match architecture {
                            Architecture::X86_64 => {
                                omega_isa_x86_64::encode_place_integer_write(
                                    &target,
                                    value,
                                    byte_size,
                                )?
                                .0
                            }
                            Architecture::Aarch64 => match shape {
                                CompilerBodyPlaceIntegerWriteShape::Direct { byte_offset } => {
                                omega_isa_aarch64::encode_runtime_machine_integer_write(
                                    byte_offset,
                                    byte_size,
                                    value,
                                )?
                                }
                                CompilerBodyPlaceIntegerWriteShape::Pointee {
                                    pointer_byte_offset,
                                    field_byte_offset,
                                } => omega_isa_aarch64::encode_runtime_pointee_integer_write(
                                    pointer_byte_offset,
                                    field_byte_offset,
                                    byte_size,
                                    value,
                                )?,
                                CompilerBodyPlaceIntegerWriteShape::FrameIndexed {
                                    descriptor_offset,
                                    index_region,
                                    index_offset,
                                    index_byte_size,
                                    element_byte_size,
                                    field_byte_offset,
                                } => omega_isa_aarch64::encode_runtime_frame_indexed_integer_write_with_index_region(
                                    descriptor_offset,
                                    index_region,
                                    index_offset,
                                    index_byte_size,
                                    element_byte_size,
                                    field_byte_offset,
                                    byte_size,
                                    value,
                                )?,
                                CompilerBodyPlaceIntegerWriteShape::FrameBaseIndexed {
                                    base_byte_offset,
                                    index_region,
                                    index_offset,
                                    index_byte_size,
                                    element_byte_size,
                                    field_byte_offset,
                                } => omega_isa_aarch64::encode_runtime_frame_base_indexed_integer_write_with_index_region(
                                    base_byte_offset,
                                    index_region,
                                    index_offset,
                                    index_byte_size,
                                    element_byte_size,
                                    field_byte_offset,
                                    byte_size,
                                    value,
                                )?,
                                CompilerBodyPlaceIntegerWriteShape::FrameBaseDoubleIndexed {
                                    base_byte_offset,
                                    outer_index_offset,
                                    outer_index_byte_size,
                                    outer_stride,
                                    inner_index_offset,
                                    inner_index_byte_size,
                                    inner_stride,
                                    field_byte_offset,
                                } => omega_isa_aarch64::encode_runtime_frame_base_double_indexed_integer_write(
                                    base_byte_offset,
                                    outer_index_offset,
                                    outer_index_byte_size,
                                    outer_stride,
                                    inner_index_offset,
                                    inner_index_byte_size,
                                    inner_stride,
                                    field_byte_offset,
                                    byte_size,
                                    value,
                                )?,
                                CompilerBodyPlaceIntegerWriteShape::MachineIndexed {
                                    base_byte_offset,
                                    index_region,
                                    index_offset,
                                    index_byte_size,
                                    element_byte_size,
                                    field_byte_offset,
                                } => omega_isa_aarch64::encode_runtime_machine_indexed_integer_write(
                                    base_byte_offset,
                                    index_region,
                                    index_offset,
                                    index_byte_size,
                                    element_byte_size,
                                    field_byte_offset,
                                    byte_size,
                                    value,
                                )?,
                                CompilerBodyPlaceIntegerWriteShape::MachineDoubleIndexed {
                                    base_byte_offset,
                                    outer_index_region,
                                    outer_index_offset,
                                    outer_index_byte_size,
                                    outer_stride,
                                    inner_index_region,
                                    inner_index_offset,
                                    inner_index_byte_size,
                                    inner_stride,
                                    field_byte_offset,
                                } => omega_isa_aarch64::encode_runtime_machine_double_indexed_integer_write(
                                    base_byte_offset,
                                    outer_index_offset,
                                    outer_index_region,
                                    outer_index_byte_size,
                                    outer_stride,
                                    inner_index_offset,
                                    inner_index_region,
                                    inner_index_byte_size,
                                    inner_stride,
                                    field_byte_offset,
                                    byte_size,
                                    value,
                                )?,
                                CompilerBodyPlaceIntegerWriteShape::PointeeDoubleIndexed {
                                    descriptor_offset,
                                    outer_index_region,
                                    outer_index_offset,
                                    outer_index_byte_size,
                                    outer_stride,
                                    inner_index_region,
                                    inner_index_offset,
                                    inner_index_byte_size,
                                    inner_stride,
                                    field_byte_offset,
                                } => omega_isa_aarch64::encode_runtime_pointee_double_indexed_integer_write(
                                    descriptor_offset,
                                    outer_index_region,
                                    outer_index_offset,
                                    outer_index_byte_size,
                                    outer_stride,
                                    inner_index_region,
                                    inner_index_offset,
                                    inner_index_byte_size,
                                    inner_stride,
                                    field_byte_offset,
                                    byte_size,
                                    value,
                                )?,
                                CompilerBodyPlaceIntegerWriteShape::General => {
                                    return Err(Diagnostic::error(
                                        "final aarch64 compiler-body integer write reached the x86-only general materializer class",
                                    ));
                                }
                            },
                            },
                            22u8,
                            CompilerInstructionRelocationRecipe::PlaceIntegerWrite(target),
                        )
                    }
                    omega_machine_bytes::CompilerInstructionValidationKind::CompilerBodyPlaceAddressWrite {
                        source,
                        target_offset,
                    } => (
                        None,
                        encode_compiler_place_address_write(architecture, &source, target_offset)?,
                        33u8,
                        CompilerInstructionRelocationRecipe::PlaceAddressWrite {
                            source,
                            target_offset,
                        },
                    ),
                    omega_machine_bytes::CompilerInstructionValidationKind::CompilerBodyDataAddressWrite {
                        data_symbol,
                        target_offset,
                    } => (
                        None,
                        match architecture {
                            Architecture::X86_64 => {
                                omega_isa_x86_64::encode_runtime_frame_data_address_write(
                                    target_offset,
                                )?.0
                            }
                            Architecture::Aarch64 => {
                                omega_isa_aarch64::encode_runtime_frame_data_address_write(
                                    target_offset,
                                )?
                            }
                        },
                        34u8,
                        CompilerInstructionRelocationRecipe::DataAddressWrite {
                            data_symbol,
                            target_offset,
                        },
                    ),
                    omega_machine_bytes::CompilerInstructionValidationKind::CompilerBodyConstantHostResult {
                        result_region,
                        result_offset,
                        result_byte_size,
                        value,
                    } => {
                        (
                            None,
                            match architecture {
                                Architecture::Aarch64 => {
                                    omega_isa_aarch64::encode_host_call_sequence_constant_result_from_operands(
                                        [
                                            omega_isa_aarch64::Aarch64CallOperand::RuntimeScalarInteger {
                                                byte_offset: result_offset,
                                                byte_count: result_byte_size,
                                            },
                                            omega_isa_aarch64::Aarch64CallOperand::ImmediateInteger(value),
                                        ]
                                        .into_iter(),
                                    )?
                                }
                                Architecture::X86_64 => {
                                    let operands = [
                                        omega_target_operations::InstructionOperand {
                                            kind: omega_target_operations::InstructionOperandKind::RuntimeScalarInteger {
                                                region: result_region,
                                                byte_offset: result_offset,
                                                byte_count: result_byte_size,
                                            },
                                        },
                                        omega_target_operations::InstructionOperand {
                                            kind: omega_target_operations::InstructionOperandKind::ImmediateInteger(value),
                                        },
                                    ];
                                    omega_isa_x86_64::encode_constant_result(&operands)?
                                }
                            },
                            34u8,
                            CompilerInstructionRelocationRecipe::StaticStorage {
                                storage_region: result_region,
                                address_site: match architecture {
                                    Architecture::Aarch64 => 16,
                                    Architecture::X86_64 => 10,
                                },
                            },
                        )
                    }
        _ => return Ok(None),
    };

    Ok(Some(spec))
}
