[package]
name = "omega-driver"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_driver"
path = "src/lib.rs"

[dependencies]
omega-core = { path = "../omega-core" }
omega-ast = { path = "../omega-ast" }
omega-lexer = { path = "../omega-lexer" }
omega-parser = { path = "../omega-parser" }
omega-resolve = { path = "../omega-resolve" }
