[package]
name = "omega-selected-instructions-to-machine-effects"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_selected_instructions_to_machine_effects"
path = "src/lib.rs"

[dependencies]
omega-register-model = { path = "../../representations/omega-register-model" }
omega-isa-aarch64 = { path = "../../backend/instruction_set_architectures/omega-isa-aarch64" }
omega-isa-x86_64 = { path = "../../backend/instruction_set_architectures/omega-isa-x86_64" }
omega-machine-optimizer = { path = "../omega-machine-optimizer" }
omega-regalloc = { path = "../omega-regalloc" }
omega-selected-instructions = { path = "../../representations/omega-selected-instructions" }
omega-target = { path = "../../representations/omega-target" }
omega-target-to-register-environment = { path = "../omega-target-to-register-environment" }
