[package]
name = "omega-target-operations"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_target_operations"
path = "src/lib.rs"

[dependencies]
omega-abstract-operations = { path = "../omega-abstract-operations" }
omega-calling-conventions = { path = "../../foundation/omega-calling-conventions" }
omega-control-flow = { path = "../omega-control-flow" }
omega-core = { path = "../../foundation/omega-core" }
psi-arena = { path = "../../../psi/foundation/psi-arena" }
psi-language-core = { path = "../../../psi/foundation/psi-language-core" }
psi-language-semantics = { path = "../../../psi/foundation/psi-language-semantics" }
psi-numerics = { path = "../../../psi/foundation/psi-numerics" }
omega-target = { path = "../../foundation/omega-target" }
