// aarch64.rs — ARM64 (macOS) backend, the sibling to x64.rs the module layout
// always anticipated. It emits ARM64 *assembly text*; the driver (main.rs) shells
// out to `clang -arch arm64` to assemble + link a Mach-O and `codesign -s -` for
// the ad-hoc signature Apple Silicon requires before it will exec.
//
// Why text + system assembler here, when x64.rs emits raw machine code: this is
// the THROWAWAY on-ramp (its trust lineage is discarded — see main.rs), and the
// point of this backend is to make epsilon-rs *runnable, hence verifiable*, on
// macOS arm64, where the x64 PE backend's output cannot execute at all. A faithful
// raw-Mach-O emitter would also have to synthesize the code-signature blob by
// hand; leaning on clang/codesign is the pragmatic path to a testable rung. When
// epsilon self-hosts, this backend is replaced wholesale, so the dependency leaves
// the trust path with the rest of the on-ramp.
//
// Slice 1: exit_process(<const>) end-to-end -> a runnable macOS arm64 executable
// whose exit status is the constant. `_main` returns the code in w0; the C runtime
// start stub calls exit() with main's return value (the analog of the x64 backend
// relying on the Windows thread stub).

use crate::ast::{Expr, Program, Statement};

pub fn lower_program(program: &Program) -> String {
    let mut asm = String::new();
    asm.push_str("// generated by epsilon-rs aarch64 backend (slice 1)\n");
    asm.push_str(".global _main\n.align 2\n_main:\n");
    let machine = &program.machines[program.entry_machine];
    let mut emitted = false;
    for statement in &machine.entry {
        if let Statement::Exit(expression) = statement {
            emit_expression_to_w0(*expression, program, &mut asm);
            asm.push_str("    ret\n");
            emitted = true;
            break;
        }
    }
    if !emitted {
        // No process exit in the entry machine: return 0.
        asm.push_str("    mov w0, #0\n    ret\n");
    }
    asm
}

fn emit_expression_to_w0(node: usize, program: &Program, asm: &mut String) {
    match program.expressions[node] {
        Expr::Int(value) => emit_load_w0(value, asm),
        // Slices > 1 (locals, arithmetic, calls, control flow) are not ported to
        // this backend yet; a non-constant exit code lowers to 0 for now.
        _ => asm.push_str("    mov w0, #0\n"),
    }
}

// Load a 32-bit constant into w0 with movz/movk (ARM64 immediates are 16-bit).
fn emit_load_w0(value: i32, asm: &mut String) {
    let bits = value as u32;
    let low = bits & 0xffff;
    let high = (bits >> 16) & 0xffff;
    asm.push_str(&format!("    movz w0, #{}\n", low));
    if high != 0 {
        asm.push_str(&format!("    movk w0, #{}, lsl #16\n", high));
    }
}
