// aarch64.rs — ARM64 (macOS) backend, the sibling to x64.rs the module layout
// always anticipated. It emits ARM64 *assembly text*; the driver (main.rs) shells
// out to `clang -arch arm64` to assemble + link a Mach-O and `codesign -s -` for
// the ad-hoc signature Apple Silicon requires before it will exec.
//
// Why text + system assembler here, when x64.rs emits raw machine code: this is
// the THROWAWAY on-ramp (its trust lineage is discarded — see main.rs), and the
// point of this backend is to make epsilon-rs *runnable, hence verifiable*, on
// macOS arm64, where the x64 PE backend's output cannot execute at all.
//
// Lowering model mirrors x64.rs: a STACK MACHINE. Every expression evaluates into
// w0 and is pushed; binary ops pop rhs then lhs. Locals live in an x29-relative
// frame. The "trap everything" decision (x64's ud2 on overflow / idiv on /0) maps
// to ARM64 condition-flag branches to a single `Ltrap: brk` per machine.
//
// Slices ported to this backend:
//   1. exit_process(<const>)              -> exit status is the constant.
//   2. expressions + locals + arithmetic  -> `let x = 3 + 4*2; exit_process(x)`,
//      with trap-on-overflow (add/sub/mul) and trap-on-divide-by-zero.
//   4. comparisons + `transition`/`state` control flow -> the entry machine's
//      state blocks become labels; a transition dispatches on the subject.
//   5. mutable reassignment (`i = e`) + back-edge transitions -> real loops.
// Not yet ported (fall through to a safe 0 / no-op): self/fields, machine calls,
// host I/O (write_line is a silent no-op for now). Those are later slices.
//
// All blocks of the entry machine (`entry` + each `state`) lower into ONE `_main`,
// sharing its x29 frame, so locals persist across transitions. State i is labeled
// `Lstate<i>`; a back-edge to an earlier state is just a backward branch = a loop.

use crate::ast::{BinaryOp, Expr, Pattern, Program, Statement};

pub fn lower_program(program: &Program) -> String {
    let machine = &program.machines[program.entry_machine];
    let local_count = machine.local_count.max(0) as i32;
    // frame = saved {x29,x30} (16) + one 8-byte slot per local, 16-aligned.
    let frame = align16(16 + 8 * local_count);

    let mut asm = String::new();
    asm.push_str("// generated by epsilon-rs aarch64 backend (slices 1-2, 4-5)\n");
    asm.push_str(".global _main\n.align 2\n_main:\n");
    // prologue
    asm.push_str(&format!("    sub sp, sp, #{}\n", frame));
    asm.push_str("    stp x29, x30, [sp]\n");
    asm.push_str("    mov x29, sp\n");

    // entry block, then each state block under its label.
    for statement in &machine.entry {
        lower_statement(statement, program, frame, &mut asm);
    }
    for (state_index, state_statements) in machine.states.iter().enumerate() {
        asm.push_str(&format!("Lstate{}:\n", state_index));
        for statement in state_statements {
            lower_statement(statement, program, frame, &mut asm);
        }
    }

    // Trailing default: reached only by fall-through off the end -> return 0.
    asm.push_str("    mov w0, #0\n");
    emit_epilogue(frame, &mut asm);

    // The single trap target: overflow and divide-by-zero land here (brk faults
    // the process, the runtime analog of x64's ud2 / idiv #DE).
    asm.push_str("Ltrap:\n    brk #0x1\n");
    asm
}

fn align16(n: i32) -> i32 {
    (n + 15) & !15
}

// Local i occupies the slot just past the saved {x29,x30} pair.
fn local_displacement(local_index: usize) -> i32 {
    16 + 8 * local_index as i32
}

fn emit_epilogue(frame: i32, asm: &mut String) {
    // w0 already holds the return/exit value.
    asm.push_str("    mov sp, x29\n");
    asm.push_str("    ldp x29, x30, [sp]\n");
    asm.push_str(&format!("    add sp, sp, #{}\n", frame));
    asm.push_str("    ret\n");
}

fn lower_statement(statement: &Statement, program: &Program, frame: i32, asm: &mut String) {
    match statement {
        Statement::Let(local_index, expression) | Statement::Assign(local_index, expression) => {
            lower_expression(*expression, program, asm);
            asm.push_str("    ldr x0, [sp], #16\n"); // pop value
            asm.push_str(&format!("    str w0, [x29, #{}]\n", local_displacement(*local_index)));
        }
        Statement::Eval(expression) => {
            lower_expression(*expression, program, asm);
            asm.push_str("    ldr x0, [sp], #16\n"); // pop and discard
        }
        Statement::Return(expression) | Statement::Exit(expression) => {
            lower_expression(*expression, program, asm);
            asm.push_str("    ldr x0, [sp], #16\n"); // pop into w0 (exit code / return value)
            emit_epilogue(frame, asm);
        }
        Statement::Transition(subject, arms) => {
            // Evaluate the subject, then dispatch: an Int pattern is a compare +
            // conditional branch to its state label; `_` is an unconditional branch.
            lower_expression(*subject, program, asm);
            asm.push_str("    ldr x0, [sp], #16\n"); // pop subject into w0
            for arm in arms {
                match arm.pattern {
                    Pattern::Int(value) => {
                        emit_load_w1(value, asm);
                        asm.push_str("    cmp w0, w1\n");
                        asm.push_str(&format!("    b.eq Lstate{}\n", arm.target));
                    }
                    Pattern::Wild => {
                        asm.push_str(&format!("    b Lstate{}\n", arm.target));
                    }
                }
            }
        }
        // Slices > 5 (self stores/reads, host I/O, machine calls) are not handled
        // by this backend yet; write_line etc. are silent no-ops, which preserves
        // the control-flow/value behavior the gated samples assert on exit codes.
        _ => {}
    }
}

fn lower_expression(node: usize, program: &Program, asm: &mut String) {
    match program.expressions[node] {
        Expr::Int(value) => {
            emit_load_w0(value, asm);
            asm.push_str("    str x0, [sp, #-16]!\n"); // push
        }
        Expr::Local(local_index) => {
            asm.push_str(&format!("    ldr w0, [x29, #{}]\n", local_displacement(local_index)));
            asm.push_str("    str x0, [sp, #-16]!\n"); // push
        }
        Expr::Binary(op, lhs, rhs) => {
            lower_expression(lhs, program, asm);
            lower_expression(rhs, program, asm);
            asm.push_str("    ldr x1, [sp], #16\n"); // pop rhs
            asm.push_str("    ldr x0, [sp], #16\n"); // pop lhs
            match op {
                BinaryOp::Add => {
                    asm.push_str("    adds w0, w0, w1\n    b.vs Ltrap\n");
                }
                BinaryOp::Sub => {
                    asm.push_str("    subs w0, w0, w1\n    b.vs Ltrap\n");
                }
                BinaryOp::Mul => {
                    // 32x32 -> 64 signed product; result fits in i32 iff it equals
                    // the sign-extension of its low 32 bits.
                    asm.push_str("    smull x0, w0, w1\n");
                    asm.push_str("    sxtw x2, w0\n    cmp x0, x2\n    b.ne Ltrap\n");
                }
                BinaryOp::Div => {
                    // ARM64 sdiv does NOT trap on /0 (returns 0); enforce the trap.
                    asm.push_str("    cbz w1, Ltrap\n    sdiv w0, w0, w1\n");
                }
                BinaryOp::Lt => emit_compare(asm, "lt"),
                BinaryOp::Gt => emit_compare(asm, "gt"),
                BinaryOp::Le => emit_compare(asm, "le"),
                BinaryOp::Ge => emit_compare(asm, "ge"),
                BinaryOp::EqEq => emit_compare(asm, "eq"),
                BinaryOp::Ne => emit_compare(asm, "ne"),
            }
            asm.push_str("    str x0, [sp, #-16]!\n"); // push result
        }
        // Unsupported in slices 1-2 (self/fields, calls, read_byte): push 0.
        _ => {
            asm.push_str("    mov w0, #0\n    str x0, [sp, #-16]!\n");
        }
    }
}

fn emit_compare(asm: &mut String, condition: &str) {
    asm.push_str("    cmp w0, w1\n");
    asm.push_str(&format!("    cset w0, {}\n", condition));
}

// Load a 32-bit constant into w0 with movz/movk (ARM64 immediates are 16-bit).
fn emit_load_w0(value: i32, asm: &mut String) {
    emit_load_reg(0, value, asm);
}

// Load a pattern constant into w1 (the transition compare operand).
fn emit_load_w1(value: i32, asm: &mut String) {
    emit_load_reg(1, value, asm);
}

fn emit_load_reg(reg: u32, value: i32, asm: &mut String) {
    let bits = value as u32;
    let low = bits & 0xffff;
    let high = (bits >> 16) & 0xffff;
    asm.push_str(&format!("    movz w{}, #{}\n", reg, low));
    if high != 0 {
        asm.push_str(&format!("    movk w{}, #{}, lsl #16\n", reg, high));
    }
}
