[package]
name = "omega-legalized-operations"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_legalized_operations"
path = "src/lib.rs"

[dependencies]
omega-calling-conventions = { path = "../omega-calling-conventions" }
omega-optimization-core = { path = "../omega-optimization-core" }
omega-optimization-unit = { path = "../omega-optimization-unit" }
omega-target = { path = "../omega-target" }
omega-abstract-operations = { path = "../omega-abstract-operations" }
omega-target-operations = { path = "../omega-target-operations" }
psi-core = { path = "../../../psi/foundation/psi-core" }
psi-terminal = { path = "../../../psi/representations/psi-terminal" }
psi-terminal-codec = { path = "../../../psi/semantics/psi-terminal-codec" }
sha2 = "0.10.9"
