#!/usr/bin/env python3
"""Pre-publication custody helpers for the canonical Delta compiler.

This module deliberately does not create a publication receipt or assign
authority to an assembly or executable artifact.  It only materializes the
already-committed source image and validates the bounded Darwin-arm64 assembly
dialect that a future lower-rooted execution is expected to publish.
"""

from __future__ import annotations

import hashlib
import re
import sys
from pathlib import Path

import source_closure_snapshot_v1 as closure


IMAGE_SOURCE_ID = "delta.compiler.lowermachine"
IMAGE_INPUT_ID = "input.delta.compiler.translation-unit"
IMAGE_RECIPE = "ordered-source-bytes-plus-lf-v1"

ASSEMBLY_HEADER = "// generated by the proof kernel-rs aarch64 backend (slices 1-2, 4-6)"
MAX_ASSEMBLY_BYTES = 16 * 1024 * 1024
MAX_ASSEMBLY_LINES = 500_000
MAX_ASSEMBLY_LINE_BYTES = 512


class PublicationSupportError(Exception):
    status = 251


class PublicationSupportResourceError(PublicationSupportError):
    status = 252


def fail(message: str) -> None:
    raise PublicationSupportError(message)


def resource(message: str) -> None:
    raise PublicationSupportResourceError(message)


def materialize_canonical_image(
    manifest_path: Path, locations_path: Path, roots: dict[str, Path]
) -> bytes:
    """Rebuild the exact canonical LF image from its committed V1 recipe."""

    try:
        manifest, _ = closure.load_document(manifest_path, "snapshot")
        closure.verify_data(manifest, locations_path, roots)
        located, tools, artifacts = closure.load_locations(
            locations_path, manifest["snapshot_id"], roots
        )
    except closure.SnapshotError as error:
        if error.status == 252:
            raise PublicationSupportResourceError(str(error)) from error
        raise PublicationSupportError(str(error)) from error

    if (
        manifest["snapshot_id"] != "delta.compiler.current.v1"
        or manifest["status"] != "canonical_compiler_root"
        or tools
        or artifacts
        or len(manifest["sources"]) != 1
        or len(manifest["generated_inputs"]) != 1
    ):
        fail("canonical compiler image profile")

    source = manifest["sources"][0]
    generated = manifest["generated_inputs"][0]
    if (
        source["id"] != IMAGE_SOURCE_ID
        or source["roles"] != ["canonical_compiler_root", "delta_source", "entry"]
        or generated["id"] != IMAGE_INPUT_ID
        or generated["role"] != "translation_unit"
        or generated["recipe"] != IMAGE_RECIPE
        or generated["inputs"]
        != [{"id": IMAGE_SOURCE_ID, "kind": "source", "ordinal": 0}]
    ):
        fail("canonical compiler image relation")

    raw = located[IMAGE_SOURCE_ID]
    image = raw + b"\n"
    if len(image) != generated["byte_length"]:
        fail("canonical compiler image extent")
    if hashlib.sha256(image).hexdigest() != generated["sha256"]:
        fail("canonical compiler image digest")
    return image


LABEL_RE = re.compile(
    r"(?:_main|Ltrap|Lflush_(?:output|loop|discard|done)|"
    r"Lmachine[0-9]+|Lm[0-9]+s[0-9]+|Lsk[0-9]+|Lstr[0-9]+|1)"
)
TARGET_RE = re.compile(
    r"(?:_main|_read|_write|Ltrap|Lflush_(?:output|loop|discard|done)|"
    r"Lmachine[0-9]+|Lm[0-9]+s[0-9]+|Lsk[0-9]+|1f)"
)
REGISTER_RE = re.compile(r"(?:[xw](?:[0-9]|[12][0-9]|30)|sp|wzr|xzr)")
IMMEDIATE_RE = re.compile(r"#(?:0|[1-9][0-9]*|0x[0-9a-f]+)")
IMMEDIATE_SHIFT_RE = re.compile(r"lsl #(12|16)")
INDEX_SCALE_SHIFT_RE = re.compile(r"lsl #3")
CONDITION_RE = re.compile(r"(?:eq|ne|lt|le|gt|ge|lo|ls|hi|hs|vs|vc)")
PAGE_RE = re.compile(
    r"(?:_(?:selfdata|iobyte|iobuf|iobuf_used)|Lstr[0-9]+)@PAGE(?:OFF)?"
)
MEMORY_RE = re.compile(
    r"\[(?:[xw](?:[0-9]|[12][0-9]|30)|sp)"
    r"(?:, (?:#-?(?:0|[1-9][0-9]*)|[xw](?:[0-9]|[12][0-9]|30)))?\]!?")

ARITIES = {
    "add": {3, 4}, "adds": {3}, "adrp": {2}, "and": {3}, "asr": {3},
    "b": {1}, "b.eq": {1}, "b.ne": {1}, "b.hs": {1}, "b.le": {1},
    "b.lo": {1}, "b.vs": {1}, "bl": {1}, "brk": {1}, "cbz": {2},
    "cmp": {2, 3}, "csel": {4}, "cset": {2}, "eor": {3},
    "ldp": {3, 4}, "ldr": {2, 3}, "ldrb": {2}, "lsl": {3},
    "mov": {2}, "movk": {2, 3}, "movz": {2, 3}, "msub": {4},
    "mul": {3}, "neg": {2}, "orr": {3}, "ret": {0}, "sdiv": {3},
    "smull": {3}, "stp": {3}, "str": {2}, "strb": {2}, "sub": {3},
    "subs": {3}, "sxtw": {2}, "uxtw": {2},
}


def _split_operands(spelling: str) -> list[str]:
    if not spelling:
        return []
    result: list[str] = []
    start = 0
    depth = 0
    for index, char in enumerate(spelling):
        if char == "[":
            depth += 1
        elif char == "]":
            depth -= 1
            if depth < 0:
                fail("assembly operand brackets")
        elif char == "," and depth == 0:
            result.append(spelling[start:index])
            if index + 1 >= len(spelling) or spelling[index + 1] != " ":
                fail("assembly operand separator")
            start = index + 2
    if depth != 0:
        fail("assembly operand brackets")
    result.append(spelling[start:])
    if any(not item or item != item.strip() or "  " in item for item in result):
        fail("assembly operand spacing")
    return result


def _operand_ok(value: str) -> bool:
    return bool(
        REGISTER_RE.fullmatch(value)
        or IMMEDIATE_RE.fullmatch(value)
        or IMMEDIATE_SHIFT_RE.fullmatch(value)
        or INDEX_SCALE_SHIFT_RE.fullmatch(value)
        or CONDITION_RE.fullmatch(value)
        or PAGE_RE.fullmatch(value)
        or MEMORY_RE.fullmatch(value)
        or TARGET_RE.fullmatch(value)
    )


def _register(value: str) -> bool:
    return bool(REGISTER_RE.fullmatch(value))


def _register_width(value: str) -> int:
    if value == "sp" or value == "xzr" or value.startswith("x"):
        return 64
    if value == "wzr" or value.startswith("w"):
        return 32
    return 0


def _same_register_width(values: list[str]) -> bool:
    widths = [_register_width(value) for value in values]
    return (
        bool(widths)
        and widths[0] != 0
        and all(width == widths[0] for width in widths)
    )


def _shift_register(value: str) -> bool:
    return _register(value) and value != "sp"


def _immediate(value: str) -> bool:
    return bool(IMMEDIATE_RE.fullmatch(value))


def _memory(value: str) -> bool:
    return bool(MEMORY_RE.fullmatch(value))


def _instruction(line: str) -> tuple[str, list[str]]:
    if not line.startswith("    ") or line[4:].startswith(" ") or line.endswith(" "):
        fail("assembly instruction indentation")
    body = line[4:]
    mnemonic, separator, operand_spelling = body.partition(" ")
    operands = _split_operands(operand_spelling if separator else "")
    if mnemonic not in ARITIES or len(operands) not in ARITIES[mnemonic]:
        fail("assembly instruction/arity")
    if any(not _operand_ok(operand) for operand in operands):
        fail("assembly operand")

    if mnemonic == "b" or mnemonic == "bl" or mnemonic.startswith("b."):
        if not TARGET_RE.fullmatch(operands[0]):
            fail("assembly branch target")
    if mnemonic == "cbz" and not TARGET_RE.fullmatch(operands[1]):
        fail("assembly conditional target")
    if mnemonic == "brk" and operands != ["#0x1"]:
        fail("assembly trap immediate")
    if mnemonic == "adrp" and (
        not PAGE_RE.fullmatch(operands[1]) or not operands[1].endswith("@PAGE")
    ):
        fail("assembly page reference")
    if mnemonic == "cset" and not CONDITION_RE.fullmatch(operands[1]):
        fail("assembly condition")
    if mnemonic == "csel" and not CONDITION_RE.fullmatch(operands[3]):
        fail("assembly condition")

    if mnemonic in ("ldr", "ldrb", "str", "strb"):
        if not _register(operands[0]) or not _memory(operands[1]):
            fail("assembly load/store shape")
        if len(operands) == 3 and not _immediate(operands[2]):
            fail("assembly post-index shape")
    elif mnemonic in ("ldp", "stp"):
        if not _register(operands[0]) or not _register(operands[1]) or not _memory(operands[2]):
            fail("assembly pair load/store shape")
        if len(operands) == 4 and not _immediate(operands[3]):
            fail("assembly pair post-index shape")
    elif mnemonic in ("movz", "movk"):
        if not _register(operands[0]) or not _immediate(operands[1]):
            fail("assembly immediate move shape")
        if len(operands) == 3 and operands[2] != "lsl #16":
            fail("assembly immediate shift")
    elif mnemonic == "mov":
        if not _register(operands[0]) or not (_register(operands[1]) or _immediate(operands[1])):
            fail("assembly move shape")
    elif mnemonic == "adrp":
        if not _register(operands[0]):
            fail("assembly page destination")
    elif mnemonic in ("cset",):
        if not _register(operands[0]):
            fail("assembly condition destination")
    elif mnemonic == "csel":
        if any(not _register(value) for value in operands[:3]):
            fail("assembly select registers")
    elif mnemonic == "cbz":
        if not _register(operands[0]):
            fail("assembly conditional register")
    elif mnemonic == "cmp":
        if not _register(operands[0]) or not (_register(operands[1]) or _immediate(operands[1])):
            fail("assembly compare shape")
        if len(operands) == 3 and operands[2] != "lsl #12":
            fail("assembly compare shift")
    elif mnemonic in ("add", "sub"):
        if not _register(operands[0]) or not _register(operands[1]):
            fail("assembly arithmetic registers")
        if not (_register(operands[2]) or _immediate(operands[2]) or PAGE_RE.fullmatch(operands[2])):
            fail("assembly arithmetic operand")
        if PAGE_RE.fullmatch(operands[2]) and not operands[2].endswith("@PAGEOFF"):
            fail("assembly page-offset operand")
        if len(operands) == 3:
            if not _same_register_width(operands[:2]):
                fail("assembly arithmetic register width")
            if _register(operands[2]) and not _same_register_width(operands):
                fail("assembly arithmetic register width")
            if PAGE_RE.fullmatch(operands[2]) and _register_width(operands[0]) != 64:
                fail("assembly page-offset register width")
        else:
            immediate_shift = (
                _immediate(operands[2])
                and operands[3] == "lsl #12"
                and _same_register_width(operands[:2])
            )
            index_scale_shift = (
                mnemonic == "add"
                and _register(operands[2])
                and operands[3] == "lsl #3"
                and _same_register_width(operands[:3])
                and _register_width(operands[0]) == 64
            )
            if not (immediate_shift or index_scale_shift):
                fail("assembly arithmetic shift")
    elif mnemonic in ("adds", "subs", "mul", "sdiv", "smull"):
        if any(not _register(value) for value in operands):
            fail("assembly arithmetic shape")
    elif mnemonic in ("asr", "lsl"):
        if not all(_shift_register(value) for value in operands[:2]) or not (
            _same_register_width(operands[:2])
        ):
            fail("assembly shift register width")
        if _register(operands[2]):
            if not _shift_register(operands[2]) or not _same_register_width(operands):
                fail("assembly shift register width")
        elif mnemonic == "asr" and _immediate(operands[2]):
            expected = "#31" if _register_width(operands[0]) == 32 else "#63"
            if operands[2] != expected:
                fail("assembly immediate shift width")
        else:
            fail("assembly shift shape")
    elif mnemonic in ("and", "eor", "orr"):
        if not _register(operands[0]) or not _register(operands[1]) or not (
            _register(operands[2]) or _immediate(operands[2])
        ):
            fail("assembly bitwise shape")
    elif mnemonic == "msub":
        if any(not _register(value) for value in operands):
            fail("assembly multiply-subtract shape")
    elif mnemonic in ("neg", "sxtw", "uxtw"):
        if any(not _register(value) for value in operands):
            fail("assembly unary shape")
    return mnemonic, operands


def validate_darwin_arm64_assembly(raw: bytes) -> None:
    """Validate bounded syntax and linkage shape without blessing an artifact."""

    if len(raw) > MAX_ASSEMBLY_BYTES:
        resource("assembly byte ceiling")
    if not raw or not raw.endswith(b"\n") or b"\r" in raw or b"\0" in raw:
        fail("assembly byte framing")
    try:
        text = raw.decode("ascii")
    except UnicodeDecodeError as error:
        fail(f"assembly ASCII: {error}")
    lines = text[:-1].split("\n")
    if len(lines) > MAX_ASSEMBLY_LINES:
        resource("assembly line ceiling")
    if any(len(line.encode()) > MAX_ASSEMBLY_LINE_BYTES for line in lines):
        resource("assembly line byte ceiling")
    if len(lines) < 4 or lines[:3] != [ASSEMBLY_HEADER, ".global _main", ".align 2"]:
        fail("assembly header")
    if any(not line for line in lines):
        fail("assembly empty line")

    labels: dict[str, int] = {}
    references: list[tuple[str, int]] = []
    numeric_forwards: list[int] = []
    bss: dict[str, tuple[int, int]] = {}
    string_bytes: dict[str, list[int]] = {}
    current_string: str | None = None
    constant_section = -1
    instructions: list[tuple[int, str, list[str]]] = []

    for index, line in enumerate(lines[3:], 3):
        if line.startswith("//"):
            fail("assembly extra comment")
        if line == ".section __TEXT,__const":
            if constant_section >= 0:
                fail("assembly duplicate constant section")
            constant_section = index
            current_string = None
            continue
        if line == ".align 2":
            if index != constant_section + 1:
                fail("assembly alignment placement")
            continue
        if line.startswith(".zerofill "):
            if constant_section >= 0:
                fail("assembly BSS after constants")
            match = re.fullmatch(
                r"\.zerofill __DATA,__bss,(_selfdata|_iobyte|_iobuf_used|_iobuf),"
                r"(0|[1-9][0-9]*),(0|[1-9][0-9]*)",
                line,
            )
            if not match or match.group(1) in bss:
                fail("assembly BSS directive")
            bss[match.group(1)] = (int(match.group(2)), int(match.group(3)))
            continue
        if line.startswith("    .byte "):
            if constant_section < 0 or current_string is None:
                fail("assembly byte placement")
            spelling = line[len("    .byte "):]
            if not re.fullmatch(r"(?:0|[1-9][0-9]*)(?:,(?:0|[1-9][0-9]*))*", spelling):
                fail("assembly byte syntax")
            values = [int(value) for value in spelling.split(",")]
            if any(value > 255 for value in values):
                fail("assembly byte value")
            string_bytes[current_string].extend(values)
            continue
        if line.endswith(":"):
            label = line[:-1]
            if not LABEL_RE.fullmatch(label):
                fail("assembly label")
            if label != "1" and label in labels:
                fail("assembly duplicate label")
            if label != "1":
                labels[label] = index
            if label.startswith("Lstr"):
                if constant_section < 0 or label in string_bytes:
                    fail("assembly string label placement")
                current_string = label
                string_bytes[label] = []
            elif constant_section >= 0:
                fail("assembly code label after constants")
            continue
        if line.startswith("."):
            fail("assembly directive")
        if constant_section >= 0:
            fail("assembly instruction after constants")

        mnemonic, operands = _instruction(line)
        instructions.append((index, mnemonic, operands))
        target: str | None = None
        if mnemonic in ("b", "b.eq", "b.ne", "b.hs", "b.le", "b.lo", "b.vs", "bl"):
            target = operands[-1]
        elif mnemonic == "cbz":
            target = operands[1]
        if target == "1f":
            numeric_forwards.append(index)
        elif target and target not in ("_read", "_write"):
            references.append((target, index))
        for operand in operands:
            match = re.fullmatch(r"(Lstr[0-9]+)@PAGE(?:OFF)?", operand)
            if match:
                references.append((match.group(1), index))

    required_labels = {
        "_main", "Ltrap", "Lflush_output", "Lflush_loop",
        "Lflush_discard", "Lflush_done",
    }
    if not required_labels.issubset(labels):
        fail("assembly required labels")
    if constant_section < 0 or not string_bytes or any(not values for values in string_bytes.values()):
        fail("assembly constant section")
    for target, _ in references:
        if target not in labels:
            fail("assembly unresolved target")
    numeric_labels = [i for i, line in enumerate(lines) if line == "1:"]
    if any(not any(label > use for label in numeric_labels) for use in numeric_forwards):
        fail("assembly unresolved numeric target")

    if bss.get("_iobyte") != (1, 0):
        fail("assembly input-byte BSS")
    if bss.get("_iobuf_used") != (4, 2) or bss.get("_iobuf") != (4096, 4):
        fail("assembly output-buffer BSS")
    selfdata = bss.get("_selfdata")
    if selfdata is None or selfdata[0] <= 0 or selfdata[0] % 8 or selfdata[1] != 3:
        fail("assembly self-data BSS")

    main = labels["_main"]
    if main + 3 >= len(lines) or lines[main + 2:main + 4] != [
        "    stp x29, x30, [sp]", "    mov x29, sp"
    ] or not re.fullmatch(r"    sub sp, sp, #[1-9][0-9]*", lines[main + 1]):
        fail("assembly main prologue")
    trap = labels["Ltrap"]
    if lines[trap + 1:trap + 3] != ["    bl Lflush_output", "    brk #0x1"]:
        fail("assembly trap publication order")

    flush_shape = [
        "    stp x19, x20, [sp, #-32]!", "    str x30, [sp, #16]",
        "    adrp x9, _iobuf_used@PAGE", "    add x9, x9, _iobuf_used@PAGEOFF",
        "    ldr w19, [x9]", "    cbz w19, Lflush_done", "    mov x20, #0",
    ]
    flush = labels["Lflush_output"]
    if lines[flush + 1:flush + 1 + len(flush_shape)] != flush_shape:
        fail("assembly flush prologue")


def _main(arguments: list[str]) -> int:
    if not arguments:
        fail("command")
    command, *rest = arguments
    if command == "materialize-image" and len(rest) >= 3:
        manifest = Path(rest[0])
        locations = Path(rest[1])
        roots = closure.parse_roles(rest[2:])
        sys.stdout.buffer.write(materialize_canonical_image(manifest, locations, roots))
        return 0
    if command == "validate-assembly" and len(rest) == 1:
        validate_darwin_arm64_assembly(Path(rest[0]).read_bytes())
        return 0
    fail("command")


if __name__ == "__main__":
    try:
        raise SystemExit(_main(sys.argv[1:]))
    except (PublicationSupportError, closure.SnapshotError, OSError) as error:
        status = getattr(error, "status", 251)
        print(f"delta publication support: {error}", file=sys.stderr)
        raise SystemExit(status)
