//! Stable identities for independently replayed abstract-to-target families.

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum AbstractToTargetTranslationFamily {
    StraightLineIntegerImmediate,
    StraightLineIntegerWidenImmediate,
    StraightLineIntegerBitwiseAndImmediate,
    StraightLineIntegerBitwiseOrImmediate,
    StraightLineIntegerBitwiseXorImmediate,
    StraightLineSaturatingIntegerAddImmediate,
    StraightLineWrappingIntegerAddImmediate,
    StraightLineSaturatingIntegerSubtractImmediate,
    StraightLineWrappingIntegerSubtractImmediate,
    StraightLineWrappingIntegerMultiplyImmediate,
    StraightLineIntegerBitwiseNotImmediate,
    StraightLineIntegerEqualImmediate,
    StraightLineIntegerLessThanImmediate,
    StraightLineIntegerLessOrEqualImmediate,
    StraightLineIntegerExactCastImmediateOperand,
    StraightLineBooleanImmediate,
    StraightLineBooleanNotImmediate,
    StraightLineBooleanEqualImmediate,
    StraightLineUnitReturn,
    StraightLinePortWriteUnitReturn,
    StraightLineUnitCallReturn,
    StraightLineByteSequenceLiteralUnitReturn,
    StraightLineIntegerLiteralUnitReturn,
    StraightLineIntegerLiteralSequenceUnitReturn,
    StraightLineIeeeFloatLiteralUnitReturn,
    StraightLineIeeeFloatLiteralSequenceUnitReturn,
    StraightLineIntegerIeeeFloatLiteralSequenceUnitReturn,
    StraightLineNearestIeeeFloatFusedMultiplyAddUnitReturn,
    StraightLineTrivialAffineLocalUnitReturn,
    StraightLineScalarCrash,
    StraightLineIntegerParameter,
    StraightLineBooleanParameter,
    StraightLineBooleanNotParameter,
    StraightLineIntegerBitwiseNotParameter,
    StraightLineBooleanEqualParameters,
    StraightLineIntegerEqualParameters,
    StraightLineIntegerLessThanParameters,
    StraightLineIntegerLessOrEqualParameters,
    StraightLineIntegerWidenParameter,
    StraightLineIntegerExactCastParameter,
    StraightLineIntegerBitwiseAndParameters,
    StraightLineIntegerBitwiseOrParameters,
    StraightLineIntegerBitwiseXorParameters,
    StraightLineWrappingIntegerShiftLeftParameters,
    StraightLineWrappingIntegerShiftRightParameters,
    StraightLineExactIntegerShiftLeftParameters,
    StraightLineExactIntegerShiftRightParameters,
    StraightLineExactIntegerAddParameters,
    StraightLineExactIntegerSubtractParameters,
    StraightLineExactIntegerMultiplyParameters,
    StraightLineExactIntegerDivideParameters,
    StraightLineExactIntegerRemainderParameters,
    StraightLineWrappingIntegerDivideParameters,
    StraightLineWrappingIntegerRemainderParameters,
    StraightLineSaturatingIntegerDivideParameters,
    StraightLineSaturatingIntegerRemainderParameters,
    StraightLineSaturatingIntegerAddParameters,
    StraightLineWrappingIntegerAddParameters,
    StraightLineSaturatingIntegerSubtractParameters,
    StraightLineWrappingIntegerSubtractParameters,
    StraightLineWrappingIntegerMultiplyParameters,
    StraightLineSaturatingIntegerMultiplyParameters,
    StructuralCallReturnCaller,
    StructuralParameterReturnCallee,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum AbstractToTargetPlanTranslationFamily {
    StructuralCallReturnProjectedQualifications,
}
