//! Stable identities for independently replayed abstract-to-target families.

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum AbstractToTargetTranslationFamily {
    StraightLineIntegerImmediate,
    StraightLineBooleanImmediate,
    StraightLineScalarCrash,
    StraightLineIntegerParameter,
    StraightLineBooleanParameter,
    StraightLineBooleanNotParameter,
    StraightLineIntegerBitwiseNotParameter,
    StraightLineBooleanEqualParameters,
    StraightLineIntegerEqualParameters,
    StraightLineIntegerLessThanParameters,
    StraightLineIntegerLessOrEqualParameters,
    StraightLineIntegerWidenParameter,
    StraightLineIntegerExactCastParameter,
    StraightLineIntegerBitwiseAndParameters,
    StraightLineIntegerBitwiseOrParameters,
    StraightLineIntegerBitwiseXorParameters,
    StraightLineWrappingIntegerShiftLeftParameters,
    StraightLineExactIntegerAddParameters,
    StraightLineExactIntegerSubtractParameters,
    StraightLineExactIntegerMultiplyParameters,
    StraightLineExactIntegerDivideParameters,
    StraightLineExactIntegerRemainderParameters,
    StraightLineWrappingIntegerDivideParameters,
    StraightLineWrappingIntegerRemainderParameters,
    StraightLineSaturatingIntegerDivideParameters,
    StraightLineSaturatingIntegerRemainderParameters,
    StraightLineSaturatingIntegerAddParameters,
    StraightLineWrappingIntegerAddParameters,
    StraightLineSaturatingIntegerSubtractParameters,
    StraightLineWrappingIntegerSubtractParameters,
    StraightLineWrappingIntegerMultiplyParameters,
    StraightLineSaturatingIntegerMultiplyParameters,
}
