[package]
name = "omega-state-graph-to-control-flow"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_state_graph_to_control_flow"
path = "src/lib.rs"

[dependencies]
omega-checked-trees = { path = "../../representations/omega-checked-trees" }
omega-control-flow = { path = "../../representations/omega-control-flow" }
omega-core = { path = "../../foundation/omega-core" }
omega-state-graph = { path = "../../representations/omega-state-graph" }
