[package]
name = "omega-terminal-abstract-operations"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_terminal_abstract_operations"
path = "src/lib.rs"

[dependencies]
psi-core = { path = "../../../psi/foundation/psi-core" }
psi-terminal = { path = "../../../psi/representations/psi-terminal" }
