[package]
name = "psi-proof"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "psi_proof"
path = "src/lib.rs"

[dependencies]
psi-arena = { path = "../../foundation/psi-arena" }
psi-diagnostics = { path = "../../foundation/psi-diagnostics" }
psi-language-semantics = { path = "../../foundation/psi-language-semantics" }
psi-numerics = { path = "../../foundation/psi-numerics" }
psi-symbols = { path = "../../foundation/psi-symbols" }
psi-syntax-trees = { path = "../../representations/psi-syntax-trees" }
psi-typed-trees = { path = "../../representations/psi-typed-trees" }
psi-validation = { path = "../psi-validation" }
