[package]
name = "omega-checked-trees-to-state-graph"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_checked_trees_to_state_graph"
path = "src/lib.rs"

[dependencies]
omega-state-graph = { path = "../../representations/omega-state-graph" }
omega-core = { path = "../../foundation/omega-core" }
omega-effects = { path = "../../semantics/omega-effects" }
omega-facts = { path = "../../semantics/omega-facts" }
omega-checked-trees = { path = "../../representations/omega-checked-trees" }
