[package]
name = "psi-language-semantics"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "psi_language_semantics"
path = "src/lib.rs"

[dependencies]
psi-core = { path = "../psi-core" }
psi-language-core = { path = "../psi-language-core" }
psi-numerics = { path = "../psi-numerics" }
psi-symbols = { path = "../psi-symbols" }
