[package]
name = "omega-typed-trees-to-checked-trees"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_typed_trees_to_checked_trees"
path = "src/lib.rs"

[dependencies]
omega-checked-trees = { path = "../../representations/omega-checked-trees" }
omega-core = { path = "../../foundation/omega-core" }
omega-effects = { path = "../../semantics/omega-effects" }
omega-facts = { path = "../../semantics/omega-facts" }
omega-proof = { path = "../../semantics/omega-proof" }
omega-typed-trees = { path = "../../representations/omega-typed-trees" }
omega-validation = { path = "../../semantics/omega-validation" }
