[package]
name = "psi-checked-trees"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "psi_checked_trees"
path = "src/lib.rs"

[dependencies]
psi-arena = { path = "../../foundation/psi-arena" }
psi-core = { path = "../../foundation/psi-core" }
psi-effects = { path = "../psi-effects" }
psi-facts = { path = "../psi-facts" }
psi-language-core = { path = "../../foundation/psi-language-core" }
psi-language-semantics = { path = "../../foundation/psi-language-semantics" }
psi-numerics = { path = "../../foundation/psi-numerics" }
psi-source = { path = "../../foundation/psi-source" }
psi-symbols = { path = "../../foundation/psi-symbols" }
psi-typed-trees = { path = "../psi-typed-trees" }
