[package]
name = "omega-state-values"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_state_values"
path = "src/lib.rs"

[dependencies]
psi-checked-trees = { path = "../../../psi/representations/psi-checked-trees" }
omega-control-flow = { path = "../../representations/omega-control-flow" }
omega-core = { path = "../../foundation/omega-core" }
psi-arena = { path = "../../../psi/foundation/psi-arena" }
psi-symbols = { path = "../../../psi/foundation/psi-symbols" }
omega-state-calls = { path = "../omega-state-calls" }
omega-state-graph = { path = "../../representations/omega-state-graph" }
psi-numerics = { path = "../../../psi/foundation/psi-numerics" }
psi-language-core = { path = "../../../psi/foundation/psi-language-core" }
psi-typed-trees = { path = "../../../psi/representations/psi-typed-trees" }
