[package]
name = "register-homes-to-post-allocation-machine"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "register_homes_to_post_allocation_machine"
path = "src/lib.rs"

[features]
test-support = []

[dependencies]
target-operations-to-selected-instructions = { path = "../03_target-operations-to-selected-instructions" }
selected-instructions-to-selected-instructions = { path = "../04_selected-instructions-to-selected-instructions" }
target = { path = "../../../psi/target" }
sha2 = "0.10.9"
selected-instructions-to-register-homes = { path = "../05_selected-instructions-to-register-homes" }
optimization-core = { path = "../../../psi/optimization-core" }
semantic-vocabulary = { path = "../../../psi/foundation/semantic-vocabulary" }

[dev-dependencies]
target-operations-to-selected-instructions = { path = "../03_target-operations-to-selected-instructions" }
abstract-operations-to-target-operations = { path = "../02_abstract-operations-to-target-operations" }
terminal-psi = { path = "../../../psi/terminal-psi" }
