[package]
name = "selected-instructions-to-register-homes"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
path = "src/lib.rs"

[features]
test-support = [
    "selected-instructions-to-selected-instructions/test-support",
    "optimization-core/test-support",
]

[dependencies]
target-operations-to-selected-instructions = { path = "../03_target-operations-to-selected-instructions" }
selected-instructions-to-selected-instructions = { path = "../04_selected-instructions-to-selected-instructions" }
terminal-psi-to-abstract-operations = { path = "../00_terminal-psi-to-abstract-operations" }
abstract-operations-to-target-operations = { path = "../02_abstract-operations-to-target-operations" }
optimization-core = { path = "../../../psi/optimization-core" }
target = { path = "../../../psi/target" }
semantic-vocabulary = { path = "../../../psi/foundation/semantic-vocabulary" }
terminal-psi = { path = "../../../psi/terminal-psi" }
sha2 = "0.10.9"

[dev-dependencies]
selected-instructions-to-selected-instructions = { path = "../04_selected-instructions-to-selected-instructions", features = ["test-support"] }
optimization-core = { path = "../../../psi/optimization-core", features = ["test-support"] }
