//! Substitutable-field inventory for the placed-image evidence section.
//!
//! The family's declared fields are driven through the shared substitution
//! matrix by `custody_tests.rs`; keeping the inventory in its own file names
//! the boundary between what is declared substitutable and the driver that
//! exercises every leg.

optimization_core::custody_field_inventory! {
    /// One substitutable axis of the honest placed-image evidence section,
    /// each variant spelling the authored leg label it replaced. Record-level
    /// and wire-level substitutions that keep the section canonical reject at
    /// independent replay under a named subject; substitutions the
    /// representation closes reject at decoding as malformed evidence.
    pub enum NativePlacedImageEvidenceFieldForTest {
        SubstitutedTargetArchitecture,
        ForeignArchitectureOverX86FootprintRegisters,
        SubstitutedTargetObjectFormat,
        ShiftedDeclaredTextExtent,
        DeclaredExtentBeyondTheContainer,
        OverflowingDeclaredExtent,
        WireLevelTextOffsetSubstitution,
        SubstitutedInventoryTextAddress,
        SubstitutedInventoryTextByteCount,
        SubstitutedInventoryTextDigest,
        SubstitutedInventoryTextFingerprint,
        SubstitutedInventorySealDigest,
        SubstitutedInventorySealFingerprint,
        SubstitutedRegionSectionOffset,
        SubstitutedRegionAddress,
        SubstitutedRegionByteCount,
        SubstitutedRegionByteDigest,
        SubstitutedRegionByteFingerprint,
        SubstitutedRegionSymbol,
        DroppedRegionFootprint,
        AddedRegionFootprint,
        SubstitutedFootprintRegisterSet,
        SubstitutedFootprintMachineStateSet,
        FootprintReducedToRegisterImpliedMachineState,
        EmptiedRegionFootprint,
        DroppedRegionRow,
        InsertedRegionRow,
        DroppedGapRow,
        InsertedGapRow,
        SubstitutedGapSectionOffset,
        SubstitutedGapAddress,
        SubstitutedGapByteCount,
        SubstitutedGapByteDigest,
        SubstitutedGapByteFingerprint,
        ShiftedDeclaredDataExtent,
        DeclaredDataExtentBeyondTheContainer,
        WireLevelDataOffsetSubstitution,
        SubstitutedInventoryDataAddress,
        SubstitutedInventoryDataByteCount,
        SubstitutedInventoryDataDigest,
        SubstitutedInventoryDataFingerprint,
        SubstitutedDataInventorySealDigest,
        SubstitutedDataInventorySealFingerprint,
        SubstitutedDataRegionOrigin,
        SubstitutedDataRegionSectionOffset,
        SubstitutedDataRegionAddress,
        SubstitutedDataRegionByteCount,
        SubstitutedDataRegionByteDigest,
        SubstitutedDataRegionByteFingerprint,
        SubstitutedDataRegionSymbol,
        DroppedDataRegionRow,
        InsertedDataRegionRow,
        DroppedDataGapRow,
        InsertedDataGapRow,
        SubstitutedDataGapSectionOffset,
        SubstitutedDataGapAddress,
        SubstitutedDataGapByteCount,
        SubstitutedDataGapByteDigest,
        SubstitutedDataGapByteFingerprint,
        ShiftedDeclaredImportDataExtent,
        SubstitutedImportDataBaseAddress,
        SubstitutedImportDataByteCount,
        SubstitutedImportDataDigest,
        SubstitutedImportDataFingerprint,
        SubstitutedImportDataInventorySealDigest,
        SubstitutedImportDataInventorySealFingerprint,
        PaddedImportDataRegionRoster,
        PaddedImportDataGapRoster,
        UnknownArchitectureTag,
        UnknownObjectFormatTag,
        UnknownRegionOriginTag,
        UnknownDataRegionOriginTag,
        UnknownFootprintPresenceTag,
        UndeclaredPointerSize,
        UndeclaredPointerAlignment,
        UndeclaredX8664MachoTargetPair,
        UndeclaredAarch64CoffTargetPair,
        UnknownFootprintRegisterCode,
        FootprintRegisterOfAnotherArchitecture,
        UnboundedFootprintRegisterCount,
        DuplicatedFootprintRegister,
        UnorderedFootprintRegisters,
        MachineStateBitsOutsideTheVocabulary,
        MachineStateSetMissingAnImpliedClass,
        ImportThunkRowELFCannotRealize,
        UnboundedRegionCount,
        UnboundedGapCount,
        UnboundedDataRegionCount,
        UnboundedDataGapCount,
        ShortenedRegionCount,
        ExtendedRegionCount,
        ShortenedGapCount,
        ExtendedGapCount,
        ShortenedDataRegionCount,
        ExtendedDataRegionCount,
        ShortenedDataGapCount,
        ExtendedDataGapCount,
        ReorderedRegionRows,
        DuplicatedRegionRow,
        ReorderedGapRows,
        DuplicatedGapRow,
        DuplicatedDataRegionRow,
        NonUTF8RegionSymbol,
        OverstatedSymbolLength,
        NonUTF8DataRegionSymbol,
        OverstatedDataSymbolLength,
        TrailingByte,
    }
}
