[package]
name = "omega-allocation-legality-to-literal-folds"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_allocation_legality_to_literal_folds"
path = "src/lib.rs"

[dependencies]
omega-live-ranges-to-allocation-legality = { path = "../omega-live-ranges-to-allocation-legality" }
omega-optimization-core = { path = "../../representations/omega-optimization-core" }
omega-regalloc = { path = "../omega-regalloc" }
omega-selected-instructions = { path = "../../representations/omega-selected-instructions" }
