[package]
name = "assembled-syntax-to-checked-compilation"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "assembled_syntax_to_checked_compilation"
path = "src/lib.rs"

[dependencies]
arena = { path = "../../../psi/foundation/arena" }
artifacts = { path = "../../tooling/artifacts" }
backend-plan = { path = "../../backend/plans/backend-plan" }
build-declarations = { path = "../../build/build-declarations" }
build-evaluation = { path = "../../build/build-evaluation" }
build-output = { path = "../../build/build-output" }
build-time-evaluation = { path = "../../../psi/semantics/build-time-evaluation" }
calling-conventions = { path = "../../representations/calling-conventions" }
checked-interpreter = { path = "../../../psi/semantics/checked-interpreter" }
checked-trees = { path = "../../../psi/representations/checked-trees" }
checked-trees-to-lowered-psi = { path = "../../../psi/pipeline/checked-trees-to-lowered-psi" }
compilation-report = { path = "../../compiler/compilation-report" }
diagnostics = { path = "../../../psi/foundation/diagnostics" }
effects = { path = "../../representations/effects" }
language-semantics = { path = "../../../psi/foundation/language-semantics" }
optimization-core = { path = "../../representations/optimization-core" }
package-compilation = { path = "../../build/package-compilation" }
provider-planning = { path = "../../build/provider-planning" }
representation-planning = { path = "../../build/representation-planning" }
selected-dispatch = { path = "../../build/selected-dispatch" }
semantic-vocabulary = { path = "../../../psi/foundation/semantic-vocabulary" }
source = { path = "../../../psi/foundation/source" }
source-files-to-assembled-syntax = { path = "../source-files-to-assembled-syntax" }
symbol-resolved-trees = { path = "../../../psi/representations/symbol-resolved-trees" }
symbol-resolved-trees-to-typed-trees = { path = "../../../psi/pipeline/symbol-resolved-trees-to-typed-trees" }
symbols = { path = "../../../psi/foundation/symbols" }
syntax-trees = { path = "../../../psi/representations/syntax-trees" }
syntax-trees-to-symbol-resolved-trees = { path = "../../../psi/pipeline/syntax-trees-to-symbol-resolved-trees" }
target = { path = "../../representations/target" }
task-plans = { path = "../../representations/task-plans" }
terminal-production = { path = "../../../psi/compiler/terminal-production" }
trust-model = { path = "../../build/trust-model" }
typed-trees = { path = "../../../psi/representations/typed-trees" }
typed-trees-to-checked-trees = { path = "../../../psi/pipeline/typed-trees-to-checked-trees" }
validation = { path = "../../../psi/semantics/validation" }
