//! The installation error vocabulary.

use calling_conventions::MachineRegister;
use machine_code::SemanticCodeSite;
use semantic_vocabulary::{MachineId, OperationId};
use target::NativeTarget;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum InstallationError {
    InvalidMagic,
    UnsupportedFormatMarker(u16),
    UnsupportedVocabularyMarker(u16),
    InvalidArchitectureTag(u8),
    InvalidObjectFormatTag(u8),
    InvalidBoolean(u8),
    InvalidPresenceFlag(u8),
    NonzeroReservedField,
    UnexpectedEnd,
    TrailingBytes(usize),
    NonCanonicalEncoding,
    NonCanonicalSubsystem,
    MissingCoffSubsystem,
    UnexpectedSubsystem,
    UnsupportedTarget(NativeTarget),
    TargetPointerFactNotRepresentable,
    ZeroProfileDecision,
    ZeroComponentProgressManifestIdentity,
    ZeroComponentProgressAcceptanceIdentity,
    ZeroProviderPlan,
    DuplicateProviderPlan,
    DuplicateProviderExecution,
    ProviderExecutionOutsideSelectedClosure,
    NonCanonicalProviderPlanOrder,
    TooManyProviderPlans,
    TooManyInstalledFunctions,
    TooManyCompilerPrivateFunctions,
    TooManyStackCallFacts,
    InvalidForeignStackContribution,
    TooManyStructuralReturns,
    TooManyInternalUnitCalls,
    TooManyInternalUnitScalarCalls,
    TooManyDynamicConformanceTables,
    TooManyDynamicConformanceSlots,
    TooManyDynamicScalarCalls,
    TooManyStoredDynamicCalls,
    TooManyForwardedDynamicDescriptorAdapters,
    TooManyForwardedDynamicDescriptorTables,
    TooManyForwardedDynamicDescriptorSlots,
    TooManyForwardedDynamicDescriptorCalls,
    TooManyDynamicParameterCalls,
    TooManyForwardedDynamicParameterCalls,
    TooManyInternalUnitCallArguments,
    TooManyInternalUnitScalarCallArguments,
    TooManyInternalUnitCallClaims,
    TooManyScalarCallPlanValues,
    TooManyScalarCallPlanRegisters,
    TooManyUnitScalarHomes,
    TooManyUnitIntegerConstants,
    TooManyUnitAffineScalarRecords,
    InvalidUnitAffineScalarRecord,
    TooManyUnitStructuralScalarFieldStores,
    TooManyUnitWriteOnlyPrimitiveStores,
    TooManyScalarStructuralScalarFieldStores,
    TooManyUnitStructuralScalarFieldStoreBytes,
    TooManyUnitWriteOnlyPrimitiveStoreBytes,
    TooManyStructuralReturnParameters,
    TooManyStructuralReturnClaims,
    TooManyStructuralReturnCleanups,
    TooManyStructuralReturnReferenceSources,
    TooManyStructuralTypes,
    TooManyStructuralFields,
    TooManyStructuralCases,
    TooManyStructuralQualifications,
    TooManySemanticCodeAttributions,
    TooManyPortEffects,
    TooManyBoundarySettlements,
    TooManySettlementScalarArguments,
    TooManySettlementArguments,
    TooManySettlementArgumentPathSegments,
    SettlementArgumentFieldTooLong,
    TooManyCompletionReceipts,
    TooManyCompletionProviderCustody,
    TooManyCompletionClaimSources,
    SettlementOffsetNotRepresentable,
    FunctionOffsetNotRepresentable,
    CompilerPrivateFunctionOffsetNotRepresentable,
    StructuralReturnOffsetNotRepresentable,
    InternalUnitCallOffsetNotRepresentable,
    InstalledScalarOffsetNotRepresentable,
    SemanticCodeAttributionOffsetNotRepresentable,
    PortEffectOffsetNotRepresentable,
    ZeroFunctionIdentity,
    InvalidCompilerPrivateFunctionIdentity,
    InvalidCompilerPrivateFunctionRoleTag(u8),
    MissingCompilerPrivateFunctionAbi,
    ZeroStructuralReturnIdentity(&'static str),
    ZeroInternalUnitCallIdentity,
    ZeroStructuralCallScalarReturnIdentity(&'static str),
    ZeroInstalledScalarIdentity,
    InvalidStructuralMultiplicity(u8),
    InvalidStructuralAccess(u8),
    UnsupportedStructuralReturnShape,
    UnsupportedStructuralReturnPlacement,
    UnsupportedInternalUnitCallPlacement,
    UnsupportedStructuralReturnRegister(MachineRegister),
    InvalidStructuralReturnRegister(u8),
    InvalidStructuralReturnLocal,
    StructuralTypeIdentityTooLong,
    InvalidStructuralTypeIdentity,
    InvalidStructuralTypeShape,
    InvalidStructuralTypeShapeTag(u8),
    InvalidStructuralFieldTypeTag(u8),
    ZeroSemanticCodeAttributionIdentity(&'static str),
    InvalidSemanticCodeSiteTag(u8),
    InvalidCallSiteOwnerTag(u8),
    InvalidStructuralSourceLocationTag(u8),
    InvalidInternalUnitCallSourceTag(u8),
    InvalidInternalUnitStructuralSourceTag(u8),
    InvalidProviderCandidateRecord(terminal_codec::CodecError),
    InvalidScalarCallingPolicyTag(u8),
    InvalidScalarEntryControlTag(u8),
    InvalidScalarCallPlanRegister {
        class: u8,
        index: u8,
    },
    UnsupportedScalarCallPlan,
    UnsupportedInstalledFixedIntegerType,
    InvalidInstalledIntegerSignTag(u8),
    InvalidInstalledIntegerValueTag(u8),
    InvalidInstalledScalarSourceTag(u8),
    InvalidIeeeFloatFormatTag(u8),
    UnsupportedInstalledScalarSource,
    InvalidBoundaryRealizationTag,
    InvalidBoundaryExecutionTag,
    InvalidCleanupActionTag(u8),
    ZeroPortEffectIdentity(&'static str),
    ZeroSettlementIdentity(&'static str),
    InvalidSettlementArgumentPathTag(u8),
    InvalidSettlementArgumentField,
    ZeroProviderExecutionEvidence,
    NoInstalledFunctions,
    NonCanonicalInstalledFunctions,
    InvalidCompilerPrivateFunction,
    StructuralReturnMachineMissing(MachineId),
    InvalidStructuralReturn(MachineId),
    InvalidInternalUnitCall(MachineId),
    InvalidInternalUnitScalarCall(MachineId),
    InvalidImageSectionLayout,
    InvalidDynamicConformanceTable,
    InvalidDynamicCall(MachineId),
    InvalidStoredDynamicCall(MachineId),
    InvalidForwardedDynamicDescriptorAdapter,
    InvalidForwardedDynamicDescriptorTable,
    InvalidForwardedDynamicDescriptorCall(MachineId),
    InvalidUnitDynamicDescriptorJoin(MachineId),
    InvalidDynamicParameterCall(MachineId),
    InvalidForwardedDynamicParameterCall(MachineId),
    InvalidUnitWriteOnlyPrimitiveStore(MachineId),
    InvalidUnitStructuralScalarFieldStore(MachineId),
    InvalidUnitAffineCleanup(MachineId),
    InvalidScalarControlAffineCleanupCount(usize),
    SemanticCodeAttributionMachineMissing(MachineId),
    NonCanonicalSemanticCodeAttributionOrder,
    DuplicateSemanticCodeAttributionSite {
        machine: MachineId,
        site: SemanticCodeSite,
    },
    InvalidSemanticCodeAttribution {
        machine: MachineId,
        site: SemanticCodeSite,
    },
    SemanticCodeAttributionClosureMismatch,
    EffectMachineMissing(MachineId),
    NonCanonicalPortEffectOrder,
    DuplicatePortEffectOperation {
        machine: MachineId,
        operation: OperationId,
    },
    InvalidPortEffectOffset {
        machine: MachineId,
        operation: OperationId,
    },
    ProviderSettlementClosureMismatch,
    ProviderExecutionClosureMismatch,
    NonCanonicalBoundarySettlementOrder,
    DuplicateBoundarySettlementOperation {
        machine: MachineId,
        operation: OperationId,
    },
    InvalidBoundarySettlementOffset {
        machine: MachineId,
        operation: OperationId,
    },
    InvalidCompletionReceiptArgumentIndex {
        machine: MachineId,
        operation: OperationId,
    },
    InvalidCompletionReceiptCustody {
        machine: MachineId,
        operation: OperationId,
    },
    InvalidCompletionProviderCustody {
        machine: MachineId,
        operation: OperationId,
    },
    InvalidCompletionClaimSource,
    InvalidBoundaryResult,
    InvalidBoundaryScalarArgument,
    BoundaryRealizationMismatch {
        machine: MachineId,
        operation: OperationId,
    },
    CountNotRepresentable(&'static str),
    MissingCompilerTextValidation,
    InvalidCompilerTextDerivationDigest,
    /// The retained placed-region inventories do not replay over the exact
    /// final image bytes, leave image bytes unclassified, or break the
    /// thunk↔binding-slot pairing an imported image requires.
    InvalidImagePlacementCustody,
    ImageBindingMismatch,
}

impl std::fmt::Display for InstallationError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(formatter, "{self:?}")
    }
}

impl std::error::Error for InstallationError {}
