[package]
name = "omega-data-planning"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_data_planning"
path = "src/lib.rs"

[dependencies]
omega-calling-conventions = { path = "../../foundation/omega-calling-conventions" }
psi-checked-trees = { path = "../../../psi/representations/psi-checked-trees" }
omega-control-flow = { path = "../../representations/omega-control-flow" }
omega-runtime-abi = { path = "../../foundation/omega-runtime-abi" }
omega-state-calls = { path = "../omega-state-calls" }
omega-platform-interface = { path = "../omega-platform-interface" }
omega-runtime-branching = { path = "../omega-runtime-branching" }
omega-runtime-text = { path = "../omega-runtime-text" }
omega-state-storage = { path = "../omega-state-storage" }
omega-state-values = { path = "../omega-state-values" }
omega-target-operations = { path = "../../representations/omega-target-operations" }
psi-diagnostics = { path = "../../../psi/foundation/psi-diagnostics" }
psi-symbols = { path = "../../../psi/foundation/psi-symbols" }

[dev-dependencies]
omega-checked-trees-to-state-graph = { path = "../../pipeline/omega-checked-trees-to-state-graph" }
omega-state-graph = { path = "../../representations/omega-state-graph" }
omega-state-graph-to-control-flow = { path = "../../pipeline/omega-state-graph-to-control-flow" }
psi-source-files-to-tokens = { path = "../../../psi/pipeline/psi-source-files-to-tokens" }
psi-symbol-resolved-trees-to-typed-trees = { path = "../../../psi/pipeline/psi-symbol-resolved-trees-to-typed-trees" }
psi-syntax-trees-to-symbol-resolved-trees = { path = "../../../psi/pipeline/psi-syntax-trees-to-symbol-resolved-trees" }
psi-tokens-to-syntax-trees = { path = "../../../psi/pipeline/psi-tokens-to-syntax-trees" }
psi-typed-trees-to-checked-trees = { path = "../../../psi/pipeline/psi-typed-trees-to-checked-trees" }
psi-validation = { path = "../../../psi/semantics/psi-validation" }
