[package]
name = "omega-symbol-resolved-trees-to-typed-trees"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_symbol_resolved_trees_to_typed_trees"
path = "src/lib.rs"

[dependencies]
psi-symbol-resolved-trees-to-typed-trees = { path = "../../../psi-rs/pipeline/psi-symbol-resolved-trees-to-typed-trees" }
