[package]
name = "omega-cli"
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "omega"
path = "src/main.rs"
test = false

[dependencies]
omega-compiler = { path = "../../compiler/omega-rs/orchestration/omega-compiler" }
omega-core = { path = "../../compiler/omega-rs/foundation/omega-core" }
psi-checked-trees-to-terminal = { path = "../../compiler/psi-rs/pipeline/psi-checked-trees-to-terminal" }
psi-core = { path = "../../compiler/psi-rs/foundation/psi-core" }
psi-terminal = { path = "../../compiler/psi-rs/representations/psi-terminal" }
