#!/usr/bin/env python3
# bc2.py — a separately written Beta reference compiler (Beta source -> Alpha assembly)
# in Python against alpha/SEMANTICS.md and the Beta language, NOT ported from beta-lang-rs.
#
# HISTORICAL ROLE — this was once used by a DDC gate that has since been removed.
# It remains only as an optional differential compiler backend. Source
# recognition is owned by beta_parser.py and shared with meaning/refinement tools.
#
# TRUST STATUS: UNTRUSTED, exactly like elab.py / prover.py / tv-encode.py. Its output is CHECKED, never
# trusted. A disagreement with canonical meaning or another implementation is a
# useful diagnostic, but agreement grants no authority. Python is an implementation
# detail of this reference tool, not part of the runtime TCB.
#
# Reads Beta on stdin, writes Alpha assembly on stdout — same interface as beta-lang-rs and bc.beta.
#
# SLICES SO FAR:
#   1  a single `proc main()` with `let` locals, assignment, `+ - * / %` (parens + precedence), `return`.
#   2  the six comparisons (materialised as 0/1) and CFG control flow: `state NAME { ... }` basic blocks
#      linked by `to STATE` / `to STATE when (cond)` (Beta has no if/while).
# Grown slice by slice toward the full language (procs/params/calls/recursion, byte[]/word[] memory,
# char/string literals, read_byte/write_byte) until it compiles bc.beta itself.
#
# Codegen is a straightforward stack machine over the register ISA, mirroring the shape the lattice's
# other Beta compilers use (r15 = data stack, r14 = frame pointer, r0 = accumulator, r1 = rhs; the ISA's
# own `sp` handles call/ret return addresses). Emitting the same shape is fine — independence lives in the
# CODE (a fresh implementation), and the gate checks behaviour, not that we differ.
import sys

from beta_parser import Parser, lex

# ---- codegen -----------------------------------------------------------------------------------
BINOP = {'+': 'add', '-': 'sub', '*': 'mul', '/': 'div', '%': 'mod'}

class Gen:
    def __init__(self):
        self.out = []
        self.lc = 0                                    # fresh-label counter (_L0, _L1, ...)
        self.curproc = None
        self.strings = []                              # string literals -> _strN db data (emitted at end)

    def emit(self, s):
        self.out.append('        ' + s)

    def label(self, s):
        self.out.append(s + ':')

    def newlabel(self):
        self.lc += 1
        return f'_L{self.lc - 1}'

    def program(self, procs):
        self.out.append('; generated by bc2.py (Beta -> Alpha assembly; independent second path, D5)')
        self.emit('imm   r15, 1048576')               # data stack pointer
        self.emit('imm   r14, 1048576')               # frame pointer
        self.emit('call  main')
        self.emit('halt  r0')
        for p in procs:
            self.proc(p)
        if self.strings:                               # once-per-program string runtime + data
            self.write_str_helper()
            for idx, s in enumerate(self.strings):
                self.label(f'_str{idx}')
                self.emit(f'db "{s}"')
        return '\n'.join(self.out) + '\n'

    def write_str_helper(self):
        # __write_str(r0 = addr, r1 = length): write r1 bytes starting at r0.
        self.label('__write_str')
        self.label('__ws_loop')
        self.emit('imm   r3, 0')
        self.emit('jeq   r1, r3, __ws_done')
        self.emit('loadb r2, r0')
        self.emit('write r2')
        self.emit('imm   r3, 1')
        self.emit('add   r0, r3')
        self.emit('sub   r1, r3')
        self.emit('jmp   __ws_loop')
        self.label('__ws_done')
        self.emit('ret')

    @staticmethod
    def strbytes(inner):
        """decoded byte length of a string literal (each \\X escape is one byte)"""
        n = i = 0
        while i < len(inner):
            i += 2 if inner[i] == '\\' else 1
            n += 1
        return n

    def collect_lets(self, body, slots):
        """prescan (source order, incl. inside states) so the frame is sized once up front"""
        for s in body:
            if s[0] == 'let' and s[1] not in slots:
                slots[s[1]] = len(slots)
            elif s[0] == 'state':
                self.collect_lets(s[2], slots)

    def proc(self, p):
        _, name, params, body = p
        self.curproc = name
        slots = {}
        for k, pname in enumerate(params):             # params occupy the first slots
            slots[pname] = k
        self.collect_lets(body, slots)
        self.label(name)
        self.emit('imm   r5, 8')                       # prologue: push old fp, fp = sp
        self.emit('sub   r15, r5')
        self.emit('store r15, r14')
        self.emit('mov   r14, r15')
        if slots:
            self.emit(f'imm   r5, {8 * len(slots)}')    # allocate frame for all locals
            self.emit('sub   r15, r5')
        for k in range(len(params)):                    # spill incoming arg regs r0..r3 into param slots
            self.emit('mov   r5, r14')
            self.emit(f'imm   r4, {8 * (k + 1)}')
            self.emit('sub   r5, r4')
            self.emit(f'store r5, r{k}')
        # entry statements run, then fall into the first state; each state is a labelled block.
        for s in body:
            if s[0] == 'state':
                self.label(f'{name}__{s[1]}')
                for st in s[2]:
                    self.stmt(st, slots)
            else:
                self.stmt(s, slots)
        self.epilogue()                                # fallthrough epilogue (mirrors the on-ramp)

    def off(self, slots, name):
        if name not in slots:
            raise SyntaxError(f'bc2: unknown name {name!r}')
        return 8 * (slots[name] + 1)                    # fp - 8*(slot+1)

    def stmt(self, s, slots):
        if s[0] in ('let', 'assign'):
            self.expr(s[2], slots)                       # value -> r0
            self.emit('mov   r1, r14')                   # store r0 to fp - off
            self.emit(f'imm   r2, {self.off(slots, s[1])}')
            self.emit('sub   r1, r2')
            self.emit('store r1, r0')
            return
        if s[0] == 'return':
            self.expr(s[1], slots)                        # value -> r0
            self.epilogue()
            return
        if s[0] == 'emit':                                # emit("...") -> write the string via __write_str
            idx = len(self.strings)
            self.strings.append(s[1])
            self.emit(f'imm   r0, _str{idx}')
            self.emit(f'imm   r1, {self.strbytes(s[1])}')
            self.emit('call  __write_str')
            return
        if s[0] == 'callstmt':                            # a call used for effect; result in r0 discarded
            self.expr(s[1], slots)
            return
        if s[0] == 'memset':                              # word[addr] = val  /  byte[addr] = val
            _, kind, addr, val = s
            self.expr(addr, slots)                        # addr -> r0
            self.emit('imm   r2, 8')                      # push addr
            self.emit('sub   r15, r2')
            self.emit('store r15, r0')
            self.expr(val, slots)                         # val -> r0
            self.emit('load  r1, r15')                    # pop addr -> r1
            self.emit('imm   r5, 8')
            self.emit('add   r15, r5')
            self.emit(f'{"store" if kind == "word" else "storeb"} r1, r0')
            return
        if s[0] == 'goto':                                # to STATE [when (cond)]
            _, target, cond = s
            dest = f'{self.curproc}__{target}'
            if cond is None:
                self.emit(f'jmp   {dest}')
            else:
                self.expr(cond, slots)                     # cond -> r0 (0/1)
                skip = self.newlabel()
                self.emit(f'jz    r0, {skip}')             # cond false -> fall through
                self.emit(f'jmp   {dest}')                 # cond true  -> take the transition
                self.label(skip)
            return
        raise SyntaxError(f'bc2: bad stmt {s}')

    def expr(self, e, slots):
        if e[0] == 'num':
            self.emit(f'imm   r0, {e[1]}')
            return
        if e[0] == 'var':
            self.emit('mov   r0, r14')
            self.emit(f'imm   r1, {self.off(slots, e[1])}')
            self.emit('sub   r0, r1')
            self.emit('load  r0, r0')
            return
        if e[0] == 'mem':                                 # word[addr] / byte[addr] read
            _, kind, addr = e
            self.expr(addr, slots)                        # addr -> r0
            self.emit(f'{"load " if kind == "word" else "loadb"} r0, r0')
            return
        if e[0] == 'call':                                # name(args): push args L->R, pop reverse to r0..
            _, name, args = e
            if name == 'read_byte':                       # intrinsic: next input byte (0xFFFF..FF at EOF) -> r0
                self.emit('read  r0')
                return
            if name == 'write_byte':                      # intrinsic: append low byte of the arg to output
                self.expr(args[0], slots)
                self.emit('write r0')
                return
            if len(args) > 4:
                raise SyntaxError(f'bc2: >4 args unsupported (call {name})')
            for a in args:
                self.expr(a, slots)                       # arg -> r0
                self.emit('imm   r2, 8')                  # push it (args share the data stack, popped below)
                self.emit('sub   r15, r2')
                self.emit('store r15, r0')
            for i in range(len(args) - 1, -1, -1):        # top of stack is the last arg -> highest reg
                self.emit(f'load  r{i}, r15')
                self.emit('imm   r5, 8')
                self.emit('add   r15, r5')
            self.emit(f'call  {name}')                    # result in r0
            return
        if e[0] == 'bin':
            _, op, a, b = e
            self.expr(a, slots)                           # A -> r0
            self.emit('imm   r2, 8')                      # push A
            self.emit('sub   r15, r2')
            self.emit('store r15, r0')
            self.expr(b, slots)                           # B -> r0
            self.emit('mov   r1, r0')                     # B -> r1
            self.emit('load  r0, r15')                    # pop A -> r0
            self.emit('imm   r5, 8')
            self.emit('add   r15, r5')
            if op in BINOP:
                self.emit(f'{BINOP[op]:5} r0, r1')        # r0 = A op B (arithmetic)
            else:
                self.cmp(op)                              # r0 = (A op B) ? 1 : 0
            return
        raise SyntaxError(f'bc2: bad expr {e}')

    # materialise a comparison of r0 (A) and r1 (B) into r0 as 0/1, using jlt (signed <) and jeq.
    # <,>,== jump straight to the true case; <=,>=,!= are the negations (jump to the false case).
    def cmp(self, op):
        JUMP = {'<':  'jlt   r0, r1', '>':  'jlt   r1, r0', '==': 'jeq   r0, r1',
                '<=': 'jlt   r1, r0', '>=': 'jlt   r0, r1', '!=': 'jeq   r0, r1'}
        true_on_jump = op in ('<', '>', '==')
        lj, lend = self.newlabel(), self.newlabel()
        self.emit(f'{JUMP[op]}, {lj}')
        self.emit(f'imm   r0, {0 if true_on_jump else 1}')   # fall-through case
        self.emit(f'jmp   {lend}')
        self.label(lj)
        self.emit(f'imm   r0, {1 if true_on_jump else 0}')   # jump-taken case
        self.label(lend)

    def epilogue(self):
        self.emit('mov   r15, r14')                       # sp = fp; pop old fp; ret
        self.emit('load  r14, r15')
        self.emit('imm   r2, 8')
        self.emit('add   r15, r2')
        self.emit('ret')

def main():
    src = sys.stdin.read()
    procs = Parser(lex(src)).parse()
    sys.stdout.write(Gen().program(procs))

if __name__ == '__main__':
    main()
