[package]
name = "omega-assigned-target-operations"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_assigned_target_operations"
path = "src/lib.rs"

[dependencies]
omega-runtime-abi = { path = "../../backend/runtime/omega-runtime-abi" }
omega-calling-conventions = { path = "../omega-calling-conventions" }
omega-target = { path = "../omega-target" }
omega-target-operations = { path = "../omega-target-operations" }
psi-core = { path = "../../../psi/foundation/psi-core" }
psi-terminal = { path = "../../../psi/representations/psi-terminal" }
