[package]
name = "omega-machine-optimizer"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_machine_optimizer"
path = "src/lib.rs"

[dependencies]
omega-optimization-core = { path = "../../../representations/omega-optimization-core" }
omega-optimization-unit = { path = "../../../representations/omega-optimization-unit" }
omega-regalloc = { path = "../omega-regalloc" }
omega-register-model = { path = "../../../representations/omega-register-model" }
omega-target = { path = "../../../representations/omega-target" }
omega-selected-instructions = { path = "../../../representations/omega-selected-instructions" }
omega-target-operations = { path = "../../../representations/omega-target-operations" }
psi-core = { path = "../../../../psi/foundation/psi-core" }
psi-terminal = { path = "../../../../psi/representations/psi-terminal" }
sha2 = "0.10.9"

[dev-dependencies]
omega-isa-x86_64 = { path = "../../../backend/instruction_set_architectures/omega-isa-x86_64" }
