[package]
name = "omega-emission-planning"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_emission_planning"
path = "src/lib.rs"

[dependencies]
omega-artifacts = { path = "../../orchestration/omega-artifacts" }
omega-calling-conventions = { path = "../../foundation/omega-calling-conventions" }
omega-checked-trees = { path = "../../representations/omega-checked-trees" }
omega-control-flow = { path = "../../representations/omega-control-flow" }
omega-core = { path = "../../foundation/omega-core" }
omega-image-emission = { path = "../images/omega-image-emission" }
omega-layout = { path = "../omega-layout" }
omega-machine-bytes = { path = "../../representations/omega-machine-bytes" }
omega-machine-instructions = { path = "../../representations/omega-machine-instructions" }
omega-object-file = { path = "../object/omega-object-file" }
omega-platform-interface = { path = "../omega-platform-interface" }
omega-runtime-bodies = { path = "../omega-runtime-bodies" }
omega-runtime-branching = { path = "../omega-runtime-branching" }
omega-runtime-dispatch-loop = { path = "../omega-runtime-dispatch-loop" }
omega-runtime-storage = { path = "../omega-runtime-storage" }
omega-runtime-text = { path = "../omega-runtime-text" }
omega-state-calls = { path = "../omega-state-calls" }
omega-state-graph = { path = "../../representations/omega-state-graph" }
omega-state-guards = { path = "../omega-state-guards" }
omega-state-schedule = { path = "../omega-state-schedule" }
omega-state-storage = { path = "../omega-state-storage" }
omega-state-values = { path = "../omega-state-values" }
omega-target = { path = "../../foundation/omega-target" }
omega-target-operations = { path = "../../representations/omega-target-operations" }
omega-typed-trees = { path = "../../representations/omega-typed-trees" }
