[package]
name = "psi-build-time-evaluation"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "psi_build_time_evaluation"
path = "src/lib.rs"

[dependencies]
psi-checked-interpreter = { path = "../psi-checked-interpreter" }
psi-diagnostics = { path = "../../foundation/psi-diagnostics" }
psi-effects = { path = "../../representations/psi-effects" }
psi-language-semantics = { path = "../../foundation/psi-language-semantics" }
psi-symbols = { path = "../../foundation/psi-symbols" }
psi-typed-trees = { path = "../../representations/psi-typed-trees" }
psi-typed-trees-to-checked-trees = { path = "../../pipeline/psi-typed-trees-to-checked-trees" }
