[package]
name = "omega-fixed-view-copies-to-reanalyzed-legality"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_fixed_view_copies_to_reanalyzed_legality"
path = "src/lib.rs"

[dependencies]
omega-allocation-legality-to-fixed-view-copies = { path = "../omega-allocation-legality-to-fixed-view-copies" }
omega-regalloc = { path = "../omega-regalloc" }
