[package]
name = "omega-state-graph"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_state_graph"
path = "src/lib.rs"

[dependencies]
omega-checked-trees = { path = "../omega-checked-trees" }
omega-control-flow = { path = "../omega-control-flow" }
omega-core = { path = "../../foundation/omega-core" }
psi-facts = { path = "../../../psi-rs/representations/psi-facts" }
psi-typed-trees = { path = "../../../psi-rs/representations/psi-typed-trees" }
