[package]
name = "omega-image"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_image"
path = "src/lib.rs"

[dependencies]
omega-core = { path = "../../../foundation/omega-core" }
omega-object-file = { path = "../../object/omega-object-file" }
omega-target = { path = "../../../foundation/omega-target" }
