[package]
name = "selected-instructions-to-selected-instructions"
edition.workspace = true
license.workspace = true
version.workspace = true

[features]
test-support = []

[dependencies]
target-operations-to-selected-instructions = { path = "../03_target-operations-to-selected-instructions" }
terminal-psi-to-abstract-operations = { path = "../00_terminal-psi-to-abstract-operations" }
abstract-operations-to-target-operations = { path = "../02_abstract-operations-to-target-operations" }
symbols = { path = "../../../psi/foundation/symbols" }
optimization-core = { path = "../../../psi/optimization-core" }
target = { path = "../../../psi/target" }
semantic-vocabulary = { path = "../../../psi/foundation/semantic-vocabulary" }
terminal-psi = { path = "../../../psi/terminal-psi" }
terminal-codec = { path = "../../../psi/terminal-codec" }
sha2 = "0.10.9"

[dev-dependencies]
mimalloc = { version = "0.1", default-features = false }
