[package]
name = "omega-relocations"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_relocations"
path = "src/lib.rs"

[dependencies]
omega-assigned-target-operations = { path = "../../../representations/omega-assigned-target-operations" }
omega-calling-conventions = { path = "../../../foundation/omega-calling-conventions" }
psi-arena = { path = "../../../../psi/foundation/psi-arena" }
psi-diagnostics = { path = "../../../../psi/foundation/psi-diagnostics" }
omega-executable-installation = { path = "../../../foundation/omega-executable-installation" }
omega-instruction-selection = { path = "../../omega-instruction-selection" }
omega-isa-aarch64 = { path = "../../instruction_set_architectures/omega-isa-aarch64" }
omega-isa-x86_64 = { path = "../../instruction_set_architectures/omega-isa-x86_64" }
omega-control-flow = { path = "../../../representations/omega-control-flow" }
psi-language-semantics = { path = "../../../../psi/foundation/psi-language-semantics" }
psi-layout-plans = { path = "../../../../psi/foundation/psi-layout-plans" }
omega-machine-bytes = { path = "../../../representations/omega-machine-bytes" }
omega-object-file = { path = "../omega-object-file" }
omega-target = { path = "../../../foundation/omega-target" }
omega-target-operations = { path = "../../../representations/omega-target-operations" }

[dev-dependencies]
psi-symbols = { path = "../../../../psi/foundation/psi-symbols" }
