[package]
name = "omega-object-file"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_object_file"
path = "src/lib.rs"

[dependencies]
omega-core = { path = "../../../foundation/omega-core" }
omega-function-identity = { path = "../../../foundation/omega-function-identity" }
psi-arena = { path = "../../../../psi/foundation/psi-arena" }
omega-target = { path = "../../../foundation/omega-target" }
