#!/usr/bin/env sh
# Canonical repository paths for the compiler lattice.
#
# This file is replaceable invocation plumbing. It names source owners only;
# it does not perform a translation or contribute semantics to a compiler edge.

if [ -z "${OMEGA_REPO_ROOT:-}" ] || [ ! -f "$OMEGA_REPO_ROOT/TASKS_BOOTSTRAP.md" ]; then
  echo "lattice paths: OMEGA_REPO_ROOT is not an Omega repository root" >&2
  return 2
fi

OMEGA_PATH_ALPHA=$OMEGA_REPO_ROOT/source/alpha
OMEGA_PATH_ALPHA_ASSEMBLER=$OMEGA_PATH_ALPHA/assembler
OMEGA_PATH_BETA=$OMEGA_REPO_ROOT/source/beta
OMEGA_PATH_BETA_COMPILER=$OMEGA_PATH_BETA/compiler
OMEGA_PATH_BETA_COMPILER_SOURCE=$OMEGA_PATH_BETA_COMPILER/beta_compiler.alpha
OMEGA_PATH_BETA_COMPILER_TAPE=$OMEGA_PATH_BETA_COMPILER/beta_compiler_bytecode.tape
OMEGA_PATH_GAMMA=$OMEGA_REPO_ROOT/source/gamma
OMEGA_PATH_GAMMA_COMPILER=$OMEGA_PATH_GAMMA/compiler
OMEGA_PATH_DELTA=$OMEGA_REPO_ROOT/source/delta
OMEGA_PATH_DELTA_COMPILER=$OMEGA_PATH_DELTA/compiler
OMEGA_PATH_OMEGA=$OMEGA_REPO_ROOT/source/omega
OMEGA_PATH_ALPHA_CHECKER=$OMEGA_PATH_ALPHA/checker

export OMEGA_REPO_ROOT
export OMEGA_PATH_ALPHA OMEGA_PATH_ALPHA_ASSEMBLER OMEGA_PATH_BETA
export OMEGA_PATH_BETA_COMPILER OMEGA_PATH_BETA_COMPILER_SOURCE
export OMEGA_PATH_BETA_COMPILER_TAPE OMEGA_PATH_GAMMA
export OMEGA_PATH_GAMMA_COMPILER OMEGA_PATH_DELTA OMEGA_PATH_DELTA_COMPILER
export OMEGA_PATH_OMEGA
export OMEGA_PATH_ALPHA_CHECKER
