#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum PunctuationKind {
    Ampersand,
    AndAnd,
    Apostrophe,
    Arrow,
    Asterisk,
    Caret,
    Colon,
    ColonColon,
    Comma,
    Dot,
    DotDot,
    DotDotEqual,
    Equal,
    EqualEqual,
    Exclamation,
    ExclamationEqual,
    Greater,
    GreaterEqual,
    GreaterGreater,
    Hash,
    LeftBrace,
    LeftBracket,
    LeftParen,
    Less,
    LessEqual,
    LessLess,
    Minus,
    Percent,
    Pipe,
    PipePipe,
    Plus,
    PlusEqual,
    MinusEqual,
    AsteriskEqual,
    SlashEqual,
    PercentEqual,
    RightBrace,
    RightBracket,
    RightParen,
    Semicolon,
    Slash,
    Tilde,
    #[default]
    Unknown,
}

impl PunctuationKind {
    pub fn ordered_lexemes() -> &'static [(&'static str, Self)] {
        &[
            ("::", Self::ColonColon),
            ("->", Self::Arrow),
            ("..=", Self::DotDotEqual),
            ("..", Self::DotDot),
            ("==", Self::EqualEqual),
            ("!=", Self::ExclamationEqual),
            ("<<", Self::LessLess),
            ("<=", Self::LessEqual),
            (">>", Self::GreaterGreater),
            (">=", Self::GreaterEqual),
            ("&&", Self::AndAnd),
            ("||", Self::PipePipe),
            ("+=", Self::PlusEqual),
            ("-=", Self::MinusEqual),
            ("*=", Self::AsteriskEqual),
            ("/=", Self::SlashEqual),
            ("%=", Self::PercentEqual),
            ("&", Self::Ampersand),
            ("'", Self::Apostrophe),
            ("*", Self::Asterisk),
            ("^", Self::Caret),
            (":", Self::Colon),
            (",", Self::Comma),
            (".", Self::Dot),
            ("=", Self::Equal),
            ("!", Self::Exclamation),
            (">", Self::Greater),
            ("#", Self::Hash),
            ("{", Self::LeftBrace),
            ("[", Self::LeftBracket),
            ("(", Self::LeftParen),
            ("<", Self::Less),
            ("-", Self::Minus),
            ("%", Self::Percent),
            ("|", Self::Pipe),
            ("+", Self::Plus),
            ("}", Self::RightBrace),
            ("]", Self::RightBracket),
            (")", Self::RightParen),
            (";", Self::Semicolon),
            ("/", Self::Slash),
            ("~", Self::Tilde),
        ]
    }

    pub fn from_lexeme(lexeme: &str) -> Option<Self> {
        Some(match lexeme {
            "&" => Self::Ampersand,
            "&&" => Self::AndAnd,
            "'" => Self::Apostrophe,
            "->" => Self::Arrow,
            "*" => Self::Asterisk,
            "^" => Self::Caret,
            ":" => Self::Colon,
            "::" => Self::ColonColon,
            "," => Self::Comma,
            "." => Self::Dot,
            ".." => Self::DotDot,
            "..=" => Self::DotDotEqual,
            "=" => Self::Equal,
            "==" => Self::EqualEqual,
            "!" => Self::Exclamation,
            "!=" => Self::ExclamationEqual,
            ">" => Self::Greater,
            ">=" => Self::GreaterEqual,
            ">>" => Self::GreaterGreater,
            "#" => Self::Hash,
            "{" => Self::LeftBrace,
            "[" => Self::LeftBracket,
            "(" => Self::LeftParen,
            "<" => Self::Less,
            "<=" => Self::LessEqual,
            "<<" => Self::LessLess,
            "-" => Self::Minus,
            "%" => Self::Percent,
            "|" => Self::Pipe,
            "||" => Self::PipePipe,
            "+" => Self::Plus,
            "+=" => Self::PlusEqual,
            "-=" => Self::MinusEqual,
            "*=" => Self::AsteriskEqual,
            "/=" => Self::SlashEqual,
            "%=" => Self::PercentEqual,
            "}" => Self::RightBrace,
            "]" => Self::RightBracket,
            ")" => Self::RightParen,
            ";" => Self::Semicolon,
            "/" => Self::Slash,
            "~" => Self::Tilde,
            _ => return None,
        })
    }
}
