[package]
name = "omega-control-flow"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_control_flow"
path = "src/lib.rs"

[dependencies]
omega-core = { path = "../../foundation/omega-core" }
psi-symbols = { path = "../../../psi-rs/foundation/psi-symbols" }
psi-checked-trees = { path = "../../../psi-rs/representations/psi-checked-trees" }
psi-facts = { path = "../../../psi-rs/representations/psi-facts" }
psi-language-semantics = { path = "../../../psi-rs/foundation/psi-language-semantics" }
psi-numerics = { path = "../../../psi-rs/foundation/psi-numerics" }
psi-typed-trees = { path = "../../../psi-rs/representations/psi-typed-trees" }
