[package]
name = "psi-build-time-evaluation"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "psi_build_time_evaluation"
path = "src/lib.rs"

[dependencies]
psi-arena = { path = "../../foundation/psi-arena" }
psi-access-plans = { path = "../../foundation/psi-access-plans" }
psi-checked-interpreter = { path = "../psi-checked-interpreter" }
psi-core = { path = "../../foundation/psi-core" }
psi-diagnostics = { path = "../../foundation/psi-diagnostics" }
psi-effects = { path = "../../representations/psi-effects" }
psi-language-core = { path = "../../foundation/psi-language-core" }
psi-language-semantics = { path = "../../foundation/psi-language-semantics" }
psi-layout-plans = { path = "../../foundation/psi-layout-plans" }
psi-numerics = { path = "../../foundation/psi-numerics" }
psi-source = { path = "../../foundation/psi-source" }
psi-symbol-resolved-trees = { path = "../../representations/psi-symbol-resolved-trees" }
psi-symbols = { path = "../../foundation/psi-symbols" }
psi-symbol-resolved-trees-to-typed-trees = { path = "../../pipeline/psi-symbol-resolved-trees-to-typed-trees" }
psi-syntax-trees = { path = "../../representations/psi-syntax-trees" }
psi-syntax-trees-to-symbol-resolved-trees = { path = "../../pipeline/psi-syntax-trees-to-symbol-resolved-trees" }
psi-typed-trees = { path = "../../representations/psi-typed-trees" }
psi-typed-trees-to-checked-trees = { path = "../../pipeline/psi-typed-trees-to-checked-trees" }

[dev-dependencies]
psi-source-files-to-tokens = { path = "../../pipeline/psi-source-files-to-tokens" }
psi-tokens-to-syntax-trees = { path = "../../pipeline/psi-tokens-to-syntax-trees" }
