[package]
name = "omega-register-homes"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
omega-register-model = { path = "../omega-register-model" }
omega-selected-instructions = { path = "../omega-selected-instructions" }
psi-core = { path = "../../../psi/foundation/psi-core" }
sha2 = "0.10.9"
