#![forbid(unsafe_code)]

//! Self-contained, target-neutral Terminal Psi.
//!
//! Begin at [`terminal_module`]: one current program with concept-owned
//! vocabulary. Optimizations precede publication; target realization follows it.
//! Canonical serialization and independent verification have separate owners.

mod artifacts;
pub mod terminal_module;
pub use artifacts::{
    AdmissionEvidence, AdmissionKind, CertificateEnvelope, CheckedProgramEntryFusedServiceField,
    CheckedProgramEntryReceiverCleanup, CheckedProgramEntryReceiverEligibility,
    CheckedProgramEntryReceiverProjection, CheckedProgramEntryTerminalReceipt,
    ControlCycleEvidence, CorrelatedAffineBranchWitness, CorrelatedAffineStepWitness,
    CrashCertificate, CrashObligationEvidence, CrashObligationOwner, DebugFileId, DebugSite,
    DebugSourceDigest, DebugSourceFile, DebugSourceOrigin, DebugSourceSpan, DebugSubject,
    EvidenceProducerProvenance, EvidenceProducerRealization, EvidenceProducerRowSource,
    EvidenceRoute, IntegerAffineWitness, IntegerCastChainWitness,
    IntegerCorrelatedForbiddenRootWitness, ObligationEvidence, PrimitiveJudgment, ProofBundle,
    ProofNode, ProofRule, ProofSystemMarker, RecursiveComponentCertificate,
    RecursiveComponentEvidence, RecursiveEdgeCertificate, TerminalDebugMap,
};

pub use language_core::BindingRelevance;
pub use terminal_module::{
    Block, BoundaryContentGuarantee, BoundaryMachineDeclaration, BoundaryMachineResult,
    BoundaryParameterKind, BoundaryStructuralResultDeclaration, ByteSequenceCarrier,
    ClaimContentProjection, ClaimTransfer, ClosedConformanceApplication,
    ClosedConformanceApplicationCommitment, ClosedConformanceCallableResult,
    ClosedConformanceParameterBinding, ClosedConformanceParameterKind,
    ClosedConformanceRealizationCallable, ClosedConformanceRow, ClosedReachApplication,
    ClosedReachArgument, ClosedReachCall, ClosedReachCallApplication, ClosedReachMachineBinding,
    ClosedReachParameter, ClosedReachSchema, CompletionReceipt, ContentConservationGuarantee,
    ContentEntryClaim, ContentIdentityReshuffle, ContentPartitionComposition,
    ContentPlaceSubstitution, ContractClause, CrashCause, CrashPredicateTerm, CrashRouteBucket,
    CrashRouteGuard, DirectBlockFloatParameter, DirectCallFloatResult, DirectMachineFloatParameter,
    DirectMachineFloatResult, DirectOperationFloatResult, DirectStructuralFloatLeaf, EntryClaim,
    ErasedProofFormal, EvidenceContractLane, EvidenceContractLaneKind, EvidenceInterfaceIdentity,
    EvidenceProjectionIdentity, EvidenceRequirementIdentity, EvidenceTermDeclaration,
    FloatMeaningEqualityProposition, FloatMeaningProjection, FloatMeaningProjectionOperation,
    FloatMeaningSource, FloatProjectionContractIdentity, FloatProjectionInput,
    FloatProjectionInputId, FloatSemanticApplication, FloatSemanticApplicationOperand,
    FloatSemanticContractIdentity, InstallationReachDependency, MachineContract,
    NominalAffineCleanup, Operation, OperationKind, OperationProjection, OperationResult,
    OutcomeSpecificCallEvidence, OutcomeSpecificCallEvidenceValidity,
    OutcomeSpecificCallResultSubstitution, OutcomeSpecificEnsure, OutcomeSpecificEvidence,
    OutcomeSpecificEvidenceUse, OutcomeSpecificGuard, ProgramLocalRootIntroductionSchema,
    ProofOnlyValueType, ProofOutput, ProofOutputCall, ProofOutputEvidenceArgument,
    ProofOutputRuntimeCall, ProofOutputRuntimeResult, ProofPropositionId, ProofValueDeclaration,
    ProofValueId, PropositionApplicationIdentity, PropositionBinderArgumentIdentity,
    PropositionBinderArgumentKind, PropositionBinderDeclaration, PropositionBinderKind,
    PropositionDeclaration, PropositionEvidence, ProviderCandidateConformance,
    ProviderParameterRefinement, ProviderRefinement, ProviderSignature, ProviderSignatureParameter,
    QuotientCorrespondenceIdentity, RecordFieldInitializer, RecordFieldValue,
    ResultQualificationEstablishment, RetainedBorrowContentProjection, RetainedBorrowCustody,
    RetainedBorrowPlace, RetainedBorrowPlaceRoot, RetainedQuotientCorrespondence,
    ScalarBlockInvariant, ScalarBlockInvariantArrival, ScalarCaseField, ScalarDomainDeclaration,
    ScalarDomainEstablishmentRoute, ScalarFloatRange, ScalarIntegerRange,
    ScalarQualificationCatalog, ScalarQualificationCoercion, ScalarQualificationSet,
    SemanticFingerprint, ServiceDeclaration, StaticRequirementDispatch, StructuralAccess,
    StructuralAffineDiscard, StructuralArgument, StructuralCaseDeclaration,
    StructuralCaseSuccessorEdge, StructuralContentProjection, StructuralDomainDeclaration,
    StructuralDomainRequirement, StructuralEstablishmentRoute, StructuralFieldDeclaration,
    StructuralFieldType, StructuralMultiplicity, StructuralOperationResult,
    StructuralParameterDeclaration, StructuralPathQualification, StructuralPathSegment,
    StructuralPlaceDeclaration, StructuralReferenceResultSource, StructuralResultClaimBinding,
    StructuralResultClaimTransfer, StructuralResultDeclaration, StructuralTypeDeclaration,
    StructuralTypeShape, SuccessorEdge, TerminalAffineCleanupAction, TerminalBlockNaturalRank,
    TerminalBorrowBoundarySource, TerminalBorrowOwnerSegment, TerminalBorrowPlace,
    TerminalBorrowPlaceSegment, TerminalDirectDynamicDispatch, TerminalDynamicConformanceSelection,
    TerminalDynamicDescriptorArgument, TerminalDynamicDescriptorParameter,
    TerminalDynamicDescriptorSource, TerminalDynamicDispatchCatalog, TerminalDynamicRequirement,
    TerminalIndirectDynamicDispatch, TerminalMachine, TerminalMachineResult, TerminalModule,
    TerminalNaturalCycle, TerminalNaturalRankComparison, TerminalNaturalRankEdge,
    TerminalObservationSchema, TerminalOperationCrashContract, TerminalParameterDynamicDispatch,
    TerminalPlacedViewInput, TerminalProofRankingRelation, TerminalProofRecursiveCallSite,
    TerminalProofRecursiveComponent, TerminalProofRecursiveEdge, TerminalProofRecursiveField,
    TerminalProofRecursiveMember, TerminalProofRecursiveTransitionLane, TerminalProofRecursiveType,
    TerminalPsiIdentity, TerminalRankedScc, TerminalReborrowRestorationClass,
    TerminalReborrowRestoredCallUse, TerminalReborrowRootHandoff, TerminalReborrowRootHandoffStep,
    TerminalReborrowSharedCohortMember, TerminalReboundDynamicDescriptor, TerminalRootServiceReach,
    TerminalStoredDynamicDescriptor, TerminalStoredDynamicDispatch, TerminalSuspensionCallPlan,
    TerminalSuspensionCallSite, TerminalSuspensionCallTarget, TerminalSuspensionLiveValue,
    TerminalSuspensionPlace, TerminalSuspensionStorage, TerminalSuspensionValueType,
    TerminalTraceBoundaryCrashSiteRow, TerminalTraceCrashSiteRow,
    TerminalTraceOperationCrashSiteRow, TerminalTraceOrdinaryEventKind,
    TerminalTraceOrdinaryEventRow, TerminalTraceResultKind, TerminalTraceResultSchema,
    TerminalTraceResultValue, TerminalTraceRootRow, TerminalTraceScalarSchema,
    TerminalTraceScalarValue, TerminalTraceStructuralSchema, TerminalTraceStructuralValue,
    TerminalTraceV1ConstructionError, TerminalTraceV1Event, TerminalTraceV1Outcome,
    TerminalTraceV1Profile, TerminalTraceV1Rows, TerminalTraceV1RuntimeTrace,
    TerminalTraceV1TraceBuilder, TerminalTraceValueComparison, Terminator,
    TrappingIntegerOperation, TrappingIntegerPrimitive, ValueDeclaration, VocabularyMarker,
    boundary, canonical_placed_view_identity, closed_conformance_application_commitment,
    closed_conformance_application_report_fingerprint, control_flow,
    float_meaning_equality_proposition_id, identity, is_bounded_structural_scalar_store_path,
    is_static_structural_path, observation, ownership,
    program_local_root_introduction_compatibility_report_identity, proof,
    retain_non_executable_quotient_correspondence, suspension_frontier_commitment, types, values,
};
