[package]
name = "selected-form-encoding-to-resolved-layout"
edition.workspace = true
license.workspace = true
version.workspace = true

[features]
test-support = []

[dependencies]
target-operations-to-selected-instructions = { path = "../03_target-operations-to-selected-instructions" }
post-allocation-machine-to-selected-form-encoding = { path = "../07_post-allocation-machine-to-selected-form-encoding" }
register-homes-to-post-allocation-machine = { path = "../06_register-homes-to-post-allocation-machine" }
selected-instructions-to-register-homes = { path = "../05_selected-instructions-to-register-homes" }
target = { path = "../../../psi/target" }
semantic-vocabulary = { path = "../../../psi/foundation/semantic-vocabulary" }
