[package]
name = "omega-core"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_core"
path = "src/lib.rs"

[dependencies]
psi-arena = { path = "../../../psi-rs/foundation/psi-arena" }
psi-language-semantics = { path = "../../../psi-rs/foundation/psi-language-semantics" }
psi-symbols = { path = "../../../psi-rs/foundation/psi-symbols" }
