[package]
name = "omega-core"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_core"
path = "src/lib.rs"

[dependencies]
psi-arena = { path = "../../../psi-rs/foundation/psi-arena" }
psi-diagnostics = { path = "../../../psi-rs/foundation/psi-diagnostics" }
psi-language-core = { path = "../../../psi-rs/foundation/psi-language-core" }
psi-numerics = { path = "../../../psi-rs/foundation/psi-numerics" }
psi-source = { path = "../../../psi-rs/foundation/psi-source" }
psi-source-loader = { path = "../../../psi-rs/foundation/psi-source-loader" }
