[package]
name = "omega-regalloc"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_regalloc"
path = "src/lib.rs"

[dependencies]
omega-optimization-core = { path = "../../foundation/omega-optimization-core" }
omega-optimization-unit = { path = "../../representations/omega-optimization-unit" }
omega-terminal-abstract-operations = { path = "../../representations/omega-terminal-abstract-operations" }
omega-register-model = { path = "../../representations/omega-register-model" }
omega-target = { path = "../../foundation/omega-target" }
omega-terminal-legalized-operations = { path = "../../representations/omega-terminal-legalized-operations" }
omega-terminal-selected-instructions = { path = "../../representations/omega-terminal-selected-instructions" }
omega-terminal-target-operations = { path = "../../representations/omega-terminal-target-operations" }
omega-terminal-target-operations-to-selected-instructions = { path = "../../pipeline/omega-terminal-target-operations-to-selected-instructions" }
psi-core = { path = "../../../psi/foundation/psi-core" }
psi-terminal = { path = "../../../psi/representations/psi-terminal" }
sha2 = "0.10.9"
