[package]
name = "omega-backend-report-types"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_backend_report_types"
path = "src/lib.rs"

[dependencies]
psi-arena = { path = "../../../psi/foundation/psi-arena" }
omega-target = { path = "../omega-target" }
