#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub enum SymbolKind {
    #[default]
    Unknown,
    Root,
    Module,
    BuiltinType,
    BuiltinFunction,
    Invariant,
    Data,
    Domain,
    Field,
    Variant,
    Machine,
    Operator,
    State,
    Trait,
    Parameter,
    TypeParameter,
    Local,
    Platform,
    HostCapability,
    Object,
    Trust,
    Function,
    Section,
    Import,
}
