pub const ORDINARY_PACKAGE_OBLIGATION_LEDGER_ENCODING_VERSION: u16 = 2;
pub const ORDINARY_PACKAGE_OBLIGATION_SCHEMA_VERSION: u16 = 7;

pub(super) const LEDGER_MAGIC: &[u8] = b"OMEGA-ORDINARY-PACKAGE-OBLIGATION-LEDGER\0";
pub(super) const LEDGER_FINGERPRINT_DOMAIN: &[u8] =
    b"OMEGA-ORDINARY-PACKAGE-OBLIGATION-LEDGER-FINGERPRINT\0";
pub(super) const MAXIMUM_LEDGER_ENCODING_BYTES: usize = 32 * 1024 * 1024;
pub(super) const MAXIMUM_LEDGER_TARGET_BYTES: usize = 4 * 1024;
pub(super) const MAXIMUM_LEDGER_PACKAGES: usize = 65_536;
pub(super) const MAXIMUM_LEDGER_DEPENDENCIES: usize = 262_144;
pub(super) const MAXIMUM_LEDGER_ALIAS_BYTES: usize = 1024 * 1024;
pub(super) const MAXIMUM_LEDGER_ROWS: usize = 65_536;
pub(super) const MAXIMUM_LEDGER_ROW_BYTES: usize = 4 * 1024 * 1024;
pub(super) const MAXIMUM_LEDGER_KEY_BYTES: usize = 1024 * 1024;
pub(super) const MAXIMUM_LEDGER_TOTAL_ROW_BYTES: usize = 16 * 1024 * 1024;
