[package]
name = "omega-register-homes-to-post-allocation-machine"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_register_homes_to_post_allocation_machine"
path = "src/lib.rs"

[dependencies]
omega-physical-instructions = { path = "../../representations/omega-physical-instructions" }
omega-selected-instructions-to-register-homes = { path = "../omega-selected-instructions-to-register-homes" }
omega-selected-instructions-to-machine-effects = { path = "../omega-selected-instructions-to-machine-effects" }
omega-target-to-register-environment = { path = "../omega-target-to-register-environment" }
omega-optimization-core = { path = "../../representations/omega-optimization-core" }
omega-register-model = { path = "../../representations/omega-register-model" }
omega-selected-instructions = { path = "../../representations/omega-selected-instructions" }
psi-core = { path = "../../../psi/foundation/psi-core" }

[dev-dependencies]
omega-isa-x86_64 = { path = "../../backend/instruction_set_architectures/omega-isa-x86_64" }
