[package]
name = "omega-visualizations"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_visualizations"
path = "src/lib.rs"

[dependencies]
omega-abstract-operations = { path = "../../representations/omega-abstract-operations" }
omega-calling-conventions = { path = "../../foundation/omega-calling-conventions" }
omega-assigned-target-operations = { path = "../../representations/omega-assigned-target-operations" }
omega-machine-bytes = { path = "../../representations/omega-machine-bytes" }
psi-arena = { path = "../../../psi/foundation/psi-arena" }
psi-symbols = { path = "../../../psi/foundation/psi-symbols" }
omega-control-flow = { path = "../../representations/omega-control-flow" }
omega-effects = { path = "../../representations/omega-effects" }
omega-machine-instructions = { path = "../../representations/omega-machine-instructions" }
omega-object-file = { path = "../../backend/object/omega-object-file" }
omega-state-graph = { path = "../../representations/omega-state-graph" }
omega-task-plans = { path = "../../foundation/omega-task-plans" }
omega-target-operations = { path = "../../representations/omega-target-operations" }
psi-checked-trees = { path = "../../../psi/representations/psi-checked-trees" }
psi-core = { path = "../../../psi/foundation/psi-core" }
psi-effects = { path = "../../../psi/representations/psi-effects" }
psi-facts = { path = "../../../psi/representations/psi-facts" }
psi-language-semantics = { path = "../../../psi/foundation/psi-language-semantics" }
psi-symbol-resolved-trees = { path = "../../../psi/representations/psi-symbol-resolved-trees" }
psi-syntax-trees = { path = "../../../psi/representations/psi-syntax-trees" }
psi-typed-trees = { path = "../../../psi/representations/psi-typed-trees" }

[dev-dependencies]
omega-target = { path = "../../foundation/omega-target" }
psi-numerics = { path = "../../../psi/foundation/psi-numerics" }
