# Emits the proof-library prefix for STATIC CONTRACT DISCHARGE -- the SAME role as gen-contract-lib.py, but
# every lemma PROOF is GENERATED by the prover (the untrusted proof-SEARCH front line), not transcribed from a
# hand-written .elab proof. The 7 lemma PROPOSITIONS are fixed (they are the contract system's spec, pinned by
# discharge.rs); the proofs come from automation and are validated by the trust anchor (check.beta) at build
# time, exactly like the hand library. This realises "automation discharges with zero hand-proving, a tiny
# kernel checks" (omega_toolchain.md) on the lattice's OWN contract pipeline -- the hand .elab base is retired.
#
# Each lemma is emitted as ONE self-contained `(def i prop proof)` at a STABLE id (the prover's `--inline`
# mode splices its lemma-prelude into a single proof, so no dep packing / id drift). discharge.rs cites these
# ids; they MUST match its constants (asserted below): add-zero-right=0 .. lt-le-trans=6.
import sys, os
HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, HERE)
import prover

# (name, id, proposition) -- the EXACT propositions discharge.rs banks (desugared Le/Lt -> Peano existentials),
# in the fixed citation order. Proofs are searched, not written.
LEMMAS = [
    ("add-zero-right", 0, "(All (= (p (v 0) z) (v 0)))"),
    ("add-commutes",   1, "(All (All (= (p (v 0) (v 1)) (p (v 1) (v 0)))))"),
    ("le-trans",       2, "(All (All (All (-> (Exists (= (p (v 3) (v 0)) (v 2))) (-> (Exists (= (p (v 2) (v 0)) (v 1))) (Exists (= (p (v 3) (v 0)) (v 1))))))))"),
    ("mult-commutes",  3, "(All (All (= (m (v 0) (v 1)) (m (v 1) (v 0)))))"),
    ("add-assoc",      4, "(All (All (All (= (p (p (v 0) (v 2)) (v 1)) (p (v 0) (p (v 2) (v 1)))))))"),
    ("mult-assoc",     5, "(All (All (All (= (m (m (v 2) (v 1)) (v 0)) (m (v 2) (m (v 1) (v 0)))))))"),
    ("lt-le-trans",    6, "(All (All (All (-> (Exists (= (p (v 3) (s (v 0))) (v 2))) (-> (Exists (= (p (v 2) (v 0)) (v 1))) (Exists (= (p (v 3) (s (v 0))) (v 1))))))))"),
]

out = []
for name, lid, prop_src in LEMMAS:
    goal = prover.parse(prover.tokenize(prop_src))
    proof = prover.solve(goal)
    if proof is None:
        sys.stderr.write("prover-contract-lib: FAILED to prove %s\n" % name)
        sys.exit(1)
    cert = prover.emit_inline(goal, proof)        # "<prop>\t<self-contained proof>"
    pr, pf = cert.split("\t", 1)
    out.append("(def %d %s %s)" % (lid, pr, pf))

# additive-comp (∀A∀B∀x∀y. x<A -> y<B -> x+y < A+B) -- "sum of bounded is bounded", the interval-propagation
# lemma. Its proof reuses add-comm 270+ times, so INLINING explodes past the checker's working set (~235 KB);
# it is banked as a shared def/use BLOCK instead (emit_lib_block): bases at ids 7..12, the lemma at id 13
# (ADD_BOUND in discharge.rs). discharge.rs cites `(use 13)` for a `self.arr[i+j]` computed-index bound.
ADD_BOUND_PROP = "(All (All (All (All (-> (Lt (v 1) (v 3)) (-> (Lt (v 0) (v 2)) (Lt (p (v 1) (v 0)) (p (v 3) (v 2)))))))))"
goal = prover.parse(prover.tokenize(ADD_BOUND_PROP))
proof = prover.solve(goal)
if proof is None:
    sys.stderr.write("prover-contract-lib: FAILED additive-comp\n")
    sys.exit(1)
block, add_bound_id = prover.emit_lib_block(goal, proof, 7)
assert add_bound_id == 13, "additive-comp id drifted: %d (discharge.rs pins ADD_BOUND=13)" % add_bound_id
out.append(block)

sys.stdout.write(" ".join(out))
