[package]
name = "register-environment"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "register_environment"
path = "src/lib.rs"

[dependencies]
register-model = { path = "../../representations/register-model" }
selected-instructions = { path = "../../representations/selected-instructions" }
target = { path = "../../representations/target" }
target-operations = { path = "../../representations/target-operations" }
isa-aarch64 = { path = "../instruction_set_architectures/isa-aarch64" }
isa-x86_64 = { path = "../instruction_set_architectures/isa-x86_64" }
