[package]
name = "terminal-production"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
language-semantics = { path = "../../foundation/language-semantics" }
semantic-vocabulary = { path = "../../foundation/semantic-vocabulary" }
checked-trees = { path = "../../representations/checked-trees" }
checked-trees-to-lowered-psi = { path = "../../pipeline/checked-trees-to-lowered-psi" }
lowered-psi = { path = "../../representations/lowered-psi" }
lowered-psi-to-lowered-psi = { path = "../../pipeline/lowered-psi-to-lowered-psi" }
lowered-psi-to-terminal-psi = { path = "../../pipeline/lowered-psi-to-terminal-psi" }
optimization = { path = "../../representations/optimization" }
symbols = { path = "../../foundation/symbols" }
terminal-psi = { path = "../../representations/terminal-psi" }
terminal-semantics = { path = "../../semantics/terminal-semantics" }
terminal-codec = { path = "../../semantics/terminal-codec" }
validation = { path = "../../semantics/validation" }

[dev-dependencies]
source-files-to-tokens = { path = "../../pipeline/00_source-files-to-tokens" }
tokens-to-syntax-trees = { path = "../../pipeline/01_tokens-to-syntax-trees" }
syntax-trees-to-symbol-resolved-trees = { path = "../../pipeline/02_syntax-trees-to-symbol-resolved-trees" }
symbol-resolved-trees-to-typed-trees = { path = "../../pipeline/03_symbol-resolved-trees-to-typed-trees" }
typed-trees-to-checked-trees = { path = "../../pipeline/04_typed-trees-to-checked-trees" }
