//! Independent verification of a SYNTHESIZED wire codec.
//!
//! `Schema::encode`/`Schema::decode` are generated by the compiler from a
//! wire schema; without a check of the generated bodies against the public
//! `Encode<compact_binary, S>`/`StrictDecode<compact_binary, S>`
//! requirement, the codec's report row is only generator-admitted. This
//! module is that check -- and it is deliberately NOT a round-trip of the
//! codec against itself alone, which is self-consistency rather than
//! independence. Instead:
//!
//! * CANONICAL EMISSION: canonical probe members are encoded by the codec
//!   realization and byte-compared against an independent reference framing
//!   written here from the compact_binary contract alone (era varint, per
//!   field a tag varint and payload, LEB128 or zigzag scalars,
//!   length-prefixed slices and nested bodies, bounded repeated carriers).
//! * STRICT DECODE ROUND-TRIP: the codec's decode is driven over the same
//!   canonical emission on a zeroed destination; it must accept, consume
//!   the exact frame, and reproduce every current-era member.
//! * STRICT-REJECTION PROBES: truncated frames, wrong eras, wrong field
//!   tags, noncanonical varints, overlong nested/repeated regions, and
//!   domain-violating slice bytes must all clear the soundness flag.
//!
//! A check that PASSES is recorded verbatim in `checks` as report
//! evidence. A requirement the realization cannot exercise (for example a
//! borrowed scalar-slice field, which has no decode-side field kind) is a
//! named gap in `gaps`, and the row keeps `Admitted` trust -- independent
//! verification claims `Derived` only when the whole requirement was
//! exercised. An actual divergence is `Err` and fails the build: the
//! generated codec then provably violates the public requirement.

use std::collections::BTreeMap;

use super::wire_codec::{WireInterpField, WireInterpScalarField};
use super::{Cell, Evaluator, Halt, Value};
use language_semantics::wire::WireScalarRange;
use typed_trees::data::DataMember;
use typed_trees::wire::{
    WireFieldEncoding, WireMember, WireRepeatedCarrier, WireScalarEncoding, WireSchema,
};

/// The outcome of independently checking one generated codec against the
/// public compact_binary requirement.
pub struct WireCodecVerification {
    /// Named checks that passed, in the order they ran.
    pub checks: Vec<String>,
    /// Requirements that could not be exercised by this realization; the
    /// codec row keeps `Admitted` trust while any remain.
    pub gaps: Vec<String>,
}

/// Which canonical probe member a check is running.
#[derive(Clone, Copy)]
enum Probe {
    /// Every field at its lower bound: zero scalars, one-byte slices, floor
    /// repeated bodies.
    Floor,
    /// Every field at its upper bound: range maxima (or the encoding's
    /// width edges), longer slices, full repeated bodies.
    Ceiling,
}

impl Probe {
    fn name(self) -> &'static str {
        match self {
            Self::Floor => "floor",
            Self::Ceiling => "ceiling",
        }
    }
}

/// The reference model's per-field encoding view, rederived from the encode
/// field walk -- deliberately NOT shared with the decode walk's
/// classification, so the two directions stay independent evidence.
enum ReferenceFieldKind {
    /// A scalar payload varint.
    Scalar,
    /// A length-prefixed raw byte payload (borrowed `&[u8]`, owned text).
    Bytes,
    /// A borrowed scalar slice (`&[i32]`-style): a byte-length prefix over
    /// packed element varints.
    ScalarElements,
    /// A bounded repeated carrier: byte-length prefix over the live packed
    /// element varints.
    Repeated {
        carrier: WireRepeatedCarrier,
        capacity: usize,
    },
    /// A nested message: byte-length prefix over child tag/payload pairs
    /// (no era discriminator).
    Nested { children: Vec<NestedReferenceField> },
}

struct NestedReferenceField {
    name: String,
    number: u64,
    encoding: WireScalarEncoding,
    range: Option<WireScalarRange>,
}

struct ReferenceField {
    name: String,
    number: u64,
    kind: ReferenceFieldKind,
    /// The element/field scalar encoding for Scalar, ScalarElements, and
    /// Repeated kinds.
    scalar_encoding: Option<WireScalarEncoding>,
    /// The declared range member values must respect: the field's own
    /// range for scalars, the element range for repeated carriers.
    range: Option<WireScalarRange>,
    /// Owned text and borrowed scalar slices have no decode-side field
    /// kind; the strict-decode checks record a gap rather than misreport.
    decodable: bool,
    /// Whether a `Bytes` member materializes as `Value::Str` (owned text)
    /// rather than a byte array.
    text_backed: bool,
}

/// A probe member value in the reference model.
enum ReferenceMember {
    /// Scalar payload, in the i64 view the codecs and ranges share.
    Scalar(i64),
    /// Raw byte content.
    Bytes(Vec<u8>),
    /// Packed scalar element content. For a FixedVec carrier `elements` is
    /// the full-capacity backing array and `live` the emitted prefix.
    Elements { elements: Vec<i64>, live: usize },
    /// Nested child scalar payloads in declaration order.
    Nested(Vec<i64>),
}

impl<'program> Evaluator<'program> {
    /// Verify the synthesized compact_binary codec for `schema` against the
    /// public requirement. `Ok` carries the checks that ran (and any gaps);
    /// `Err` is a concrete divergence between the generated codec and the
    /// requirement -- evidence of a real defect, never an approximation.
    pub(in crate::interpreter) fn verify_synthesized_wire_codec(
        &mut self,
        schema: &WireSchema,
    ) -> Result<WireCodecVerification, String> {
        let schema_name = schema.name.as_str().to_owned();
        let era = self.program.wire_schema_current_era(schema);

        let (enc_fields, _has_text) = self.wire_encode_fields(schema).map_err(|halt| {
            format!(
                "{schema_name}: encode field collection: {}",
                halt_text(&halt)
            )
        })?;
        let fields: Vec<ReferenceField> = enc_fields
            .iter()
            .map(|(name, number, content)| {
                self.reference_field(&schema_name, name, *number, content, schema)
            })
            .collect::<Result<_, String>>()?;

        let field_types: BTreeMap<String, _> = self
            .program
            .wire_members(schema.members)
            .iter()
            .filter_map(|member| match member {
                WireMember::Field(field) => {
                    Some((field.name.as_str().to_owned(), field.type_reference))
                }
                _ => None,
            })
            .collect();
        let (dec_fields, gaps) = if fields.iter().all(|field| field.decodable) {
            match self
                .wire_decode_fields(&schema_name, schema, |name| field_types.get(name).copied())
            {
                Ok(dec_fields) => (Some(dec_fields), Vec::new()),
                Err(halt) => (
                    None,
                    vec![format!("strict decode not exercised: {}", halt_text(&halt))],
                ),
            }
        } else {
            let names = fields
                .iter()
                .filter(|field| !field.decodable)
                .map(|field| format!("`{}`", field.name))
                .collect::<Vec<_>>()
                .join(", ");
            (
                None,
                vec![format!(
                    "strict decode not exercised: field(s) {names} have no decode-side wire kind"
                )],
            )
        };

        let mut checks = Vec::new();
        let mut ceiling: Option<(BTreeMap<String, ReferenceMember>, Vec<u8>)> = None;
        for probe in [Probe::Floor, Probe::Ceiling] {
            let members: BTreeMap<String, ReferenceMember> = fields
                .iter()
                .map(|field| (field.name.clone(), field.member(probe)))
                .collect();
            let input = self.member_input_value(&schema_name, schema, &fields, &members)?;
            let input_cell = self
                .allocate_cell(input)
                .map_err(|halt| format!("{schema_name}: {}", halt_text(&halt)))?;
            let emitted = self
                .wire_encode_body(&schema_name, era, &enc_fields, &input_cell)
                .map_err(|halt| format!("{schema_name}: {}", halt_text(&halt)))?;
            let reference = reference_emission(era, &fields, &members);
            if emitted != reference {
                return Err(format!(
                    "{schema_name}: generated encode emission diverges from the independent \
                     compact_binary reference for the {} member (codec {} byte(s), reference {} byte(s))",
                    probe.name(),
                    emitted.len(),
                    reference.len()
                ));
            }
            if let Some(dec_fields) = &dec_fields {
                self.check_decode_round_trip(
                    &schema_name,
                    era,
                    schema,
                    dec_fields,
                    &fields,
                    &members,
                    &emitted,
                    probe,
                )?;
            }
            if matches!(probe, Probe::Ceiling) {
                ceiling = Some((members, emitted));
            }
        }
        checks.push(
            "canonical emission byte-compared against an independent compact_binary \
             reference for 2 members"
                .to_owned(),
        );

        if let Some(dec_fields) = &dec_fields {
            checks.push(
                "strict decode round-trips the canonical emission and reproduces every \
                 current-era field"
                    .to_owned(),
            );
            let (members, emitted) = ceiling.expect("the ceiling member always runs");
            checks.extend(self.check_strict_rejections(
                &schema_name,
                era,
                schema,
                dec_fields,
                &fields,
                &members,
                &emitted,
            )?);
        }

        Ok(WireCodecVerification { checks, gaps })
    }

    /// Map one encode-field view onto the reference model's field kind,
    /// resolving the declared range the probe members must respect.
    fn reference_field(
        &self,
        schema_name: &str,
        name: &str,
        number: u64,
        content: &WireInterpField,
        schema: &WireSchema,
    ) -> Result<ReferenceField, String> {
        let wire_field = self
            .program
            .wire_members(schema.members)
            .iter()
            .find_map(|member| match member {
                WireMember::Field(field) if field.name.as_str() == name => Some(field),
                _ => None,
            })
            .ok_or_else(|| format!("{schema_name}: field `{name}` is not a wire member"))?;
        let (kind, decodable, scalar_encoding, range, text_backed) = match content {
            WireInterpField::Direct(WireFieldEncoding::Scalar(encoding)) => (
                ReferenceFieldKind::Scalar,
                true,
                Some(*encoding),
                validation::scalar_representation_range(self.program, wire_field.type_reference),
                false,
            ),
            WireInterpField::Direct(WireFieldEncoding::Text) => {
                (ReferenceFieldKind::Bytes, false, None, None, true)
            }
            WireInterpField::ByteSlice => (ReferenceFieldKind::Bytes, true, None, None, false),
            WireInterpField::ScalarSlice(slice) => (
                ReferenceFieldKind::ScalarElements,
                false,
                Some(slice.element),
                None,
                false,
            ),
            WireInterpField::Repeated(repeated) => (
                ReferenceFieldKind::Repeated {
                    carrier: repeated.carrier,
                    capacity: repeated.max_count,
                },
                true,
                Some(repeated.element),
                typed_trees::wire::repeated_element_type(
                    self.program,
                    wire_field.type_reference,
                    repeated.carrier,
                )
                .and_then(|element| validation::scalar_representation_range(self.program, element)),
                false,
            ),
            WireInterpField::Nested(children) => (
                ReferenceFieldKind::Nested {
                    children: self.nested_reference_fields(
                        schema_name,
                        name,
                        children,
                        wire_field,
                    )?,
                },
                true,
                None,
                None,
                false,
            ),
        };
        Ok(ReferenceField {
            name: name.to_owned(),
            number,
            kind,
            scalar_encoding,
            range,
            decodable,
            text_backed,
        })
    }

    /// Nested children with their declared ranges for member picking.
    fn nested_reference_fields(
        &self,
        schema_name: &str,
        field_name: &str,
        children: &[(String, u64, WireScalarEncoding)],
        wire_field: &typed_trees::wire::WireField,
    ) -> Result<Vec<NestedReferenceField>, String> {
        let child_schema = self
            .program
            .wire_field_nested_schema(wire_field)
            .ok_or_else(|| {
                format!("{schema_name}: nested field `{field_name}` has no wire schema")
            })?;
        children
            .iter()
            .map(|(name, number, encoding)| {
                let range = self
                    .program
                    .wire_members(child_schema.members)
                    .iter()
                    .find_map(|member| match member {
                        WireMember::Field(child) if child.name.as_str() == name.as_str() => {
                            validation::scalar_representation_range(
                                self.program,
                                child.type_reference,
                            )
                        }
                        _ => None,
                    });
                Ok(NestedReferenceField {
                    name: name.clone(),
                    number: *number,
                    encoding: *encoding,
                    range,
                })
            })
            .collect()
    }

    /// The interpreter `Value` for one probe member set, shaped the way the
    /// codec's encode walk reads the destination struct.
    fn member_input_value(
        &mut self,
        schema_name: &str,
        schema: &WireSchema,
        fields: &[ReferenceField],
        members: &BTreeMap<String, ReferenceMember>,
    ) -> Result<Value, String> {
        let data = self
            .program
            .data_definitions()
            .iter()
            .find(|data| {
                self.program.symbols.display_path(data.symbol, "::")
                    == self.program.symbols.display_path(schema.symbol, "::")
            })
            .ok_or_else(|| format!("{schema_name}: schema has no data declaration"))?;
        let mut value_fields = BTreeMap::new();
        for member in self.program.data_members(data) {
            let DataMember::Field(field) = member else {
                continue;
            };
            let field_name = field.name.as_str().to_owned();
            let value = match (
                members.get(&field_name),
                fields.iter().find(|candidate| candidate.name == field_name),
            ) {
                (Some(reference_member), Some(field)) => {
                    self.materialize_member(schema_name, field, reference_member)?
                }
                // Erased or otherwise non-current members never reach the
                // codec walks; Unit stands in for them untouched.
                _ => Value::Unit,
            };
            let cell = self
                .allocate_cell(value)
                .map_err(|halt| format!("{schema_name}: {}", halt_text(&halt)))?;
            value_fields.insert(field_name, cell);
        }
        Ok(Value::Struct {
            type_symbol: data.symbol,
            type_name: data.name.as_str().to_owned(),
            fields: value_fields,
        })
    }

    /// One probe member as an interpreter `Value` -- `Value::Int` scalars,
    /// `Value::Str` for owned text, byte `Value::Array` for borrowed slices,
    /// carrier-shaped storage for repeated fields.
    fn materialize_member(
        &mut self,
        schema_name: &str,
        field: &ReferenceField,
        member: &ReferenceMember,
    ) -> Result<Value, String> {
        let int_array = |evaluator: &mut Self, values: &[i64]| -> Result<Value, String> {
            let cells: Vec<Cell> = values
                .iter()
                .map(|value| {
                    evaluator
                        .allocate_cell(Value::Int(*value))
                        .map_err(|halt| format!("{schema_name}: {}", halt_text(&halt)))
                })
                .collect::<Result<_, String>>()?;
            Ok(Value::Array(cells))
        };
        match (member, &field.kind) {
            (ReferenceMember::Scalar(value), ReferenceFieldKind::Scalar) => Ok(Value::Int(*value)),
            (ReferenceMember::Bytes(bytes), ReferenceFieldKind::Bytes) => {
                if field.text_backed {
                    self.allocate_text(bytes.clone())
                        .map_err(|halt| format!("{schema_name}: {}", halt_text(&halt)))
                } else {
                    int_array(
                        self,
                        &bytes
                            .iter()
                            .map(|byte| i64::from(*byte))
                            .collect::<Vec<_>>(),
                    )
                }
            }
            (
                ReferenceMember::Elements { elements, live },
                ReferenceFieldKind::Repeated {
                    carrier: WireRepeatedCarrier::FixedVec,
                    ..
                },
            ) => {
                let items = int_array(self, elements)?;
                let items = self
                    .allocate_cell(items)
                    .map_err(|halt| format!("{schema_name}: {}", halt_text(&halt)))?;
                let length = self
                    .allocate_cell(Value::Int(*live as i64))
                    .map_err(|halt| format!("{schema_name}: {}", halt_text(&halt)))?;
                let mut vec_fields = BTreeMap::new();
                vec_fields.insert("items".to_owned(), items);
                vec_fields.insert("length".to_owned(), length);
                Ok(Value::Struct {
                    type_symbol: symbols::SymbolHandle::invalid(),
                    type_name: "FixedVec".to_owned(),
                    fields: vec_fields,
                })
            }
            (ReferenceMember::Elements { elements, .. }, _) => int_array(self, elements),
            (ReferenceMember::Nested(values), ReferenceFieldKind::Nested { children }) => {
                let mut child_fields = BTreeMap::new();
                for (child, value) in children.iter().zip(values.iter()) {
                    let cell = self
                        .allocate_cell(Value::Int(*value))
                        .map_err(|halt| format!("{schema_name}: {}", halt_text(&halt)))?;
                    child_fields.insert(child.name.clone(), cell);
                }
                Ok(Value::Struct {
                    type_symbol: symbols::SymbolHandle::invalid(),
                    type_name: format!("{schema_name}.{}", field.name),
                    fields: child_fields,
                })
            }
            _ => Err(format!(
                "{schema_name}: member and field kind disagree for `{}`",
                field.name
            )),
        }
    }

    /// A zeroed destination struct for the strict-decode probes: the decode
    /// walk writes nested and repeated members IN PLACE through their
    /// cells, so those must already carry the destination's storage shape.
    fn zeroed_destination(
        &mut self,
        schema_name: &str,
        schema: &WireSchema,
        dec_fields: &[(String, u64, WireInterpScalarField)],
    ) -> Result<Value, String> {
        let data = self
            .program
            .data_definitions()
            .iter()
            .find(|data| {
                self.program.symbols.display_path(data.symbol, "::")
                    == self.program.symbols.display_path(schema.symbol, "::")
            })
            .ok_or_else(|| format!("{schema_name}: schema has no data declaration"))?;
        let zero_cell = |evaluator: &mut Self, value: Value| -> Result<Cell, String> {
            evaluator
                .allocate_cell(value)
                .map_err(|halt| format!("{schema_name}: {}", halt_text(&halt)))
        };
        let mut fields = BTreeMap::new();
        for member in self.program.data_members(data) {
            let DataMember::Field(field) = member else {
                continue;
            };
            let field_name = field.name.as_str().to_owned();
            let zero = match dec_fields.iter().find(|(name, _, _)| *name == field_name) {
                Some((_, _, WireInterpScalarField::Scalar { .. })) => Value::Int(0),
                Some((_, _, WireInterpScalarField::ByteSlice { .. })) => Value::Array(Vec::new()),
                Some((_, _, WireInterpScalarField::Nested(children))) => {
                    let mut child_fields = BTreeMap::new();
                    for (child_name, _, _, _) in children {
                        child_fields.insert(child_name.clone(), zero_cell(self, Value::Int(0))?);
                    }
                    Value::Struct {
                        type_symbol: symbols::SymbolHandle::invalid(),
                        type_name: field_name.clone(),
                        fields: child_fields,
                    }
                }
                Some((_, _, WireInterpScalarField::Repeated { encoding, .. })) => {
                    let elements = Value::Array(
                        (0..encoding.max_count)
                            .map(|_| zero_cell(self, Value::Int(0)))
                            .collect::<Result<Vec<Cell>, String>>()?,
                    );
                    match encoding.carrier {
                        WireRepeatedCarrier::FixedArray => elements,
                        WireRepeatedCarrier::FixedVec => {
                            let items = zero_cell(self, elements)?;
                            let length = zero_cell(self, Value::Int(0))?;
                            let mut vec_fields = BTreeMap::new();
                            vec_fields.insert("items".to_owned(), items);
                            vec_fields.insert("length".to_owned(), length);
                            Value::Struct {
                                type_symbol: symbols::SymbolHandle::invalid(),
                                type_name: "FixedVec".to_owned(),
                                fields: vec_fields,
                            }
                        }
                    }
                }
                // Non-current-era fields are never touched by the decode
                // walk; Unit stands in untouched.
                None => Value::Unit,
            };
            fields.insert(field_name, zero_cell(self, zero)?);
        }
        Ok(Value::Struct {
            type_symbol: data.symbol,
            type_name: data.name.as_str().to_owned(),
            fields,
        })
    }

    /// Drive the codec's decode over a canonical emission and require the
    /// exact cursor, a sound verdict, and every current-era field's value.
    fn check_decode_round_trip(
        &mut self,
        schema_name: &str,
        era: u64,
        schema: &WireSchema,
        dec_fields: &[(String, u64, WireInterpScalarField)],
        fields: &[ReferenceField],
        members: &BTreeMap<String, ReferenceMember>,
        emitted: &[u8],
        probe: Probe,
    ) -> Result<(), String> {
        let destination = self.zeroed_destination(schema_name, schema, dec_fields)?;
        let destination_cell = self
            .allocate_cell(destination)
            .map_err(|halt| format!("{schema_name}: {}", halt_text(&halt)))?;
        let (cursor, ok) = self
            .wire_decode_body(schema_name, era, dec_fields, emitted, &destination_cell)
            .map_err(|halt| format!("{schema_name}: {}", halt_text(&halt)))?;
        if !ok {
            return Err(format!(
                "{schema_name}: strict decode rejected the codec's own canonical {} member emission",
                probe.name()
            ));
        }
        if cursor != emitted.len() {
            return Err(format!(
                "{schema_name}: strict decode consumed {cursor} of {} emitted bytes for the {} member",
                emitted.len(),
                probe.name()
            ));
        }
        let Value::Struct {
            fields: decoded, ..
        } = &*destination_cell.borrow()
        else {
            return Err(format!(
                "{schema_name}: decode destination is not a data value"
            ));
        };
        for field in fields.iter().filter(|field| field.decodable) {
            let member = members
                .get(&field.name)
                .expect("the member map covers every field");
            let cell = decoded
                .get(&field.name)
                .map(|cell| self.deref_cell(cell.clone()))
                .ok_or_else(|| {
                    format!("{schema_name}: destination has no field `{}`", field.name)
                })?;
            if !member_matches(field, member, &cell) {
                return Err(format!(
                    "{schema_name}: strict decode did not reproduce field `{}` for the {} member",
                    field.name,
                    probe.name()
                ));
            }
        }
        Ok(())
    }

    /// The strict-rejection probes: mutations of the canonical emission the
    /// public strict-decode contract requires to clear the soundness flag.
    /// Each runs on a fresh zeroed destination because the sticky-failure
    /// contract still runs the whole operation sequence.
    fn check_strict_rejections(
        &mut self,
        schema_name: &str,
        era: u64,
        schema: &WireSchema,
        dec_fields: &[(String, u64, WireInterpScalarField)],
        fields: &[ReferenceField],
        members: &BTreeMap<String, ReferenceMember>,
        emitted: &[u8],
    ) -> Result<Vec<String>, String> {
        let mut frames: Vec<(&'static str, Vec<u8>)> = Vec::new();
        let era_width = independent_varint(era).len();
        if emitted.len() > era_width {
            frames.push(("truncated frame", emitted[..emitted.len() - 1].to_vec()));
        }
        let mut foreign_era = independent_varint(era + 1);
        foreign_era.extend_from_slice(&emitted[era_width..]);
        frames.push(("foreign era", foreign_era));
        if era <= 0x7f {
            // A two-byte spelling of a one-byte era carries a terminal
            // zero-payload group -- the canonicality check rejects it.
            let mut overlong = vec![(era as u8) | 0x80, 0x00];
            overlong.extend_from_slice(&emitted[era_width..]);
            frames.push(("noncanonical era varint", overlong));
        }
        if let Some(first) = fields.first() {
            // Re-tag the first field with the next number; the decoder's
            // expected-tag check fails.
            let mut wrong_tag = independent_varint(era);
            independent_varint_to(&mut wrong_tag, first.number + 1);
            reference_field_body(&mut wrong_tag, first, members.get(&first.name));
            for sibling in &fields[1..] {
                reference_field_emission(&mut wrong_tag, sibling, members.get(&sibling.name));
            }
            frames.push(("wrong field tag", wrong_tag));
        }
        for (index, field) in fields.iter().enumerate() {
            match &field.kind {
                ReferenceFieldKind::Nested { .. } | ReferenceFieldKind::Repeated { .. } => {
                    // The declared body length one byte PAST the real body:
                    // the region CLOSE lands past the bound.
                    let mut overrun = independent_varint(era);
                    for (sibling_index, sibling) in fields.iter().enumerate() {
                        if sibling_index != index {
                            reference_field_emission(
                                &mut overrun,
                                sibling,
                                members.get(&sibling.name),
                            );
                            continue;
                        }
                        independent_varint_to(&mut overrun, sibling.number);
                        let mut body = Vec::new();
                        reference_field_body(&mut body, sibling, members.get(&sibling.name));
                        independent_varint_to(&mut overrun, body.len() as u64 + 1);
                        overrun.extend(body);
                    }
                    frames.push(("declared body length overrun", overrun));
                    break;
                }
                _ => {}
            }
        }
        for (index, field) in fields.iter().enumerate() {
            // A domain violation only probes schemas whose decode actually
            // checks a predicate (a `&[u8] in Utf8` field); a plain byte
            // slice legitimately accepts any content.
            if !matches!(field.kind, ReferenceFieldKind::Bytes) {
                continue;
            }
            let has_predicate = dec_fields.iter().any(|(name, _, content)| {
                *name == field.name
                    && matches!(content, WireInterpScalarField::ByteSlice { predicates } if !predicates.is_empty())
            });
            if !has_predicate {
                continue;
            }
            // 0x80 alone is invalid UTF-8 and non-ASCII; NonEmpty/NoNul hold.
            let mut violation = independent_varint(era);
            for (sibling_index, sibling) in fields.iter().enumerate() {
                if sibling_index != index {
                    reference_field_emission(&mut violation, sibling, members.get(&sibling.name));
                    continue;
                }
                independent_varint_to(&mut violation, sibling.number);
                independent_varint_to(&mut violation, 1);
                violation.push(0x80);
            }
            frames.push(("domain-violating slice bytes", violation));
            break;
        }

        for (name, frame) in &frames {
            let destination = self.zeroed_destination(schema_name, schema, dec_fields)?;
            let destination_cell = self
                .allocate_cell(destination)
                .map_err(|halt| format!("{schema_name}: {}", halt_text(&halt)))?;
            let (_cursor, ok) = self
                .wire_decode_body(schema_name, era, dec_fields, frame, &destination_cell)
                .map_err(|halt| format!("{schema_name}: {}", halt_text(&halt)))?;
            if ok {
                return Err(format!(
                    "{schema_name}: strict decode accepted a {name} probe frame"
                ));
            }
        }
        Ok(if frames.is_empty() {
            Vec::new()
        } else {
            vec![format!(
                "strict decode rejects {} malformed frames (truncation, foreign era, wrong tag, \
                 noncanonical varint, region overrun, domain violation as applicable)",
                frames.len()
            )]
        })
    }
}

impl ReferenceField {
    /// The canonical probe member for this field.
    fn member(&self, probe: Probe) -> ReferenceMember {
        match &self.kind {
            ReferenceFieldKind::Scalar => ReferenceMember::Scalar(scalar_probe_value(
                self.scalar_encoding.expect("scalar kind carries encoding"),
                self.range,
                matches!(probe, Probe::Ceiling),
            )),
            ReferenceFieldKind::Bytes => ReferenceMember::Bytes(match probe {
                // Non-empty ASCII satisfies every recognized byte predicate,
                // so a domain-carrying slice still round-trips.
                Probe::Floor => b"o".to_vec(),
                Probe::Ceiling => b"Omega".to_vec(),
            }),
            ReferenceFieldKind::ScalarElements => {
                let element = self
                    .scalar_encoding
                    .expect("slice kind carries element encoding");
                let elements = match probe {
                    Probe::Floor => Vec::new(),
                    Probe::Ceiling => vec![
                        scalar_probe_value(element, self.range, false),
                        scalar_probe_value(element, self.range, true),
                        7,
                    ],
                };
                ReferenceMember::Elements {
                    live: elements.len(),
                    elements,
                }
            }
            ReferenceFieldKind::Repeated { carrier, capacity } => {
                let element = self
                    .scalar_encoding
                    .expect("repeated kind carries element encoding");
                let upper = matches!(probe, Probe::Ceiling);
                let elements: Vec<i64> = (0..*capacity)
                    .map(|_| scalar_probe_value(element, self.range, upper))
                    .collect();
                let live = match carrier {
                    WireRepeatedCarrier::FixedArray => *capacity,
                    WireRepeatedCarrier::FixedVec => match probe {
                        Probe::Floor => usize::from(*capacity > 0),
                        Probe::Ceiling => *capacity,
                    },
                };
                ReferenceMember::Elements { elements, live }
            }
            ReferenceFieldKind::Nested { children } => ReferenceMember::Nested(
                children
                    .iter()
                    .map(|child| {
                        scalar_probe_value(
                            child.encoding,
                            child.range,
                            matches!(probe, Probe::Ceiling),
                        )
                    })
                    .collect(),
            ),
        }
    }
}

/// Whether a decoded field cell carries exactly the probe member's value
/// (byte-equal for slices, element-equal for carriers, scalar equality
/// under the destination's decoded representation).
fn member_matches(field: &ReferenceField, member: &ReferenceMember, cell: &Cell) -> bool {
    match member {
        ReferenceMember::Scalar(value) => cell.borrow().as_int() == Some(*value),
        ReferenceMember::Bytes(bytes) => match &*cell.borrow() {
            Value::Str(text) => &*text.borrow() == bytes.as_slice(),
            Value::Array(elements) => {
                elements.len() == bytes.len()
                    && elements
                        .iter()
                        .zip(bytes.iter())
                        .all(|(element, byte)| element.borrow().as_int() == Some(i64::from(*byte)))
            }
            _ => false,
        },
        ReferenceMember::Elements { elements, live } => match &field.kind {
            ReferenceFieldKind::Repeated {
                carrier: WireRepeatedCarrier::FixedVec,
                ..
            } => match &*cell.borrow() {
                Value::Struct { fields, .. } => {
                    let Some(length) = fields.get("length") else {
                        return false;
                    };
                    if length.borrow().as_int() != Some(*live as i64) {
                        return false;
                    }
                    let Some(items) = fields.get("items") else {
                        return false;
                    };
                    let Value::Array(item_cells) = &*items.borrow() else {
                        return false;
                    };
                    item_cells.len() >= *live
                        && item_cells[..*live]
                            .iter()
                            .zip(elements[..*live].iter())
                            .all(|(element, value)| element.borrow().as_int() == Some(*value))
                }
                _ => false,
            },
            _ => match &*cell.borrow() {
                Value::Array(item_cells) => {
                    item_cells.len() == elements.len()
                        && item_cells
                            .iter()
                            .zip(elements.iter())
                            .all(|(element, value)| element.borrow().as_int() == Some(*value))
                }
                _ => false,
            },
        },
        ReferenceMember::Nested(values) => match (&*cell.borrow(), &field.kind) {
            (Value::Struct { fields, .. }, ReferenceFieldKind::Nested { children }) => {
                children.len() == values.len()
                    && children.iter().zip(values.iter()).all(|(child, value)| {
                        fields
                            .get(&child.name)
                            .map(|child_cell| child_cell.borrow().as_int() == Some(*value))
                            .unwrap_or(false)
                    })
            }
            _ => false,
        },
    }
}

/// One scalar probe value inside the encoding's contract: the declared
/// range bound when the field declares one, else the encoding's width edge
/// (zigzag edges exercise the sign-bit fold).
fn scalar_probe_value(
    encoding: WireScalarEncoding,
    range: Option<WireScalarRange>,
    upper: bool,
) -> i64 {
    if encoding.byte_size == 1 {
        return i64::from(upper);
    }
    if let Some(range) = range {
        return if upper { range.maximum } else { range.minimum };
    }
    match (encoding.byte_size, encoding.zigzag) {
        (4, false) => {
            if upper {
                i64::from(u32::MAX)
            } else {
                0
            }
        }
        (8, false) => {
            if upper {
                u64::MAX as i64
            } else {
                0
            }
        }
        (4, true) => {
            if upper {
                i64::from(i32::MAX)
            } else {
                i64::from(i32::MIN)
            }
        }
        (8, true) => {
            if upper {
                i64::MAX
            } else {
                i64::MIN
            }
        }
        _ => 0,
    }
}

/// The verifier's own canonical LEB128 emission -- a separate
/// implementation from `wire_varint_bytes` so a defect in the shared helper
/// cannot mask itself in the comparison.
fn independent_varint(value: u64) -> Vec<u8> {
    let mut bytes = Vec::new();
    let mut remaining = value;
    loop {
        let mut byte = (remaining & 0x7f) as u8;
        remaining >>= 7;
        if remaining != 0 {
            byte |= 0x80;
        }
        bytes.push(byte);
        if remaining == 0 {
            return bytes;
        }
    }
}

fn independent_varint_to(out: &mut Vec<u8>, value: u64) {
    out.extend(independent_varint(value));
}

/// The independent reference framing of one member set: era varint, then
/// each field's tag varint and payload in field-number order.
fn reference_emission(
    era: u64,
    fields: &[ReferenceField],
    members: &BTreeMap<String, ReferenceMember>,
) -> Vec<u8> {
    let mut bytes = independent_varint(era);
    for field in fields {
        reference_field_emission(&mut bytes, field, members.get(&field.name));
    }
    bytes
}

fn reference_field_emission(
    out: &mut Vec<u8>,
    field: &ReferenceField,
    member: Option<&ReferenceMember>,
) {
    let Some(member) = member else {
        return;
    };
    independent_varint_to(out, field.number);
    reference_field_body(out, field, Some(member));
}

/// One field's payload after its tag: the compact_binary contract restated
/// -- scalars as LEB128 (zigzag for signed), byte/text/slice/repeated and
/// nested bodies under a byte-length varint, nested bodies without their
/// own era.
fn reference_field_body(
    out: &mut Vec<u8>,
    field: &ReferenceField,
    member: Option<&ReferenceMember>,
) {
    let Some(member) = member else {
        return;
    };
    match (&field.kind, member) {
        (ReferenceFieldKind::Scalar, ReferenceMember::Scalar(value)) => {
            let encoding = field.scalar_encoding.expect("scalar kind carries encoding");
            independent_varint_to(out, reference_scalar_payload(*value, encoding));
        }
        (ReferenceFieldKind::Bytes, ReferenceMember::Bytes(bytes)) => {
            independent_varint_to(out, bytes.len() as u64);
            out.extend_from_slice(bytes);
        }
        (ReferenceFieldKind::ScalarElements, ReferenceMember::Elements { elements, .. }) => {
            let element = field
                .scalar_encoding
                .expect("slice kind carries element encoding");
            let body: Vec<u8> = elements
                .iter()
                .flat_map(|value| independent_varint(reference_scalar_payload(*value, element)))
                .collect();
            independent_varint_to(out, body.len() as u64);
            out.extend(body);
        }
        (ReferenceFieldKind::Repeated { .. }, ReferenceMember::Elements { elements, live }) => {
            let element = field
                .scalar_encoding
                .expect("repeated kind carries element encoding");
            let body: Vec<u8> = elements[..*live]
                .iter()
                .flat_map(|value| independent_varint(reference_scalar_payload(*value, element)))
                .collect();
            independent_varint_to(out, body.len() as u64);
            out.extend(body);
        }
        (ReferenceFieldKind::Nested { children }, ReferenceMember::Nested(values)) => {
            let mut body = Vec::new();
            for (child, value) in children.iter().zip(values.iter()) {
                independent_varint_to(&mut body, child.number);
                independent_varint_to(&mut body, reference_scalar_payload(*value, child.encoding));
            }
            independent_varint_to(out, body.len() as u64);
            out.extend_from_slice(&body);
        }
        _ => {}
    }
}

/// The LEB128 payload a scalar member encodes as, per the compact_binary
/// contract: booleans as 0/1, unsigned at the declared width, signed
/// zigzag-folded at 64 bits after the source-width sign extension. Written
/// independently of `wire_scalar_varint_value` so a defect there cannot
/// mask itself here.
fn reference_scalar_payload(value: i64, encoding: WireScalarEncoding) -> u64 {
    match (encoding.byte_size, encoding.zigzag) {
        (1, _) => u64::from(value != 0),
        (4, false) => u64::from(value as u32),
        (8, false) => value as u64,
        (4, true) => (((value as i32) as i64) << 1 ^ (((value as i32) as i64) >> 63)) as u64,
        (8, true) => ((value << 1) ^ (value >> 63)) as u64,
        _ => 0,
    }
}

/// The message a `Halt` carries -- halts have no display/debug impl by
/// design (they are control flow, not errors), so the verifier extracts the
/// text for its evidence strings.
fn halt_text(halt: &Halt) -> String {
    match halt {
        Halt::Exit(code) => format!("exit {code}"),
        Halt::Unsupported(message) | Halt::Trap(message) | Halt::Resource(message) => {
            message.clone()
        }
    }
}
