pub use omega_optimization_core::{
    DuplicateOptimizationRuleIdentity, IdentityBundleDecodeError, IdentityDecodeError,
    Optimization, OptimizationDecisionLogIdentity, OptimizationIdentityBundle,
    OptimizationIdentityBundleIdentity, OptimizationRuleIdentity, OptimizationRuleSetIdentity,
    OptimizationSelectionIdentity, OptimizationSelections, OptimizationWorkloadProfileIdentity,
    TargetCostModelIdentity, TransformationLedgerIdentity,
};
pub use omega_optimization_pipeline::OptimizationReportRequest;

pub use psi_checked_interpreter::{
    FilesystemSponsor, FilesystemSponsorError, FilesystemSponsorLimits,
};

pub use crate::pipeline::{
    AdmittedExternalRootEntryFactHandoff, AggregateFieldSchema, AggregateFieldValue,
    BUILD_OBSERVATION_SCHEMA_VERSION, BoundExternalRootPostHandoffWriterInvocation,
    BuildEvaluationUsage, BuildFilesystemAuthorizedPath, BuildFilesystemByteOperand,
    BuildFilesystemGrantAccess, BuildFilesystemGrantRefusal, BuildFilesystemGrantRefusalReason,
    BuildFilesystemLogicalHandleIdentity, BuildFilesystemLogicalHandleInput,
    BuildFilesystemLogicalHandleInputResolution, BuildFilesystemLogicalHandleKind,
    BuildFilesystemLogicalHandleOutput, BuildFilesystemLogicalHandleOutputSource,
    BuildFilesystemMetadataObservation, BuildFilesystemMetadataObservationKind,
    BuildFilesystemMutableByteOperand, BuildFilesystemMutableByteOperandResolution,
    BuildFilesystemMutableI64Operand, BuildFilesystemMutableI64OperandResolution,
    BuildFilesystemObservedByteRegion, BuildFilesystemObservedByteRegionKind,
    BuildFilesystemOperationAttempt, BuildFilesystemOperationResult,
    BuildFilesystemPathLikeOperand, BuildFilesystemProvider, BuildFilesystemReplayRecordError,
    BuildFilesystemReplayRecordLimits, BuildFilesystemReturnedPath,
    BuildFilesystemReturnedPathCompleteness, BuildFilesystemReturnedPathKind, BuildFilesystemRoot,
    BuildFilesystemRootedPathOperandResolution, BuildFilesystemScalarOperand,
    BuildFilesystemScalarOperandValue, BuildObservationClass, BuildObservationSummary,
    BuildStagedOutputMaterializationError, BuildStagedOutputTree, BuildStagedOutputTreeCommitment,
    BuildTimeValue, ByteOrder, CheckedCompilation, CompilerExecutableCommitment,
    CompilerExecutableCommitmentError, ConsumptionInstant, DataSymbolId, EntryStubId,
    ExecutableTcbBuildPolicy, ExternalRootPostHandoffWriterBindingError, InstalledImageSubextent,
    InstalledProgramStorageRoots, IntegerInterpretation, LayoutFieldEntryReport,
    LayoutPlacementReport, LayoutPlanReport, MaterializationAction, MaterializationContext,
    MaterializationDiagnostic, MaterializationWrite, OwnedTerminalComponentDeploymentError,
    PROGRAM_STORAGE_INSTALLATION_ARTIFACT, PackageCompilationInputError, PackageCompilationInputs,
    PackageDependencyBinding, PackageDependencyClosure, PackageGeneratedSource,
    PackageGeneratedSourceBundle, PackageSourceBinding, PackageSourceConsumptionCommitment,
    PartitionedProgramStorageRoots, ProgramEntryPhysicalContractPlan,
    ProgramEntryReceiverActivation, ProgramEntryReceiverActivationError,
    ProgramEntryReceiverPlacementRecord, ProgramEntryReceiverStoragePlan,
    ProgramEntrySourceExtentFieldLayout, ProgramEntrySourceExtentFieldRole,
    ProgramEntrySourceExtentValueLayout, ProgramEntrySourceReceiverSignature,
    ProgramEntrySourceResultSignature, ProgramEntrySourceVisibleParameterSignature,
    ProgramLocalEntryReceiverActivation, ProgramLocalEntryReceiverActivationError,
    ProgramLocalStorageAccountHandoffError, ProgramLocalStorageCustody,
    ProgramLocalStorageCustodyError, ProgramLocalStorageInstallationHandoffError,
    ProgramLocalStorageRecordEmissionError, ProgramLocalStorageRecordedWholeRootArgumentError,
    ProgramLocalStorageRecordedWholeRootArgumentRecovery, ProgramLocalStorageSubjectHandoffError,
    ProgramStorageEntryBridgeError, ProgramStorageEntryContinuationAbiPlan,
    ProgramStorageEntryContinuationInboundArgument, ProgramStorageEntryContinuationInboundPlan,
    ProgramStorageEntryContinuationReceiverAbiPlan, ProgramStorageEntryContinuationReceiverBinding,
    ProgramStorageEntryContinuationReceiverBindingError,
    ProgramStorageEntryContinuationVisibleArgumentPlan, ProgramStorageEntryDiagnostic,
    ProgramStorageEntryEmittedArrivalCopyEvidence, ProgramStorageEntryEmittedArrivalEvidence,
    ProgramStorageEntryEmittedArrivalRootEvidence,
    ProgramStorageEntryEmittedWholeRootArgumentCarrier,
    ProgramStorageEntryEmittedWholeRootArgumentError, ProgramStorageEntryEmittedWrapperEvidence,
    ProgramStorageEntryExecutorDispatch, ProgramStorageEntryExtentLogicalValue,
    ProgramStorageEntryExtentOperandImage, ProgramStorageEntryInitialStorageAuthorityKind,
    ProgramStorageEntryNativeBridgePlan, ProgramStorageEntryOutgoingStackWord,
    ProgramStorageEntryParameter, ProgramStorageEntryPlanBinding,
    ProgramStorageEntryProviderInvocation, ProgramStorageEntryRecordedWholeRootArgumentError,
    ProgramStorageEntryRecordedWholeRootArgumentRecovery,
    ProgramStorageEntryReservedOutgoingStackFrameError,
    ProgramStorageEntryReservedOutgoingStackFramePlan, ProgramStorageEntryRootAuthorityDisposition,
    ProgramStorageEntryRootAuthorityDispositionError, ProgramStorageEntryRootRole,
    ProgramStorageEntrySourceContinuationHandoff, ProgramStorageEntryWholeRootArgumentBinding,
    ProgramStorageEntryWholeRootArgumentCarrier, ProgramStorageEntryWholeRootArgumentError,
    ProgramStorageEntryWholeRootAuthority, ProgramStorageEntryWholeRootAuthorityError,
    ProgramStorageEntryWholeRootLogicalValueCarrier, ProgramStorageEntryWholeRootLogicalValueError,
    ProgramStorageEntryWholeRootOperandCarrier, ProgramStorageEntryWholeRootOperandError,
    ProgramStorageEntryWrapperBodyTemplatePlan, ProgramStorageEntryWrapperBodyTemplateStep,
    ProgramStorageEntryWrapperCallerFrameError, ProgramStorageEntryWrapperCallerFramePlan,
    ProgramStorageEntryWrapperCallerFrameStep, ProgramStorageEntryWrapperReceiverTransfer,
    ProgramStorageEntryWrapperRootTransferPlan, ProgramStorageEntryWrapperTransferPlan,
    ProgramStorageInstallationHandoffError, ProgramStorageInstallationRecord,
    ProgramStorageInstalledExtentRecord, ProgramStoragePartitionError,
    ProgramStorageRecordEmissionError, ProgramStorageRootInput,
    ProgramStorageRootInstallationError, ProviderPlanProvenance, ProviderSchemaDeclaration,
    ProviderSelectionProvenance, RecordedProgramLocalStorageInstallation,
    RecordedProgramStorageInstallation, RelocationTarget, ReservedProgramEntryReceiverStorage,
    ReviewOnlyBuildFilesystemReplayRecord, SOURCE_CLOSURE_SNAPSHOT_SCHEMA, SOURCE_FEATURE_CATALOG,
    SOURCE_FEATURE_CENSUS_SCHEMA, SOURCE_FEATURE_IDS, SOURCE_RESOURCE_IDS, ScalarFieldSchema,
    ScalarFieldValue, SelectedExternalRootEntryFactBinding,
    SelectedExternalRootPostHandoffWriterPreparation, SelectedExternalRootProviderPlan,
    SelectedExternalRootWriterPreparationError, SelectedProgramEntrySourceSignature,
    SelectedProgramStorageEntryPlan, SelectedProviderReviewProvenance, SourceClosureSnapshot,
    SourceClosureSnapshotEntry, SourceFeatureCensus, SourceFeatureCount, SourceInspectionRoot,
    SourceResourceObservation, SuppliedTerminalComponentDeploymentError, SymbolicFieldValue,
    SymbolicMaterializationPlan, TerminalComponentCandidate, TerminalComponentCandidateParts,
    TerminalComponentCompileError, TerminalComponentCompileRequest,
    TerminalComponentDeploymentInputOwner, TerminalComponentDeploymentInputRejection,
    TerminalComponentDeploymentInputs, TerminalComponentDeploymentOutputError,
    TerminalComponentDeploymentOutputStage, TerminalComponentDeploymentSupply,
    TerminalComponentDriverError, TerminalComponentProviderExecution,
    TerminalComponentProviderSettlement, TerminalComponentStagingInputBindingError,
    TerminalComponentStagingInputs, TerminalNativeArtifact, TerminalNativeArtifactParts,
    TerminalNativeProviderExecution, TerminalNativeProviderSettlement, ValidatedAccessPlan,
    ValidatedConstMaterialization, ValidatedPlacementPlan,
    ValidatedWrittenBoundExternalRootPostHandoffWriterDestination,
    WrittenBoundExternalRootConsumerValidationError,
    WrittenBoundExternalRootPostHandoffWriterDestination,
    WrittenBoundExternalRootWriterRecoveryError, acquire_and_deploy_terminal_component_output,
    bind_emitted_program_storage_entry_native_bridge,
    bind_external_root_post_handoff_writer_invocation, bind_generated_program_storage_entry_plan,
    bind_program_local_storage_entry_emitted_whole_root_arguments,
    bind_program_local_storage_entry_whole_root_logical_values,
    bind_program_local_storage_entry_whole_root_operands,
    bind_program_storage_entry_emitted_whole_root_arguments, bind_program_storage_entry_plan,
    bind_program_storage_entry_whole_root_arguments,
    bind_program_storage_entry_whole_root_logical_values,
    bind_program_storage_entry_whole_root_operands,
    bind_recorded_program_local_storage_entry_whole_root_arguments,
    bind_recorded_program_storage_entry_whole_root_arguments,
    capture_verified_build_filesystem_replay_record, census_source_closure,
    compile_terminal_component_output, compile_to_checked, compile_to_checked_with_packages,
    compile_to_checked_with_packages_and_replay_record,
    compile_to_checked_with_packages_in_build_dir,
    compile_to_checked_with_packages_in_sponsored_build_dir, compile_to_checked_with_replay_record,
    compiler_intrinsic_diagnostic_label, compute_access_plan, compute_layout_plan,
    compute_placement_plan, decode_scalar_layout, deploy_and_write_terminal_component_output,
    deploy_supplied_terminal_component_output, derive_symbolic_materialization,
    establish_program_storage_entry_program_local_roots,
    evaluate_and_materialize_typed_owned_layout_into, evaluate_calling_policy_plan,
    inspect_source_closure, inspect_source_closure_with_packages,
    install_and_activate_program_storage_entry_receiver,
    install_established_program_storage_entry_program_local_roots,
    install_program_storage_entry_provider_invocation, materialize_aggregate_layout_into,
    materialize_scalar_layout_into, materialize_typed_owned_layout_into,
    normalized_layout_plan_fingerprint, plan_program_local_storage_entry_wrapper_caller_frame,
    plan_program_storage_entry_wrapper_caller_frame, program_storage_installation_record_json,
    realize_terminal_native_artifact, recover_review_only_build_filesystem_replay_record,
    reserve_program_local_storage_entry_outgoing_stack_frame,
    reserve_program_storage_entry_outgoing_stack_frame, selected_external_root_entry_fact_bindings,
    selected_external_root_provider_plan, selected_external_root_provider_plan_id,
    stage_acquire_and_deploy_terminal_component_output, stage_terminal_component,
    toolchain_source_identity_digest, validate_const_materializable_typed_owned_layout,
    write_finalized_terminal_component_output,
};
