use crate::pipeline::PackageCompilationInputs;
use crate::pipeline::frontend::{
    discover_imports, discover_imports_with_packages, extend_source_storage, lex_sources,
    load_package_generated_source, load_sources, parse_sources,
};
use crate::pipeline::project::{project_roots, validate_selected_target};
use crate::pipeline::source::{ImportQueue, SourceStorage};
use crate::pipeline::stage::{SOURCE_FILES_TO_TOKENS, TOKENS_TO_SYNTAX_TREES};
use crate::pipeline::timing::CompileTimings;
use psi_diagnostics::Diagnostic;
use psi_syntax_trees::SyntaxTrees;
use std::path::{Path, PathBuf};
use std::sync::Arc;

#[derive(Clone)]
pub(super) struct AssembledSyntax {
    pub(super) syntax_trees: SyntaxTrees,
    pub(super) files: Vec<crate::pipeline::source::SourceFile>,
    pub(super) sources: Arc<psi_source::SourceMap>,
    /// Exact companion `build.omg` selected during project discovery. Build
    /// authority is attached to this source, never reconstructed from a leaf
    /// filename after imports have expanded the source frontier.
    pub(super) build_source_id: Option<psi_source::SourceId>,
    pub(super) source_scoped_top_level_bindings: Vec<psi_symbols::SourceScopedTopLevelBinding>,
    pub(super) generated_source_custody: Vec<(
        psi_source::SourceId,
        omega_build_output::PackageGeneratedSource,
    )>,
}

/// Exact parsed extension produced by one admitted build activation.
///
/// Keeping these roots separate from the retained base is the source-side
/// input needed by the incremental D18 lowerer. The carrier can still be
/// consumed into the transitional combined syntax without parsing or reading
/// the generated bytes again.
pub(super) struct RetainedGeneratedSyntaxExtension {
    syntax_trees: SyntaxTrees,
    units: Vec<RetainedGeneratedSyntaxUnit>,
    sources: Arc<psi_source::SourceMap>,
    generated_source_custody: Vec<(
        psi_source::SourceId,
        omega_build_output::PackageGeneratedSource,
    )>,
    base_sources: Arc<psi_source::SourceMap>,
}

struct RetainedGeneratedSyntaxUnit {
    source_id: psi_source::SourceId,
    path: PathBuf,
    root_item_count: usize,
}

impl RetainedGeneratedSyntaxExtension {
    pub(super) fn source_count(&self) -> usize {
        self.units.len()
    }

    pub(super) fn generated_source_custody(
        &self,
    ) -> &[(
        psi_source::SourceId,
        omega_build_output::PackageGeneratedSource,
    )] {
        &self.generated_source_custody
    }

    pub(super) fn is_nonempty_data_only(&self) -> bool {
        self.syntax_trees.root_item_count() > 0
            && self
                .syntax_trees
                .root_items()
                .all(|item| matches!(item, psi_syntax_trees::item::Item::Data(_)))
    }

    pub(super) fn seeded_inputs(
        &self,
        assembled: &AssembledSyntax,
    ) -> Result<(&SyntaxTrees, Arc<psi_source::SourceMap>), Vec<Diagnostic>> {
        if !Arc::ptr_eq(&assembled.sources, &self.base_sources) {
            return Err(vec![Diagnostic::error(
                "retained generated-source extension no longer matches its base source frontier",
            )]);
        }
        Ok((&self.syntax_trees, self.sources.clone()))
    }

    /// Consume the retained extension into the existing whole-program route.
    /// Root handles are reminted by `SyntaxTrees::extend_from`; source-file
    /// rows are rebound to those exact appended handles in the same unit order.
    pub(super) fn append_to(self, assembled: &mut AssembledSyntax) -> Result<(), Vec<Diagnostic>> {
        if !Arc::ptr_eq(&assembled.sources, &self.base_sources) {
            return Err(vec![Diagnostic::error(
                "retained generated-source extension no longer matches its base source frontier",
            )]);
        }

        let retained_root_count = self.units.iter().try_fold(0usize, |count, unit| {
            count.checked_add(unit.root_item_count).ok_or_else(|| {
                vec![Diagnostic::error(
                    "generated-source root count exceeds the compiler range",
                )]
            })
        })?;
        if retained_root_count != self.syntax_trees.root_item_count() {
            return Err(vec![Diagnostic::error(
                "retained generated-source roots do not match their source units",
            )]);
        }

        let first_appended_root = assembled.syntax_trees.root_item_count();
        assembled.syntax_trees.extend_from(&self.syntax_trees);
        let appended_roots = &assembled.syntax_trees.root_item_handles()[first_appended_root..];
        let mut root_offset = 0usize;
        for unit in self.units {
            let root_end = root_offset
                .checked_add(unit.root_item_count)
                .expect("retained generated-source root count was validated");
            let root_items = appended_roots[root_offset..root_end].to_vec();
            assembled.files.push(crate::pipeline::source::SourceFile {
                source_id: unit.source_id,
                path: unit.path,
                root_items,
            });
            root_offset = root_end;
        }
        debug_assert_eq!(root_offset, appended_roots.len());
        assembled.sources = self.sources;
        assembled
            .generated_source_custody
            .extend(self.generated_source_custody);
        Ok(())
    }
}

pub(super) fn retain_generated_syntax_extension(
    assembled: &AssembledSyntax,
    package_root: &Path,
    package_identity: Option<psi_core::PackageKeyIdentity>,
    generated_sources: &[omega_build_output::PackageGeneratedSource],
) -> Result<RetainedGeneratedSyntaxExtension, Vec<Diagnostic>> {
    let base_source_count = assembled.sources.len();
    let mut sources = (*assembled.sources).clone();
    let mut syntax_trees = SyntaxTrees::new(psi_source::SourceId(base_source_count));
    let mut units = Vec::with_capacity(generated_sources.len());
    let mut retained = Vec::with_capacity(generated_sources.len());
    for generated in generated_sources {
        let source = std::str::from_utf8(generated.bytes()).map_err(|_| {
            vec![Diagnostic::error(format!(
                "included generated source `{}` is not UTF-8 Omega source",
                String::from_utf8_lossy(generated.relative_path())
            ))]
        })?;
        let mut logical_path = package_root.join(".omega/generated");
        for component in generated.relative_path().split(|byte| *byte == b'/') {
            logical_path.push(
                std::str::from_utf8(component)
                    .expect("validated generated source paths retain UTF-8 components"),
            );
        }
        if sources
            .files()
            .any(|existing| existing.path == logical_path)
        {
            return Err(vec![Diagnostic::error(format!(
                "generated source logical path `{}` collides with an existing source",
                logical_path.display()
            ))]);
        }

        let source_id = psi_source::SourceId(sources.len());
        let tokens = crate::lexer::Lexer::new(source)
            .tokenize()
            .map_err(|error| {
                let position = psi_source::SourcePosition::of(source, error.span.start);
                vec![Diagnostic::error(format!(
                    "{}:{}:{}: {}",
                    logical_path.display(),
                    position.line,
                    position.column,
                    error.message
                ))]
            })?;
        let parsed =
            crate::parser::parse_syntax_trees_with_id(source_id, &tokens).map_err(|error| {
                let position = psi_source::SourcePosition::of(source, error.source_span.span.start);
                vec![Diagnostic::error(format!(
                    "{}:{}:{}: {}",
                    logical_path.display(),
                    position.line,
                    position.column,
                    error.message
                ))]
            })?;
        let root_item_count = parsed.root_item_count();
        syntax_trees.extend_from(&parsed);
        let added = sources.add_with_metadata_and_resolution_stratum(
            logical_path.clone(),
            source.to_owned(),
            package_root.to_path_buf(),
            package_identity,
            psi_source::SourceOrigin::User,
            psi_source::SourceResolutionStratum::CurrentActivationExtension,
        );
        debug_assert_eq!(added.source_id, source_id);
        units.push(RetainedGeneratedSyntaxUnit {
            source_id,
            path: logical_path,
            root_item_count,
        });
        retained.push((source_id, generated.clone()));
    }
    Ok(RetainedGeneratedSyntaxExtension {
        syntax_trees,
        units,
        sources: Arc::new(sources),
        generated_source_custody: retained,
        base_sources: assembled.sources.clone(),
    })
}

pub(super) fn source_files_to_syntax_trees_for_engine(
    root_path: &Path,
    target_name: Option<&str>,
    package_inputs: Option<&PackageCompilationInputs>,
    timings: &mut CompileTimings,
) -> Result<(usize, AssembledSyntax), Vec<Diagnostic>> {
    let project_roots = project_roots(root_path);
    let selected_build_path = project_roots
        .build
        .as_deref()
        .map(|path| {
            path.canonicalize().map_err(|error| {
                vec![Diagnostic::error(format!(
                    "failed to establish exact build source {}: {error}",
                    path.display()
                ))]
            })
        })
        .transpose()?;
    let mut imports = ImportQueue::default();
    for root in project_roots.sources {
        imports.seed(root);
    }

    let toolchain_root = crate::pipeline::frontend::bundled_omega_root();
    let mut source_storage = match package_inputs {
        Some(package_inputs) => {
            package_inputs.validate_for_compilation(root_path, &toolchain_root)?;
            let root_package = package_inputs
                .package_root(package_inputs.root())
                .expect("validated package inputs retain their root")
                .to_path_buf();
            let mut storage = SourceStorage::for_package_compilation(
                root_package,
                package_inputs.root(),
                toolchain_root,
            );
            for (identity, source_root) in package_inputs.packages() {
                storage.register_reconciled_package_root(source_root.to_path_buf(), identity);
            }
            storage
        }
        None => {
            let root_package = root_path
                .parent()
                .map(Path::to_path_buf)
                .unwrap_or_else(|| PathBuf::from("."));
            SourceStorage::for_compilation(root_package, toolchain_root)
        }
    };
    let generated_source_custody = match package_inputs {
        Some(package_inputs) => append_dependency_generated_sources_to_storage(
            &mut source_storage,
            &mut imports,
            target_name,
            package_inputs,
            timings,
        )?,
        None => Vec::new(),
    };
    load_pending_imports(
        &mut source_storage,
        &mut imports,
        root_path,
        target_name,
        package_inputs,
        timings,
    )?;

    let build_source_id = selected_build_path
        .as_deref()
        .map(|selected| {
            source_storage
                .files
                .iter()
                .find(|(_, file)| {
                    file.path
                        .canonicalize()
                        .is_ok_and(|loaded| loaded == selected)
                })
                .map(|(_, file)| file.source_id)
                .ok_or_else(|| {
                    vec![Diagnostic::error(format!(
                        "selected build source {} disappeared from the loaded frontier",
                        selected.display()
                    ))]
                })
        })
        .transpose()?;
    validate_selected_build_role(&source_storage, build_source_id)?;
    let source_scoped_top_level_bindings = inject_build_prelude(
        &mut source_storage,
        build_source_id,
        target_name.is_some(),
        timings,
    )?;

    validate_selected_target(&source_storage, target_name)?;
    let source_file_count = source_storage.file_count();
    let syntax = assemble_syntax(
        source_storage,
        build_source_id,
        source_scoped_top_level_bindings,
        generated_source_custody,
    )?;

    Ok((source_file_count, syntax))
}

fn append_dependency_generated_sources_to_storage(
    source_storage: &mut SourceStorage,
    imports: &mut ImportQueue,
    target_name: Option<&str>,
    package_inputs: &PackageCompilationInputs,
    timings: &mut CompileTimings,
) -> Result<
    Vec<(
        psi_source::SourceId,
        omega_build_output::PackageGeneratedSource,
    )>,
    Vec<Diagnostic>,
> {
    let selected_target = target_name
        .map(|target_name| omega_target::TargetProfile::from_omega_target_name(Some(target_name)))
        .transpose()
        .map_err(|diagnostic| vec![diagnostic])?;
    package_inputs
        .validate_dependency_generated_source_target(selected_target)
        .map_err(|errors| {
            errors
                .into_iter()
                .map(|error| Diagnostic::error(error.to_string()))
                .collect::<Vec<_>>()
        })?;
    let mut entries = Vec::new();
    for bundle in package_inputs.dependency_generated_source_bundles() {
        let package_root = package_inputs
            .package_root(bundle.package())
            .expect("validated generated-source bundle retains its package root");
        for source in bundle.sources() {
            let logical_path = generated_source_logical_path(package_root, source)?;
            if logical_path.exists()
                || entries
                    .iter()
                    .any(|(existing, _): &(PathBuf, _)| existing == &logical_path)
            {
                return Err(vec![Diagnostic::error(format!(
                    "generated dependency source logical path `{}` collides with another source",
                    logical_path.display(),
                ))]);
            }
            entries.push((logical_path, source.clone()));
        }
    }

    for (logical_path, _) in &entries {
        imports.mark_loaded(logical_path.clone());
    }

    let mut retained = Vec::with_capacity(entries.len());
    for (logical_path, source) in entries {
        let text = std::str::from_utf8(source.bytes()).map_err(|_| {
            vec![Diagnostic::error(format!(
                "included generated source `{}` is not UTF-8 Omega source",
                logical_path.display(),
            ))]
        })?;
        let source_id = psi_source::SourceId(source_storage.next_source_id());
        let lexed = timings.record(SOURCE_FILES_TO_TOKENS, || {
            lex_sources(load_package_generated_source(
                logical_path,
                text,
                source_id.0,
            ))
        })?;
        let parsed = timings.record(TOKENS_TO_SYNTAX_TREES, || {
            parse_sources(lexed, &mut source_storage.syntax_trees)
        })?;
        let discovered = discover_imports_with_packages(
            &parsed,
            &source_storage.syntax_trees,
            target_name,
            package_inputs,
        )?;
        imports.enqueue(discovered)?;
        extend_source_storage(source_storage, parsed)?;
        retained.push((source_id, source));
    }
    Ok(retained)
}

fn generated_source_logical_path(
    package_root: &Path,
    source: &omega_build_output::PackageGeneratedSource,
) -> Result<PathBuf, Vec<Diagnostic>> {
    let mut logical_path = package_root.join(".omega/generated");
    for component in source.relative_path().split(|byte| *byte == b'/') {
        logical_path.push(std::str::from_utf8(component).map_err(|_| {
            vec![Diagnostic::error(
                "generated dependency source path is not canonical UTF-8",
            )]
        })?);
    }
    Ok(logical_path)
}

/// Require the exact selected free build root to declare its project role
/// through the same compiler-neutral grammar used by package orchestration.
///
fn validate_selected_build_role(
    source_storage: &SourceStorage,
    build_source_id: Option<psi_source::SourceId>,
) -> Result<(), Vec<Diagnostic>> {
    let Some(build_source_id) = build_source_id else {
        return Ok(());
    };
    let source = source_storage.sources.get(build_source_id).ok_or_else(|| {
        vec![Diagnostic::error(
            "selected build source has no retained source text",
        )]
    })?;
    omega_build_declarations::project_build_declaration_from_source(&source.source)
        .map(|_| ())
        .map_err(|error| {
            vec![Diagnostic::error(format!(
                "{}: invalid project build declaration: {error}",
                source.path.display()
            ))]
        })
}

fn load_pending_imports(
    source_storage: &mut SourceStorage,
    imports: &mut ImportQueue,
    root_path: &Path,
    target_name: Option<&str>,
    package_inputs: Option<&PackageCompilationInputs>,
    timings: &mut CompileTimings,
) -> Result<(), Vec<Diagnostic>> {
    while imports.has_pending() {
        let frontier = imports.take_frontier();
        let frontier = match package_inputs {
            Some(package_inputs) => validate_package_source_frontier(frontier, package_inputs)?,
            None => frontier,
        };
        let first_source_id = source_storage.next_source_id();
        let lexed = timings.record(SOURCE_FILES_TO_TOKENS, || {
            let sources = load_sources(frontier, first_source_id)?;
            lex_sources(sources)
        })?;
        let parsed = timings.record(TOKENS_TO_SYNTAX_TREES, || {
            parse_sources(lexed, &mut source_storage.syntax_trees)
        })?;
        let discovered_imports = match package_inputs {
            Some(package_inputs) => discover_imports_with_packages(
                &parsed,
                &source_storage.syntax_trees,
                target_name,
                package_inputs,
            )?,
            None => discover_imports(
                &parsed,
                &source_storage.syntax_trees,
                root_path,
                target_name,
            )?,
        };

        imports.enqueue(discovered_imports)?;
        extend_source_storage(source_storage, parsed)?;
    }

    Ok(())
}

fn validate_package_source_frontier(
    frontier: Vec<PathBuf>,
    package_inputs: &PackageCompilationInputs,
) -> Result<Vec<PathBuf>, Vec<Diagnostic>> {
    let toolchain_root = crate::pipeline::frontend::bundled_omega_root();
    let mut validated = Vec::with_capacity(frontier.len());
    let mut diagnostics = Vec::new();

    for source in frontier {
        let canonical = match source.canonicalize() {
            Ok(canonical) => canonical,
            Err(error) => {
                diagnostics.push(Diagnostic::error(format!(
                    "failed to canonicalize package source {} before loading: {error}",
                    source.display()
                )));
                continue;
            }
        };
        if canonical.starts_with(&toolchain_root) {
            validated.push(canonical);
            continue;
        }

        let Some(owner) = package_inputs.package_for_source(&canonical) else {
            diagnostics.push(Diagnostic::error(format!(
                "package source {} escapes every reconciled source root",
                canonical.display()
            )));
            continue;
        };
        if owner != package_inputs.root()
            && canonical.file_name().and_then(|name| name.to_str()) == Some("build.omg")
        {
            diagnostics.push(Diagnostic::error(format!(
                "dependency build file {} may not join the compiled program",
                canonical.display()
            )));
            continue;
        }
        validated.push(canonical);
    }

    if diagnostics.is_empty() {
        Ok(validated)
    } else {
        Err(diagnostics)
    }
}

/// The TOOLCHAIN-PROVIDED build vocabulary (build_and_package_model.md): a
/// build.omg has exactly one free `machine build(builder: &mut Build) { ... }`
/// entry. The `Build` / `Subsystem` types are CORE-DEFINED, never authored per
/// file. When a build.omg root declares that build-machine shape and no `Build` data of
/// its own, the build-machine fragment is injected as a virtual source (a
/// program-declared `Build` wins, which keeps migration and deliberate
/// overrides possible). Package identity uses the same injected `Build`
/// surface through `builder.package(name)`; there is no second declaration
/// type or compiler-only constant shape.
const BUILD_PRELUDE: &str = r#"
// Toolchain-provided build vocabulary (virtual source; build_and_package_model.md).
pub data Subsystem {
    case Console;
    case Gui;
    case EfiApplication;
    case Unspecified(value: u16);
}
// compiler-owned TargetProfile declaration
// compiler-owned X86DeploymentFeatures declaration
// compiler-owned optimization declarations
// Compiler-owned package-build path carrier. The evaluator replaces values
// produced by `resolve` with activation-local rooted authority; an authored
// `BuildPath {}` has the right static shape but no usable runtime root.
pub data BuildPath [copy] {
}
pub data BuildSource {
}
pub data BuildOutput {
}
pub data BuildLog {
}
pub data Build {
    // compiler-owned Build.target field
    // compiler-owned Build.x86_deployment_features field
    subsystem: Subsystem;
    freestanding: bool;
    optimizations: Optimizations;
    source: BuildSource;
    output: BuildOutput;
    log: BuildLog;
}
pub data PackageSelection {
    case Root;
    case Named(package: &[u8]);
}
pub data Source {
    case Path(location: &[u8]);
    case Git(repository: &[u8], revision: &[u8], selection: PackageSelection);
}
pub machine Build::depend(&mut self, source: Source) {
}
pub machine Build::depend_as(&mut self, alias: &[u8], source: Source) {
}
pub machine Build::package(&mut self, name: &[u8]) {
}
pub machine Build::application(&mut self, name: &[u8]) {
}
pub machine Build::member(&mut self, path: &[u8]) {
}
pub machine BuildSource::resolve(&self, relative: &[u8]) -> BuildPath {
    BuildPath {}
}
pub machine BuildOutput::resolve(&self, relative: &[u8]) -> BuildPath {
    BuildPath {}
}
pub machine BuildSource::open(&self, path: BuildPath, flags: i32) -> i32 {
    0
}
pub machine BuildSource::read(&self, descriptor: i32, buffer: &mut [u8], count: u64) -> i64 {
    0
}
pub machine BuildSource::close(&self, descriptor: i32) -> i32 {
    0
}
pub machine BuildOutput::create(&mut self, path: BuildPath, mode: i32) -> i32 {
    0
}
pub machine BuildOutput::write(&mut self, descriptor: i32, bytes: &[u8]) -> i64 {
    0
}
pub machine BuildOutput::close(&mut self, descriptor: i32) -> i32 {
    0
}
pub machine BuildOutput::include_source(&mut self, generated: BuildPath) {
}
pub machine BuildLog::write_line(&mut self, text: &[u8]) {
}
// compiler-owned optimization enable machine
// compiler-owned optimization report machine
"#;

const BUILD_TARGET_FIELD_SLOT: &str = "    // compiler-owned Build.target field\n";
const BUILD_TARGET_FIELD: &str = "    target: TargetProfile;\n";
const BUILD_X86_DEPLOYMENT_FEATURES_FIELD_SLOT: &str =
    "    // compiler-owned Build.x86_deployment_features field\n";
const BUILD_X86_DEPLOYMENT_FEATURES_FIELD: &str =
    "    x86_deployment_features: X86DeploymentFeatures;\n";
const BUILD_TARGET_PROFILE_SLOT: &str = "// compiler-owned TargetProfile declaration\n";
const BUILD_TARGET_PROFILE: &str = r#"pub data TargetProfile {
    case LinuxArm64;
    case LinuxX86_64;
    case MacosArm64;
    case WindowsX86_64;
    case UefiX86_64;
    case CrossPlatformCli;
    case LocalUnchecked;
}
"#;
const BUILD_X86_DEPLOYMENT_FEATURES_SLOT: &str =
    "// compiler-owned X86DeploymentFeatures declaration\n";
const BUILD_X86_DEPLOYMENT_FEATURES: &str = r#"pub data X86DeploymentFeatures {
    case Baseline;
    case AvxFma3;
}
"#;

fn construct_build_prelude(base: &str, has_exact_target: bool) -> String {
    assert_eq!(
        base.matches(BUILD_TARGET_FIELD_SLOT).count(),
        1,
        "build prelude must contain exactly one compiler-owned target slot"
    );
    assert_eq!(
        base.matches(BUILD_TARGET_PROFILE_SLOT).count(),
        1,
        "build prelude must contain exactly one compiler-owned target profile slot"
    );
    assert_eq!(
        base.matches(BUILD_X86_DEPLOYMENT_FEATURES_FIELD_SLOT)
            .count(),
        1,
        "build prelude must contain exactly one compiler-owned x86 deployment-feature field slot"
    );
    assert_eq!(
        base.matches(BUILD_X86_DEPLOYMENT_FEATURES_SLOT).count(),
        1,
        "build prelude must contain exactly one compiler-owned x86 deployment-feature declaration slot"
    );
    let replacement = if has_exact_target {
        BUILD_TARGET_FIELD
    } else {
        ""
    };
    let with_target = base
        .replacen(BUILD_TARGET_PROFILE_SLOT, BUILD_TARGET_PROFILE, 1)
        .replacen(
            BUILD_X86_DEPLOYMENT_FEATURES_SLOT,
            BUILD_X86_DEPLOYMENT_FEATURES,
            1,
        )
        .replacen(BUILD_TARGET_FIELD_SLOT, replacement, 1)
        .replacen(
            BUILD_X86_DEPLOYMENT_FEATURES_FIELD_SLOT,
            if has_exact_target {
                BUILD_X86_DEPLOYMENT_FEATURES_FIELD
            } else {
                ""
            },
            1,
        );
    super::optimization::build_vocabulary::install(&with_target)
}

fn inject_build_prelude(
    source_storage: &mut SourceStorage,
    build_source_id: Option<psi_source::SourceId>,
    has_exact_target: bool,
    timings: &mut CompileTimings,
) -> Result<Vec<psi_symbols::SourceScopedTopLevelBinding>, Vec<Diagnostic>> {
    let mut has_build_machine = false;
    let mut build_source_declares_build_data = false;
    let mut program_declares_build_data = false;
    for (_, file) in source_storage.files.iter() {
        let is_build_file = Some(file.source_id) == build_source_id;
        for root_item in &file.root_items {
            match source_storage.syntax_trees.root_item(*root_item) {
                psi_syntax_trees::item::Item::Machine(machine)
                    if is_build_file && machine.name.as_str() == "build" =>
                {
                    has_build_machine = true;
                }
                psi_syntax_trees::item::Item::Data(data) if data.name.as_str() == "Build" => {
                    if is_build_file {
                        build_source_declares_build_data = true;
                    } else {
                        program_declares_build_data = true;
                    }
                }
                _ => {}
            }
        }
    }
    let inject_build_vocabulary = has_build_machine && !build_source_declares_build_data;
    if !inject_build_vocabulary {
        return Ok(Vec::new());
    }

    // Targetless checking is not an artifact activation and therefore exposes
    // no synthetic target. Exact-target requests receive the canonical field;
    // retaining the former Build shape here keeps targetless semantic checks
    // honest while product requests migrate to immutable activation.
    let prelude = construct_build_prelude(BUILD_PRELUDE, has_exact_target);

    let first_source_id = source_storage.next_source_id();
    let lexed = timings.record(SOURCE_FILES_TO_TOKENS, || {
        let sources = crate::pipeline::frontend::load_injected_source(
            "<build-prelude>",
            &prelude,
            first_source_id,
        );
        lex_sources(sources)
    })?;
    let parsed = timings.record(TOKENS_TO_SYNTAX_TREES, || {
        parse_sources(lexed, &mut source_storage.syntax_trees)
    })?;
    extend_source_storage(source_storage, parsed)?;
    let bindings = match (program_declares_build_data, build_source_id) {
        (true, Some(build_source_id)) => vec![psi_symbols::SourceScopedTopLevelBinding::new(
            build_source_id,
            psi_source::SourceId(first_source_id),
            "Build",
        )],
        _ => Vec::new(),
    };
    Ok(bindings)
}

fn assemble_syntax(
    sources: SourceStorage,
    build_source_id: Option<psi_source::SourceId>,
    source_scoped_top_level_bindings: Vec<psi_symbols::SourceScopedTopLevelBinding>,
    generated_source_custody: Vec<(
        psi_source::SourceId,
        omega_build_output::PackageGeneratedSource,
    )>,
) -> Result<AssembledSyntax, Vec<Diagnostic>> {
    let files = sources.files.storage_slice().to_vec();
    Ok(AssembledSyntax {
        syntax_trees: sources.syntax_trees,
        files,
        sources: Arc::new(sources.sources),
        build_source_id,
        source_scoped_top_level_bindings,
        generated_source_custody,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn retained_generated_syntax_extension_rejoins_units_without_reparsing() {
        let base_text = "machine base() -> u64 { 1 }";
        let base_tokens = crate::lexer::Lexer::new(base_text)
            .tokenize()
            .expect("lex base source");
        let base_syntax =
            crate::parser::parse_syntax_trees_with_id(psi_source::SourceId(0), &base_tokens)
                .expect("parse base source");
        let mut base_sources = psi_source::SourceMap::default();
        base_sources.add(PathBuf::from("src/main.omg"), base_text.to_owned());
        let base_sources = Arc::new(base_sources);
        let mut assembled = AssembledSyntax {
            files: vec![crate::pipeline::source::SourceFile {
                source_id: psi_source::SourceId(0),
                path: PathBuf::from("src/main.omg"),
                root_items: base_syntax.root_item_handles().to_vec(),
            }],
            syntax_trees: base_syntax,
            sources: base_sources.clone(),
            build_source_id: None,
            source_scoped_top_level_bindings: Vec::new(),
            generated_source_custody: Vec::new(),
        };

        let extension_inputs = [
            (".omega/generated/first.omg", "machine first() -> u64 { 2 }"),
            (
                ".omega/generated/second.omg",
                "data Later { value: u64 }\nmachine second() -> u64 { 3 }",
            ),
        ];
        let mut extension_syntax = SyntaxTrees::new(psi_source::SourceId(1));
        let mut extension_units = Vec::new();
        let mut combined_sources = (*base_sources).clone();
        for (offset, (path, text)) in extension_inputs.iter().enumerate() {
            let source_id = psi_source::SourceId(offset + 1);
            let tokens = crate::lexer::Lexer::new(text)
                .tokenize()
                .expect("lex extension source");
            let parsed = crate::parser::parse_syntax_trees_with_id(source_id, &tokens)
                .expect("parse extension source");
            extension_units.push(RetainedGeneratedSyntaxUnit {
                source_id,
                path: PathBuf::from(path),
                root_item_count: parsed.root_item_count(),
            });
            extension_syntax.extend_from(&parsed);
            combined_sources.add_with_metadata_and_resolution_stratum(
                PathBuf::from(path),
                (*text).to_owned(),
                PathBuf::from("."),
                None,
                psi_source::SourceOrigin::User,
                psi_source::SourceResolutionStratum::CurrentActivationExtension,
            );
        }
        let extension = RetainedGeneratedSyntaxExtension {
            syntax_trees: extension_syntax,
            units: extension_units,
            sources: Arc::new(combined_sources),
            generated_source_custody: Vec::new(),
            base_sources,
        };

        extension
            .append_to(&mut assembled)
            .expect("retained extension should match its exact base");

        assert_eq!(assembled.sources.len(), 3);
        assert_eq!(assembled.files.len(), 3);
        assert_eq!(assembled.syntax_trees.root_item_count(), 4);
        assert_eq!(assembled.files[1].root_items.len(), 1);
        assert_eq!(assembled.files[2].root_items.len(), 2);
        assert_eq!(
            assembled
                .sources
                .get(psi_source::SourceId(2))
                .expect("second extension source")
                .source
                .as_ref(),
            extension_inputs[1].1,
        );
        let root_names = assembled
            .files
            .iter()
            .flat_map(|file| file.root_items.iter())
            .filter_map(|root| match assembled.syntax_trees.root_item(*root) {
                psi_syntax_trees::item::Item::Data(data) => Some(data.name.as_str()),
                psi_syntax_trees::item::Item::Machine(machine) => Some(machine.name.as_str()),
                _ => None,
            })
            .collect::<Vec<_>>();
        assert_eq!(root_names, ["base", "first", "Later", "second"]);
    }

    #[test]
    fn build_prelude_owns_canonical_dependency_vocabulary() {
        let tokens = psi_source_files_to_tokens::Lexer::new(BUILD_PRELUDE)
            .tokenize()
            .expect("toolchain build prelude must lex");
        let syntax_trees = psi_tokens_to_syntax_trees::parse_syntax_trees(&tokens)
            .expect("toolchain build prelude must parse as ordinary Omega");

        let source = syntax_trees
            .root_items()
            .find_map(|item| match item {
                psi_syntax_trees::item::Item::Data(data) if data.name.as_str() == "Source" => {
                    Some(data)
                }
                _ => None,
            })
            .expect("build prelude must define Source");
        let source_cases = syntax_trees.items.data_members(source.members);
        let [
            psi_syntax_trees::item::DataMember::Variant(path),
            psi_syntax_trees::item::DataMember::Variant(git),
        ] = source_cases
        else {
            panic!("Source must contain exactly Path and Git cases");
        };
        assert_eq!(path.name.as_str(), "Path");
        assert_eq!(
            syntax_trees
                .items
                .data_payload_fields(path.payload)
                .iter()
                .map(|field| field.name.as_str())
                .collect::<Vec<_>>(),
            ["location"]
        );
        assert_eq!(git.name.as_str(), "Git");
        assert_eq!(
            syntax_trees
                .items
                .data_payload_fields(git.payload)
                .iter()
                .map(|field| field.name.as_str())
                .collect::<Vec<_>>(),
            ["repository", "revision", "selection"]
        );

        let package_selection = syntax_trees
            .root_items()
            .find_map(|item| match item {
                psi_syntax_trees::item::Item::Data(data)
                    if data.name.as_str() == "PackageSelection" =>
                {
                    Some(data)
                }
                _ => None,
            })
            .expect("build prelude must define PackageSelection");
        assert_eq!(
            syntax_trees
                .items
                .data_members(package_selection.members)
                .iter()
                .filter_map(|member| match member {
                    psi_syntax_trees::item::DataMember::Variant(variant) => {
                        Some(variant.name.as_str())
                    }
                    _ => None,
                })
                .collect::<Vec<_>>(),
            ["Root", "Named"]
        );

        let mut dependency_methods = syntax_trees
            .root_items()
            .filter_map(|item| match item {
                psi_syntax_trees::item::Item::Machine(machine)
                    if machine
                        .attached_data
                        .as_ref()
                        .is_some_and(|owner| owner.as_str() == "Build") =>
                {
                    Some(machine)
                }
                _ => None,
            })
            .collect::<Vec<_>>();
        dependency_methods.sort_by_key(|machine| machine.name.as_str());
        assert_eq!(dependency_methods.len(), 5);
        assert_eq!(dependency_methods[0].name.as_str(), "Build::application");
        assert_eq!(dependency_methods[1].name.as_str(), "Build::depend");
        assert_eq!(dependency_methods[2].name.as_str(), "Build::depend_as");
        assert_eq!(dependency_methods[3].name.as_str(), "Build::member");
        assert_eq!(dependency_methods[4].name.as_str(), "Build::package");

        let parameter_names = |machine: &psi_syntax_trees::item::Machine| {
            let [entry] = syntax_trees.items.state_handles(machine.states) else {
                panic!("dependency method must have exactly one entry state");
            };
            syntax_trees
                .items
                .state_parameters(syntax_trees.items.state(*entry).parameters)
                .iter()
                .map(|handle| syntax_trees.items.state_parameter(*handle).name.as_str())
                .collect::<Vec<_>>()
        };
        assert_eq!(parameter_names(dependency_methods[0]), ["self", "name"]);
        assert_eq!(parameter_names(dependency_methods[1]), ["self", "source"]);
        assert_eq!(
            parameter_names(dependency_methods[2]),
            ["self", "alias", "source"]
        );
        assert_eq!(parameter_names(dependency_methods[3]), ["self", "path"]);
        assert_eq!(parameter_names(dependency_methods[4]), ["self", "name"]);
        assert!(!syntax_trees.root_items().any(|item| matches!(
            item,
            psi_syntax_trees::item::Item::Machine(machine)
                if machine.attached_data.is_none() && machine.name.as_str() == "path"
        )));
    }

    #[test]
    fn targeted_build_preludes_expose_one_closed_target_while_targetless_omit_it() {
        let expected_cases = [
            "LinuxArm64",
            "LinuxX86_64",
            "MacosArm64",
            "WindowsX86_64",
            "UefiX86_64",
            "CrossPlatformCli",
            "LocalUnchecked",
        ];
        for (has_exact_target, expected_target_fields) in [(false, 0), (true, 1)] {
            let prelude = construct_build_prelude(BUILD_PRELUDE, has_exact_target);
            let tokens = psi_source_files_to_tokens::Lexer::new(&prelude)
                .tokenize()
                .expect("constructed build prelude must lex");
            let syntax_trees = psi_tokens_to_syntax_trees::parse_syntax_trees(&tokens)
                .expect("constructed build prelude must parse as ordinary Omega");
            let target_profile = syntax_trees
                .root_items()
                .find_map(|item| match item {
                    psi_syntax_trees::item::Item::Data(data)
                        if data.name.as_str() == "TargetProfile" =>
                    {
                        Some(data)
                    }
                    _ => None,
                })
                .expect("build prelude must define TargetProfile");
            assert_eq!(
                syntax_trees
                    .items
                    .data_members(target_profile.members)
                    .iter()
                    .filter_map(|member| match member {
                        psi_syntax_trees::item::DataMember::Variant(variant) => {
                            Some(variant.name.as_str())
                        }
                        _ => None,
                    })
                    .collect::<Vec<_>>(),
                expected_cases
            );
            let x86_deployment_features = syntax_trees
                .root_items()
                .find_map(|item| match item {
                    psi_syntax_trees::item::Item::Data(data)
                        if data.name.as_str() == "X86DeploymentFeatures" =>
                    {
                        Some(data)
                    }
                    _ => None,
                })
                .expect("build prelude must define X86DeploymentFeatures");
            assert_eq!(
                syntax_trees
                    .items
                    .data_members(x86_deployment_features.members)
                    .iter()
                    .filter_map(|member| match member {
                        psi_syntax_trees::item::DataMember::Variant(variant) => {
                            Some(variant.name.as_str())
                        }
                        _ => None,
                    })
                    .collect::<Vec<_>>(),
                ["Baseline", "AvxFma3"]
            );
            let build = syntax_trees
                .root_items()
                .find_map(|item| match item {
                    psi_syntax_trees::item::Item::Data(data) if data.name.as_str() == "Build" => {
                        Some(data)
                    }
                    _ => None,
                })
                .expect("build prelude must define Build");
            let target_fields = syntax_trees
                .items
                .data_members(build.members)
                .iter()
                .filter_map(|member| match member {
                    psi_syntax_trees::item::DataMember::Field(field)
                        if field.name.as_str() == "target" =>
                    {
                        Some(field)
                    }
                    _ => None,
                })
                .collect::<Vec<_>>();
            assert_eq!(target_fields.len(), expected_target_fields);
            if let [field] = target_fields.as_slice() {
                assert!(matches!(
                    syntax_trees
                        .type_references
                        .type_reference(field.type_reference),
                    psi_syntax_trees::types::TypeReferenceNode::Named(name)
                        if name.as_str() == "TargetProfile"
                ));
            }
            let x86_feature_fields = syntax_trees
                .items
                .data_members(build.members)
                .iter()
                .filter_map(|member| match member {
                    psi_syntax_trees::item::DataMember::Field(field)
                        if field.name.as_str() == "x86_deployment_features" =>
                    {
                        Some(field)
                    }
                    _ => None,
                })
                .collect::<Vec<_>>();
            assert_eq!(x86_feature_fields.len(), expected_target_fields);
            if let [field] = x86_feature_fields.as_slice() {
                assert!(matches!(
                    syntax_trees
                        .type_references
                        .type_reference(field.type_reference),
                    psi_syntax_trees::types::TypeReferenceNode::Named(name)
                        if name.as_str() == "X86DeploymentFeatures"
                ));
            }
        }
    }

    #[test]
    fn build_prelude_owns_the_exact_optimization_vocabulary() {
        let expected_cases = omega_optimization_core::Optimization::ALL
            .iter()
            .map(|optimization| optimization.build_case_name())
            .collect::<Vec<_>>();
        let expected_fields = std::iter::once("human_report")
            .chain(
                omega_optimization_core::Optimization::ALL
                    .iter()
                    .map(|optimization| optimization.build_counter_field()),
            )
            .collect::<Vec<_>>();
        let prelude = construct_build_prelude(BUILD_PRELUDE, false);
        let tokens = psi_source_files_to_tokens::Lexer::new(&prelude)
            .tokenize()
            .expect("toolchain build prelude must lex");
        let syntax_trees = psi_tokens_to_syntax_trees::parse_syntax_trees(&tokens)
            .expect("toolchain build prelude must parse as ordinary Omega");
        let optimization = syntax_trees
            .root_items()
            .find_map(|item| match item {
                psi_syntax_trees::item::Item::Data(data)
                    if data.name.as_str() == "Optimization" =>
                {
                    Some(data)
                }
                _ => None,
            })
            .expect("build prelude must define Optimization");
        assert_eq!(
            syntax_trees
                .items
                .data_members(optimization.members)
                .iter()
                .filter_map(|member| match member {
                    psi_syntax_trees::item::DataMember::Variant(variant) => {
                        Some(variant.name.as_str())
                    }
                    _ => None,
                })
                .collect::<Vec<_>>(),
            expected_cases
        );
        let optimizations = syntax_trees
            .root_items()
            .find_map(|item| match item {
                psi_syntax_trees::item::Item::Data(data)
                    if data.name.as_str() == "Optimizations" =>
                {
                    Some(data)
                }
                _ => None,
            })
            .expect("build prelude must define Optimizations");
        assert_eq!(
            syntax_trees
                .items
                .data_members(optimizations.members)
                .iter()
                .filter_map(|member| match member {
                    psi_syntax_trees::item::DataMember::Field(field) => {
                        Some(field.name.as_str())
                    }
                    _ => None,
                })
                .collect::<Vec<_>>(),
            expected_fields
        );
        let build = syntax_trees
            .root_items()
            .find_map(|item| match item {
                psi_syntax_trees::item::Item::Data(data) if data.name.as_str() == "Build" => {
                    Some(data)
                }
                _ => None,
            })
            .expect("build prelude must define Build");
        assert!(
            syntax_trees
                .items
                .data_members(build.members)
                .iter()
                .any(|member| matches!(
                    member,
                    psi_syntax_trees::item::DataMember::Field(field)
                        if field.name.as_str() == "optimizations"
                ))
        );
        assert!(syntax_trees.root_items().any(|item| matches!(
            item,
            psi_syntax_trees::item::Item::Machine(machine)
                if machine.name.as_str() == "Optimizations::enable"
        )));
        assert!(syntax_trees.root_items().any(|item| matches!(
            item,
            psi_syntax_trees::item::Item::Machine(machine)
                if machine.name.as_str() == "Optimizations::emit_report"
        )));
    }
}
