[package]
name = "omega-symbol-resolved-trees"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_symbol_resolved_trees"
path = "src/lib.rs"

[dependencies]
psi-symbol-resolved-trees = { path = "../../../psi-rs/representations/psi-symbol-resolved-trees" }
