[package]
name = "omega-source-profile"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
name = "omega_source_profile"
path = "src/lib.rs"

[dependencies]
psi-syntax-trees = { path = "../../../psi/representations/psi-syntax-trees" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
