use super::super::SemanticLadder;

pub(crate) const LADDERS: &[SemanticLadder] = &[
    SemanticLadder {
        family: "non-authoritative target cost model",
        paths: &[
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/costs/mod.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/costs/model.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/costs/identity.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/costs/tests.rs",
        ],
    },
    SemanticLadder {
        family: "pre-allocation machine-effect codec",
        paths: &[
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/analyses/pre_allocation_effects/codec/mod.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/analyses/pre_allocation_effects/codec/cursor.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/analyses/pre_allocation_effects/codec/error.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/analyses/pre_allocation_effects/codec/v6/mod.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/analyses/pre_allocation_effects/codec/v6/framing.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/analyses/pre_allocation_effects/codec/v6/instruction.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/analyses/pre_allocation_effects/codec/v6/ownership.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/analyses/pre_allocation_effects/codec/v6/structural.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/analyses/pre_allocation_effects/codec/v6/values.rs",
        ],
    },
    SemanticLadder {
        family: "declarative bounded instruction-pair matching",
        paths: &[
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/peephole_matching/mod.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/peephole_matching/model.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/peephole_matching/registers.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/peephole_matching/instruction.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/peephole_matching/liveness.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/peephole_matching/relations.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/compare_zero_branch_nonzero/pattern.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_compare_zero/pattern.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_compare_i64_left_operand/pattern.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_compare_i64_right_operand/pattern.rs",
        ],
    },
    SemanticLadder {
        family: "AArch64 compare-zero/nonzero-branch CBNZ fusion",
        paths: &[
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/compare_zero_branch_nonzero/mod.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/compare_zero_branch_nonzero/pattern.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/compare_zero_branch_nonzero/model.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/compare_zero_branch_nonzero/compute.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/compare_zero_branch_nonzero/validate.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/compare_zero_branch_nonzero/identity.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/compare_zero_branch_nonzero/codec.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/compare_zero_branch_nonzero/tests/mod.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/compare_zero_branch_nonzero/tests/fixture.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/compare_zero_branch_nonzero/tests/fuel.rs",
            "omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/coordination/physical_pipeline/equal_zero_parameter.rs",
            "omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/coordination/physical_pipeline/not_equal_zero_parameter.rs",
        ],
    },
    SemanticLadder {
        family: "AArch64 non-terminal same-view copy elision",
        paths: &[
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_compare_zero/mod.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_compare_zero/contract.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_compare_zero/pattern.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_compare_zero/compute.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_compare_zero/validate.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_compare_zero/validate/replay.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_compare_zero/tests/mod.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_compare_zero/tests/matching.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_compare_zero/tests/operational.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_compare_zero/tests/corruption.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_compare_zero/tests/codec.rs",
            "omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/machine/aarch64_same_view_copy/mod.rs",
            "omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/machine/aarch64_same_view_copy/before_compare_zero.rs",
            "omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/machine/aarch64_same_view_copy/publication.rs",
            "omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/machine/aarch64_same_view_copy/custody_corruption.rs",
        ],
    },
    SemanticLadder {
        family: "AArch64 CompareI64-left same-view copy elision",
        paths: &[
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_compare_i64_left_operand/mod.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_compare_i64_left_operand/contract.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_compare_i64_left_operand/pattern.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_compare_i64_left_operand/compute.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_compare_i64_left_operand/validate.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_compare_i64_left_operand/validate/replay.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_compare_i64_left_operand/tests/mod.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_compare_i64_left_operand/tests/matching.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_compare_i64_left_operand/tests/operational.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_compare_i64_left_operand/tests/corruption.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_compare_i64_left_operand/tests/codec.rs",
            "omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/machine/aarch64_same_view_copy/mod.rs",
            "omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/machine/aarch64_same_view_copy/before_compare_i64_left_operand.rs",
            "omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/machine/aarch64_same_view_copy/publication.rs",
            "omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/machine/aarch64_same_view_copy/custody_corruption.rs",
        ],
    },
    SemanticLadder {
        family: "AArch64 CompareI64-right same-view copy elision",
        paths: &[
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_compare_i64_right_operand/mod.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_compare_i64_right_operand/contract.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_compare_i64_right_operand/pattern.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_compare_i64_right_operand/compute.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_compare_i64_right_operand/validate.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_compare_i64_right_operand/validate/replay.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_compare_i64_right_operand/tests/mod.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_compare_i64_right_operand/tests/matching.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_compare_i64_right_operand/tests/operational.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_compare_i64_right_operand/tests/corruption.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_compare_i64_right_operand/tests/codec.rs",
            "omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/machine/aarch64_same_view_copy/mod.rs",
            "omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/machine/aarch64_same_view_copy/before_compare_i64_right_operand.rs",
            "omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/machine/aarch64_same_view_copy/publication.rs",
            "omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/machine/aarch64_same_view_copy/custody_corruption.rs",
        ],
    },
    SemanticLadder {
        family: "AArch64 comparison-consumer same-view copy mechanics",
        paths: &[
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/same_view_copy_before_compare/mod.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/same_view_copy_before_compare/roots.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/same_view_copy_before_compare/footprints.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/same_view_copy_before_compare/proposal.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/same_view_copy_before_compare/replay.rs",
        ],
    },
    SemanticLadder {
        family: "AArch64 same-view copy artifact",
        paths: &[
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/same_view_copy_elision/mod.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/same_view_copy_elision/artifact/mod.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/same_view_copy_elision/artifact/model.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/same_view_copy_elision/artifact/identity.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/same_view_copy_elision/artifact/codec/mod.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/same_view_copy_elision/artifact/codec/cursor.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/same_view_copy_elision/artifact/codec/encode.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/same_view_copy_elision/artifact/codec/decode.rs",
        ],
    },
    SemanticLadder {
        family: "AArch64 same-view copy test support",
        paths: &[
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/same_view_copy_elision/test_support/mod.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/same_view_copy_elision/test_support/fixture.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/same_view_copy_elision/test_support/right_operand.rs",
        ],
    },
    SemanticLadder {
        family: "AArch64 exact same-view return-copy elision",
        paths: &[
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_return/mod.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_return/pattern.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_return/compute.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_return/validate/mod.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_return/validate/roots.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_return/validate/footprints.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_return/validate/replay.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_return/tests/mod.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_return/tests/matching.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_return/tests/operational.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_return/tests/corruption.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/elide_same_view_copy_before_return/tests/codec.rs",
        ],
    },
    SemanticLadder {
        family: "AArch64 same-view copy pipeline custody",
        paths: &[
            "omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/stages/machine/post_allocation_optimizations/aarch64_same_view_copy/mod.rs",
            "omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/stages/machine/post_allocation_optimizations/aarch64_same_view_copy/model.rs",
            "omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/stages/machine/post_allocation_optimizations/aarch64_same_view_copy/baseline_source.rs",
            "omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/stages/machine/post_allocation_optimizations/aarch64_same_view_copy/selected_lowering_source.rs",
            "omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/stages/machine/post_allocation_optimizations/aarch64_same_view_copy/execution.rs",
        ],
    },
    SemanticLadder {
        family: "AArch64 MOVN proposal",
        paths: &[
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/materialize_i64_movn/compute/mod.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/materialize_i64_movn/compute/budget.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/materialize_i64_movn/compute/materialization.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/materialize_i64_movn/compute/recipe.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/materialize_i64_movn/compute/selection.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/materialize_i64_movn/compute/source.rs",
            "omega-rust/omega/pipeline/optimization/omega-machine-optimizer/src/rules/aarch64/materialize_i64_movn/compute/tests.rs",
        ],
    },
];
