use super::super::SemanticLadder;

pub(crate) const LADDERS: &[SemanticLadder] = &[
    SemanticLadder {
        family: "optimization manifest",
        paths: &[
            "source/omega-rust/omega/representations/omega-optimization-core/src/manifest/codec.rs",
            "source/omega-rust/omega/representations/omega-optimization-core/src/manifest/decision.rs",
            "source/omega-rust/omega/representations/omega-optimization-core/src/manifest/error.rs",
            "source/omega-rust/omega/representations/omega-optimization-core/src/manifest/fact_reference.rs",
            "source/omega-rust/omega/representations/omega-optimization-core/src/manifest/pass.rs",
            "source/omega-rust/omega/representations/omega-optimization-core/src/manifest/work_usage.rs",
        ],
    },
    SemanticLadder {
        family: "optimization-unit identity encoding",
        paths: &[
            "source/omega-rust/omega/representations/omega-optimization-unit/src/identity/operation_encoding/calls_and_effects.rs",
            "source/omega-rust/omega/representations/omega-optimization-unit/src/identity/operation_encoding/control.rs",
            "source/omega-rust/omega/representations/omega-optimization-unit/src/identity/operation_encoding/scalar.rs",
            "source/omega-rust/omega/representations/omega-optimization-unit/src/identity/operation_encoding/scalar_shapes.rs",
            "source/omega-rust/omega/representations/omega-optimization-unit/src/identity/operation_encoding/structural.rs",
            "source/omega-rust/omega/representations/omega-optimization-unit/src/identity/carrier_encoding.rs",
        ],
    },
    SemanticLadder {
        family: "optimizer ranked-cycle component validation",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/unit_validation/context/ranked_cycles/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/unit_validation/context/ranked_cycles/model.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/unit_validation/context/ranked_cycles/graph.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/unit_validation/context/ranked_cycles/components.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/unit_validation/context/ranked_cycles/topology.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/unit_validation/context/ranked_cycles/replay.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/unit_validation/context/ranked_cycles/freeze.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/unit_validation/context/ranked_cycles/countdown_ranking/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/unit_validation/context/ranked_cycles/countdown_ranking/terminal.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/unit_validation/context/ranked_cycles/countdown_ranking/current.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/unit_validation/context/ranked_cycles/countdown_ranking/current/invariant_constants.rs",
        ],
    },
    SemanticLadder {
        family: "optimizer exact countdown induction analysis",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/analyses/control_flow/countdown_induction/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/analyses/control_flow/countdown_induction/model.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/analyses/control_flow/countdown_induction/compute.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/analyses/control_flow/countdown_induction/replay.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/analyses/control_flow/countdown_induction/replay/region.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/analyses/control_flow/countdown_induction/validate.rs",
        ],
    },
    SemanticLadder {
        family: "optimizer exact countdown invariant-constant analysis",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/analyses/control_flow/countdown_invariant_constants/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/analyses/control_flow/countdown_invariant_constants/model.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/analyses/control_flow/countdown_invariant_constants/compute.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/analyses/control_flow/countdown_invariant_constants/replay.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/analyses/control_flow/countdown_invariant_constants/validate.rs",
        ],
    },
    SemanticLadder {
        family: "optimizer exact countdown invariant-constant placement analysis",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/analyses/control_flow/countdown_invariant_constant_placement/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/analyses/control_flow/countdown_invariant_constant_placement/model.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/analyses/control_flow/countdown_invariant_constant_placement/compute.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/analyses/control_flow/countdown_invariant_constant_placement/replay.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/analyses/control_flow/countdown_invariant_constant_placement/validate.rs",
        ],
    },
    SemanticLadder {
        family: "SCCP validation",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/sparse_conditional_constant_propagation/boolean_candidate.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/sparse_conditional_constant_propagation/integer_candidate.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/sparse_conditional_constant_propagation/observation.rs",
        ],
    },
    SemanticLadder {
        family: "SCCP integer-evaluation validation",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/sparse_conditional_constant_propagation/integer_evaluation/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/sparse_conditional_constant_propagation/integer_evaluation/rule_identity.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/sparse_conditional_constant_propagation/integer_evaluation/unary_operations.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/sparse_conditional_constant_propagation/integer_evaluation/binary_operation_shape.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/sparse_conditional_constant_propagation/integer_evaluation/binary_semantics.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/sparse_conditional_constant_propagation/integer_evaluation/literal_facts.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/sparse_conditional_constant_propagation/integer_evaluation/model.rs",
        ],
    },
    SemanticLadder {
        family: "SCCP Boolean-evaluation validation",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/sparse_conditional_constant_propagation/boolean_evaluation/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/sparse_conditional_constant_propagation/boolean_evaluation/rule_identity.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/sparse_conditional_constant_propagation/boolean_evaluation/boolean_literals.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/sparse_conditional_constant_propagation/boolean_evaluation/integer_comparisons/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/sparse_conditional_constant_propagation/boolean_evaluation/integer_comparisons/constant.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/sparse_conditional_constant_propagation/boolean_evaluation/integer_comparisons/range_against_constant.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/sparse_conditional_constant_propagation/boolean_evaluation/integer_comparisons/range_against_constant/semantics.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/sparse_conditional_constant_propagation/boolean_evaluation/integer_comparisons/range_against_range.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/sparse_conditional_constant_propagation/boolean_evaluation/integer_comparisons/range_against_range/semantics.rs",
        ],
    },
    SemanticLadder {
        family: "SCCP Boolean-result constant-evaluation rules",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/sparse_conditional_constant_propagation/constant_evaluation/boolean/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/sparse_conditional_constant_propagation/constant_evaluation/boolean/model.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/sparse_conditional_constant_propagation/constant_evaluation/boolean/evaluation.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/sparse_conditional_constant_propagation/constant_evaluation/boolean/proposal.rs",
        ],
    },
    SemanticLadder {
        family: "SCCP proof-certified integer-cast constant-evaluation rule",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/sparse_conditional_constant_propagation/constant_evaluation/integer/exact_integer_cast_constants/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/sparse_conditional_constant_propagation/constant_evaluation/integer/exact_integer_cast_constants/proposal.rs",
        ],
    },
    SemanticLadder {
        family: "SCCP binary integer constant-evaluation rules",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/sparse_conditional_constant_propagation/constant_evaluation/integer/binary/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/sparse_conditional_constant_propagation/constant_evaluation/integer/binary/model.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/sparse_conditional_constant_propagation/constant_evaluation/integer/binary/evaluation.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/sparse_conditional_constant_propagation/constant_evaluation/integer/binary/proposal.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/sparse_conditional_constant_propagation/constant_evaluation/integer/binary/witness.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/sparse_conditional_constant_propagation/constant_evaluation/integer/binary/shapes/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/sparse_conditional_constant_propagation/constant_evaluation/integer/binary/shapes/arithmetic.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/sparse_conditional_constant_propagation/constant_evaluation/integer/binary/shapes/quotient.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/sparse_conditional_constant_propagation/constant_evaluation/integer/binary/shapes/shifts.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/sparse_conditional_constant_propagation/constant_evaluation/integer/binary/shapes/bitwise.rs",
        ],
    },
    SemanticLadder {
        family: "SCCP unary integer constant-evaluation rules",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/sparse_conditional_constant_propagation/constant_evaluation/integer/unary/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/sparse_conditional_constant_propagation/constant_evaluation/integer/unary/model.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/sparse_conditional_constant_propagation/constant_evaluation/integer/unary/proposal.rs",
        ],
    },
    SemanticLadder {
        family: "SCCP range-against-constant rules",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/sparse_conditional_constant_propagation/range_comparisons/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/sparse_conditional_constant_propagation/range_comparisons/model.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/sparse_conditional_constant_propagation/range_comparisons/against_constant/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/sparse_conditional_constant_propagation/range_comparisons/against_constant/proposal.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/sparse_conditional_constant_propagation/range_comparisons/against_constant/evaluation.rs",
        ],
    },
    SemanticLadder {
        family: "SCCP range-against-range rules",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/sparse_conditional_constant_propagation/range_comparisons/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/sparse_conditional_constant_propagation/range_comparisons/model.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/sparse_conditional_constant_propagation/range_comparisons/against_range/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/sparse_conditional_constant_propagation/range_comparisons/against_range/proposal.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/sparse_conditional_constant_propagation/range_comparisons/against_range/evaluation.rs",
        ],
    },
    SemanticLadder {
        family: "independent GVN expression keys",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/global_value_numbering/expression_keys/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/global_value_numbering/expression_keys/model.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/global_value_numbering/expression_keys/total.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/global_value_numbering/expression_keys/proof_certified.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/global_value_numbering/expression_keys/compatible_policy.rs",
        ],
    },
    SemanticLadder {
        family: "Psi global-value-numbering rules",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/global_value_numbering/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/global_value_numbering/effect_admission.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/global_value_numbering/expression_keys/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/global_value_numbering/local/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/global_value_numbering/dominating/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/global_value_numbering/phi_translated/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/global_value_numbering/phi_translated/accounting.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/global_value_numbering/identities/mod.rs",
        ],
    },
    SemanticLadder {
        family: "Psi GVN total scalar identity tests",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/tests/global_value_numbering/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/tests/global_value_numbering/total_scalar_identity/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/tests/global_value_numbering/total_scalar_identity/catalog.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/tests/global_value_numbering/total_scalar_identity/wrapping_neutral.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/tests/global_value_numbering/total_scalar_identity/wrapping_shift_zero_count.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/tests/global_value_numbering/total_scalar_identity/wrapping_multiply_zero.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/tests/global_value_numbering/total_scalar_identity/saturating_neutral.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/tests/global_value_numbering/total_scalar_identity/saturating_multiply_zero.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/tests/global_value_numbering/total_scalar_identity/bitwise_neutral.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/tests/global_value_numbering/total_scalar_identity/bitwise_absorbing.rs",
        ],
    },
    SemanticLadder {
        family: "Psi GVN scalar common-subexpression tests",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/tests/global_value_numbering/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/tests/global_value_numbering/scalar_common_subexpression/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/tests/global_value_numbering/scalar_common_subexpression/contract_custody.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/tests/global_value_numbering/scalar_common_subexpression/same_block.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/tests/global_value_numbering/scalar_common_subexpression/dominating.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/tests/global_value_numbering/scalar_common_subexpression/phi_translated.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/tests/global_value_numbering/scalar_common_subexpression/compatible_policy.rs",
        ],
    },
    SemanticLadder {
        family: "transformation ledger",
        paths: &[
            "source/omega-rust/omega/representations/omega-optimization-unit/src/ledger/model.rs",
            "source/omega-rust/omega/representations/omega-optimization-unit/src/ledger/error.rs",
            "source/omega-rust/omega/representations/omega-optimization-unit/src/ledger/validation.rs",
            "source/omega-rust/omega/representations/omega-optimization-unit/src/ledger/codec/mod.rs",
            "source/omega-rust/omega/representations/omega-optimization-unit/src/ledger/codec/encoding.rs",
            "source/omega-rust/omega/representations/omega-optimization-unit/src/ledger/codec/decoding.rs",
            "source/omega-rust/omega/representations/omega-optimization-unit/src/ledger/codec/cursor.rs",
            "source/omega-rust/omega/representations/omega-optimization-unit/src/ledger/tests.rs",
        ],
    },
    SemanticLadder {
        family: "rewrite model",
        paths: &[
            "source/omega-rust/omega/representations/omega-optimization-unit/src/rewrite/model/mod.rs",
            "source/omega-rust/omega/representations/omega-optimization-unit/src/rewrite/canonical_encoding.rs",
            "source/omega-rust/omega/representations/omega-optimization-unit/src/rewrite/model/foundations.rs",
            "source/omega-rust/omega/representations/omega-optimization-unit/src/rewrite/model/scalar_evaluation.rs",
            "source/omega-rust/omega/representations/omega-optimization-unit/src/rewrite/model/sccp.rs",
            "source/omega-rust/omega/representations/omega-optimization-unit/src/rewrite/model/cfg_rewrite_plans.rs",
            "source/omega-rust/omega/representations/omega-optimization-unit/src/rewrite/model/scalar_rewrite_plans.rs",
            "source/omega-rust/omega/representations/omega-optimization-unit/src/rewrite/model/contracts.rs",
        ],
    },
    SemanticLadder {
        family: "optimization-unit seed construction",
        paths: &[
            "source/omega-rust/omega/representations/omega-optimization-unit/src/construction/mod.rs",
            "source/omega-rust/omega/representations/omega-optimization-unit/src/construction/function.rs",
            "source/omega-rust/omega/representations/omega-optimization-unit/src/construction/provenance.rs",
            "source/omega-rust/omega/representations/omega-optimization-unit/src/construction/scalar_dataflow.rs",
            "source/omega-rust/omega/representations/omega-optimization-unit/src/construction/control_flow.rs",
            "source/omega-rust/omega/representations/omega-optimization-unit/src/construction/facts.rs",
            "source/omega-rust/omega/representations/omega-optimization-unit/src/construction/structural_custody.rs",
        ],
    },
    SemanticLadder {
        family: "copy propagation rule",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/copy_propagation/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/copy_propagation/redundant_block_parameter/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/copy_propagation/redundant_block_parameter/proposal.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/copy_propagation/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/copy_propagation/validation.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/copy_propagation/observation.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/copy_propagation/operation_rewrite.rs",
        ],
    },
    SemanticLadder {
        family: "control-flow cleanup independent validation",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/control_flow_cleanup/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/control_flow_cleanup/contract.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/control_flow_cleanup/constant_conditionals/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/control_flow_cleanup/constant_conditionals/replay.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/control_flow_cleanup/empty_block_threading/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/control_flow_cleanup/empty_block_threading/linear/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/control_flow_cleanup/empty_block_threading/linear/replay.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/control_flow_cleanup/empty_block_threading/path_qualified/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/control_flow_cleanup/empty_block_threading/path_qualified/replay.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/control_flow_cleanup/block_merging/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/control_flow_cleanup/block_merging/adjacent/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/control_flow_cleanup/block_merging/adjacent/replay.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/control_flow_cleanup/block_merging/non_adjacent/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/control_flow_cleanup/block_merging/non_adjacent/replay.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/control_flow_cleanup/shared_jump_fusion/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/control_flow_cleanup/shared_jump_fusion/replay.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/control_flow_cleanup/unreachable_private_machines/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/control_flow_cleanup/unreachable_private_machines/replay.rs",
        ],
    },
    SemanticLadder {
        family: "control-flow merge mechanics",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/control_flow_cleanup/block_merging/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/control_flow_cleanup/block_merging/adjacent.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/control_flow_cleanup/block_merging/adjacent_accounting.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/control_flow_cleanup/block_merging/non_adjacent.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/control_flow_cleanup/block_merging/non_adjacent_accounting.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/control_flow_cleanup/block_merging/substitutions.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/control_flow_cleanup/merge_boundary_ownership.rs",
        ],
    },
    SemanticLadder {
        family: "empty-block threading rules",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/control_flow_cleanup/empty_block_threading/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/control_flow_cleanup/empty_block_threading/linear.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/control_flow_cleanup/empty_block_threading/path_qualified.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/control_flow_cleanup/empty_block_threading/binding_composition.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/control_flow_cleanup/empty_block_threading/ownership_identity.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/control_flow_cleanup/empty_block_threading/linear_accounting.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/control_flow_cleanup/empty_block_threading/path_qualified_accounting.rs",
        ],
    },
    SemanticLadder {
        family: "dead scalar elimination rules",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/dead_scalar_elimination/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/dead_scalar_elimination/literal/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/dead_scalar_elimination/literal/operation_admission.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/dead_scalar_elimination/unconditionally_total/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/dead_scalar_elimination/unconditionally_total/operation_admission.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/support/dead_scalar_node/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/support/dead_scalar_node/model.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/support/dead_scalar_node/proposal.rs",
        ],
    },
    SemanticLadder {
        family: "dead scalar elimination producer tests",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/tests/dead_scalar_elimination/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/tests/dead_scalar_elimination/contract_custody.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/tests/dead_scalar_elimination/literal.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/tests/dead_scalar_elimination/unconditionally_total.rs",
        ],
    },
    SemanticLadder {
        family: "proof-check identity rules",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/proof_check_elision/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/proof_check_elision/dead_scalar/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/proof_check_elision/dead_scalar/operation_admission.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/proof_check_elision/scalar_identities.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/proof_check_elision/divide_by_one.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/proof_check_elision/multiply_by_zero.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/proof_check_elision/zero_dividend.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/proof_check_elision/zero_value_shift.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/proof_check_elision/self_subtract.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/proof_check_elision/self_remainder.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/proof_check_elision/self_divide.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/proof_check_elision/remainder_by_one.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/proof_check_elision/signed_remainder_by_negative_one.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/proof_check_elision/negative_one_shift_right.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/proof_check_elision/identity_rewrite/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/proof_check_elision/identity_rewrite/model.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/proof_check_elision/identity_rewrite/proposal.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/proof_check_elision/identity_rewrite/typed_literals.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/support/node_elision_accounting.rs",
        ],
    },
    SemanticLadder {
        family: "proof-check contract and operational custody tests",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/tests/proof_check_elision/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/rules/passes/tests/proof_check_elision/contract_custody.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-psi-optimizer/src/pass_manager/tests/execution/fixed_points/proof_check_operational.rs",
        ],
    },
    SemanticLadder {
        family: "independent proof-check validation",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/proof_check_elision/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/proof_check_elision/rule_catalog.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/proof_check_elision/candidate_validation.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/proof_check_elision/identity_classification.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/proof_check_elision/same_operand.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/candidates/proof_check_elision/unit_divisor.rs",
        ],
    },
];
