use super::super::SemanticLadder;

mod callee_save_storage;
mod fixed_precolored_segment_homes;
mod fixed_precolored_split_requirements;

pub(crate) const LADDERS: &[SemanticLadder] = &[
    SemanticLadder {
        family: "selected-plan canonical identity",
        paths: &[
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/identity.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/identity/ordinary.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/identity/primitives.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/identity/projected_structural.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/identity/structural_legalized.rs",
        ],
    },
    SemanticLadder {
        family: "selected-CFG liveness computation",
        paths: &[
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/analyses/liveness/compute.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/analyses/liveness/compute/control.rs",
        ],
    },
    SemanticLadder {
        family: "logical spill-operation planning",
        paths: &[
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/logical_spill_operations/mod.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/logical_spill_operations/model.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/logical_spill_operations/identity.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/logical_spill_operations/compute/mod.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/logical_spill_operations/compute/action.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/logical_spill_operations/compute/work.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/logical_spill_operations/validate/mod.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/logical_spill_operations/validate/replay.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/logical_spill_operations/validate/work.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/logical_spill_operations/validate/receipt.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/logical_spill_operations/codec/mod.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/logical_spill_operations/codec/encoding.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/logical_spill_operations/codec/decoding.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/logical_spill_operations/codec/cursor.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/logical_spill_operations/codec/values.rs",
        ],
    },
    SemanticLadder {
        family: "stack-slot coloring",
        paths: &[
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/stack_slot_coloring/mod.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/stack_slot_coloring/model.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/stack_slot_coloring/identity.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/stack_slot_coloring/compute/mod.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/stack_slot_coloring/compute/intervals.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/stack_slot_coloring/compute/first_fit.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/stack_slot_coloring/compute/work.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/stack_slot_coloring/validate/mod.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/stack_slot_coloring/validate/root.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/stack_slot_coloring/validate/replay.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/stack_slot_coloring/validate/work.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/stack_slot_coloring/validate/receipt.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/stack_slot_coloring/codec/mod.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/stack_slot_coloring/codec/encoding.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/stack_slot_coloring/codec/decoding.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/stack_slot_coloring/codec/cursor.rs",
        ],
    },
    SemanticLadder {
        family: "abstract spill insertion",
        paths: &[
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/abstract_spill_insertion/mod.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/abstract_spill_insertion/model.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/abstract_spill_insertion/identity.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/abstract_spill_insertion/compute.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/abstract_spill_insertion/validate.rs",
        ],
    },
    SemanticLadder {
        family: "reload-value home assignment",
        paths: &[
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/reload_value_homes/mod.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/reload_value_homes/model.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/reload_value_homes/identity.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/reload_value_homes/compute.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/reload_value_homes/replay.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/reload_value_homes/replay/mechanics.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/reload_value_homes/validate.rs",
        ],
    },
    SemanticLadder {
        family: "synthetic reload-value namespace",
        paths: &[
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/synthetic_reload_values/mod.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/synthetic_reload_values/model.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/synthetic_reload_values/identity.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/synthetic_reload_values/compute.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/synthetic_reload_values/replay.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/synthetic_reload_values/validate.rs",
        ],
    },
    SemanticLadder {
        family: "recursive spill-recovery victim choice",
        paths: &[
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/spill_recovery_choice/mod.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/spill_recovery_choice/model.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/spill_recovery_choice/identity.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/spill_recovery_choice/compute.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/spill_recovery_choice/replay.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/spill_recovery_choice/validate.rs",
        ],
    },
    SemanticLadder {
        family: "recursive spill-recovery logical actions",
        paths: &[
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/spill_recovery_actions/mod.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/spill_recovery_actions/model.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/spill_recovery_actions/identity.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/spill_recovery_actions/compute.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/spill_recovery_actions/replay.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/spill_recovery_actions/validate.rs",
        ],
    },
    SemanticLadder {
        family: "generalized epoch-zero and epoch-one spill insertion",
        paths: &[
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_spill_insertion/mod.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_spill_insertion/model.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_spill_insertion/identity.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_spill_insertion/compute.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_spill_insertion/replay.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_spill_insertion/validate.rs",
        ],
    },
    SemanticLadder {
        family: "generalized epoch-zero and epoch-one reload-home reanalysis",
        paths: &[
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_reload_value_homes/mod.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_reload_value_homes/model.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_reload_value_homes/identity.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_reload_value_homes/compute.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_reload_value_homes/compute/roots.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_reload_value_homes/compute/sources.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_reload_value_homes/compute/homes.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_reload_value_homes/compute/schedule.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_reload_value_homes/compute/work.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_reload_value_homes/replay.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_reload_value_homes/replay/roots.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_reload_value_homes/replay/sources.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_reload_value_homes/replay/homes.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_reload_value_homes/replay/timeline.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_reload_value_homes/replay/work.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_reload_value_homes/validate.rs",
        ],
    },
    SemanticLadder {
        family: "generalized epoch-two spill-recovery worklist",
        paths: &[
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_spill_recovery_worklist/mod.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_spill_recovery_worklist/model.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_spill_recovery_worklist/identity.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_spill_recovery_worklist/compute.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_spill_recovery_worklist/replay.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_spill_recovery_worklist/validate.rs",
        ],
    },
    SemanticLadder {
        family: "generalized epoch-two spill-recovery victim choice",
        paths: &[
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_spill_recovery_choice/mod.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_spill_recovery_choice/model.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_spill_recovery_choice/identity.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_spill_recovery_choice/compute.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_spill_recovery_choice/compute/original_eligibility.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_spill_recovery_choice/replay.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_spill_recovery_choice/replay/original_eligibility.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_spill_recovery_choice/validate.rs",
        ],
    },
    SemanticLadder {
        family: "generalized epoch-two logical recovery actions",
        paths: &[
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_spill_recovery_actions/mod.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_spill_recovery_actions/model.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_spill_recovery_actions/identity.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_spill_recovery_actions/compute.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_spill_recovery_actions/compute/original.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_spill_recovery_actions/replay.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_spill_recovery_actions/replay/original.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/generalized_spill_recovery_actions/validate.rs",
        ],
    },
    SemanticLadder {
        family: "recursive epoch-two spill insertion",
        paths: &[
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/recursive_spill_insertion/mod.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/recursive_spill_insertion/model.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/recursive_spill_insertion/identity.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/recursive_spill_insertion/compute.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/recursive_spill_insertion/replay.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/recursive_spill_insertion/validate.rs",
        ],
    },
    SemanticLadder {
        family: "complete recursive reload-home closure",
        paths: &[
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/recursive_reload_value_homes/mod.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/recursive_reload_value_homes/model.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/recursive_reload_value_homes/identity.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/recursive_reload_value_homes/compute.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/recursive_reload_value_homes/compute/roots.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/recursive_reload_value_homes/compute/sources.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/recursive_reload_value_homes/compute/homes.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/recursive_reload_value_homes/compute/schedule.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/recursive_reload_value_homes/compute/work.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/recursive_reload_value_homes/replay.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/recursive_reload_value_homes/replay/roots.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/recursive_reload_value_homes/replay/sources.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/recursive_reload_value_homes/replay/homes.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/recursive_reload_value_homes/replay/timeline.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/recursive_reload_value_homes/replay/work.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/recursive_reload_value_homes/validate.rs",
        ],
    },
    SemanticLadder {
        family: "target-neutral spill-pseudo instructions",
        paths: &[
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/spill_pseudo_instructions/mod.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/spill_pseudo_instructions/model.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/spill_pseudo_instructions/identity.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/spill_pseudo_instructions/compute.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/spill_pseudo_instructions/replay.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/spill_pseudo_instructions/validate.rs",
        ],
    },
    SemanticLadder {
        family: "V2 target-neutral homed spill-pseudo instructions",
        paths: &[
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/spill_pseudo_instructions/homed/mod.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/spill_pseudo_instructions/homed/model.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/spill_pseudo_instructions/homed/identity.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/spill_pseudo_instructions/homed/compute.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/spill_pseudo_instructions/homed/compute/work.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/spill_pseudo_instructions/homed/replay.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/spill_pseudo_instructions/homed/replay/work.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/spill_pseudo_instructions/homed/validate.rs",
        ],
    },
    SemanticLadder {
        family: "target-neutral abstract spill memory effects",
        paths: &[
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/abstract_spill_memory_effects/mod.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/abstract_spill_memory_effects/model.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/abstract_spill_memory_effects/identity.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/abstract_spill_memory_effects/compute.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/abstract_spill_memory_effects/compute/storage.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/abstract_spill_memory_effects/compute/work.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/abstract_spill_memory_effects/replay.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/abstract_spill_memory_effects/replay/work.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/abstract_spill_memory_effects/validate.rs",
        ],
    },
    SemanticLadder {
        family: "target-neutral abstract spill access constraints",
        paths: &[
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/abstract_spill_access_constraints/mod.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/abstract_spill_access_constraints/model.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/abstract_spill_access_constraints/model/error.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/abstract_spill_access_constraints/identity.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/abstract_spill_access_constraints/compute.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/abstract_spill_access_constraints/compute/accesses.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/abstract_spill_access_constraints/compute/dependencies.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/abstract_spill_access_constraints/compute/work.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/abstract_spill_access_constraints/replay.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/abstract_spill_access_constraints/replay/accesses.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/abstract_spill_access_constraints/replay/dependencies.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/abstract_spill_access_constraints/replay/work.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/abstract_spill_access_constraints/validate.rs",
        ],
    },
    SemanticLadder {
        family: "allocation-visible callee-saved requirements",
        paths: &[
            "omega-rust/omega/pipeline/target-to-register-environment/src/abi_preservation.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/preservation/mod.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/preservation/model.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/preservation/error.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/preservation/identity.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/preservation/custody.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/preservation/validation.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/preservation/compute/mod.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/preservation/compute/state.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/preservation/compute/ordinary.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/preservation/compute/structural.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/preservation/compute/work.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/preservation/replay/mod.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/preservation/replay/state.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/preservation/replay/ordinary.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/preservation/replay/structural.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/preservation/replay/writes.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/preservation/replay/work.rs",
        ],
    },
    SemanticLadder {
        family: "allocation-visible callee-saved requirement coverage",
        paths: &[
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/callee_saved_requirements/mod.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/callee_saved_requirements/fixture.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/callee_saved_requirements/positive.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/callee_saved_requirements/corruption.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/callee_saved_requirements/budget.rs",
        ],
    },
    callee_save_storage::PRODUCTION,
    callee_save_storage::COVERAGE,
    SemanticLadder {
        family: "non-authoritative spill-frame requirements",
        paths: &[
            "omega-rust/omega/pipeline/post-allocation-machine-to-frame-layout/src/spill_requirements/mod.rs",
            "omega-rust/omega/pipeline/post-allocation-machine-to-frame-layout/src/spill_requirements/model.rs",
            "omega-rust/omega/pipeline/post-allocation-machine-to-frame-layout/src/spill_requirements/identity.rs",
            "omega-rust/omega/pipeline/post-allocation-machine-to-frame-layout/src/spill_requirements/compute.rs",
            "omega-rust/omega/pipeline/post-allocation-machine-to-frame-layout/src/spill_requirements/replay.rs",
            "omega-rust/omega/pipeline/post-allocation-machine-to-frame-layout/src/spill_requirements/validation.rs",
            "omega-rust/omega/pipeline/post-allocation-machine-to-frame-layout/src/spill_requirements/custody.rs",
        ],
    },
    SemanticLadder {
        family: "non-authoritative spill-frame requirement coverage",
        paths: &[
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/frame_requirements/mod.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/frame_requirements/fixture.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/frame_requirements/positive.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/frame_requirements/corruption.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/frame_requirements/budget.rs",
        ],
    },
    SemanticLadder {
        family: "fixed/precolored point intervals",
        paths: &[
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/analyses/fixed_precolored_intervals/mod.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/analyses/fixed_precolored_intervals/model.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/analyses/fixed_precolored_intervals/identity.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/analyses/fixed_precolored_intervals/compute.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/analyses/fixed_precolored_intervals/replay.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/analyses/fixed_precolored_intervals/validate.rs",
        ],
    },
    fixed_precolored_split_requirements::PRODUCTION,
    fixed_precolored_split_requirements::COVERAGE,
    fixed_precolored_segment_homes::PRODUCTION,
    fixed_precolored_segment_homes::COVERAGE,
    SemanticLadder {
        family: "post-allocation manifest mutation custody tests",
        paths: &[
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/post_allocation_manifest_mutation_matrix/mod.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/post_allocation_manifest_mutation_matrix/fixture.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/post_allocation_manifest_mutation_matrix/fields.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/post_allocation_manifest_mutation_matrix/wire.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/post_allocation_manifest_mutation_matrix/wire_offsets.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/post_allocation_manifest_mutation_matrix/custody.rs",
        ],
    },
    SemanticLadder {
        family: "recursive spill-recovery worklist",
        paths: &[
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/spill_recovery_worklist/mod.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/spill_recovery_worklist/model.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/spill_recovery_worklist/identity.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/spill_recovery_worklist/compute.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/spill_recovery_worklist/replay.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/spill_recovery_worklist/validate.rs",
        ],
    },
    SemanticLadder {
        family: "selected machine-effect carrier",
        paths: &[
            "omega-rust/omega/representations/selected-instructions/src/selected_instructions/effects/catalog.rs",
            "omega-rust/omega/representations/selected-instructions/src/selected_instructions/effects/catalog/model.rs",
            "omega-rust/omega/representations/selected-instructions/src/selected_instructions/effects/catalog/constraint_keys.rs",
            "omega-rust/omega/representations/selected-instructions/src/selected_instructions/effects/catalog/validation.rs",
            "omega-rust/omega/representations/selected-instructions/src/selected_instructions/effects/catalog/identity.rs",
        ],
    },
    SemanticLadder {
        family: "assigned target-operation carrier",
        paths: &[
            "omega-rust/omega/representations/assigned-target-operations/src/lib.rs",
            "omega-rust/omega/representations/assigned-target-operations/src/assigned_operations/operations/operation.rs",
            "omega-rust/omega/representations/assigned-target-operations/src/assigned_operations.rs",
            "omega-rust/omega/representations/assigned-target-operations/src/assigned_operations/operations/unit.rs",
            "omega-rust/omega/representations/assigned-target-operations/src/assigned_operations/values/mod.rs",
            "omega-rust/omega/representations/assigned-target-operations/src/assigned_operations/values/boolean.rs",
            "omega-rust/omega/representations/assigned-target-operations/src/assigned_operations/values/integer.rs",
            "omega-rust/omega/representations/assigned-target-operations/src/assigned_operations/storage.rs",
        ],
    },
    SemanticLadder {
        family: "fixed-view-copy codec",
        paths: &[
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/allocation_recovery/fixed_view_copy/codec/mod.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/allocation_recovery/fixed_view_copy/codec/decoding.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/allocation_recovery/fixed_view_copy/codec/envelope.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/allocation_recovery/fixed_view_copy/codec/content.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/allocation_recovery/fixed_view_copy/codec/evidence.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/allocation_recovery/fixed_view_copy/codec/copy.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/allocation_recovery/fixed_view_copy/codec/primitives.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/allocation_recovery/fixed_view_copy/codec/values.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/allocation_recovery/fixed_view_copy/codec/selected/function.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/allocation_recovery/fixed_view_copy/codec/selected/register.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/allocation_recovery/fixed_view_copy/codec/selected/block.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/allocation_recovery/fixed_view_copy/codec/selected/instruction.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/allocation_recovery/fixed_view_copy/codec/selected/provenance.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/allocation_recovery/fixed_view_copy/codec/selected/scalar.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/allocation_recovery/fixed_view_copy/codec/selected/structural/mod.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/allocation_recovery/fixed_view_copy/codec/selected/structural/signature.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/allocation_recovery/fixed_view_copy/codec/selected/structural/call.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/allocation_recovery/fixed_view_copy/codec/selected/structural/calling.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/allocation_recovery/fixed_view_copy/codec/selected/structural/declarations.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/allocation_recovery/fixed_view_copy/codec/selected/structural/settlements.rs",
        ],
    },
    SemanticLadder {
        family: "fixed-view-copy segment evidence",
        paths: &[
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/allocation_recovery/fixed_view_copy/evidence/mod.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/allocation_recovery/fixed_view_copy/evidence/model.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/allocation_recovery/fixed_view_copy/evidence/compute.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/allocation_recovery/fixed_view_copy/evidence/replay.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/allocation_recovery/fixed_view_copy/work.rs",
        ],
    },
    SemanticLadder {
        family: "fixed/precolored segment-home pipeline custody",
        paths: &[
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/fixed_view/fixed_precolored_segment_homes/mod.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/fixed_view/fixed_precolored_segment_homes/model.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/fixed_view/fixed_precolored_segment_homes/compute.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/fixed_view/fixed_precolored_segment_homes/validation.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/fixed_view/fixed_precolored_segment_homes/custody.rs",
        ],
    },
    SemanticLadder {
        family: "fixed-view-copy validation",
        paths: &[
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/allocation_recovery/fixed_view_copy/validate/mod.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/allocation_recovery/fixed_view_copy/validate/roots.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/allocation_recovery/fixed_view_copy/validate/source_evidence.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/allocation_recovery/fixed_view_copy/validate/seal.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/allocation_recovery/fixed_view_copy/validate/copy_constraint.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/allocation_recovery/fixed_view_copy/validate/usage.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/allocation_recovery/fixed_view_copy/validate/transformation.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/allocation_recovery/fixed_view_copy/validate/leaf_destination.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/allocation_recovery/fixed_view_copy/validate/shared_entry.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/rewrites/allocation_recovery/fixed_view_copy/validate/apply.rs",
        ],
    },
    SemanticLadder {
        family: "independent live-range replay",
        paths: &[
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/analyses/live_ranges/validate/replay/architectural_units.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/analyses/live_ranges/validate/replay/canonical.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/analyses/live_ranges/validate/replay/comparison.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/analyses/live_ranges/validate/replay/constraints.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/analyses/live_ranges/validate/replay/fragments.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/analyses/live_ranges/validate/replay/function.rs",
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/analyses/live_ranges/validate/replay/tests.rs",
        ],
    },
    SemanticLadder {
        family: "structural-catalog tests",
        paths: &[
            "omega-rust/omega/pipeline/optimization-validation/src/tests/structural_catalog/mod.rs",
            "omega-rust/omega/pipeline/optimization-validation/src/tests/structural_catalog/catalog.rs",
            "omega-rust/omega/pipeline/optimization-validation/src/tests/structural_catalog/type_declarations.rs",
            "omega-rust/omega/pipeline/optimization-validation/src/tests/structural_catalog/content_projection.rs",
            "omega-rust/omega/pipeline/optimization-validation/src/tests/structural_catalog/function_catalog.rs",
            "omega-rust/omega/pipeline/optimization-validation/src/tests/structural_catalog/structural_roots.rs",
            "omega-rust/omega/pipeline/optimization-validation/src/tests/structural_catalog/provider_specialization.rs",
        ],
    },
    SemanticLadder {
        family: "register-allocation tests",
        paths: &[
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/mod.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/allocation_legality.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/abstract_spill_insertion.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/fixed_view_copies.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/fixed_view_copy_operational/mod.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/fixed_view_copy_operational/fixture.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/fixed_view_copy_operational/execution.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/fixed_view_copy_operational/budget.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/fixed_view_copy_operational/evidence.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/fixed_precolored_intervals/mod.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/fixed_precolored_intervals/fixture.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/fixed_precolored_intervals/positive.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/fixed_precolored_intervals/corruption.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/fixed_precolored_intervals/budget.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/generalized_spill_insertion.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/generalized_reload_value_homes.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/generalized_spill_recovery_worklist.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/homed_spill_pseudo_instructions.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/abstract_spill_memory_effects/mod.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/abstract_spill_memory_effects/fixture.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/abstract_spill_memory_effects/positive.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/abstract_spill_memory_effects/positive/effect.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/abstract_spill_access_constraints/mod.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/abstract_spill_access_constraints/fixture.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/abstract_spill_access_constraints/positive.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/abstract_spill_access_constraints/corruption.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/abstract_spill_access_constraints/budget.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/abstract_spill_memory_effects/corruption.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/abstract_spill_memory_effects/budget.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/generalized_spill_recovery_choice.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/generalized_spill_recovery_actions.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/recursive_spill_insertion.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/recursive_reload_value_homes.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/spill_pseudo_instructions.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/live_ranges.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/liveness.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/logical_spill_operations.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/original_spill_recovery_actions.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/original_recursive_spill_insertion.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/register_homes.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/reload_value_homes.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/spill_recovery_choice.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/spill_recovery_actions.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/spill_recovery_worklist.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/selected_input.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/stack_slot_coloring.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/synthetic_reload_values.rs",
        ],
    },
    SemanticLadder {
        family: "selected-lowering tests",
        paths: &[
            "tests/native-differential/tests/pipeline_ownership/stages/machine/selected_lowering/mod.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/machine/selected_lowering/exact_add_operational/mod.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/machine/selected_lowering/exact_add_operational/fixture.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/machine/selected_lowering/exact_add_operational/execution.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/machine/selected_lowering/exact_add_operational/budget.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/machine/selected_lowering/exact_add_operational/corruption.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/machine/selected_lowering/exact_immediates.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/machine/selected_lowering/exact_subtract_operational/mod.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/machine/selected_lowering/exact_subtract_operational/fixture.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/machine/selected_lowering/exact_subtract_operational/execution.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/machine/selected_lowering/exact_subtract_operational/budget.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/machine/selected_lowering/exact_subtract_operational/corruption.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/machine/selected_lowering/exact_subtract_operational/semantic_boundary.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/machine/selected_lowering/exit_contract.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/machine/selected_lowering/named_suite.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/machine/selected_lowering/pressure_recovery.rs",
        ],
    },
    SemanticLadder {
        family: "extracted focused tests",
        paths: &[
            "omega-rust/omega/pipeline/selected-instructions-to-register-homes/src/assignment/spill_choice/compute/tests.rs",
            "omega-rust/omega/pipeline/abstract-operations-to-target-operations/src/lowering/unit/boundary_call/tests.rs",
        ],
    },
    SemanticLadder {
        family: "selected-block validation",
        paths: &[
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/validation/blocks/mod.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/validation/blocks/entry_control/mod.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/validation/blocks/return_routes.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/validation/blocks/immediate_return.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/validation/blocks/parameter_return.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/validation/blocks/exact_binary_return.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/validation/blocks/active_resident_exact_add_chain_return.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/validation/blocks/active_resident_exact_add_bridge_chain_return.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/validation/blocks/instruction_projection.rs",
        ],
    },
    SemanticLadder {
        family: "projected structural call-return selection",
        paths: &[
            "omega-rust/omega/representations/selected-instructions/src/selected_instructions/calls/projected_return/mod.rs",
            "omega-rust/omega/representations/selected-instructions/src/selected_instructions/calls/projected_return/model.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/construction/projected_structural_call_return/mod.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/construction/projected_structural_call_return/projection.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/construction/projected_structural_call_return/constraints.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/construction/projected_structural_call_return/transfer.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/validation/projected_structural_call_return/mod.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/validation/projected_structural_call_return/source.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/validation/projected_structural_call_return/target.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/identity/projected_structural.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/tests/selection/projected_structural_call_return.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/selection/assignment_and_legalization/projected_structural_call_return.rs",
        ],
    },
    SemanticLadder {
        family: "attached-Unit scalar-call selection and allocation",
        paths: &[
            "omega-rust/omega/representations/legalized-operations/src/legalized_operations/calls/scalar.rs",
            "omega-rust/omega/representations/legalized-operations/src/legalized_operations/identity/scalar_call_unit.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/catalog.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/source/scalar_call_unit/mod.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/source/scalar_call_unit/grammar.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/source/scalar_call_unit/operations.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/source/scalar_call_unit/nodes.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/source/scalar_call_unit/callee.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/source/scalar_call_unit/projection.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/replay/scalar_call_unit/mod.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/replay/scalar_call_unit/contract.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/replay/scalar_call_unit/grammar.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/replay/scalar_call_unit/operations.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/replay/scalar_call_unit/callee.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/tests/fixtures/scalar_call_unit.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/tests/legalization/scalar_call_unit.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/construction/scalar_call_unit.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/validation/scalar_call_unit.rs",
            "omega-rust/omega/pipeline/target-to-register-environment/src/catalog.rs",
            "tests/native-differential/tests/pipeline_ownership/fixtures/scalar_call_unit.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/runtime_scalar_call_chain/mod.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/runtime_scalar_call_chain/fixture.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/runtime_scalar_call_chain/custody.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/runtime_scalar_call_chain/allocation.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/allocation/register_allocation/runtime_scalar_call_chain/corruption.rs",
        ],
    },
    SemanticLadder {
        family: "legalization source conditions",
        paths: &[
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/source/conditions/mod.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/source/conditions/model.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/source/conditions/direct_parameter.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/source/conditions/integer_parameter_comparison.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/source/conditions/integer_equal_parameters.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/source/conditions/integer_less_than_parameters.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/source/conditions/i64_less_than_parameters.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/source/conditions/i64_less_or_equal_parameters.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/source/conditions/integer_less_or_equal_parameters.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/source/conditions/integer_parameter_not_equal.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/source/conditions/integer_not_equal_parameters.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/source/conditions/u64_equal_zero_parameter.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/source/conditions/u64_not_equal_zero_parameter.rs",
        ],
    },
    SemanticLadder {
        family: "legalization replay conditions",
        paths: &[
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/replay/conditions/mod.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/replay/conditions/model.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/replay/conditions/direct_parameter.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/replay/conditions/integer_parameter_comparison.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/replay/conditions/integer_equal_parameters.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/replay/conditions/integer_less_than_parameters.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/replay/conditions/i64_less_than_parameters.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/replay/conditions/i64_less_or_equal_parameters.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/replay/conditions/integer_less_or_equal_parameters.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/replay/conditions/integer_parameter_not_equal.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/replay/conditions/integer_not_equal_parameters.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/replay/conditions/u64_equal_zero_parameter.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/replay/conditions/u64_not_equal_zero_parameter.rs",
        ],
    },
    SemanticLadder {
        family: "selected scalar entry conditions",
        paths: &[
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/construction/scalar/blocks/entry/mod.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/construction/scalar/blocks/entry/direct_parameter.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/construction/scalar/comparison_immediate_pair.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/construction/scalar/zero_comparison_immediate_pair.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/construction/scalar/blocks/entry/integer_equal_parameters.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/construction/scalar/blocks/entry/integer_less_than_parameters.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/construction/scalar/blocks/entry/i64_less_than_parameters.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/construction/scalar/blocks/entry/i64_less_or_equal_parameters.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/construction/scalar/blocks/entry/integer_less_or_equal_parameters.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/construction/scalar/blocks/entry/integer_not_equal_parameters.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/construction/scalar/blocks/entry/equal_zero_parameter.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/construction/scalar/blocks/entry/not_equal_zero_parameter.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/validation/blocks/entry_control/mod.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/validation/blocks/entry_control/direct_parameter.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/validation/blocks/entry_control/integer_equal_parameters.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/validation/blocks/entry_control/integer_less_than_parameters.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/validation/blocks/entry_control/i64_less_than_parameters.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/validation/blocks/entry_control/i64_less_or_equal_parameters.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/validation/blocks/entry_control/integer_less_or_equal_parameters.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/validation/blocks/entry_control/integer_not_equal_parameters.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/validation/blocks/entry_control/equal_zero_parameter.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/selection/validation/blocks/entry_control/not_equal_zero_parameter.rs",
        ],
    },
    SemanticLadder {
        family: "legalization source leaves",
        paths: &[
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/source/leaves/mod.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/source/leaves/context.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/source/leaves/immediate.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/source/leaves/entry_parameter.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/source/leaves/direct_exact_binary.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/source/leaves/widened_exact_binary.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/source/leaves/exact_add.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/source/leaves/active_resident_exact_add_chain.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/source/leaves/active_resident_exact_add_bridge_chain.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/source/leaves/return_projection.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/source/leaves/operation_projection.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/source/leaves/fuel.rs",
        ],
    },
    SemanticLadder {
        family: "legalization replay leaves",
        paths: &[
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/replay/leaf/mod.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/replay/leaf/recipe.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/replay/leaf/immediate.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/replay/leaf/exact_arithmetic.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/replay/leaf/bridge_chain.rs",
            "omega-rust/omega/pipeline/target-operations-to-selected-instructions/src/legalization/replay/leaf/fuel.rs",
        ],
    },
    SemanticLadder {
        family: "assignment and legalization tests",
        paths: &[
            "tests/native-differential/tests/pipeline_ownership/stages/selection/assignment_and_legalization/mod.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/selection/assignment_and_legalization/active_resident_bridge_chain.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/selection/assignment_and_legalization/runtime_integer_equal_conditional/mod.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/selection/assignment_and_legalization/runtime_integer_equal_conditional/fixture.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/selection/assignment_and_legalization/runtime_integer_equal_conditional/selected_graph.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/selection/assignment_and_legalization/runtime_integer_equal_conditional/corruption.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/selection/assignment_and_legalization/runtime_integer_less_than_conditional/mod.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/selection/assignment_and_legalization/runtime_integer_less_than_conditional/fixture.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/selection/assignment_and_legalization/runtime_integer_less_than_conditional/selected_graph.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/selection/assignment_and_legalization/runtime_integer_less_than_conditional/corruption.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/selection/assignment_and_legalization/runtime_integer_less_or_equal_conditional/mod.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/selection/assignment_and_legalization/runtime_integer_less_or_equal_conditional/fixture.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/selection/assignment_and_legalization/runtime_integer_less_or_equal_conditional/selected_graph.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/selection/assignment_and_legalization/runtime_integer_less_or_equal_conditional/corruption.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/selection/assignment_and_legalization/runtime_signed_integer_less_or_equal_conditional/mod.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/selection/assignment_and_legalization/runtime_signed_integer_less_or_equal_conditional/fixture.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/selection/assignment_and_legalization/runtime_signed_integer_less_or_equal_conditional/selected_graph.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/selection/assignment_and_legalization/runtime_signed_integer_less_or_equal_conditional/corruption.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/selection/assignment_and_legalization/runtime_integer_not_equal_conditional/mod.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/selection/assignment_and_legalization/runtime_integer_not_equal_conditional/fixture.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/selection/assignment_and_legalization/runtime_integer_not_equal_conditional/selected_graph.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/selection/assignment_and_legalization/runtime_integer_not_equal_conditional/corruption.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/selection/assignment_and_legalization/runtime_u64_equal_zero_parameter/mod.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/selection/assignment_and_legalization/runtime_u64_equal_zero_parameter/fixture.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/selection/assignment_and_legalization/runtime_u64_equal_zero_parameter/selected_graph.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/selection/assignment_and_legalization/runtime_u64_equal_zero_parameter/corruption.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/selection/assignment_and_legalization/runtime_u64_not_equal_zero_parameter/mod.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/selection/assignment_and_legalization/runtime_u64_not_equal_zero_parameter/fixture.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/selection/assignment_and_legalization/runtime_u64_not_equal_zero_parameter/selected_graph.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/selection/assignment_and_legalization/runtime_u64_not_equal_zero_parameter/corruption.rs",
        ],
    },
    SemanticLadder {
        family: "runtime integer-equality publication tests",
        paths: &[
            "tests/native-differential/tests/pipeline_ownership/stages/realization/runtime_integer_equal_conditional/mod.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/realization/runtime_integer_equal_conditional/fixture.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/realization/runtime_integer_equal_conditional/publication.rs",
        ],
    },
    SemanticLadder {
        family: "runtime integer-less-than publication tests",
        paths: &[
            "tests/native-differential/tests/pipeline_ownership/stages/realization/runtime_integer_less_than_conditional/mod.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/realization/runtime_integer_less_than_conditional/fixture.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/realization/runtime_integer_less_than_conditional/publication.rs",
        ],
    },
    SemanticLadder {
        family: "runtime signed-integer-less-than publication tests",
        paths: &[
            "tests/native-differential/tests/pipeline_ownership/stages/realization/runtime_signed_integer_less_than_conditional/mod.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/realization/runtime_signed_integer_less_than_conditional/fixture.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/realization/runtime_signed_integer_less_than_conditional/publication.rs",
        ],
    },
    SemanticLadder {
        family: "runtime integer-less-or-equal publication tests",
        paths: &[
            "tests/native-differential/tests/pipeline_ownership/stages/realization/runtime_integer_less_or_equal_conditional/mod.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/realization/runtime_integer_less_or_equal_conditional/fixture.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/realization/runtime_integer_less_or_equal_conditional/publication.rs",
        ],
    },
    SemanticLadder {
        family: "runtime signed-integer-less-or-equal publication tests",
        paths: &[
            "tests/native-differential/tests/pipeline_ownership/stages/realization/runtime_signed_integer_less_or_equal_conditional/mod.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/realization/runtime_signed_integer_less_or_equal_conditional/fixture.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/realization/runtime_signed_integer_less_or_equal_conditional/publication.rs",
        ],
    },
    SemanticLadder {
        family: "runtime integer-not-equal publication tests",
        paths: &[
            "tests/native-differential/tests/pipeline_ownership/stages/realization/runtime_integer_not_equal_conditional/mod.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/realization/runtime_integer_not_equal_conditional/fixture.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/realization/runtime_integer_not_equal_conditional/publication.rs",
        ],
    },
    SemanticLadder {
        family: "runtime U64 parameter-equals-zero publication tests",
        paths: &[
            "tests/native-differential/tests/pipeline_ownership/coordination/physical_pipeline/equal_zero_parameter.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/realization/runtime_u64_equal_zero_parameter/mod.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/realization/runtime_u64_equal_zero_parameter/fixture.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/realization/runtime_u64_equal_zero_parameter/publication.rs",
        ],
    },
    SemanticLadder {
        family: "runtime U64 parameter-not-equal-zero publication tests",
        paths: &[
            "tests/native-differential/tests/pipeline_ownership/coordination/physical_pipeline/not_equal_zero_parameter.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/realization/runtime_u64_not_equal_zero_parameter/mod.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/realization/runtime_u64_not_equal_zero_parameter/fixture.rs",
            "tests/native-differential/tests/pipeline_ownership/stages/realization/runtime_u64_not_equal_zero_parameter/publication.rs",
        ],
    },
];
