use super::super::SemanticLadder;

pub(crate) const LADDERS: &[SemanticLadder] = &[
    SemanticLadder {
        family: "logical spill-operation planning",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/logical_spill_operations/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/logical_spill_operations/model.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/logical_spill_operations/identity.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/logical_spill_operations/compute/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/logical_spill_operations/compute/action.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/logical_spill_operations/compute/work.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/logical_spill_operations/validate/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/logical_spill_operations/validate/replay.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/logical_spill_operations/validate/work.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/logical_spill_operations/validate/receipt.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/logical_spill_operations/codec/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/logical_spill_operations/codec/encoding.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/logical_spill_operations/codec/decoding.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/logical_spill_operations/codec/cursor.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/logical_spill_operations/codec/values.rs",
        ],
    },
    SemanticLadder {
        family: "stack-slot coloring",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/stack_slot_coloring/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/stack_slot_coloring/model.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/stack_slot_coloring/identity.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/stack_slot_coloring/compute/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/stack_slot_coloring/compute/intervals.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/stack_slot_coloring/compute/first_fit.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/stack_slot_coloring/compute/work.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/stack_slot_coloring/validate/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/stack_slot_coloring/validate/root.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/stack_slot_coloring/validate/replay.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/stack_slot_coloring/validate/work.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/stack_slot_coloring/validate/receipt.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/stack_slot_coloring/codec/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/stack_slot_coloring/codec/encoding.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/stack_slot_coloring/codec/decoding.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/stack_slot_coloring/codec/cursor.rs",
        ],
    },
    SemanticLadder {
        family: "selected machine-effect carrier",
        paths: &[
            "source/omega-rust/omega/representations/omega-selected-instructions/src/machine_effects/mod.rs",
            "source/omega-rust/omega/representations/omega-selected-instructions/src/machine_effects/model.rs",
            "source/omega-rust/omega/representations/omega-selected-instructions/src/machine_effects/constraint_keys.rs",
            "source/omega-rust/omega/representations/omega-selected-instructions/src/machine_effects/validation.rs",
            "source/omega-rust/omega/representations/omega-selected-instructions/src/machine_effects/identity.rs",
        ],
    },
    SemanticLadder {
        family: "assigned target-operation carrier",
        paths: &[
            "source/omega-rust/omega/representations/omega-assigned-target-operations/src/lib.rs",
            "source/omega-rust/omega/representations/omega-assigned-target-operations/src/operation.rs",
            "source/omega-rust/omega/representations/omega-assigned-target-operations/src/plan.rs",
            "source/omega-rust/omega/representations/omega-assigned-target-operations/src/unit.rs",
            "source/omega-rust/omega/representations/omega-assigned-target-operations/src/scalar/mod.rs",
            "source/omega-rust/omega/representations/omega-assigned-target-operations/src/scalar/boolean.rs",
            "source/omega-rust/omega/representations/omega-assigned-target-operations/src/scalar/integer.rs",
            "source/omega-rust/omega/representations/omega-assigned-target-operations/src/scalar/calls_and_locations.rs",
        ],
    },
    SemanticLadder {
        family: "fixed-view-copy codec",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/codec/content.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/codec/copy.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/codec/primitives.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/codec/values.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/codec/selected/function.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/codec/selected/register.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/codec/selected/block.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/codec/selected/instruction.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/codec/selected/provenance.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/codec/selected/scalar.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/codec/selected/structural/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/codec/selected/structural/signature.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/codec/selected/structural/call.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/codec/selected/structural/calling.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/codec/selected/structural/declarations.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/codec/selected/structural/settlements.rs",
        ],
    },
    SemanticLadder {
        family: "fixed-view-copy validation",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/validate/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/validate/roots.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/validate/copy_constraint.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/validate/usage.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/validate/transformation.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/validate/leaf_destination.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/validate/shared_entry.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/validate/apply.rs",
        ],
    },
    SemanticLadder {
        family: "independent live-range replay",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/analyses/live_ranges/validate/replay/architectural_units.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/analyses/live_ranges/validate/replay/canonical.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/analyses/live_ranges/validate/replay/comparison.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/analyses/live_ranges/validate/replay/constraints.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/analyses/live_ranges/validate/replay/fragments.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/analyses/live_ranges/validate/replay/function.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/analyses/live_ranges/validate/replay/tests.rs",
        ],
    },
    SemanticLadder {
        family: "structural-catalog tests",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/tests/structural_catalog/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/tests/structural_catalog/catalog.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/tests/structural_catalog/type_declarations.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/tests/structural_catalog/content_projection.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/tests/structural_catalog/function_catalog.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/tests/structural_catalog/structural_roots.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/tests/structural_catalog/provider_specialization.rs",
        ],
    },
    SemanticLadder {
        family: "register-allocation tests",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/allocation_legality.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/fixed_view_copies.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/live_ranges.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/liveness.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/logical_spill_operations.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/register_homes.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/selected_input.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/stack_slot_coloring.rs",
        ],
    },
    SemanticLadder {
        family: "selected-lowering tests",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/machine/selected_lowering/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/machine/selected_lowering/exact_immediates.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/machine/selected_lowering/exit_contract.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/machine/selected_lowering/named_suite.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/machine/selected_lowering/pressure_recovery.rs",
        ],
    },
    SemanticLadder {
        family: "extracted focused tests",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/spill_choice/compute/tests.rs",
            "source/omega-rust/omega/pipeline/omega-abstract-operations-to-target-operations/src/lowering/unit/boundary_call/tests.rs",
        ],
    },
    SemanticLadder {
        family: "selected-block validation",
        paths: &[
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/selection/validation/blocks/mod.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/selection/validation/blocks/entry_control.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/selection/validation/blocks/return_routes.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/selection/validation/blocks/immediate_return.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/selection/validation/blocks/parameter_return.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/selection/validation/blocks/exact_binary_return.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/selection/validation/blocks/active_resident_exact_add_chain_return.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/selection/validation/blocks/instruction_projection.rs",
        ],
    },
    SemanticLadder {
        family: "legalization source leaves",
        paths: &[
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/legalization/source/leaves/mod.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/legalization/source/leaves/context.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/legalization/source/leaves/immediate.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/legalization/source/leaves/entry_parameter.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/legalization/source/leaves/direct_exact_binary.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/legalization/source/leaves/widened_exact_binary.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/legalization/source/leaves/active_resident_exact_add_chain.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/legalization/source/leaves/return_projection.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/legalization/source/leaves/operation_projection.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/legalization/source/leaves/fuel.rs",
        ],
    },
];
