use super::super::SemanticLadder;

pub(crate) const LADDERS: &[SemanticLadder] = &[
    SemanticLadder {
        family: "logical spill-operation planning",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/logical_spill_operations/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/logical_spill_operations/model.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/logical_spill_operations/identity.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/logical_spill_operations/compute/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/logical_spill_operations/compute/action.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/logical_spill_operations/compute/work.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/logical_spill_operations/validate/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/logical_spill_operations/validate/replay.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/logical_spill_operations/validate/work.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/logical_spill_operations/validate/receipt.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/logical_spill_operations/codec/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/logical_spill_operations/codec/encoding.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/logical_spill_operations/codec/decoding.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/logical_spill_operations/codec/cursor.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/logical_spill_operations/codec/values.rs",
        ],
    },
    SemanticLadder {
        family: "stack-slot coloring",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/stack_slot_coloring/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/stack_slot_coloring/model.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/stack_slot_coloring/identity.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/stack_slot_coloring/compute/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/stack_slot_coloring/compute/intervals.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/stack_slot_coloring/compute/first_fit.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/stack_slot_coloring/compute/work.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/stack_slot_coloring/validate/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/stack_slot_coloring/validate/root.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/stack_slot_coloring/validate/replay.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/stack_slot_coloring/validate/work.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/stack_slot_coloring/validate/receipt.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/stack_slot_coloring/codec/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/stack_slot_coloring/codec/encoding.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/stack_slot_coloring/codec/decoding.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/stack_slot_coloring/codec/cursor.rs",
        ],
    },
    SemanticLadder {
        family: "abstract spill insertion",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/abstract_spill_insertion/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/abstract_spill_insertion/model.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/abstract_spill_insertion/identity.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/abstract_spill_insertion/compute.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/abstract_spill_insertion/validate.rs",
        ],
    },
    SemanticLadder {
        family: "reload-value home assignment",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/reload_value_homes/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/reload_value_homes/model.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/reload_value_homes/identity.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/reload_value_homes/compute.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/reload_value_homes/replay.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/reload_value_homes/replay/mechanics.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/reload_value_homes/validate.rs",
        ],
    },
    SemanticLadder {
        family: "synthetic reload-value namespace",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/synthetic_reload_values/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/synthetic_reload_values/model.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/synthetic_reload_values/identity.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/synthetic_reload_values/compute.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/synthetic_reload_values/replay.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/synthetic_reload_values/validate.rs",
        ],
    },
    SemanticLadder {
        family: "recursive spill-recovery victim choice",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/spill_recovery_choice/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/spill_recovery_choice/model.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/spill_recovery_choice/identity.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/spill_recovery_choice/compute.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/spill_recovery_choice/replay.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/spill_recovery_choice/validate.rs",
        ],
    },
    SemanticLadder {
        family: "recursive spill-recovery logical actions",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/spill_recovery_actions/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/spill_recovery_actions/model.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/spill_recovery_actions/identity.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/spill_recovery_actions/compute.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/spill_recovery_actions/replay.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/spill_recovery_actions/validate.rs",
        ],
    },
    SemanticLadder {
        family: "generalized epoch-zero and epoch-one spill insertion",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_spill_insertion/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_spill_insertion/model.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_spill_insertion/identity.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_spill_insertion/compute.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_spill_insertion/replay.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_spill_insertion/validate.rs",
        ],
    },
    SemanticLadder {
        family: "generalized epoch-zero and epoch-one reload-home reanalysis",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_reload_value_homes/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_reload_value_homes/model.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_reload_value_homes/identity.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_reload_value_homes/compute.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_reload_value_homes/compute/roots.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_reload_value_homes/compute/sources.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_reload_value_homes/compute/homes.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_reload_value_homes/compute/schedule.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_reload_value_homes/compute/work.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_reload_value_homes/replay.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_reload_value_homes/replay/roots.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_reload_value_homes/replay/sources.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_reload_value_homes/replay/homes.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_reload_value_homes/replay/timeline.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_reload_value_homes/replay/work.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_reload_value_homes/validate.rs",
        ],
    },
    SemanticLadder {
        family: "generalized epoch-two spill-recovery worklist",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_spill_recovery_worklist/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_spill_recovery_worklist/model.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_spill_recovery_worklist/identity.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_spill_recovery_worklist/compute.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_spill_recovery_worklist/replay.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_spill_recovery_worklist/validate.rs",
        ],
    },
    SemanticLadder {
        family: "generalized epoch-two spill-recovery victim choice",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_spill_recovery_choice/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_spill_recovery_choice/model.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_spill_recovery_choice/identity.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_spill_recovery_choice/compute.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_spill_recovery_choice/compute/original_eligibility.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_spill_recovery_choice/replay.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_spill_recovery_choice/replay/original_eligibility.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_spill_recovery_choice/validate.rs",
        ],
    },
    SemanticLadder {
        family: "generalized epoch-two logical recovery actions",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_spill_recovery_actions/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_spill_recovery_actions/model.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_spill_recovery_actions/identity.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_spill_recovery_actions/compute.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_spill_recovery_actions/replay.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/generalized_spill_recovery_actions/validate.rs",
        ],
    },
    SemanticLadder {
        family: "recursive epoch-two spill insertion",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/recursive_spill_insertion/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/recursive_spill_insertion/model.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/recursive_spill_insertion/identity.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/recursive_spill_insertion/compute.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/recursive_spill_insertion/replay.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/recursive_spill_insertion/validate.rs",
        ],
    },
    SemanticLadder {
        family: "target-neutral spill-pseudo instructions",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/spill_pseudo_instructions/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/spill_pseudo_instructions/model.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/spill_pseudo_instructions/identity.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/spill_pseudo_instructions/compute.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/spill_pseudo_instructions/replay.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/spill_pseudo_instructions/validate.rs",
        ],
    },
    SemanticLadder {
        family: "post-allocation manifest mutation custody tests",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/post_allocation_manifest_mutation_matrix/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/post_allocation_manifest_mutation_matrix/fixture.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/post_allocation_manifest_mutation_matrix/fields.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/post_allocation_manifest_mutation_matrix/wire.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/post_allocation_manifest_mutation_matrix/wire_offsets.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/post_allocation_manifest_mutation_matrix/custody.rs",
        ],
    },
    SemanticLadder {
        family: "recursive spill-recovery worklist",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/spill_recovery_worklist/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/spill_recovery_worklist/model.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/spill_recovery_worklist/identity.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/spill_recovery_worklist/compute.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/spill_recovery_worklist/replay.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/spill_recovery_worklist/validate.rs",
        ],
    },
    SemanticLadder {
        family: "selected machine-effect carrier",
        paths: &[
            "source/omega-rust/omega/representations/omega-selected-instructions/src/machine_effects/mod.rs",
            "source/omega-rust/omega/representations/omega-selected-instructions/src/machine_effects/model.rs",
            "source/omega-rust/omega/representations/omega-selected-instructions/src/machine_effects/constraint_keys.rs",
            "source/omega-rust/omega/representations/omega-selected-instructions/src/machine_effects/validation.rs",
            "source/omega-rust/omega/representations/omega-selected-instructions/src/machine_effects/identity.rs",
        ],
    },
    SemanticLadder {
        family: "assigned target-operation carrier",
        paths: &[
            "source/omega-rust/omega/representations/omega-assigned-target-operations/src/lib.rs",
            "source/omega-rust/omega/representations/omega-assigned-target-operations/src/operation.rs",
            "source/omega-rust/omega/representations/omega-assigned-target-operations/src/plan.rs",
            "source/omega-rust/omega/representations/omega-assigned-target-operations/src/unit.rs",
            "source/omega-rust/omega/representations/omega-assigned-target-operations/src/scalar/mod.rs",
            "source/omega-rust/omega/representations/omega-assigned-target-operations/src/scalar/boolean.rs",
            "source/omega-rust/omega/representations/omega-assigned-target-operations/src/scalar/integer.rs",
            "source/omega-rust/omega/representations/omega-assigned-target-operations/src/scalar/calls_and_locations.rs",
        ],
    },
    SemanticLadder {
        family: "fixed-view-copy codec",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/codec/content.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/codec/copy.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/codec/primitives.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/codec/values.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/codec/selected/function.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/codec/selected/register.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/codec/selected/block.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/codec/selected/instruction.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/codec/selected/provenance.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/codec/selected/scalar.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/codec/selected/structural/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/codec/selected/structural/signature.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/codec/selected/structural/call.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/codec/selected/structural/calling.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/codec/selected/structural/declarations.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/codec/selected/structural/settlements.rs",
        ],
    },
    SemanticLadder {
        family: "fixed-view-copy validation",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/validate/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/validate/roots.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/validate/copy_constraint.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/validate/usage.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/validate/transformation.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/validate/leaf_destination.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/validate/shared_entry.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/rules/allocation_recovery/fixed_view_copy/validate/apply.rs",
        ],
    },
    SemanticLadder {
        family: "independent live-range replay",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/analyses/live_ranges/validate/replay/architectural_units.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/analyses/live_ranges/validate/replay/canonical.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/analyses/live_ranges/validate/replay/comparison.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/analyses/live_ranges/validate/replay/constraints.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/analyses/live_ranges/validate/replay/fragments.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/analyses/live_ranges/validate/replay/function.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/analyses/live_ranges/validate/replay/tests.rs",
        ],
    },
    SemanticLadder {
        family: "structural-catalog tests",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/tests/structural_catalog/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/tests/structural_catalog/catalog.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/tests/structural_catalog/type_declarations.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/tests/structural_catalog/content_projection.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/tests/structural_catalog/function_catalog.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/tests/structural_catalog/structural_roots.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-validation/src/tests/structural_catalog/provider_specialization.rs",
        ],
    },
    SemanticLadder {
        family: "register-allocation tests",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/allocation_legality.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/abstract_spill_insertion.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/fixed_view_copies.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/fixed_view_copy_operational/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/fixed_view_copy_operational/fixture.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/fixed_view_copy_operational/execution.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/fixed_view_copy_operational/budget.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/generalized_spill_insertion.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/generalized_reload_value_homes.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/generalized_spill_recovery_worklist.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/generalized_spill_recovery_choice.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/generalized_spill_recovery_actions.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/recursive_spill_insertion.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/spill_pseudo_instructions.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/live_ranges.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/liveness.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/logical_spill_operations.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/register_homes.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/reload_value_homes.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/spill_recovery_choice.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/spill_recovery_actions.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/spill_recovery_worklist.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/selected_input.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/stack_slot_coloring.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/allocation/register_allocation/synthetic_reload_values.rs",
        ],
    },
    SemanticLadder {
        family: "selected-lowering tests",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/machine/selected_lowering/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/machine/selected_lowering/exact_add_operational/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/machine/selected_lowering/exact_add_operational/fixture.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/machine/selected_lowering/exact_add_operational/execution.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/machine/selected_lowering/exact_add_operational/budget.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/machine/selected_lowering/exact_add_operational/corruption.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/machine/selected_lowering/exact_immediates.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/machine/selected_lowering/exact_subtract_operational/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/machine/selected_lowering/exact_subtract_operational/fixture.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/machine/selected_lowering/exact_subtract_operational/execution.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/machine/selected_lowering/exact_subtract_operational/budget.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/machine/selected_lowering/exact_subtract_operational/corruption.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/machine/selected_lowering/exact_subtract_operational/semantic_boundary.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/machine/selected_lowering/exit_contract.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/machine/selected_lowering/named_suite.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/machine/selected_lowering/pressure_recovery.rs",
        ],
    },
    SemanticLadder {
        family: "extracted focused tests",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-regalloc/src/allocation/spill_choice/compute/tests.rs",
            "source/omega-rust/omega/pipeline/omega-abstract-operations-to-target-operations/src/lowering/unit/boundary_call/tests.rs",
        ],
    },
    SemanticLadder {
        family: "selected-block validation",
        paths: &[
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/selection/validation/blocks/mod.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/selection/validation/blocks/entry_control.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/selection/validation/blocks/return_routes.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/selection/validation/blocks/immediate_return.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/selection/validation/blocks/parameter_return.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/selection/validation/blocks/exact_binary_return.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/selection/validation/blocks/active_resident_exact_add_chain_return.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/selection/validation/blocks/active_resident_exact_add_bridge_chain_return.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/selection/validation/blocks/instruction_projection.rs",
        ],
    },
    SemanticLadder {
        family: "projected structural call-return selection",
        paths: &[
            "source/omega-rust/omega/representations/omega-selected-instructions/src/projected_structural_call_return/mod.rs",
            "source/omega-rust/omega/representations/omega-selected-instructions/src/projected_structural_call_return/model.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/selection/construction/projected_structural_call_return/mod.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/selection/construction/projected_structural_call_return/projection.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/selection/construction/projected_structural_call_return/constraints.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/selection/construction/projected_structural_call_return/transfer.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/selection/validation/projected_structural_call_return/mod.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/selection/validation/projected_structural_call_return/source.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/selection/validation/projected_structural_call_return/target.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/selection/identity/projected_structural.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/tests/selection/projected_structural_call_return.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/selection/assignment_and_legalization/projected_structural_call_return.rs",
        ],
    },
    SemanticLadder {
        family: "legalization source leaves",
        paths: &[
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/legalization/source/leaves/mod.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/legalization/source/leaves/context.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/legalization/source/leaves/immediate.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/legalization/source/leaves/entry_parameter.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/legalization/source/leaves/direct_exact_binary.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/legalization/source/leaves/widened_exact_binary.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/legalization/source/leaves/exact_add.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/legalization/source/leaves/active_resident_exact_add_chain.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/legalization/source/leaves/active_resident_exact_add_bridge_chain.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/legalization/source/leaves/return_projection.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/legalization/source/leaves/operation_projection.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/legalization/source/leaves/fuel.rs",
        ],
    },
    SemanticLadder {
        family: "legalization replay leaves",
        paths: &[
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/legalization/replay/leaf/mod.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/legalization/replay/leaf/recipe.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/legalization/replay/leaf/immediate.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/legalization/replay/leaf/exact_arithmetic.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/legalization/replay/leaf/bridge_chain.rs",
            "source/omega-rust/omega/pipeline/omega-target-operations-to-selected-instructions/src/legalization/replay/leaf/fuel.rs",
        ],
    },
    SemanticLadder {
        family: "assignment and legalization tests",
        paths: &[
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/selection/assignment_and_legalization/mod.rs",
            "source/omega-rust/omega/pipeline/optimization/omega-optimization-pipeline/src/tests/stages/selection/assignment_and_legalization/active_resident_bridge_chain.rs",
        ],
    },
];
